# Summary

# Imports

In [1]:
%run _imports.ipynb

Setting the PYTHON_VERSION environment variable.
Setting the SPARK_MASTER environment variable.
Setting the DB_TYPE environment variable.
Setting the DB_PORT environment variable.

2017-12-06 11:45:46.595554

In [2]:
NOTEBOOK_NAME = 'load_pmc_xml_tables'
os.makedirs(NOTEBOOK_NAME, exist_ok=True)

# Parameters

In [3]:
MANUSCRIPT_DATA_DIR = Path('../downloads/ncbi/pmc/manuscript/').absolute()

# Example

In [4]:
!ls ../downloads/ncbi/pmc/manuscript/

filelist.csv		 PMC0033XXXXX		  PMC0046XXXXX
PMC0021XXXXX		 PMC0034XXXXX		  PMC0047XXXXX
PMC0022XXXXX		 PMC0035XXXXX		  PMC0048XXXXX
PMC0023XXXXX		 PMC0036XXXXX		  PMC0049XXXXX
PMC0024XXXXX		 PMC0037XXXXX		  PMC004XXXXXX.xml.tar.gz
PMC0025XXXXX		 PMC0038XXXXX		  PMC0050XXXXX
PMC0026XXXXX		 PMC0039XXXXX		  PMC0051XXXXX
PMC0027XXXXX		 PMC003XXXXXX.xml.tar.gz  PMC0052XXXXX
PMC0028XXXXX		 PMC0040XXXXX		  PMC0053XXXXX
PMC0029XXXXX		 PMC0041XXXXX		  PMC0054XXXXX
PMC002XXXXXX.xml.tar.gz  PMC0042XXXXX		  PMC0055XXXXX
PMC0030XXXXX		 PMC0043XXXXX		  PMC0056XXXXX
PMC0031XXXXX		 PMC0044XXXXX		  PMC005XXXXXX.xml.tar.gz
PMC0032XXXXX		 PMC0045XXXXX

In [5]:
manuscript_files = pd.read_csv('../downloads/ncbi/pmc/manuscript/filelist.csv')

In [6]:
manuscript_files.head()

                          File       PMCID      PMID         MID
0  PMC0021XXXXX/PMC2136438.xml  PMC2136438  19023455  NIHMS10936
1  PMC0021XXXXX/PMC2185066.xml  PMC2185066  18769527  NIHMS31656
2  PMC0022XXXXX/PMC2268633.xml  PMC2268633  17661176  NIHMS37031
3  PMC0022XXXXX/PMC2287164.xml  PMC2287164  18389087  NIHMS38164
4  PMC0022XXXXX/PMC2288569.xml  PMC2288569  18650957  NIHMS40219

In [10]:
import pmc_tables

In [82]:
# import xml.etree.ElementTree as ET
# import re

# count = 0


# def get_tables(root):
#     table_wraps_all = []
#     tables_all = []
#     for child in root:
#         table_wraps = child.findall('*/table-wrap')
#         tables = child.findall('**/table')
#         assert len(table_wraps) == len(tables), (len(table_wraps), len(tables))
#         table_wraps_all.extend(table_wraps)
#         tables_all.extend(tables)
#     return table_wraps_all, tables_all


# def caption_to_string(element):
#     if element is None:
#         return ""
#     element_text = ET.tostring(element, encoding='utf8', method='text').decode('utf-8')
#     element_text = element_text.strip().replace('\n', ' ')
#     element_text = re.sub(' +', ' ', element_text)
#     return element_text


# for i, row in enumerate(manuscript_files.itertuples()):
#     print('\n' + f"{row.File}")

#     results = {}
    
#     tree = ET.parse(MANUSCRIPT_DATA_DIR.joinpath(row.File))
#     tables = tree.findall('.//table')
#     table_wraps = tree.findall('.//table-wrap')
    
#     for table_wrap in table_wraps:
#         print("  " + "-" * 40)
#         id_ = table_wrap.get('id')
#         assert id_ is not None
#         print(f"  id: {id_}")
#         # Attrib
#         attrib_set = set(table_wrap.attrib)
#         if attrib_set - {'id', 'position'}:
#             print(f"tw({id_}): {attrib_set}")
#         # Label
#         label = table_wrap.find('label')
#         label_text = label.text if label is not None else ""
#         print(f"  label_text: {label_text}")
#         # Caption
#         caption = table_wrap.find('caption')
#         caption_text = caption_to_string(caption)
#         print(f"  caption_text: {caption_text}")
#         # Footer
#         footer = table_wrap.find('table-wrap-foot')
#         footer_text = caption_to_string(footer)
#         print(f"  footer_text: {footer_text}")
#         # Other children
#         other_children = [
#             c.tag for c in table_wrap.getchildren() 
#             if c.tag not in ['label', 'caption', 'table', 'table-wrap-foot']
#         ]
#         if other_children:
#             print(other_children)
        
#         # Tables
#         tables = table_wrap.findall('table')
#         for i, table in enumerate(tables):
#             unique = f"{row.PMCID}/{op.basename(row.File)}::{id_}-{i}"
#             assert unique not in results
#             print(f"    unique: {unique}")
#             # Attrib
#             attrib_set = {a for a in table.attrib if a not in ['frame', 'rules']}
#             if attrib_set:
#                 print(attrib_set)
#             # Children
#             children_set = {c.tag for c in table.getchildren() if c.tag not in ['thead', 'tbody']}
#             if children_set:
#                 print(children_set)
#             # DataFrame
#             table_bytes = ET.tostring(table)
#             display(HTML(table_bytes.decode('utf-8')))
#             table_dfs = pd.read_html(table_bytes, na_values=['', '-', '–'])
#             assert len(table_dfs) == 1
#             table_df = table_dfs[0]
#             display(table_df)
#             #
#             table_df_dev = pmc_tables.read_html(table_bytes, na_values=['', '-', '–'])[0]
#             table_df_dev = pmc_tables.process_dataframe(table_df_dev)
#             display(table_df_dev)
                
#     root = tree.getroot()
#     a, b = get_tables(root)
    
#     count += 1
#     if count > 20:
#         break

In [ ]:
import xml.etree.ElementTree as ET
import re

count = 0


def get_tables(root):
    table_wraps_all = []
    tables_all = []
    for child in root:
        table_wraps = child.findall('*/table-wrap')
        tables = child.findall('**/table')
        assert len(table_wraps) == len(tables), (len(table_wraps), len(tables))
        table_wraps_all.extend(table_wraps)
        tables_all.extend(tables)
    return table_wraps_all, tables_all


def caption_to_string(element):
    if element is None:
        return ""
    element_text = ET.tostring(element, encoding='utf8', method='text').decode('utf-8')
    element_text = element_text.strip().replace('\n', ' ')
    element_text = re.sub(' +', ' ', element_text)
    return element_text


def extract_tables_from_xml(xml_file):
    tree = ET.parse(xml_file)
    tables = tree.findall('.//table')
    table_wraps = tree.findall('.//table-wrap')

    data = {}
    
    for table_wrap in table_wraps:
        # Id
        id_ = table_wrap.get('id')
        assert id_ is not None
        logger.debug(f"  id: {id_}")
        # Attrib
        attrib_set = set(table_wrap.attrib)
        if attrib_set - {'id', 'position'}:
            print(f"tw({id_}): {attrib_set}")
        # Label
        label = table_wrap.find('label')
        label_text = label.text if label is not None else ""
        logger.debug(f"  label_text: {label_text}")
        # Caption
        caption = table_wrap.find('caption')
        caption_text = caption_to_string(caption)
        logger.debug(f"  caption_text: {caption_text}")
        # Footer
        footer = table_wrap.find('table-wrap-foot')
        footer_text = caption_to_string(footer)
        logger.debug(f"  footer_text: {footer_text}")
        # Other children
        other_children = [
            c.tag for c in table_wrap.getchildren() 
            if c.tag not in ['label', 'caption', 'table', 'table-wrap-foot']
        ]
        if other_children:
            logger.info(other_children)
        # Tables
        tables = table_wrap.findall('table')
        for i, table in enumerate(tables):
            unique = f"{op.basename(row.File)}::{id_}-{i}"
            assert unique not in results
            logger.debug(f"    unique: {unique}")
            # Attrib
            attrib_set = {a for a in table.attrib if a not in ['frame', 'rules']}
            if attrib_set:
                logger.info(attrib_set)
            # Children
            children_set = {c.tag for c in table.getchildren() if c.tag not in ['thead', 'tbody']}
            if children_set:
                logger.info(children_set)
            # DataFrame
            table_bytes = ET.tostring(table)
            # display(HTML(table_bytes.decode('utf-8')))
            # table_dfs = pd.read_html(table_bytes, na_values=['', '-', '–'])
            # assert len(table_dfs) == 1
            # table_df = table_dfs[0]
            # display(table_df)
            #
            data[unique] = (table_df_dev, {
                'id': id_,
                'file_name': row.File,
                
            })
            try:
                table_df_dev = pmc_tables.read_html(table_bytes, na_values=['', '-', '–'])[0]
                table_df_dev = pmc_tables.process_dataframe(table_df_dev)
                # display(table_df_dev)
                store.put('/' + unique, table_df_dev)
            except:
                pass

In [106]:
store.close()

In [109]:
with pd.HDFStore('pmc-tables-1.h5', 'w') as store:

    for i, row in enumerate(manuscript_files.itertuples()):
        print('\n' + f"{row.File}")

        results = {}
        xml_file = MANUSCRIPT_DATA_DIR.joinpath(row.File)

        count += 1
        if count > 1_000:
            break

PMC0021XXXXX/PMC2136438.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean absolute error (MAE) of prediction for four alternate predictors. The average, minimum and maximum value calculated over 25 simulated rate maps are reported. The last column gives the percentage of simulations where the MAE for the geostatistical methods is lower than for the local empirical Bayes smoother.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Average of the reference risk values and the estimates obtained using four alternate approaches. The average, minimum and maximum value of the statistic calculated over 25 simulated rate maps are reported.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean absolute error (MAE) of prediction of the boundary statistic by five alternate estimators. The average, minimum and maximum MAE calculated over 25 simulated rate maps are reported. The last column gives the percentage of realizations where the MAE for the geostatistical methods is lower than for the local empirical Bayes smoother.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Average of the reference boundary statistic values and the estimates obtained using five alternate approaches. The average, minimum and maximum value of the statistic calculated over 25 simulated rate maps are reported.
  footer_text:

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py:809: FutureWarning: The 'tupleize_cols' argument has been deprecated and will be removed in a future version. Column tuples will then always be converted to MultiIndex.


  self.options, self.engine = self._clean_options(options, engine)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2136438.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2136438.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2136438.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2136438.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

    unique: PMC2136438/PMC2136438.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Average proportion of false positives necessary to the detection of all 67 target edges using three types of neutral models and four estimators for the boundary statistic. The average, minimum and maximum proportions calculated over 25 simulated rate maps are reported. The last column gives the percentage of simulations where the particular method yields the smallest proportion of false positives.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Goodness statistic measuring the agreement between the actual proportion of false positives and the significance level used in tests based on three types of neutral models and four estimators for the boundary statistic. The average, minimum and maximum values calculated over 25 simulated rate maps are reported. The last column gives the percentage of simulations where the particular method yields the largest goodness statistic.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T6-0
  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: Average p-value for the tests conducted over the sets of target and non-target edges. The average, minimum and maximum values calculated over 25 simulated rate maps are reported. The last column reports the ratio of average p-values for non-target versus target edges.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T7-0

PMC0021XXXXX/PMC2185066.xml
  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: Estimation Performance of the Rate Parameters When Different Noise Levels cin Are Added to the Input Function. The Results Are Calculated From 100 Simulation Runs
  footer_text:
    unique: PMC2185066/PMC2185066.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE II
  caption_text: Estimation Performance of the Rate Parameters When Different Noise Level Is Added to the Voxel TACs. The Results Are Calculated From 100 Simulation Runs
  footer_text:
    unique: PMC2185066/PMC2185066.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2136438.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2136438.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2136438.xml::T7-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2185066.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2185066.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2185066.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: TABLE III
  caption_text: Performance of Estimating the Factor Images, in Terms of CC and PM. in Each Parenthesis, the First Number Is the Mean, and the Second Number Is the Corresponding Standard Deviation of the Performance Measure CC or PM. Here, the Noise Level σ2 = 30
  footer_text:
    unique: PMC2185066/PMC2185066.xml::T3-0

PMC0022XXXXX/PMC2268633.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Distribution of deaths by sex and place of birth, NHW residents, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text: * Chronic obstructive pulmonary disease
    unique: PMC2268633/PMC2268633.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T6-0
  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T7-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T7-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T8-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T8
  label_text: Table 8
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T8-0
  ----------------------------------------
  id: T9
  label_text: Table 9
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T9-0
  ----------------------------------------
  id: T10
  label_text: Table 10
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T10-0

PMC0022XXXXX/PMC2287164.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sequence variants
  footer_text:
    unique: PMC2287164/PMC2287164.xml::T1-0

PMC0022XXXXX/PMC2288569.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Oral health characteristics of cohort at age 32 years, by sex and SES
  footer_text: a One participant unable to be classified for the age-32 SES variable. * P < 0.05; ** P < 0.01; *** P < 0.001.
    unique: PMC2288569/PMC2288569.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Distribution of responses to individual OHIP-14 items and mean item scores (n = 924)
  footer_text:
    unique: PMC2288569/PMC2288569.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T9-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2268633.xml::T10-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2287164.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2288569.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2288569.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2288569.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Prevalence, extent and severity of impacts by OHIP-14 subscale and total score (n = 924)
  footer_text:
    unique: PMC2288569/PMC2288569.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Prevalence of impacts (fairly/very often), by sex, oral disease prevalence, self-rated oral health and usual reason for visiting a dentist
  footer_text:
    unique: PMC2288569/PMC2288569.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Prevalence of impacts (fairly/very often), by SES at age 32 years, oral disease prevalence, self-rated oral health and usual reason for visiting a dentist
  footer_text:
    unique: PMC2288569/PMC2288569.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Logistic regression model for prevalence of impacts (‘fairly often’ or ‘very often’) at age 32 years (n = 923) Coeff. Odds ratio 95% CI for OR P-value
  footer_text: −2 Log-likelihood = 896.69; Cox & Snell R2 = 0.11; Nagelkerke R2 = 0.16; Hosmer and Lemeshow chi-squared test = 3.01, d.f. = 8, P = 0.93.
    unique: PMC2288569/PMC2288569.xml::T6-0
  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: Poisson regression models for the extent and severity of impacts (n = 923)
  footer_text: a Ratio of geometric mean values.
    unique: PMC2288569/PMC2288569.xml::T7-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2288569.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2288569.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2288569.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2288569.xml::T7-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2288569.xml::T8-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T8
  label_text: Table 8
  caption_text: International comparisons of prevalence, extent and severity of overall impacts and selected dimensions among dentate adults
  footer_text: a Slade et al. (10). b Estimated for the UK and Australian samples by scrutinizing the data distributions.
    unique: PMC2288569/PMC2288569.xml::T8-0

PMC0022XXXXX/PMC2293303.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Lifetime prevalence associations of gambling types with lifetime onset and persistence of CIDI/DSM-IV pathological gambling (PG)
  footer_text: * Significant at the .05 level, two-sided test. 1 Multivariate model controlling for sex, race-ethnicity, age of first gambling, years since first gambling, and 11 gambling types. 2 Multivariate model controlling for sex, race-ethnicity, aoo of first gambling, aoo of first problem, years since first problem, and 11 gambling types
    unique: PMC2293303/PMC2293303.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Lifetime comorbidity of CIDI/DSM-IV pathological gambling (PG) with other lifetime CIDI/DSM-IV disorders and temporal priorities in age of onset (AOO)
  footer_text: * Significant at the .05 level, two-sided test. 1 The percent of respondents with PG who also meet criteria for the other disorder. 2 The ORs are calculated in the total sample, including respondents who never gambled. The ORs were calculated controlling for age at interview so as to avoid confounding due to time at risk.
    unique: PMC2293303/PMC2293303.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Reciprocal time-lagged associations of temporally primary problem gambling predicting the subsequent first onset of other disorders and of temporally primary other disorders predicting the subsequent first onset of CIDI/DSM-IV PG1

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2293303.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2293303.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2293303.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2323355.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  footer_text: * Significant at the .05 level, two-sided test. 1 Models are bivariate for each disorder and controlling for age, sex, and race-ethnicity. 2 There are no onsets of ADHD, ODD, CD that came after the PG onsets
    unique: PMC2293303/PMC2293303.xml::T3-0

PMC0023XXXXX/PMC2323355.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Selected genes identified by comparison of NE from patients with EAC (N with T) vs. without EAC (N without T). Threshold value set at 2.7; N with T: gene score in the group of patients with esophageal adenocarcinoma; N without T: gene score in the group of patients without esophageal adenocarcinoma. Gene identifiers and gene names are shown in the two leftmost columns.
  footer_text:
    unique: PMC2323355/PMC2323355.xml::T1-0

PMC0023XXXXX/PMC2365750.xml

PMC0023XXXXX/PMC2396881.xml

PMC0024XXXXX/PMC2423936.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of mouse lines, their genotypes and designations
  footer_text: a Wild type mice were homozygous for Trsp and albumin Cre. b Trsp liver knockout mice lacked Trsp in their liver. c A34 transgenic mice carrying 2 copies of the T34→A34 mutant transgene. d G37 transgenic mice carrying 2 copies of the A37→G37 mutant transgene. e G37 transgenic mice carrying 16 copies of the A37→G37 mutant transgene. f Designations used in the text to denote each mouse line.
    unique: PMC2423936/PMC2423936.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Primers for assessing real-time PCRa
  footer_text: a Primers designed for determining real-time PCR of each mRNA examined are shown in the table.
    unique: PMC2423936/PMC2423936.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Transcripts in elevated levels within liver of knockout mice relative to wild type mice a
  footer_text: a Genes elevated ≥ 2.0 fold in ΔTrsp mice compared to Trsp mice with a P-value ≤ 0.05 were assessed and shown in the table. The corresponding transcript levels were also analyzed in A34, G37L and G37H replacement mice relative to Trsp mice. Gene Unigene Accession Number, gene description, fold change with P value, and gene function(s) are shown. Four control and four experimental animals were used for comparing ΔTrsp, A34 and G37L with Trsp, while three control and three experimental animals were used for comparing G37H with Trsp. b Genes are grouped into classes according to function.
    unique: PMC2423936/PMC2423936.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2423936.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2423936.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2423936.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2423936.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Transcripts in reduced levels within liver of knockout mice relative to wild type mice a
  footer_text: a Genes depleted ≥ 2.0 fold in ΔTrsp mice as compared to Trsp mice with a P-value ≤ 0.05 were assessed and shown in the table. The corresponding transcript levels were also analyzed in A34, G37L and G37H replacement mice relative to Trsp mice. Gene Unigene Accession Number, gene description, fold change with P value, and gene function(s) are shown. Four control and four experimental animals were used for comparing ΔTrsp, A34 and G37L with Trsp, while three control and three experimental animals were used for comparing G37H with Trsp. b Genes are grouped into classes according to function.
    unique: PMC2423936/PMC2423936.xml::T4-0

PMC0024XXXXX/PMC2424084.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Characteristics of the Study Sample: Community-dwelling Framingham Heart Study Original Cohort
  footer_text: * Cardiovascular disease= coronary heart disease, stroke, transient ischemic attack, congestive heart failure, or intermittent claudication. Hypertension= blood pressure ≥ 140/90 or on antihypertensive medication treatment. Diabetes=causal blood glucose of 200 mg/dl or greater or treatment with oral hypoglycemic agent or insulin. Depressive symptoms assessed at examinations 22 and 25 with the Center for Epidemiologic Studies Depression Scale (CES-D). A score of 16 or greater defined the presence of depressive symptoms. Medical conditions included any of the following five conditions: diabetes, cardiovascular disease, cancer, chronic obstructive pulmonary disease, and hip fracture. NA= not available as data not collected. Rx=medication treatment
    unique: PMC2424084/PMC2424084.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424084.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424084.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424084.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424084.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Self-reported Prevalence of Functional Limitation or Physical Disability: Framingham Heart Study Original Cohort, Mean Age 82 years
  footer_text: Nagi physical performance scale limitation= some difficulty, a lot of difficulty, unable to do, do not do on physician order Rosow-Breslau functional health scale disability= unable to do. Modified Katz ADL scale disability=human assistance needed, minimally dependent; dependent † At exam 25 this question was asked as part of the modified Katz ADL Scale ‡ At Exams 20 and 25 the question was changed to transferring (getting in and out of a chair) and walking on a level surface about 50 yards
    unique: PMC2424084/PMC2424084.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Sex-specific Trends in Self-reported Functional Limitations and Physical Disability Adjusted for Age
  footer_text:
    unique: PMC2424084/PMC2424084.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Appendix 1
  caption_text: Study Sample: Framingham Original Cohort, Aged 79 to 88, Attending Index Examinations 15, 20, and 25
  footer_text: † Examinations off-site in participants’ homes or nursing homes were not available at examination 15. ‡ The Framingham Disability Study collected physical function data at examination 15.(19;43)
    unique: PMC2424084/PMC2424084.xml::T4-0

PMC0024XXXXX/PMC2424085.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Characteristics of Participants, by Age Group: Health and Retirement Study, 1998
  footer_text: Note. ADL = activities of daily living. IADL = instrumental activities of daily living. ADL include bathing, dressing, eating, transferring, and toileting. IADL include shopping, preparing meals, using the telephone, managing medications, and managing finances.

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424085.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424085.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424090.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424090.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2424090.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

    unique: PMC2424085/PMC2424085.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Harrell's C Statistic of Cox Mortality Models Including Different Risk Factors by Age Groups: Health and Retirement Study, 1998
  footer_text: a Permutation test of whether slope of regression between age group and C statistic = 0.
    unique: PMC2424085/PMC2424085.xml::T2-0

PMC0024XXXXX/PMC2424090.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of those who died compared to those who did not die during follow-up.
  footer_text: a CES-D = Center for Epidemiologic Studies Depression Scale – Short Form
    unique: PMC2424090/PMC2424090.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Relative risk of mortality associated with perceived discrimination
  footer_text: Hazard ratios and 95% confidence interval; Hazard ratios are estimated from separate models adjusted for age, sex, race, race*age, and lifetime SES.
    unique: PMC2424090/PMC2424090.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Relative risk of mortality associated with unfair treatment and personal rejection
  footer_text: Hazard ratios and 95% confidence interval; Hazard ratios are estimated from separate models adjusted for age, sex, race, race*age, and lifetime SES.
    unique: PMC2424090/PMC2424090.xml::T3-0

PMC0024XXXXX/PMC2430055.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Peripheral blood cell counts in 10-month post-transplant animals
  footer_text: Data shown are mean (±SD) values from three to five mice per genotype * p<0.05, ** p<0.005 when compared to wild type VEX
    unique: PMC2430055/PMC2430055.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Differential counts of sorted VEX (+) myeloid cells from 10-month post-transplant animals
  footer_text: Data shown are percentages of >250 cells counted per sample. Blast/Pro: myeloblast and promyelocytes; Myelo: myelocytes; Band: band-form granulocytes; Eos: eosinophils; Mono: monocytes
    unique: PMC2430055/PMC2430055.xml::T2-0

PMC0024XXXXX/PMC2430763.xml

PMC0024XXXXX/PMC2435206.xml

PMC0024XXXXX/PMC2435220.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Counts of edge classification results
  footer_text:
    unique: PMC2435220/PMC2435220.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Accuracy and error statistics for boundary classification using the little b and polygon wombling approaches
  footer_text:
    unique: PMC2435220/PMC2435220.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Counts from classification table for Big B, Ladder and Local Moran methods
  footer_text:
    unique: PMC2435220/PMC2435220.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Specificity, Type I and Type II error, and sensitivity of the Big B, Ladder and Local Moran methods
  footer_text:
    unique: PMC2435220/PMC2435220.xml::T4-0

PMC0024XXXXX/PMC2435384.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Average ± SD values (%) of degree of substitution (DS) and purity of the MPS-peptide-dextran conjugates (n = 3).
  footer_text:
    unique: PMC2435384/PMC2435384.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Inter-run accuracy (%Error) and precision (%CV) of the reversed-phase assay (n =5)
  footer_text:
    unique: PMC2435384/PMC2435384.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean ± SD values of degradation half lives (h) of DMP conjugates in pH 7.4 buffer and rat blood (n = 3).
  footer_text: a–j Means with similar letters are significantly different each other: ANOVA with post-hoc Scheffe test..
    unique: PMC2435384/PMC2435384.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2430055.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2430055.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435220.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435220.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435220.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435220.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435384.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435384.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435384.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435391.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2435391.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Human IBD patient description
  footer_text: NOTE. CD; Crohn’s disease, UC; ulcerative colitis, Sm Intest; small intestine.
    unique: PMC2435391/PMC2435391.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Gene expression analysis in the colon of Hnf4αF/F and Hnf4αΔIEpC mice
  footer_text: NOTE. Quantitative real-time PCR of colon mRNA from 2-month-old mice (n=6). All the values are means ± SD. Significant difference compared to Hnf4αF/F mice: * , p< 0.05 ** , p< 0.01 *** , p< 0.001.
    unique: PMC2435391/PMC2435391.xml::T2-0

PMC0024XXXXX/PMC2435511.xml

PMC0024XXXXX/PMC2440269.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Percent of Potentially Eligible Subjects Rejected by Reason for Exclusion
  footer_text:
    unique: PMC2440269/PMC2440269.xml::T1-0

PMC0024XXXXX/PMC2440297.xml

PMC0024XXXXX/PMC2440637.xml

PMC0024XXXXX/PMC2440700.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of mean lifespan and its components in all experimental groups
  footer_text:

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2435391.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2440700.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2440700.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

    unique: PMC2440700/PMC2440700.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Cox regression results (hazard ratio and Wald statistics) of potentially influential factors for lifespan, AFF* and flightspan*
  footer_text: * limited sampling in experiment 4 precluded meaningful calculations
    unique: PMC2440700/PMC2440700.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mortality models based on the experimental data (λ: initial mortality, γ: rate of exponential mortality increase, s: mortality deceleration)
  footer_text:
    unique: PMC2440700/PMC2440700.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Brood production (relative brood production) during the initial three experimental weeks
  footer_text:
    unique: PMC2440700/PMC2440700.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Comparison of mean lifespan, AFF, and flightspan relative to brood production in all experimental groups
  footer_text:
    unique: PMC2440700/PMC2440700.xml::T5-0

PMC0024XXXXX/PMC2441880.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographics of Asian-American current and former smokers, California Health Interview Study, 2003
  footer_text: a Significance for women * p≤0.0001; ** p≤0.01; *** p≤0.05; **** p≤0.001 cpd, cigarettes per day; div, divorced; HS, high school; sep, separated; wid, widowed
    unique: PMC2441880/PMC2441880.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2440700.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2440700.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2440700.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2441880.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Multivariate logistic analysis of factors associated with former or lighter smoking among Asian Americans, California Health Interview Study, 2003
  footer_text: a The p-value for interaction comparing effects of smoke-free home among long-term residents vs smoke-free home among recent immigrants for (1) former vs current smoker outcome is p=0.02 and (2) lighter vs heavier smoker outcome is p=0.03. Reference group for each category reflects having smoke-free home for the respective category of years in U.S. cpd, cigarettes per day; HS, high school; yrs, years
    unique: PMC2441880/PMC2441880.xml::T2-0

PMC0024XXXXX/PMC2441916.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Quantitation of Th1 and Th2 IS formed on supported planar bilayersa
  footer_text: a Quantitation of data from Figs. 1 and 2 (100 μM) and Fig. 5 (10 and 1 μM).
    unique: PMC2441916/PMC2441916.xml::T1-0

PMC0024XXXXX/PMC2443692.xml

PMC0024XXXXX/PMC2443732.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Organic Acids Sulfated In Situ to Identify the Urinary Negative Ion of 230.996 m/z
  footer_text:
    unique: PMC2443732/PMC2443732.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2441880.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2441916.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2443732.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2443732.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Identification of Mouse Urinary Biomarkers after 3 Gy γ Radiation
  footer_text:
    unique: PMC2443732/PMC2443732.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Identification of Mouse Urinary Biomarkers after 8 Gy γ Radiation
  footer_text:
    unique: PMC2443732/PMC2443732.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: TABLE 4
  caption_text: Historical Biomarkers of Radiation Exposure
  footer_text: Notes. 1[M-H]−(± 10 ppm) either not detected or not statistically significantly different (P ≥ 0.05) according to exposure status; 2[M-H]−(± 10 ppm) elevated (P < 0.05) in urine from mice exposed to 3 Gy; 3[M-H]−(± 10 ppm) elevated (P < 0.05) in urine from mice exposed to 8 Gy; 4[M-H]−(± 10 ppm) elevated (P < 0.05) in urine from mice both exposed to 3 and 8 Gy. All comparisons made with mean creatinine-normalized relative concentrations by t test with α = 0.05.
    unique: PMC2443732/PMC2443732.xml::T4-0

PMC0024XXXXX/PMC2444046.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Nine CRM community readiness stages [9]
  footer_text:
    unique: PMC2444046/PMC2444046.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2443732.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2443732.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2444046.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2444046.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2444046.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Aggregate community readiness results
  footer_text: Note: All tests of significance are significant, p < .05, two-tailed. All tests of significance are based on 60 dfs. Effect Size: Effect sizes are reported as Cohen’s D. Cohen [35] has suggested the following guidelines for interpreting the magnitude of D: .20=Small; .50=Medium; .80=Large.
    unique: PMC2444046/PMC2444046.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Community readiness scores by community, pre- and post-intervention
  footer_text: * Note: Following the CRM protocol [9], overall readiness stages are truncated or rounded down to the lower integer.
    unique: PMC2444046/PMC2444046.xml::T3-0

PMC0024XXXXX/PMC2446451.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: A full factorial design for four components (factors) each at two levels (four columns A–D) and their interactions
  footer_text:
    unique: PMC2446451/PMC2446451.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Number of groups in a two-level full factorial design as the number of factors increase
  footer_text:
    unique: PMC2446451/PMC2446451.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: FFD for the Guide to Decide Project
  footer_text:
    unique: PMC2446451/PMC2446451.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2446451.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2446451.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2446451.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2446451.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2446469.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2446469.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Analysis of participants’ knowledge scores*
  footer_text: * Analysis controls for participants’ numeracy score. The main effect “Pictograph” is included even though it is not important because it has significant interactions with other factors.
    unique: PMC2446451/PMC2446451.xml::T4-0

PMC0024XXXXX/PMC2446469.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Participant Characteristics by Wave: Baltimore Epidemiological Catchment Area Study, Baltimore, MD, 1981–2005
  footer_text: Note. MDD = major depressive disorder. Because of missing data, n = 3332 at wave 1, n = 2743 at wave 2, n = 1801 at wave 3, and n = 1037 at wave 4. P values are from the χ2 (categorical variables) or t test (continuous variables) for MDD vs no MDD within each wave. *** P < .01; † P < .001.
    unique: PMC2446469/PMC2446469.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Incidence of Type 2 Diabetes per 1000 Person-Years, by Age Group at Wave 3 and Depression Status: Baltimore Epidemiological Catchment Area Study, Baltimore, MD, 1993–1996
  footer_text: Note. MDD = major depressive disorder.
    unique: PMC2446469/PMC2446469.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Association of Depression and Risk of Type 2 Diabetes: Baltimore Epidemiological Catchment Area Study, Baltimore, MD, 1981–2005
  footer_text: Note. MDD = major depressive disorder; HR = hazard ratio; CI = confidence interval. Reference category for all models was never diagnosed with MDD. a Model 1 adjusted for age, race, gender, education, and body mass index. Model 2 added family history of diabetes to model 1. Model 3 added smoking status, alcohol use, stairs climbed per day, and frequency of eating balanced meals to model 2. Model 4 added frequency of social contact with relatives to model 3. b Model 1 adjusted for age, race, gender, and education. Model 2 added smoking status and alcohol use to model 1. Model 3 added social network size to model 2. Model 4 added antidepressant use to model 3. * P < .10; ** P < .05.
    unique: PMC2446469/PMC2446469.xml::T3-0

PMC0024XXXXX/PMC2453010.xml

PMC0024XXXXX/PMC2453029.xml
  ----------------------------------------
  id: T1
  label_text: Table 1

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2446469.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453029.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453029.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453029.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  caption_text: Intake of soy isoflavones and breast cancer risk
  footer_text: a Adjusted for age, years of interview, dialect, education, family history of breast cancer, parity, age when period became regular, menopausal status (if applicable), body mass index, and n-3 fatty acid.
    unique: PMC2453029/PMC2453029.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Intake of soy isoflavones and breast cancer risk in postmenopausal women by body mass index
  footer_text: a Adjusted for age, years of interview, dialect, education, family history of breast cancer, parity, age when period became regular, body mass index, and n-3 fatty acid.
    unique: PMC2453029/PMC2453029.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Intake of soy isoflavones and breast cancer risk (RR, 95% CI)a in postmenopausal women by oestrogen receptor (ER) and progesterone receptor (PR) status
  footer_text: a Adjusted for age, years of interview, dialect, education, family history of breast cancer, parity, age when period became regular, body mass index, and n-3 fatty acid. b We did not include breast cancers that were ER+ PR− (n = 57), ER+PR unknown (n = 1), ER−PR+ (n = 4) or ER − PR unknown (n = 2) in the analysis.
    unique: PMC2453029/PMC2453029.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Intake of soy isoflavones and breast cancer risk by the length of follow-up
  footer_text: a Adjusted for age, years of interview, dialect, education, family history of breast cancer, parity, age when period became regular, menopausal status (if applicable), body mass index, and n-3 fatty acid.
    unique: PMC2453029/PMC2453029.xml::T4-0

PMC0024XXXXX/PMC2453069.xml

PMC0024XXXXX/PMC2453243.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453029.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2453677.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline characteristics and risk factors for cardiovascular disease and/or diabetes of study participants randomized to ILS or placebo
  footer_text: Data are medians ± interquartile range unless otherwise indicated. Twenty Pacific Islanders were included in the “Asian” group. Physical activity data are based on responses to the Modifiable Activity Questionnaire. MET-hours represent the average amount of time engaged in specified physical activities multiplied by the MET value of each activity. BP, blood pressure; HRT, hormone replacement therapy; TG, triglyceride. * P < 0.01, men vs. women † P < 0.05, men vs. women.
    unique: PMC2453677/PMC2453677.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Percent change in risk factors for cardiovascular disease and diabetes over year 1 in those randomized to placebo
  footer_text: Data are medians ± interquartile range. BP, blood pressure; TG, triglyceride. † P < 0.05, men vs. women.
    unique: PMC2453677/PMC2453677.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Percent change in risk factors for cardiovascular disease and diabetes over year 1 in those randomized to ILS
  footer_text: Data are medians ± interquartile range. BP, blood pressure; TG, triglyceride. * P < 0.01, men vs. women † P < 0.05, men vs. women.
    unique: PMC2453677/PMC2453677.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453677.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453677.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453677.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453683.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2453683.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of study participants within different BMI categories. Data shown as mean ± standard deviation for continuous variables, and n (percent) for dichotomous variables
  footer_text: Abbreviations: BMI, body mass index; SD, standard deviation, LDL, low-density lipoprotein; HDL, high-density lipoprotein; WC, waist circumference SI conversion factors: To convert glucose to mmol/L, multiply mg/dL values by 0.0555; total, LDL and HDL cholesterol to mmol/L, multiply mg/dL values by 0.0259; triglycerides to mmol/L, multiply mg/dL values by 0.0113 * Global GEE age- and sex-adjusted p-value, except for age which is sex-adjusted and sex, which is age-adjusted
    unique: PMC2453683/PMC2453683.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Age-and sex-adjusted rates of hypertension, elevated levels of low lipoprotein cholesterol, type 2 diabetes, treatment and control among BMI categories
  footer_text: Abbreviations: CI, confidence interval; BMI, body mass index; LDL-C, low-density lipoprotein cholesterol; Hb A1c, Hemoglobin A1c level; FPG, fasting plasma glucose SI conversion factor: To convert fasting plasma glucose to mmol/L, multiply mg/dL values by 0.0555 * Global GEE p-value † Data only available for Offspring cohort
    unique: PMC2453683/PMC2453683.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Online Appendix Table 1
  caption_text: Age-and sex-adjusted rates of hypertension, elevated levels of low-density lipoprotein cholesterol, type 2 diabetes, treatment and control among WC categories
  footer_text: Abbreviations: CI, confidence interval; WC, waist circumference; LDL-C, low-density lipoprotein cholesterol; Hb A1c, Hemoglobin A1c level; FPG, fasting plasma glucose SI conversion factor: To convert fasting plasma glucose to mmol/L, multiply mg/dL values by 0.0555 * Global GEE p-value † Data only available for Offspring cohort
    unique: PMC2453683/PMC2453683.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Online Appendix Table 2
  caption_text: Sex-adjusted rates of hypertension, elevated levels of low lipoprotein cholesterol, type 2 diabetes, treatment and control among BMI categories, stratified by age
  footer_text: Abbreviations: CI, confidence interval; BMI, body mass index; LDL-C, low-density lipoprotein cholesterol; Hb A1c, Hemoglobin A1c level; FPG, fasting plasma glucose SI conversion factor: To convert fasting plasma glucose to mmol/L, multiply mg/dL values by 0.0555 * Global GEE p-value † Among participants younger than 50 years of age with a BMI 18.5-<25, there were only 5 individuals with diabetes mellitus. Of those, 5 received hypoglycemic treatment and 3 had FPG <126 mg/dL ‡ Interpret p-value with caution as there are only small number in the cells of participants younger than 50 years of age with a BMI 18.5-<25
    unique: PMC2453683/PMC2453683.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453683.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453683.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453683.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2453683.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T5
  label_text: Online Appendix Table 3
  caption_text: Age-adjusted rates of hypertension, elevated levels of low-density lipoprotein cholesterol, type 2 diabetes, treatment and control among BMI categories, stratified by sex
  footer_text: Abbreviations: CI, confidence interval; BMI, body mass index; LDL-C, low-density lipoprotein cholesterol; Hb A1c, Hemoglobin A1c level; FPG, fasting plasma glucose SI conversion factor: To convert fasting plasma glucose to mmol/L, multiply mg/dL values by 0.0555 * Global GEE p-value † Global ANOVA p-value
    unique: PMC2453683/PMC2453683.xml::T5-0

PMC0024XXXXX/PMC2459142.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic characteristics of the resident-level sample population and by gender
  footer_text: a Indicates a test performed using either independent t-test for gender differences in means or a test in differences in proportions, p<0.05 (2-tailed). b This is measured out of nine possible common medical conditions (e.g., diabetes, hypertension, depression). * p<0.05
    unique: PMC2459142/PMC2459142.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Neighborhood-level random components from multilevel Poisson regression models
  footer_text: a Random coefficient (variance) at the neighborhood level-variance in Model 0 represents random variation in neighborhoods whereas variance in Model 1 through Model 3 denote residual variance conditional on model covariates/predictors. b Intraclass correlations (ICC) is defined as a ratio of between-neighborhood variability/(between-neighborhood variability + within-neighborhood variability). c Model 0: unconditional model (i.e., no level-specific predictors/covariates); Model 1: model with only individual-level covariates; Model 2: model with both individual- and neighborhood-level covariates; Model 3: model with both individual- and neighborhood-level covariates and key built-environment predictors. d This is the proportion of variance explained at neighborhood level after addition of the neighborhood-level key built-environment variables, calculated as: {variance (Model 2)–variance (Model 3)/variance (Model 2), where variance (Model 2) represents the total between-neighborhood-level variance that can be explained by addition of the between-neighborhood variables. * p<0.05; ** p<0.001
    unique: PMC2459142/PMC2459142.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2459142.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2459142.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2459142.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Adjusted estimates of neighborhood-level Poisson regression model analyses: associations between built-environment factors, overweight/obese, and various forms of physical activitya
  footer_text: a Adjusting for neighborhood-level covariates of residential density, median household income, percentage of African-American and Hispanic residents, and resident-level covariates of age, gender, race/ethnicity, employment status, home ownership, household income, health status, fruit and vegetable intake, fried-food consumption, and BMI. b Prevalence=exp (coefficient).
    unique: PMC2459142/PMC2459142.xml::T3-0

PMC0024XXXXX/PMC2459287.xml

PMC0024XXXXX/PMC2464454.xml

PMC0024XXXXX/PMC2464569.xml

PMC0024XXXXX/PMC2475592.xml

PMC0024XXXXX/PMC2475600.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: G6PC mutations accounting for GSD-Ia
  footer_text: Numbering according to cDNA sequence in Lei et al. [1993], GeneBank Accession Number U01120. Nucleotide +1 is the A of the ATG initiation codon (which is codon +1). The domains for missense and nonsense mutations are based on the finding that human G6PC is anchored in the ER by 9 transmambrane helices [Pan et al., 1998a, 1998c]. NH2, amino terminal domain; H, helical transmembrane domain; C, cytoplasmic loop; L, luminal loop; AS, active site; COOH, carboxyl terminal domain.
    unique: PMC2475600/PMC2475600.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2475600.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2475600.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Prevalent G6PC mutations in GSD-Ia patients
  footer_text:
    unique: PMC2475600/PMC2475600.xml::T2-0

PMC0024XXXXX/PMC2475702.xml

PMC0024XXXXX/PMC2475706.xml

PMC0024XXXXX/PMC2478639.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Consensus radiation dose-response signature
  footer_text: * not in time-independent dose signature - overlap of 6hr and 24hr signatures only. 1 Data from (6); X= gene not present on array; no=no change in prior experiment; YES= same direction change in prior experiment. 2 Data from (8); X= gene not present on array; no=no change in prior experiment; YES= same direction change in prior experiment. 3 Data from (15); YES= reported in human radiation signature. (All genes presumed to be tested since whole genome platform was used.) 4 Literature search for TP53 regulation of genes using MedMiner (31). No= no reported relationship found; YES= reported regulation by p53.
    unique: PMC2478639/PMC2478639.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2478639.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2478639.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2480524.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2480524.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2480524.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Performance of the 74-gene classifier in predicting all five doses for samples assayed six and 24 hours after exposure (upper) or for predicting four dose ranges for the same samples (lower).
  footer_text:
    unique: PMC2478639/PMC2478639.xml::T2-0

PMC0024XXXXX/PMC2478698.xml

PMC0024XXXXX/PMC2480524.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Means (and standard deviations) of numbers of items observed eaten (in any amount more than none), and numbers of items reported eaten (in any amount more than none), for two school meals (breakfast, lunch), over children in the four groups 1,2
  footer_text: 1 F-MPD interviews used Forward-order prompts (morning-to-evening) for meals/snacks eaten and were conducted in the Morning about the Previous Day’s intake; R-MPD interviews used Reverse-order prompts (evening-to-morning) for meals/snacks eaten and were conducted in the Morning about the Previous Day’s intake; F-ESD interviews used Forward-order prompts for meals/snacks eaten and were conducted in the Evening about that Same Day’s intake. 2 Means on the same row with different superscript letters differed significantly. 3 Analysis of variance failed to detect a significant difference in the numbers of items observed eaten between the four groups, F (3, 282) = 0.63, p = 0.5946. 4 Analysis of variance detected a significant difference in the numbers of items reported eaten between the four groups, F (3, 282) = 3.94, p = 0.0089. Post-hoc two-sample t tests indicated that significantly more items were reported eaten for F-MPD1 interviews than for R-MPD interviews, t(161) = 2.9628, p = 0.0035, and for F-ESD interviews than for R-MPD interviews t(125) = 2.7956, p = 0.0060.
    unique: PMC2480524/PMC2480524.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Number (and percent) of types of intrusion1 – stretch and confabulation2 – for each of four groups3 by meal component
  footer_text: 1 An intrusion is an item that was reported eaten but was not observed eaten at that school meal. Examples of items reported eaten that were classified as intrusions because they differed from items observed eaten included fruit juices (e.g., apple observed, orange reported), milk flavors (e.g., white observed, chocolate reported), dry cereals (e.g., flake-shaped observed, donut-shaped reported), and vegetables (e.g., broccoli observed, green beans reported). Examples of items reported eaten that were classified as matches because they were similar to items observed eaten included all types of pizza (e.g., cheese, pepperoni) and all types of white milk (e.g., whole, 1%, skim). 2 An intrusion was further classified either as a stretch if it referred to an item that was observed on the child’s tray for that meal, but for which the amount observed eaten was none, or as a confabulation if it referred to an item that was not observed on the child’s tray for that meal. 3 F-MPD interviews used Forward-order prompts (morning-to-evening) for meals/snacks eaten and were conducted in the Morning about the Previous Day’s intake; R-MPD interviews used Reverse-order prompts (evening-to-morning) for meals/snacks eaten and were conducted in the Morning about the Previous Day’s intake; F-ESD interviews used Forward-order prompts for meals/snacks eaten and were conducted in the Evening about that Same Day’s intake.
    unique: PMC2480524/PMC2480524.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Predicted probabilities (and standard errors) from logistic regression models of the likelihood that reported items were intrusions, confabulations, and stretches, and the likelihood that intrusions were confabulations, for each of the four groups 1,2,3
  footer_text: 1 F-MPD interviews used Forward-order prompts (morning-to-evening) for meals/snacks eaten and were conducted in the Morning about the Previous Day’s intake; R-MPD interviews used Reverse-order prompts (evening-to-morning) for meals/snacks eaten and were conducted in the Morning about the Previous Day’s intake; F-ESD interviews used Forward-order prompts for meals/snacks eaten and were conducted in the Evening about that Same Day’s intake. Intrusions were items reported as eaten that had not been observed eaten at that meal. Confabulations were intrusions that were not observed on the child’s meal tray. Stretches were intrusions that were observed on the child’s meal tray 2 For each school meal, observed amounts and reported amounts for each item were recorded in terms of servings of standardized school portions. A reported item was an intrusion if the amount reported eaten was any amount more than none when the observation indicated that none of the item was eaten. 3 Predicted probabilities on the same row with different superscript letters differed significantly. 4 F-MPD1 versus F-ESD (p < 0.001); F-MPD2 versus F-ESD (p < 0.001); R-MPD versus F-ESD (p = 0.002); F-MPD1 versus R-MPD (p = 0.0102). 5 F-MPD1 versus F-ESD (p < 0.001); F-MPD2 versus F-ESD (p < 0.001); R-MPD versus F-ESD (p < 0.001); F-MPD1 versus R-MPD (p = 0.0165). 6 No significant differences. 7 F-MPD1 versus F-ESD (p < 0.001); F-MPD2 versus F-ESD (p = 0.001); R-MPD versus F-ESD (p = 0.011). Furthermore, the likelihood that an intrusion was a confabulation was significantly higher for White children than for Black children (p = 0.032).
    unique: PMC2480524/PMC2480524.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Number (and percent) of liking ratings1 for each of the four groups2 by item classification3 (match, omission, stretch, confabulation)
  footer_text: 1 Refer to the Appendix for the specific prompts used to obtain liking ratings for each study. 2 F-MPD interviews used Forward-order prompts (morning-to-evening) for meals/snacks eaten and were conducted in the Morning about the Previous Day’s intake; R-MPD interviews used Reverse-order prompts (evening-to-morning) for meals/snacks eaten and were conducted in the Morning about the Previous Day’s intake; F-ESD interviews used Forward-order prompts for meals/snacks eaten and were conducted in the Evening about that Same Day’s intake. 3 A match was an item that was observed eaten (in any amount more than none) and reported eaten (in any amount more than none) at a meal. An omission was an item that was observed eaten (in any amount more than none) but not reported eaten at a meal. An intrusion (an item reported eaten [in any amount more than none] that was not observed eaten) was further classified either as a stretch if it referred to an item that was observed on the tray for that meal, but for which the amount observed eaten was none, or as a confabulation if it referred to an item that was not observed on the tray for that meal. 4 A liking rating was not obtained for 12 matches, 88 omissions, 1 stretch, and 12 confabulations.
    unique: PMC2480524/PMC2480524.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2480524.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2480524.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2481383.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2481507.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2481507.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T5
  label_text:
  caption_text: Details by study relevant to the current analyses
  footer_text: 1 For inter-reviewer reliability (IRR), one dietitian interviewed a child while the other dietitian(s) sat behind the child and completed an interview form according to what was heard. At the end of the interview, the listening dietitian(s) could ask the child questions. Results on 8 children indicated that only one additional question would have been asked if a different dietitian had conducted the interview. (These 8 interviews were used for IRR only.) In addition, the Principal Investigator (PI) assessed QCI by reviewing the interview form, audio recording, and typed transcript for a random 5% of each dietitian’s interviews and verified adherence to the interview protocol across dietitians. 2 The interview form, audio recording, and typed transcript from one interview conducted each week by each interviewer was randomly selected and reviewed by another interviewer who completed a QCI checklist by marking adequate, needs improvement, or not applicable for each of 53 items. Each QCI checklist was reviewed by the PI and interviewer. Across 51 QCI checklists (21% of the 242 interviews), 95% of items (2,133 of 2,249) that were not rated not applicable were rated adequate; this indicates that interviewers adequately followed the interview protocols. 3 The interview form, audio recording, and typed transcript from one interview conducted each evening was randomly selected and reviewed by another dietitian, who completed a QCI checklist by marking adequate, needs improvement, or not applicable for each of 56 items. Each QCI checklist was reviewed by the PI and interviewer. Across 22 QCI checklists (32% of the 69 interviews), 97% of items (937 of 970) that were not rated not applicable were rated adequate; this indicates that interviewers adequately followed the interview protocols. 4 Omission rate = (omissions / omissions + matches)× 100; it is the proportion of items observed eaten but not reported eaten. Values range from 0% to 100%, with higher rates indicating more omissions. 100% − omission rate = Match rate. 5 In the original publications of the three validation studies, items were given meal-component weights (combination entrée = 2, condiment = 0.33, remaining meal components = 1) so that errors for condiments (e.g., ketchup) counted less than errors for most meal components, and errors for combination entrées (e.g., cheeseburger) counted more. 6 Intrusion rate = (intrusions / intrusions + matches)× 100; it is the proportion of items reported eaten but not observed eaten. Values range from 0% to 100%, with higher rates indicating more intrusions.
    unique: PMC2480524/PMC2480524.xml::T5-0

PMC0024XXXXX/PMC2481383.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Pediatric modified RIFLE (pRIFLE) criteria
  footer_text:
    unique: PMC2481383/PMC2481383.xml::T1-0

PMC0024XXXXX/PMC2481507.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Coding of fields
  footer_text:
    unique: PMC2481507/PMC2481507.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Concordance between clinicians and interviewers
  footer_text: a Calculated using only cases with entries from both data sources. b Excludes patients classified as “other” or “multi-ethnic”.
    unique: PMC2481507/PMC2481507.xml::T2-0

PMC0024XXXXX/PMC2481516.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Strata of the distal medulla and their lamina cell terminals
  footer_text: Data from Fischbach and Dittrich (1989) and Bausenwein et al. (1992)
    unique: PMC2481516/PMC2481516.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Numbers of pre- and postsynaptic sites at medulla terminals
  footer_text: 1 Difference between highest and lowest number, as percentage of mean. All seven cells were located in all three columns. We had difficulty however to find the processes of remaining cells, especially C2, in all columns. As a result it remains a formal possibility that these cells are not present in all columns.
    unique: PMC2481516/PMC2481516.xml::T2-0

PMC0024XXXXX/PMC2483306.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Estimation for parameters in the Markov model
  footer_text: IDU, injection drug user; HCC, hepatocellular carcinoma
    unique: PMC2483306/PMC2483306.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2483306.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2483306.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2483306.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2488963.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Medical costs of hepatitis B-associated illnesses and vaccination costs
  footer_text: a All medical costs are expressed in 2003 U.S. dollars. b Only medical costs for acute infection are one-time costs.
    unique: PMC2483306/PMC2483306.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: The baseline cost–benefit result of the syringe exchange program-delivered hepatitis B vaccination involving 1964 IDUs in Chicago IL and Hartford and Bridgeport CT
  footer_text: HBV, hepatitis B virus; IDU, injection drug user; QALY, quality-adjusted life year
    unique: PMC2483306/PMC2483306.xml::T3-0

PMC0024XXXXX/PMC2484123.xml

PMC0024XXXXX/PMC2488960.xml

PMC0024XXXXX/PMC2488962.xml

PMC0024XXXXX/PMC2488963.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: BHandHLYP/6-311G**, CCSD(T)/aug-cc-pVDZ, CCSD(T)/aug-cc-pVTZ and BD(T)/aug-cc-pVDZ Changes in Energy.1
  footer_text: 1 Energies computed using BHandHLYP/6-311G** optimized geometries. All values are in kcal·mol−1. 2 Zero-point vibration corrected electronic energy. 3 Energies are relative to isoprene’s global minima, the s-trans conformation. 4 Energies are relative to isoprene’s s-gauche conformation.
    unique: PMC2488963/PMC2488963.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: CCSD(T)/aug-cc-pVDZ and BD(T)/aug-cc-pVDZ Changes in Energy from Reactants to Pre-reactive Complexes.1
  footer_text: 1 Energies computed using BHandHLYP/6-311G** optimized geometries. All values are in kcal·mol−1. 2 Zero-point vibration corrected electronic energy.
    unique: PMC2488963/PMC2488963.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2488963.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2488963.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2488963.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491345.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: CCSD(T)/aug-cc-pVDZ and BD(T)/aug-cc-pVDZ Energies of Activation, relative to the reactants.1
  footer_text: 1 Energies computed using BHandHLYP/6-311G** optimized geometries. All values are in kcal·mol−1. 2 Zero-point vibration corrected electronic energy. 3 Calculated using Transition State Theory where Ea = ΔH°‡ + 2RT.
    unique: PMC2488963/PMC2488963.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: CCSD(T)/aug-cc-pVDZ and BD(T)/aug-cc-pVDZ Energies of Reaction, relative to reactants.1
  footer_text: 1 Energies computed using BHandHLYP/6-311G* * optimized geometries. All values are in kcal·mol−1. 2 Zero-point vibration corrected electronic energy.
    unique: PMC2488963/PMC2488963.xml::T4-0

PMC0024XXXXX/PMC2491345.xml
  ----------------------------------------
  id: T1
tw(T1): {'id', 'orientation', 'position'}
  label_text: Table 1
  caption_text: Methylation of Polycomb target genes during inflammation, aging and cancer
  footer_text: a Genes hypermethylated in the ileum of 8-month-old Gpx-1/2-KO mice versus non-DKO controls b Genes hypermethylated in the ileum of 8-month-old control mice versus 28-day-old control mice c Genes hypermethylated in tumors of B6;129 Gpx-1/2-KO mice d Genes affected by DNA methylation only in tumors e No expression, zero EST counts; low expression, 1–2 EST counts; Yes, 3 or more EST counts in mouse intestinal tissue. The total numbers in this Table were adjusted since for several genes Polycomb binding or expression data were not available. PcG data are from Boyer et al. (ref. 11).
    unique: PMC2491345/PMC2491345.xml::T1-0

PMC0024XXXXX/PMC2491491.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Descriptive Statistics for Seattle and Tahoma High Capacity School Buses in the 2005−2006 School Year (>50 Seats)
  footer_text: Continuous data are presented as the overall mean (SD). a Summarized values for subject buses represent the students' typical buses although substitute buses are occasionally used during periods of servicing or vehicle inspection. b Descriptive statistics presented for buses with valid data only. c 25% and 27% of all Seattle buses and Seattle subject buses, respectively, were retrofit with aftermarket DOCs. All other DOCs were original equipment installed by the manufacturer. d Remaining buses have unknown engine types.
    unique: PMC2491491/PMC2491491.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491491.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491491.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491491.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491491.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491491.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: PM2.5 Concentrations (μg/m3) Measured Aboard the Bus, Lead Vehicle, and Estimates of Self Pollution
  footer_text: a Paired trips imply that a bus and lead vehicle drove the same route simultaneously.
    unique: PMC2491491/PMC2491491.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Mean (SD) Characteristics of Ambient and Trip Conditions During Monitored Bus Trips
  footer_text:
    unique: PMC2491491/PMC2491491.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: TABLE 4
  caption_text: Ordinary Least Squares Multivariate Regression Results for Roadway Concentrations (CLV, μg/m3)
  footer_text:
    unique: PMC2491491/PMC2491491.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Ordinary Least Squares Multivariate Regression Results For In-Cabin Concentrations (Cbus, μg/m3
  footer_text:
    unique: PMC2491491/PMC2491491.xml::T5-0

PMC0024XXXXX/PMC2491716.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Subject characteristics
  footer_text: a FEV1: forced expiratory volume in 1 s. b PC20: provocative dose of methacholine causing a 20% fall in FEV1.
    unique: PMC2491716/PMC2491716.xml::T1-0

PMC0024XXXXX/PMC2491717.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Prevalence of demographic characteristics, high depressive symptomatology, and sexual debut timing in the study population
  footer_text: a High depressive symptomatology was based on scoring at or above the proportionately adjusted cutpoint on the modified Center for Epidemiologic Studies Depression scale (range 0–27). The cutpoints are 10 for males and 11 for females. b Sexual debut prior to age sixteen was classified as early, debut between ages 16 and 18 was classified as typical, and debut after age 18 (including those who did not debut by Wave III interview) was classified as late.
    unique: PMC2491717/PMC2491717.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Sexual debut timing and emerging adult depressive symptomatology: Logistic regression results, Female Participants
  footer_text: a High depressive symptomatology was based on scoring at or above the proportionately adjusted depression cutpoint on the modified Center for Epidemiologic Studies Depression scale (range 0–27). The cutpoints are 10 for males and 11 for females. b Sexual debut prior to age sixteen was classified as early, debut between ages 16 and 18 was classified as typical, debut after age 18 (including those who did not debut by Wave III interview) was classified as late. c For multi-category predictor variables, p-values refer to joint tests of statistical significance
    unique: PMC2491717/PMC2491717.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Sexual debut timing and emerging adult depressive symptomatology: Logistic regression results, Male Participants
  footer_text: a High depressive symptomatology was based on scoring at or above the proportionately adjusted depression cutpoint on the modified Center for Epidemiologic Studies Depression scale (range 0–27). The cutpoints are 10 for males and 11 for females. b Sexual debut prior to age sixteen was classified as early, debut between ages 16 and 18 was classified as typical, debut after age 18 (including those who did not debut by Wave III interview) was classified as late. c For multi-category predictor variables, p-values refer to joint tests of statistical significance
    unique: PMC2491717/PMC2491717.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491716.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491717.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491717.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491717.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2491719.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Traditional DMARDs in clinical application.
  footer_text:
    unique: PMC2491719/PMC2491719.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Presently used biologic DMARDs
  footer_text:
    unique: PMC2491719/PMC2491719.xml::T2-0

PMC0024XXXXX/PMC2492751.xml

PMC0024XXXXX/PMC2493046.xml

PMC0024XXXXX/PMC2493414.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Intercorrelations Among Maternal Depressed Mood, Other Risk Factors, and Covariates
  footer_text: * p < .05
    unique: PMC2493414/PMC2493414.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Correlations Between Risk Factors and Categorical Substance Use by Grade
  footer_text: * p < .05
    unique: PMC2493414/PMC2493414.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491719.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2491719.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493414.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493414.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493414.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493414.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Effects of Risk Factors on Growth in Adolescent Alcohol Use from Grade 7 through Grade 11 (N = 792)
  footer_text: Note. Coeff. = Unstandardized coefficient; S.E. = Standard error; df = degrees of freedom * p < .05. Table 3
    unique: PMC2493414/PMC2493414.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Effects of Risk Factors on Growth in Adolescent Cigarette Use from Grade 7 through Grade 11 (N = 792)
  footer_text: Note. Coeff. = Unstandardized coefficient; S.E. = Standard error * p < .05 + < .10
    unique: PMC2493414/PMC2493414.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Effects of Risk Factors on Growth in Adolescent Marijuana Use from Grade 7 through Grade 11 (N = 785)
  footer_text: Note. Coeff. = Unstandarized coefficient; S.E. = Standard error * p < .05
    unique: PMC2493414/PMC2493414.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493414.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493415.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493415.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2493415.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: An illustration of word-pair stimulus composition for the study and test phases in relation to the level of fan during study and the stimulus or foil type at test
  footer_text:
    unique: PMC2493415/PMC2493415.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mean proportion of responses to each of the four word-pair types in the word-pair recognition test as a function of the number of associates (fan) for word1 and word2 and whether the pair was repeated in Experiment 1
  footer_text: Correct responses are shown in bold. Variability is listed in parentheses as 95% confidence intervals.
    unique: PMC2493415/PMC2493415.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean proportion of responses to each of the four word-pair types in the word-pair recognition test as a function of the number of associates (fan) for word1 and word2 and whether the pair was repeated in Experiment 2
  footer_text: Correct responses are shown in bold. Variability is listed in parentheses as 95% confidence intervals.
    unique: PMC2493415/PMC2493415.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493415.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493415.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493415.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493420.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table A
  caption_text: Mean median correct response latency to each of the four word-pair types in the word-pair recognition test as a function of the number of associates (fan) for word1 and word2 in Experiment 1
  footer_text: Correct responses in bold. Variability is listed in parentheses as 95% confidence intervals.
    unique: PMC2493415/PMC2493415.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table B
  caption_text: Mean median correct response latency to each of the four word-pair types in the word-pair recognition test as a function of the number of associates (fan) for word1 and word2 in Experiment 2
  footer_text: Correct responses in bold. Variability is listed in parentheses as 95% confidence interval.
    unique: PMC2493415/PMC2493415.xml::T5-0

PMC0024XXXXX/PMC2493416.xml

PMC0024XXXXX/PMC2493420.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Preflight growth in CeMM in type I cassettes
  footer_text:
    unique: PMC2493420/PMC2493420.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Growth in flight
  footer_text:
    unique: PMC2493420/PMC2493420.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493420.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493420.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493421.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493467.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493467.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Molting in flight
  footer_text:
    unique: PMC2493420/PMC2493420.xml::T3-0

PMC0024XXXXX/PMC2493421.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Table of Means (Standard Errors) for Behavioral Anxiety as a Function of Dyad Type, Person, and Discussion Topic
  footer_text: Note. Means sharing a common subscript within each Dyad Type (Interracial and Same-race) do not differ significantly.
    unique: PMC2493421/PMC2493421.xml::T1-0

PMC0024XXXXX/PMC2493442.xml

PMC0024XXXXX/PMC2493443.xml

PMC0024XXXXX/PMC2493452.xml

PMC0024XXXXX/PMC2493464.xml

PMC0024XXXXX/PMC2493467.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Experimental electrolyte solutions and applied voltages
  footer_text:
    unique: PMC2493467/PMC2493467.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Pore size of AAO tubular membranes produced by 2.7 wt % oxalic acid at 30 and 40 V at 0°C
  footer_text:
    unique: PMC2493467/PMC2493467.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Pore size of AAO tubular membranes produced by 3 wt %, 5 wt %, 7 wt %, 10 wt % and 20 wt % sulfuric acid at 12.5, 15 and 20 V at 0°C
  footer_text:
    unique: PMC2493467/PMC2493467.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Interpore distance of AAO tubular membranes produced by 3 wt %, 5 wt %, 7 wt %, 10 wt % and 20 wt % sulfuric acid at 12.5, 15 and 20 V at 0°C
  footer_text:
    unique: PMC2493467/PMC2493467.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Interpore distances for AAO tubular membranes anodized by 2.7% oxalic acid at 30 and 40 V at 0°C
  footer_text:
    unique: PMC2493467/PMC2493467.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: AAO Growth rate for each sulfuric acid electrolyte concentration
  footer_text:
    unique: PMC2493467/PMC2493467.xml::T6-0

PMC0024XXXXX/PMC2493470.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Participant characteristics at baseline.
  footer_text: * 1 female control, 1 male control, and 2 male exercisers were missing baseline DEXA. † T-test comparing baseline characteristics for female exercisers versus controls. ‡ T-test comparing baseline characteristics for male exercisers versus controls.
    unique: PMC2493470/PMC2493470.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Geometric means (95% confidence intervals) for the effect of exercise on CRP: differences at baseline and after 12 months of exercise intervention.
  footer_text: † p-value for exercisers versus controls at baseline; ‡ p-value for changes from baseline to 12months, among exercisers versus controls, with adjustment for baseline values.
    unique: PMC2493470/PMC2493470.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: CRP levels at baseline and 12 months in exercise intervention and control participants: stratified by baseline BMI.
  footer_text: † P-value for difference in CRP changes from baseline to twelve months in exercise intervention versus control stratified by BMI group, controlling for baseline CRP values.
    unique: PMC2493470/PMC2493470.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493467.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493467.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493467.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493467.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493470.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493470.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493470.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2493538.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Correlations Among B-YAACQ Scores, Measures of Past-Month Alcohol Consumption, and AUDIT Scores At Baseline and 6-Week Follow-up
  footer_text: Note. All correlations significant at p < .01. Correlations in bold represent concurrent correlations. ns range from 279 to 291 due to missing data. * defined as 5+ drinks per occasion for men; 4+ drinks per occasion for women.
    unique: PMC2493538/PMC2493538.xml::T1-0

PMC0024XXXXX/PMC2493539.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Data processing and structure refinement statistics
  footer_text: 1 Highest resolution shell (2.39-2.31 Å). 2 Rsymm = Σ |Ih - <Ih>|/ Σ Ih, where <Ih> is the average intensity over symmetry equivalents. 3 Rwork and Rfree = Σ | | Fo | - | Fc | |/ Σ | Fo | for the working set and test set (6%) of reflections.
    unique: PMC2493539/PMC2493539.xml::T1-0

PMC0024XXXXX/PMC2493570.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Kinetic Constantsa for Clarithromycin Transport by SCC-25 Cells and Gingival Fibroblasts
  footer_text: a Km (Michaelis constant) and Vmax (maximum transport velocity) were determined by Lineweaver-Burk analysis of transport activity assayed in the presence of several different concentrations of clarithromycin (8 to 50 μg/ml) during the rapid initial phase of uptake (first 3 minutes). The Cellular/Extracellular concentration ratio was determined in medium containing 2 μg/ml clarithromycin. The data represent the mean ± SEM of four experiments with SCC-25 cells and three experiments with gingival fibroblasts. b Values within columns are significantly different (P < 0.05, t-test) c Values within columns are significantly different (P < 0.05, Mann-Whitney rank sum test)
    unique: PMC2493570/PMC2493570.xml::T1-0

PMC0024XXXXX/PMC2493571.xml

PMC0024XXXXX/PMC2493613.xml

PMC0024XXXXX/PMC2493614.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493538.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493539.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493570.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493614.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Metalloproteinase-independent biological activity of TIMPs
  footer_text:
    unique: PMC2493614/PMC2493614.xml::T1-0

PMC0024XXXXX/PMC2493615.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Clinical characteristics of 127 cases and 214 controls.
  footer_text: Chi-square likelihood ratio p-values from conditional logistic regression analysis, adjusted for age at index biopsy, date of index biopsy, and duration of follow-up and weighted based on the batch-quota and counter-matched sampling. For progression interval and follow-up biopsies, p-value is from t-tests. * 413 controls were originally matched to cases on age at EH diagnosis, date of EH diagnosis, and duration of follow-up, based on the original community diagnoses of EH. Because the 172 controls who were ineligible based on the pathology panel diagnoses are not included above, the distribution of age, date, and follow-up interval among the 241 eligible controls above differs slightly from the distribution among all 413 potential controls. The conditional logistic regression models retained individual matching on age at index biopsy, date of index biopsy, and duration of follow-up interval. ** Not mutually exclusive.
    unique: PMC2493615/PMC2493615.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: PTEN expression at index biopsy for 115 cases and 193 controls*.
  footer_text: * PTEN expression status at index biopsy was unavailable for 11 cases and 27 controls. IHC was unsuccessful for 12 cases (9.4%) and 21 controls (9.8%). P-value for case-control difference: 0.85.
    unique: PMC2493615/PMC2493615.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: PTEN expression by panel WHO EH classification at index biopsy for 115 cases and 193 controls.
  footer_text: PTEN expression status at index biopsy was unavailable for 11 cases and 27 controls. IHC was unsuccessful for 12 cases (9.4%) and 21 controls (9.8%). * P-value based on Chi-square test (PTEN status vs. panel WHO classification) among cases and controls separately.
    unique: PMC2493615/PMC2493615.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493615.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493615.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493615.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493615.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493615.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2493615.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Rate ratios of developing endometrial carcinoma after a diagnosis of EH according to PTEN expression (normal vs. null) at index biopsy, combined with panel WHO classification.
  footer_text: EH = endometrial hyperplasia; DPEM = disordered proliferative endometrium; SH = simple hyperplasia; CH = complex hyperplasia; AH = atypical hyperplasia; RR = rate ratio; CI = confidence interval. Rate ratios are based on conditional logistic regression analysis adjusted for age at index biopsy, date of index biopsy, interval between EH and carcinoma (or censoring, for controls), and weighted based on the batch-quota and counter-matched sampling. All controls were diagnosed with EH at the same age and date as the cases and remained at risk (i.e., no hysterectomy or uterine cancer) for at least as long as the progression interval of the cases. *Adjusted for age at index biopsy, date of index biopsy, progression interval, BMI at index biopsy, follow-up biopsies, and MPA-based treatment for EH. PTEN expression status at index biopsy was unavailable for 11 cases and 27 controls (RR=0.81, 95% CI, 0.23-2.86). IHC was unsuccessful for 12 cases and 21 controls (RR=0.67, 95% CI, 0.21-2.14). IHC was unsuccessful for 3 cases and 13 controls with DPEM (RR=0.27, 95% CI, 0.05-1.48), 7 cases and 8 controls with SH or CH (RR=0.79, 95% CI, 0.15-4.12), and 2 cases with AH (RR N/A).
    unique: PMC2493615/PMC2493615.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: PTEN expression at index biopsy vs. hysterectomy for 104 cases with successful IHC in both specimens.
  footer_text: PTEN expression status was unavailable for hysterectomy specimens from 3 cases, index biopsy specimens from 4 cases, and both index biopsy and hysterectomy specimens from 7 cases. IHC was unsuccessful for index biopsy specimens from 11 cases, for hysterectomy specimens from 8 cases, and both index biopsy and hysterectomy specimen for 1 case. P-value is based on Chi-square McNemar’s test.
    unique: PMC2493615/PMC2493615.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: PTEN mutations in paired index biopsy – cancer specimens from 4 cases with PTEN-null glands in both their index biopsies and hysterectomy specimens.
  footer_text: Dx, diagnosis; CH, complex hyperplasia; AH, atypical hyperplasia; DPEM, disordered proliferative endometrium; AC, endometrioid adenocarcinoma.
    unique: PMC2493615/PMC2493615.xml::T6-0

PMC0024XXXXX/PMC2494536.xml

PMC0024XXXXX/PMC2494579.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic and anthropometric data of 18 GHRH-R mutant (GHRH-R mut.) individuals and two control groups. Control B was used only for liver size
  footer_text: * P < 0·0001 in comparison to GHRH-R mutant group. Values are means ± SD. BMI, body mass index; BSA, body surface area.
    unique: PMC2494579/PMC2494579.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Absolute sizes of organs in GHRH-R mutant (GHRH-R mut.) and control subjects
  footer_text: Values are means ± SD. Significant correlations are in bold characters.
    unique: PMC2494579/PMC2494579.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Abdominal sizes of organs corrected by stature (S), weight (W) and body surface area (BSA) in patients with GHRH-R mutant (GHRH-R mut.) and control subjects
  footer_text: Significant correlations are in bold characters.
    unique: PMC2494579/PMC2494579.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494579.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494579.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494579.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494579.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Correlation between sizes of organs and height; sizes of organs and body surface area (BSA) of all the subjects (pooled GHRH-R mutant and control subjects)
  footer_text: Values are means ± SD. Significant correlations are in bold characters.
    unique: PMC2494579/PMC2494579.xml::T4-0

PMC0024XXXXX/PMC2494595.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline characteristics of female and male participants*
  footer_text: * Values for continuous variables are means ± SEM, and for categorical variables, percentages † Servings were calculated based on the standardized serving sizes from the Dietary Guidelines for Americans ‡ We tested whether the baseline data was statistically different by sex, by computing two-sample T-tests for continuous variables and the Fisher's exact test for the race variable; dietary intakes were log-transformed prior to hypothesis testing to improve normality. P<0.05 was considered statistically significant.
    unique: PMC2494595/PMC2494595.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Effect of experimental diets on serum β-glucuronidase activity, stratified by sex and day on experimental diet
  footer_text: Abbreviations: F&V, fruit and vegetable diet; CI, confidence interval * Back-log-transformed least-square means ±SE of serum β-glucuronidase activity. Means are adjusted for: sex, days on experimental diet, UGT1A1 genotype, order of assigned experimental diet, carryover effect, β-glucuronidase activity during the pre-intervention period, 2-way interactions between sex, days on experimental diet, UGT1A1 genotype, and experimental diet † Ratio was calculated by exponentiating the difference of the log-transformed adjusted, least-square means ‡ Serum β-glucuronidase activity was significantly higher during F&V than during basal diet, P<0.05 § β-glucuronidase activity averaged over days 8 and 15 of experimental diet
    unique: PMC2494595/PMC2494595.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Serum β-glucuronidase activity during pre-intervention and experimental periods, stratified by sex and day on experimental diet
  footer_text: Abbreviations: F&V, fruit and vegetable diet; CI, confidence interval * Geometric means ± SE of β-glucuronidase activity; means were unadjusted because paired t-tests were used to compare values † Experimental diet versus Pre-intervention ratios were calculated by exponentiating the difference of the log-transformed (unadjusted) geometric means. Paired t-tests, inherently adjusting for within-person characteristics, were used to calculate the significance of the ratios. ‡ Serum β-glucuronidase activity was significantly different for the pre-intervention than the experimental diet, P<0.05 § For experimental diets, data stratified by sex represent values averaged over days 8 and 15 of experimental diet ∥ Pre-intervention β-glucuronidase activity was sample at one time point
    unique: PMC2494595/PMC2494595.xml::T3-0

PMC0024XXXXX/PMC2494699.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494595.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494595.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494595.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494699.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Plasma metabolite and insulin concentrations in 12 week old and 22 week old control and diabetic rats (n = 7).
  footer_text: * p < 0.05 between control and diabetic group. ‡ p < 0.05 between young and old groups.
    unique: PMC2494699/PMC2494699.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Plasma metabolite and insulin concentrations in 12 week old control and diabetic rats treated with a low or high dose of the PPARα agonist WY14,643 (n = 4–7).
  footer_text: * P < 0.05 between control and diabetic group. # P < 0.05 between treated and untreated groups.
    unique: PMC2494699/PMC2494699.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: mRNA levels in 12 week old and 22 week old control and diabetic rats and 12 week old rats treated with WY14,643 measured by QPCR (n = 3).
  footer_text: * p < 0.05 between control and diabetic groups. ‡ p < 0.05 between young and old groups. # p < 0.05 between treated and untreated groups.
    unique: PMC2494699/PMC2494699.xml::T3-0

PMC0024XXXXX/PMC2494872.xml

PMC0024XXXXX/PMC2494875.xml

PMC0024XXXXX/PMC2495052.xml

PMC0024XXXXX/PMC2495056.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494699.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2494699.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Rotated factor pattern (multiplied by 100 and rounded to the nearest integer) for first 3 factors from principal components analysis of all line items from the NIH-AARP Diet and Health Study food frequency questionnaire.
  footer_text:
    unique: PMC2495056/PMC2495056.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Baseline characteristics by quintile of factor scores for men and for women (all values are totals, percents, or means).
  footer_text: a p for linear trend < 0.05 b p for linear trend < 0.01 c p for linear trend < 0.001 d p for linear trend <0.0001 e Chi square test of independence of factor quintile against level of categorical variable < 0.0001 for all categorical variables for each of the three factors.
    unique: PMC2495056/PMC2495056.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2495056.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2495056.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Age and multivariate-adjusted1 hazard ratios and 95% confidence intervals (CI) for colorectal cancer (2,151 cases in men and 959 in women) in the AARP Diet and Health Study by quintiles of factor scores.
  footer_text: 1 Multivariate models adjusted for ethnicity, tobacco use, physical activity, body mass index, education, family history of colon cancer, regular NSAIDs use, and, in the case of women, use of menopausal hormone therapy. 2 Relative risks estimated using Cox proportional hazards regression.
    unique: PMC2495056/PMC2495056.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Multivariate-adjusted1 hazard ratios and 95% confidence intervals (CI) for cancer of the proximal colon (826 cases in men, 459 in women), distal colon (646 cases in men, 230 in women), and rectum (631 cases in men, 258 in women) in the AARP Diet and Health Study by quintiles of factor scores.
  footer_text: 1 Multivariate models adjusted for ethnicity, tobacco use, physical activity, body mass index, education, family history of colon cancer, regular NSAIDs use, and, in the case of women, use of menopausal hormone therapy. 2 Relative risks estimated using Cox proportional hazards regression.
    unique: PMC2495056/PMC2495056.xml::T4-0

PMC0024XXXXX/PMC2496967.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2495056.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2495056.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2496968.xml

PMC0024XXXXX/PMC2497421.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Main events in the evolution of the disease.
  footer_text:
    unique: PMC2497421/PMC2497421.xml::T1-0

PMC0024XXXXX/PMC2497431.xml

PMC0024XXXXX/PMC2497432.xml

PMC0024XXXXX/PMC2497437.xml

PMC0024XXXXX/PMC2497438.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Selected characteristics of cervical and vulvar squamous cell carcinoma cases
  footer_text: * Represents the percentage of tested individuals
    unique: PMC2497438/PMC2497438.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: IL2 tagSNP characteristics, smoking prevalence, and results from tests of independence of IL2 tagSNPs and cigarette smoking in controls
  footer_text: * rs number refers to the National Center for Bioinformatics (NCBI) dbSNP build 127 reference sequence number. † Locations are with respect to the first nucleotide position in the NCBI GenBank entry: accession number AF359939. ‡ Location of tagSNP within gene: 5’flanking is upstream of the first exon of the gene, exon is in the coding region of the gene, intron is between coding regions of the gene. § Prevalence of current cigarette smoking among all controls (n=236) who carried at least one copy of the variant allele for each tagSNP ∥ OR, odds ratio; CI, confidence interval. The ORs are the exponentiated joint effect parameters for cigarette smoking and tagSNP genotype among controls from the full model (39) assuming a log-additive genetic model. These can be interpreted as the association between IL2 tagSNP genotypes and cigarette smoking among controls. ** Likelihood ratio test p value (39)
    unique: PMC2497438/PMC2497438.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497438.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497438.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497438.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497438.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Interaction odds ratios between IL2 genotypes and cigarette smoking on cervical and vulvar cancer risk
  footer_text: * rs number refers to the National Center for Bioinformatics (NCBI) dbSNP build 127 reference sequence number. † IOR, interaction odds ratio; CI, confidence interval. ‡ Dominant genetic model. § Recessive genetic model.
    unique: PMC2497438/PMC2497438.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Interaction odds ratios between IL2 haplotypes and cigarette smoking on cervical and vulvar cancer risk based on a log-additive model
  footer_text: * Alleles in each haplotype are listed from 5′ to 3′ (rs2069762, rs2069763, rs2069777, and rs2069778). Variant alleles are underlined. † IOR, interaction odds ratio; CI, confidence interval. Calculated assuming a log-additive genetic model.
    unique: PMC2497438/PMC2497438.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Interaction odds ratios between IL2 diplotypes and cigarette smoking on cervical and vulvar cancer risk
  footer_text: * The two haplotypes carried on each chromosome are separated by the “/”. Alleles in each haplotype are listed from 5′ to 3′ (rs2069762, rs2069763, rs2069777, and rs2069778). Variant alleles are underlined. † IOR, interaction odds ratio; CI, confidence interval.
    unique: PMC2497438/PMC2497438.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Main effect of each tagSNP on cervical and vulvar cancer risk
  footer_text: * rs number refers to the National Center for Bioinformatics (NCBI) dbSNP build 127 reference sequence number. † OR, odds ratio; CI, confidence interval. All controls were seropositive for HPV16 or HPV18 L1 antibodies.
    unique: PMC2497438/PMC2497438.xml::T6-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497438.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497438.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497442.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2497439.xml

PMC0024XXXXX/PMC2497442.xml
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Peak principal bone strains (Mean ± SD, in με) during mastication
  footer_text: Max= tension; Min = compression; Shear = Max + Min (absolute value); Direc: direction of tension relative to the midline line (PM and MI) or the occlusal plane (MM, angle in degrees) * Independent t tests (Sham-Reduction comparison); # ANOVA/Tukey tests (Gauge-site comparision).
    unique: PMC2497442/PMC2497442.xml::T2-0

PMC0024XXXXX/PMC2497445.xml

PMC0024XXXXX/PMC2497446.xml

PMC0024XXXXX/PMC2497447.xml

PMC0024XXXXX/PMC2497450.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patient Characteristics
  footer_text: Abbreviations: ESFT, Ewing sarcoma family of # Age at time of apheresis * Given between apheresis and immunotherapy ¤ for surviving patients
    unique: PMC2497450/PMC2497450.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Vaccine Peptide Sequences
  footer_text: a t(11;22)(q24;q12) Ewing’s Sarcoma Family of Tumors (ESFT) b t(2;13)(q35;q14) Alveolar Rhabdomyosarcoma (AR)
    unique: PMC2497450/PMC2497450.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Characteristics of surviving patients
  footer_text: Abbreviation: dx, diagnosis; NA, not applicable; LN, lymph node; SX, surgery; SCT, stem cell transplant; XRT, radiation treatment; CR, complete response; PR, partial response; PD, progression of disease; IL-2, interleukin 2; mod, moderate; OS, overall survival; AWD, alive with disease; NED, no evidence of disease. * NED since initiating immunotherapy
    unique: PMC2497450/PMC2497450.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497450.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497450.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497450.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0024XXXXX/PMC2497451.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: IC50 and IC90 values for competitive antagonism of human nAChRs by various neuromuscular blocking agents. Macroscopic currents were activated by 300 μM ACh, −50 mV. CE50 values are estimates of the clinical concentrations of the antagonists that decrease muscle tension by 50% based on pharmacokinetic/pharmacodynamic modeling (32,33). They are not corrected for the free fraction of drug after accounting for protein binding which ranges from 0.31 for vecuronium to 0.63 for atracurium (33).
  footer_text:
    unique: PMC2497451/PMC2497451.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Fractional analysis (Equation 3) of the extent of synergy of between combinations of competitive antagonists. Synergy is indicated by fractional values significantly less then 1.0.
  footer_text:
    unique: PMC2497451/PMC2497451.xml::T2-0

PMC0024XXXXX/PMC2497455.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Frequency of degeneration among unmyelinated axons.
  footer_text: [From Kissin et al. (66)]
    unique: PMC2497455/PMC2497455.xml::T1-0

PMC0024XXXXX/PMC2497466.xml

PMC0025XXXXX/PMC2502065.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497451.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497451.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2497455.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2502065.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Effect of adolescent fluoxetine treatment on the number of BrdU-labeled cells in SFR mice
  footer_text: 1 Dose of fluoxetine (Fluox) in mg/kg/day. Data are mean ± SD and were compared by one-way ANOVA. Statistical differences (16 versus 25 mg/kg of Fluox) were resolved post hoc using Tukey Kramer Multiple Comparisons tests. *** p < 0.001 compared with adolescent Fluox (16).
    unique: PMC2502065/PMC2502065.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Effect of adult fluoxetine treatment on the number of BrdU-labeled cells in SFR mice
  footer_text: 1 Dose of fluoxetine (Fluox) in mg/kg/day. Data are mean ± SD and were compared by one-way ANOVA. Statistical differences were resolved post hoc using Tukey Kramer Multiple Comparisons tests. No statistically significant differences were observed.
    unique: PMC2502065/PMC2502065.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Effect of adolescent fluoxetine treatment on the number of BrdU-labeled cells in IMS mice
  footer_text: 1 Dose of fluoxetine (Fluox) in mg/kg/day. Data are mean ± SD and were compared by one-way ANOVA. Statistical differences were resolved post hoc using Tukey Kramer Multiple Comparisons tests. No statistically significant differences were observed. nd: not determined.
    unique: PMC2502065/PMC2502065.xml::T3-0

PMC0025XXXXX/PMC2504020.xml

PMC0025XXXXX/PMC2504029.xml
  ----------------------------------------
  id: T4
  label_text:
  caption_text: Food groups used to calculate the Comprehensive Healthy Dietary Pattern score1
  footer_text: 1 Range in parentheses; n in brackets. Points were assigned to each category of intake when the dietary pattern scores were calculated. 2 Denotes food groups included in the Simplified Healthy Dietary Pattern. 3 Denotes food groups not included in either the Comprehensive or the Simplified Healthy Dietary Pattern.
    unique: PMC2504029/PMC2504029.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2502065.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2502065.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504029.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504029.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Participant characteristics and nutrient intakes across quintiles (Q) of an a priori—defined Healthy Dietary Pattern in the Multi-Ethnic Study of Atherosclerosis1
  footer_text: 1 Values are unadjusted x̄ ± SE or percentages, except for macro- and micronutrients, which are adjusted for total energy intake (kcal/d). 2 P for trend across quintiles calculated from linear regression with the a priori Healthy Dietary Pattern modeled continuously (score). 3 Chi-square test for difference among race-ethnic groups. 4 MET, metabolic equivalents.
    unique: PMC2504029/PMC2504029.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Geometric mean or odds ratios for select cardiovascular disease risk markers across quintiles (Q) of an a priori—defined Healthy Dietary Pattern in the Multi-Ethnic Study of Atherosclerosis1
  footer_text: 1 CRP, C-reactive protein; IL-6, interleukin-6; CAC, coronary artery calcification; ABI, ankle brachial index; LAE, large artery elasticity; SAE, small artery elasticity; ACR, albumin to creatinine ratio; IMT, intima-media thickness; CC, common carotid artery; IC, internal carotid artery. 2 P for trend across quintiles calculated with the Healthy Dietary Pattern modeled continuously (score). 3 All values are geometric x̄; 95% CI in parentheses. 4 Adjusted for energy intake (kcal/d), age (y), race-ethnicity (white, black, Hispanic, Chinese), and study center. 5 Adjusted as for model 1 plus education (<high school, high school, >high school), physical activity (active and inactive leisure in metabolic equivalents per min/wk), smoking (current or not current and pack-years), and supplement use (≥ weekly). Data for LAE and SAE also adjusted for height, weight, systolic blood pressure, and pulse rate. 6 Adjusted as for model 2 plus waist circumference (cm). 7 All values are odds ratios; 95% CI in parentheses. 8 Values calculated in 2380 participants with an Agatston score > 0. 9 All values are x̄ ± SD.
    unique: PMC2504029/PMC2504029.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504029.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504029.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504253.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Regression coefficients (or odds ratios) for the relation between select cardiovascular disease (CVD) risk markers and a priori Comprehensive and Simplified Healthy Diet Patterns in the Multi-Ethnic Study of Atherosclerosis1
  footer_text: 1 CRP, C-reactive protein; IL-6, interleukin-6; IMT, intima-media thickness; CAC, coronary artery calsification; ABI, ankle brachial index; LAE, large artery elasticity; SAE, small artery elasticity; ACR, albumin to creatinine ratio. 2 Adjusted for energy intake (kcal/d), age (y), race-ethnicity (white, black, Hispanic, Chinese), study center, education (<high school, high school, >high school), physical activity (active and inactive leisure in metabolic equivalents per min/wk), smoking (current or not current and pack-years), and supplement use (≥weekly). 3 Model includes the covariates in footnote 2 and both the difference between scores (Healthy Dietary Pattern score — Simplified Healthy Dietary Pattern score) and the Simplified Healthy Dietary Pattern score. 4 Data were analyzed on the natural log scale. 5 β-coefficient ± SE per 1 SD (10.2) for the Comprehensive Healthy Dietary Pattern score and per 1 SD (3.52) for the Simplified Healthy Dietary Pattern score. 6 P < 0.05. 7 Odds ratio; 95% CI in parentheses (all such values). 8 Estimated from 2380 participants with an Agatston score >0. 9 Data for LAE and SAE also adjusted for height, weight, systolic blood pressure, and pulse rate. Greater elasticity values are favorable.
    unique: PMC2504029/PMC2504029.xml::T3-0

PMC0025XXXXX/PMC2504253.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: In vitro biofilm biomass
  footer_text: a Biomass is given in grams per cm2 of surface area. Values are the mean ± standard deviation for four determinations. b P-value <0.05 compared to the als1/als1 als3/als3 strain.
    unique: PMC2504253/PMC2504253.xml::T1-0

PMC0025XXXXX/PMC2504411.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Clinical features in 1,033 consecutive adults with ALF in the United States (1998-2007)
  footer_text: APAP= Acetaminophen, HAV= Hepatitis A virus, HBV= Hepatitis B virus, ALF = acute liver failure, ALT = alanine aminotransferase (Data provided by William Lee, MD, and the US ALFSG, July 2007)
    unique: PMC2504411/PMC2504411.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504411.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504411.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504411.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Treatable causes of acute liver failure
  footer_text: HELLP – hemolysis, elevated liver enzymes, and low platelet count
    unique: PMC2504411/PMC2504411.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Diagnosis and management of acetaminophen overdose
  footer_text:
    unique: PMC2504411/PMC2504411.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Acetaminophen content of selected narcotic analgesics and over-the-counter medications
  footer_text: * Contact Poison Control Center for exact dosage of other constituents. Note: This list does not contain all acetaminophen-containing products. ACM - acetaminophen
    unique: PMC2504411/PMC2504411.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Management of cerebral edema in acute liver failure
  footer_text: ICU – intensive care unit, CT – computerized tomography, ICP – intracranial pressure, INR – international normalized ratio, ALF – acute liver failure
    unique: PMC2504411/PMC2504411.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Management of coagulopathy in acute liver failure
  footer_text: * Not FDA approved for use in this setting DIC – disseminated intravascular coagulation, PT – prothrombin time, INR – international normalized ratio, PTT – partial thromboplastin time, CBC – complete blood count, ALF – acute liver failure, GI – gastrointestinal, H2 – Histamine-2, FFP – fresh frozen plasma, ICP – intracranial pressure, DVT – deep venous thrombosis, PE – pulmonary embolus.
    unique: PMC2504411/PMC2504411.xml::T6-0

PMC0025XXXXX/PMC2504492.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic Variable Descriptive Statistics Overall and by Nation
  footer_text:
    unique: PMC2504492/PMC2504492.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Shift Variables Descriptive Statistics Overall and by Nation
  footer_text:
    unique: PMC2504492/PMC2504492.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Study Variable Descriptive Statistics and Correlations
  footer_text: * Significant at the.05 level (two-tailed) ** Significant at the.01 level (two-tailed) N= 906
    unique: PMC2504492/PMC2504492.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Regression of Off-shift Well-being Outcomes on Statistical Controls and Shift Characteristics
  footer_text: a Step 1 df = 5, 814; Step 2 df = 14, 805. b Step 1 df = 5, 815; Step 2 df = 14, 806. c Step 1 df = 5, 807; Step 2 df = 14, 798. * p <.05 ** p <.01 *** p <.001
    unique: PMC2504492/PMC2504492.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504492.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504492.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504492.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504492.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2504519.xml

PMC0025XXXXX/PMC2504524.xml

PMC0025XXXXX/PMC2504689.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Anti-TB activities, cytotoxicity (IC50) and selectivity indices (SIs) of extract partitions and the isolated polyynes 1-5 from A. sinensis
  footer_text: a Minimum inhibitory concentration defined as the concentration at which the samples exhibit an inhibition of ≥ 90% in the MABA assay. b Average ± SD of triplicate determinations. c Selectivity index (SI = IC50/MIC). d Positive control (Rifampin); negative control was solvent (DMSO). n/a = not applicable.
    unique: PMC2504689/PMC2504689.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: 1H-NMR data of polyyne 1-5 from A. sinensis [CDCl3, 400 MHz, δH (J Hz)]
  footer_text:
    unique: PMC2504689/PMC2504689.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: The 13C-NMR spectral data of polyynes 1-5, isolated from A. sinensis (CDCl3, 100 MHz)
  footer_text:
    unique: PMC2504689/PMC2504689.xml::T3-0

PMC0025XXXXX/PMC2504695.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504689.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504689.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504689.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2504728.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean (SD) Neuropsychological Test Performance for the Three Age Groups in Experiment 1
  footer_text: Note. CVLT = California Verbal Learning Test * = significant group differences † = significant group differences
    unique: PMC2504728/PMC2504728.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Factor Loadings for 227 Older Adults and 96 Young Adults
  footer_text: Note. CVLT = California Verbal Learning Test
    unique: PMC2504728/PMC2504728.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean and (SDs) of FL and MTL factor scores in young, old-young, and older adults
  footer_text: Note. FL = frontal lobe; MTL = medial temporal lobe
    unique: PMC2504728/PMC2504728.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Characteristics of Young and Older Adult Groups in Experiment 2
  footer_text: Note. FL = frontal lobe; MTL = medial temporal lobe
    unique: PMC2504728/PMC2504728.xml::T4-0
    unique: PMC2504728/PMC2504728.xml::T4-1
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Mean Proportion Correct (SD) on Source and Item Memory Tasks in Young Adults in Experiment 2
  footer_text: Note. FL = frontal lobe; MTL= medial temporal lobe
    unique: PMC2504728/PMC2504728.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Mean Proportion Correct (SD) on Source and Item Memory Tasks in Older Adults in Experiment 2
  footer_text: Note. FL = frontal lobe; MTL= medial temporal lobe
    unique: PMC2504728/PMC2504728.xml::T6-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T4-1'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T7-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504728.xml::T8-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504735.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: Characteristics of Young Adults in Experiment 3
  footer_text: Note.FL = frontal lobe; MTL= medial temporal lobe
    unique: PMC2504728/PMC2504728.xml::T7-0
  ----------------------------------------
  id: T8
  label_text: Table 8
  caption_text: Mean Proportion Correct (SD) on Source Memory Task in Young Adults in Experiment 3
  footer_text: Note. FL = frontal lobe; MTL= medial temporal lobe
    unique: PMC2504728/PMC2504728.xml::T8-0

PMC0025XXXXX/PMC2504735.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Contaminants Discovered in the Bay Street Neighborhood.
  footer_text: Note: RDEC is the Residential Direct Exposure Criteria established by the Rhode Island Department of Environmental Management.
    unique: PMC2504735/PMC2504735.xml::T1-0

PMC0025XXXXX/PMC2504736.xml

PMC0025XXXXX/PMC2504739.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Ototoxicity Grading Criteria
  footer_text: A loss is defined as a change from baseline at any one frequency * Patient requires hearing aids
    unique: PMC2504739/PMC2504739.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Patient Characteristics
  footer_text: † PFRT = Posterior Fossa Irradiation, TBRT= Tumor Bed Irradiation
    unique: PMC2504739/PMC2504739.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Frequency of Grade 3 or 4 Ototoxicity by Amifostine Administration and Study Cohort
  footer_text: † PFRT = Posterior Fossa Irradiation, TBRT= Tumor Bed Irradiation
    unique: PMC2504739/PMC2504739.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504739.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504739.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504739.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Grade 3 and 4 Adverse Events Occurring Within 2 Days of Amifostine Administration and Considered At Least Possibly Attributable to Amifostine
  footer_text: † Reported is the frequency observed in 62 patients receiving amifostine over 235 courses of treatment.
    unique: PMC2504739/PMC2504739.xml::T4-0

PMC0025XXXXX/PMC2504742.xml

PMC0025XXXXX/PMC2504743.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of Tracer Injections in MI Cortex
  footer_text: a Values in parentheses represent number of injection penetrations b Wh indicates whiskers, Fp indicates forepaw
    unique: PMC2504743/PMC2504743.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504743.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504749.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504751.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504751.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2504749.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Participant Characteristics
  footer_text: Note. PPVT-III = Peabody Picture Vocabulary Test-III (standard score); EVT = Expressive Vocabulary Test (standard score); TELD-3 = Test of Early Language Development-3 (standard score); GFTA-2 = Goldman-Fristoe Test of Articulation-2 (standard score); TSO = parent-reported time since initial onset of stuttering (months); %SLD = mean frequency of stuttering-like disfluencies (percent) per 100 words; SSI-3 = Stuttering Severity Instrument-3 (total score); = test scores could not be obtained, because the participant refused to cooperate with further testing.
    unique: PMC2504749/PMC2504749.xml::T1-0

PMC0025XXXXX/PMC2504751.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Co-infections in breast milk are not associated with clinical or subclinical mastitis
  footer_text: a No infectious agent had a statistically significant difference in prevalence between specimens with and without either clinical or subclinical mastitis, using GEE. b Clinical mastitis defined by report of any symptoms of breast inflammation using a standardized questionnaire. c Subclinical mastitis defined by milk Na+ >12 mM [3].
    unique: PMC2504751/PMC2504751.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Plasma HIV-1 RNA load, mastitis parameters and milk co-infections as related to detection of HIV-1 RNA or DNA in breast milk
  footer_text: a Detection of HIV-1 RNA at ≥ 50 copies/mL lactoserum, and HIV-1 DNA at ≥ 1−10 copies/cell pellet from 1 to 14 mL whole milk [3]. b GEE logistic model adjusted for all variables in the first column, except mycoplasma and mycobacteria. Mycoplasmal detection was too rare to include in the multivariable modeling. Mycobacteria were not included because their detection likely represents contamination from the skin rather than infection within the breast tissue. c Model does not converge due to a proportion estimate of 0.0 or 1.0 in one group.
    unique: PMC2504751/PMC2504751.xml::T2-0

PMC0025XXXXX/PMC2504754.xml

PMC0025XXXXX/PMC2504759.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Means and S.D. of the participant groups for age, gender, and full-scale IQ.
  footer_text:
    unique: PMC2504759/PMC2504759.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504759.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504761.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504761.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2504761.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: PCR primer sequences and GeneBank Accession Numbers
  footer_text:
    unique: PMC2504761/PMC2504761.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Flow cytometric analysis of peripheral blood cell from wild-type, Fli-1ΔCTA/Fli-1+ heterozygous and Fli-1ΔCTA/Fli-1ΔCTA mice
  footer_text: The percentages of B220+ cells were assessed by flow cytometry. Values represent mean ± SD. ‡ indicates p<0.0001 when compared to wild-type. * indicates p<0.05 when compared to Fli-1ΔCTA/Fli-1ΔCTA homozygous mice.
    unique: PMC2504761/PMC2504761.xml::T2-0

PMC0025XXXXX/PMC2504765.xml

PMC0025XXXXX/PMC2504766.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Studies of the epidemiology of viral-associated wheezing illnesses in infancy and early childhood
  footer_text:
    unique: PMC2504766/PMC2504766.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Studies of virus detection associated with acute asthma exacerbations in children and adults
  footer_text:
    unique: PMC2504766/PMC2504766.xml::T2-0

PMC0025XXXXX/PMC2505184.xml

PMC0025XXXXX/PMC2505321.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean and standard error of 2-DG (nCi/g) uptake
  footer_text: a Indicates significant differences (p < 0.05) between right and left side within groups, and between the right side of the muscimol and saline groups. b Indicates significant differences (p < 0.05) between the right side of the muscimol and saline groups.
    unique: PMC2505321/PMC2505321.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504766.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2504766.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2505321.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2505342.xml

PMC0025XXXXX/PMC2505356.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Correlations between GZTS Scales and NEO-PI-R Factors and Most Strongly Related Facet.
  footer_text: Note. N = 757 to 854 from a BLSA sub-sample of 900 individuals who were administered both tests during the same visit. Last two columns report the specific NEO-PI-R facet with which each GZTS scale is most highly correlated. Correlations over ± .40 are given in bold. GZTS = Guilford-Zimmerman Temperament Survey; NEO-PI-R = Revised NEO Personality Inventory; N = Neuroticism; E = Extraversion; O = Openness to Experience; A = Agreeableness; C = Conscientiousness. * Conscientiousness was estimated using the mean of General Activity and Restraint. Table adapted from Terracciano et al. (39)
    unique: PMC2505356/PMC2505356.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Personality predictors of all-cause mortality
  footer_text: Note. For all personality scales tested, age and sex were significant covariates. HR = Hazard ratio. * Conscientiousness was estimated using the mean of General Activity and Restraint.
    unique: PMC2505356/PMC2505356.xml::T2-0

PMC0025XXXXX/PMC2507862.xml

PMC0025XXXXX/PMC2507878.xml

PMC0025XXXXX/PMC2507881.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2505356.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2505356.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2507881.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Summary of cell surface expressed m157 mutations in C1498 cells
  footer_text: a only five (of 630) clones survived tertiary screening; clones1E8 and DA10 contained multiple mutations. b only those mutations resulting in a nonconservative, in-frame amino acid substitution are listed. Each unique m157 mutation (shown in bold) and its corresponding alanine substitution variant was regenerated by site-directed PCR mutagenesis. c each unique m157 mutation was transduced into C1498 cells and subsequently sorted by flow cytometry for high-level m157 expression; mean fluorescence intensity (MFI) values are listed after subtracting background MFI from parental C1498 cells. MFI for control C1498-m157 cells (wt-m157) is also indicated as a reference. d represents percentage of wt-m157 activity for each mutant after subtracting the background from parental C1498 cells. e positions mapped using PyMOL analysis software and the published PDB structure file for m157 (ID code: 2NYK); see also Figure 8.
    unique: PMC2507881/PMC2507881.xml::T1-0

PMC0025XXXXX/PMC2507886.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Human NAT2 alleles
  footer_text: Adapted from http://N-acetyltransferasenomenclature.louisville.edu [56]. a Human NAT2 alleles should be written in upper case and italicized. Protein products of the alleles are also upper case but not italicized and the asterisk is omitted. For example, the allele NAT2*4 encodes the protein NAT2 4. NAT2*4 has historically been designated “wildtype”. Since it is the most common occurring alleles in some but not all ethnic groups the designation of “wildtype” allele is somewhat arbitrary. b Reference gene sequence published in Genbank Assession Number X14672. The frequency of individual SNPs and alleles in various ethnic groups is available online from the National Cancer Institute’s SNP500Cancer database. RS refers to reference SNP. Signature SNP for each cluster is italicized. Although additional SNPs have been identified outside the open reading frame [42,43,57], they will not be named until a functional effect is observed. SNPs should be identified by designating “A” of the ATG translation initiation codon as number 1. SNPs upstream of this site are designated by negative numbers and SNPs downstream of this site are designated by positive numbers [56]. c Phenotype assignments reflect most current research but are not necessarily a consensus of all research papers. Evidence exists for heterogeneity within the “slow” acetylator phenotype [58–62].
    unique: PMC2507886/PMC2507886.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2507886.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2507886.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary of Non-Synonymous SNP-Induced Changes in NAT2 Function & Structure
  footer_text:
    unique: PMC2507886/PMC2507886.xml::T2-0

PMC0025XXXXX/PMC2512965.xml

PMC0025XXXXX/PMC2512970.xml

PMC0025XXXXX/PMC2515386.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Crystallographic Data Statistics for the Gal4(1-100)/DNA Complex
  footer_text: rmsd = root-mean-square deviation. Values for the outer resolution shell are given in parentheses. Rmerge= ΣΣi | II − <I>Σ/ | <I>, where <I> is the mean intensity of the N reflections with intensities Ii and common indices h,k,l for the native and derivative crystals, respectively. R factor = Σhkl | | Fobs − | k | Fcal/ | | Σhkl | Fobs |, where Fobs and Fcal Are observed and calculated structure factors,respectively. For Rfree the sum is extended over a subset of reflections (10%) that were excluded from all stages of refinement.
    unique: PMC2515386/PMC2515386.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: DSC analysis of Gal4(1-100) and mutants
  footer_text:
    unique: PMC2515386/PMC2515386.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Sedimentation coefficients of Gal4 constructs and DNA complex
  footer_text:
    unique: PMC2515386/PMC2515386.xml::T3-0

PMC0025XXXXX/PMC2515561.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Fold Decrease in Urokinase Plasminogen Activated Receptor (uPAR) Expression in Hkh2 Cells as Compared to HCT116 Cells
  footer_text:
    unique: PMC2515561/PMC2515561.xml::T1-0

PMC0025XXXXX/PMC2515566.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515386.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515386.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515386.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515561.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515566.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Phase-I goals and lifestyle guidelines given to participants
  footer_text: DASH, dietary approaches to stop hypertension
    unique: PMC2515566/PMC2515566.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Baseline characteristics
  footer_text:
    unique: PMC2515566/PMC2515566.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Attendance, adherence, and weight loss by race and gender
  footer_text: a With missing data imputed using multiple imputation procedures.
    unique: PMC2515566/PMC2515566.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Baseline measures and adherence indicators as predictors of change in weight
  footer_text: a A negative parameter estimate indicates that increase in the measure predicts greater weight loss (weight loss is a negative change score)
    unique: PMC2515566/PMC2515566.xml::T4-0

PMC0025XXXXX/PMC2515624.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515566.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515566.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515624.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515624.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: A list of major components of the Hh pathway in vertebrates
  footer_text:
    unique: PMC2515624/PMC2515624.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary of Hh signaling activation in human cancers
  footer_text:
    unique: PMC2515624/PMC2515624.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Summary of Hh signaling inhibitors
  footer_text:
    unique: PMC2515624/PMC2515624.xml::T3-0

PMC0025XXXXX/PMC2515713.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Descriptive information regarding study
  footer_text:
    unique: PMC2515713/PMC2515713.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Parameter Estimates for Mean Change in Cortisol
  footer_text: *p < .05 **p < .01 *** p < .001 1 Although not pertinent to the hypotheses of the present study, group intercept estimates are reported for completeness.
    unique: PMC2515713/PMC2515713.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Association between Aggression and Mean Change in Cortisol
  footer_text: † p < .10 * p < .05 **p < .01 *** p < .001 1 Although not pertinent to the hypotheses of the present study, scaling estimates for the intercept, linear slope, and quadratic change are reported for completeness.
    unique: PMC2515713/PMC2515713.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515624.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515713.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515713.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515713.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515713.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2515822.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: The Association between Aggression and Mean Change in Cortisol in Maltreated and Nonmaltreated Children
  footer_text: † p < .10 * p < .05 ** p < .01 *** p < .001 1 Although not pertinent to the hypotheses of the present study, scaling estimates for the intercept, linear slope, and quadratic change are reported for completeness.
    unique: PMC2515713/PMC2515713.xml::T4-0

PMC0025XXXXX/PMC2515822.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Oligonucleotide primer pairs and PCR parameters
  footer_text: a The top primer is the sense primer and the bottom primer is the antisense primer
    unique: PMC2515822/PMC2515822.xml::T1-0

PMC0025XXXXX/PMC2515935.xml

PMC0025XXXXX/PMC2516078.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: The effects of amino acid changes on the λmax shift
  footer_text: Amino acid residue numbers are those of bovine RH1 pigment. Residues 164, 261, and 269 correspond to 180, 277, and 285 in the human M/LWS pigments, respectively. a Forward amino acid replacements have been defined previously (Yokoyama 2000a,b; Shi et al. 2001; Yokoyama and Tada 2003; Takahashi and Yokoyama 2005). b Takahashi and Ebrey (2003). c Sugawara et al. (2005). d Yokoyama et al. (2005). e Zhukovsky and Oprian (1989). f Sakmar et al. (1989). g Babu et al. (2001). h Yokoyama and Tada (2003, references therein).
    unique: PMC2516078/PMC2516078.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516078.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516078.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516078.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: The λmax’s of M/LWS pigments measured using the in vitro assay
  footer_text: The λmax’s that are underlined were measured by subtracting a spectrum measured after photobleaching from a spectrum measured before light exposure (difference spectra), and the λmax’s that are not underlined were measured before light exposure (dark spectra). The “Ancestor d” pigments in group 1 have identical amino acid sequences, but their λmax’s, evaluated by different investigators, differed by 2 nm, while those in the other groups have different amino acids at 180, 197, 277, 285, and 308 (see column 1). Sq. monkey, squirrel monkey. a Yokoyama and Radlwimmer (2001). b Matsumoto et al. (2006). c Yokoyama et al. (2005). d Sun et al. (1997). e Asenjo et al. (1994). f Merbs and Nathans (1993). g Merbs and Nathans (1992). h Hiramatsu et al. (2005). i Davies et al. (2007). j Hiramatsu et al. (2004, references therein).
    unique: PMC2516078/PMC2516078.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: The effects of amino acid replacements on the λmax shift obtained by Yokoyama and Radlwimmer (2001) and by our mutagenesis method
  footer_text: Some θ’s in Yokoyama and Radlwimmer (2001) were close to zero (—) or could not be determined (?).
    unique: PMC2516078/PMC2516078.xml::T3-0

PMC0025XXXXX/PMC2516917.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Candidate prostate cancer genes (decreased in prostate vs. seminal vesicle)
  footer_text: * Genes upregulated in cultured prostate cancer cells following 5-aza-dC treatment. # Cytobands coinciding with prostate cancer susceptibility loci. ≠ Average ratio of expression in seminal vesicle compared to normal prostate
    unique: PMC2516917/PMC2516917.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516917.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516917.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516963.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516963.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516963.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Candidate prostate cancer genes (increased in prostate vs. seminal vesicle)
  footer_text: ≠ Average ratio of expression in normal prostate compared to seminal vesicle.
    unique: PMC2516917/PMC2516917.xml::T2-0

PMC0025XXXXX/PMC2516963.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Patient Characteristics in the Two Cohorts*
  footer_text: * Missing values were present for some variables as follows. In the development cohort, race data (missing n=178), marital status (n=11); in the validation cohort, race data (n=151), marital status (n=9). † No statistically significant differences in baseline characteristics between the two cohorts.
    unique: PMC2516963/PMC2516963.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Variables Considered as Risk Factors for Hospitalization in the Development Cohort*
  footer_text: * Prev=prevalence; RR=relative risk; CI=confidence interval. Missing values were present for some variables as follows: race data (missing n=178), marital status (n=11). † Abnormal laboratory results included hematocrit < 30 ml/dL, serum albumin < 3.0 mg/dL, or serum creatinine > 1.5 mg/dL in previous year. The most abnormal result during the previous year was used to score this variable.
    unique: PMC2516963/PMC2516963.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Independent Risk Factors for Hospitalization*
  footer_text: * RR=relative risk; CI=confidence interval. n=number of patients with the risk factor present. † Adjusted relative risk derived from multivariable models in PROC GENMOD. ‡ _Includes imputed values for 11 missing subjects.
    unique: PMC2516963/PMC2516963.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Performance of the Predictive Model in the Two Cohorts*
  footer_text: * RR=relative risk; CI=confidence interval. Includes imputed values for marital status for 11 subjects in development cohort and 9 subjects in validation cohort. † χ2trend = 115.6, P<0.0001 ‡ χ2trend = 1151.3, P<0.0001
    unique: PMC2516963/PMC2516963.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2516963.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517055.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517055.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517055.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2517055.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Individual and Mean (±SEM) ED50 (mg/kg, i.m.) Values for Zolpidem Generalization From Ethanol
  footer_text: Values from sessions with vehicle (i.m.) pretreatment are shown in parentheses but not included in calculation of the mean. NC, not calculable because maximum ethanol-appropriate responding <50%. a Maximum ethanol-appropriate responding ≤79% (i.e., partial generalization).
    unique: PMC2517055/PMC2517055.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Individual and Mean Apparent pKB (95% confidence interval) for Antagonism of Zolpidem Generalization From 1.0 and 2.0 g/kg Ethanol by Ro15-4513 in Cynomolgus Monkeys
  footer_text:
    unique: PMC2517055/PMC2517055.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Test Drugs Generalizing From Ethanol in Cynomolgus Monkeys From Published Reports and the Current Data Set (Zolpidem)
  footer_text: ■, complete generalization (≥80% ethanol-appropriate responding for the entire session); partial generalization (≥20 and ≤79% ethanol-appropriate responding for the entire session); □, no generalization (<20% ethanol-appropriate responding for the entire session); NC, data not collected. a Grant et al., 2000 b Vivian et al., 2002.
    unique: PMC2517055/PMC2517055.xml::T3-0

PMC0025XXXXX/PMC2517140.xml

PMC0025XXXXX/PMC2517158.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of Study Subjects assessed in 1998/99 as a Function of their Diagnostic Classification in 1998/99 and 2002/2003
  footer_text: 1 Number (percent) with at least on E*4 allele 2 Number (Percent) of participants in the group meeting CHS criteria for the condition 3 Number (percent) scoring 8 or higher on the Center for Epidemiological Studies Depression Scale (28) 4 Neuropsychological Composite Variables expressed as T-scores using age-and education-adjusted norms. 5 p < .001
    unique: PMC2517158/PMC2517158.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Coordinates (in MNI Space) of Peak Voxels in Regions Showing Significant Differences from Normal Control Subjects
  footer_text:
    unique: PMC2517158/PMC2517158.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Volume of Region of Interest Extracted using SPM2 as a Function of Diagnostic Group by Year of Study
  footer_text: Note: The volume unit is the mean volume (mL) per voxel within the region of interest, adjusted for the total brain volume, and the Gaussian smoothing filter.
    unique: PMC2517158/PMC2517158.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517158.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517158.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517158.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2517215.xml

PMC0025XXXXX/PMC2517226.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Cluster of C. elegans CED-1 regulated genes
  footer_text: Shown are the mean ± error of expression levels in wild-type (n = 3) and ced-1(e1735) (n = 2) animals. Eggs were placed in S basal to hatch overnight, causing growth arrest in L1. Synchronized L1 wild-type and ced-1(e1735) animals were grown on E. coli at 25°C for 26 hours and RNA was isolated. Expression data were normalized and cluster of CED-1 regulated genes was performed as described in Experimental Procedures.
    unique: PMC2517226/PMC2517226.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517226.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517235.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517235.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517235.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2517235.xml
  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: Percent correct classification of within-form and cross-form discriminant analyses based on spectral parameters alone (F1/F2 in Bark values) shown in the left column, and spectral parameters plus vocalic duration shown in the right column.
  footer_text:
    unique: PMC2517235/PMC2517235.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE II
  caption_text: Acoustic similarity (F1/F2 in Bark values) of Japanese and American English (AE) vowels: hVb(a) syllables produced in citation.
  footer_text:
    unique: PMC2517235/PMC2517235.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE III
  caption_text: Acoustic similarity (F1/F2 Bark values) of Japanese and American English (AE) vowels: hVb(a) syllables produced in sentence.
  footer_text:
    unique: PMC2517235/PMC2517235.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: TABLE IV
  caption_text: Perceptual Assimilation Patterns. Categorization responses, expressed as percentages of total responses summed over speakers and listeners for citation-form (A) and sentence-form (B) materials. Bold = modal perceptual classification; boxed = modal acoustic classification.
  footer_text:
    unique: PMC2517235/PMC2517235.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: APPENDIX
  caption_text: AVERAGE FORMANT FREQUENCIES AND DURATIONS OF JAPANESE (J) AND AMERICAN ENGLISH (AE) VOWELS.
  footer_text:
    unique: PMC2517235/PMC2517235.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517235.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517268.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517268.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2517268.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Questionnaire Items Used as Independent Variables and Covariates with Respective Response Options
  footer_text:
    unique: PMC2517268/PMC2517268.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Characteristics of Respondents and Health Centers with Univariate Regression Coefficients Predicting Change in Morale and Burnout among HDC Team Members (n = 622)
  footer_text: † Change in response on 1-5 scale. + p ≤ .10. * p ≤ .05. ** p ≤ .01. ‡ “During calendar year 2003, to what degree did the Collaborative worsen or improve staff morale at your center?”: 1 = “greatly worsened”; 2 = “somewhat worsened”; 3 = “no change”; 4 = “somewhat improved”; 5 = “greatly improved.” § “Team members became burned out because of their Collaborative duties.” 1 = “strongly disagree”; 2 = “disagree”; 3 = “neither agree nor disagree”; 4 = “agree”; 5 = “strongly agree.” ¶ Range = 1-3: Low to high index of HDC outcomes. ∥ Range = 1-5: Low to high scoring of HDC performance. †† 1 = “none”; 2 = “a little bit”; 3 = “a moderate amount”; 4 = “quite a bit”; 5 = “a great deal.” ‡‡ Data from the Uniform Data System: aggregate summary for each health center, averaged over health centers. §§ Range = 0-4: “no decrease in provider participation” to “decrease in participation” across four provider types. ¶¶ 1 = “strongly disagree”; 2 = “disagree”; 3 = “neither agree nor disagree”; 4 = “agree”; 5 = “strongly agree.” ∥∥ Range = 0-8: Support in up to eight areas including training, information systems, funding for quality improvement was reported as “very useful” or “critically useful.” HDC, Health Disparities Collaboratives; HC, health center; FTE, full-time equivalent; CEO, Chief Executive Officer; QI, quality improvement.
    unique: PMC2517268/PMC2517268.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Predictors of Staff Morale and Burnout Associated with the Health Disparities Collaboratives*
  footer_text: * Mixed linear regression estimates † “During calendar year 2003, to what degree did the Collaborative worsen or improve staff morale at your center?” 1 = “greatly worsened”; 2 = “somewhat worsened”; 3 = “no change”; 4 = “somewhat improved”; 5 = “greatly improved.” ‡ Final models identical regardless of inclusion of HDC outcome variables. § “Team members became burned out because of their Collaborative duties.” 1 = “strongly disagree”; 2 = “disagree”; 3 = “neither agree nor disagree”; 4 = “agree”; 5 = “strongly agree.” HDC, Health Disparities Collaboratives; HC, health center.
    unique: PMC2517268/PMC2517268.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517268.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517272.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517272.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517272.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517272.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2517272.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of the Patient Sample, N= 25,957
  footer_text: Note. In subsequent analyses, patients without admission source and admission severity score were excluded, with a resulting analytic sample of 24,618.
    unique: PMC2517272/PMC2517272.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Nursing Organization Characteristics, Hospital Level (n = 164)
  footer_text: PES-NWI, Practice Environment Scale of the Nursing Work Index. PES-NWI scores are scored from 1 = strongly disagree; 2 = disagree; 3 = agree, and; 4 = strongly agree that the characteristic is present in their current job.
    unique: PMC2517272/PMC2517272.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Unadjusted Outcome Rates
  footer_text:
    unique: PMC2517272/PMC2517272.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Unadjusted Outcome Rates (%) by Organizational Characteristics, (n= 24,618)
  footer_text: * Differences across groups significant at p< .05. ** Differences across groups significant at p<.01. NCI = National Cancer Institute
    unique: PMC2517272/PMC2517272.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Predictors of Patient Outcomes, Controlling for Hospital and Patient Characteristics
  footer_text: Note: D, 30-day mortality; C, Complications; FTR, Failure to Rescue; NCI, National Cancer Institute; CI, Confidence interval. All models include 25 patient characteristics, bed size, teaching status, and performance of advanced procedures (output suppressed). Marginal analyses consider these patient and hospital characteristics, plus each one of the predictor variables. Partial analyses consider all patient and hospital characteristics, as well as all predictor variables simultaneously. Details on variables and measurement are available in Appendix S1.
    unique: PMC2517272/PMC2517272.xml::T5-0

PMC0025XXXXX/PMC2517273.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Descriptive statistics and comparison of survey responders and non-responders. (Standard deviations for continuous variables in parentheses)
  footer_text: a *** p < 0.001 ** 0.001 ≤ p < 0.01 * 0.01 ≤ p < 0.05 b Sample size for each QM was different because not all facilities had a score reported.
    unique: PMC2517273/PMC2517273.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Impact of publication of report card on the QMs: A pre/post analyses
  footer_text: Based on linear combinations of coefficients from estimated model: QMi,t=α+βt+γPi+δPit+∑iφiDi where P =1 post publication and D is a vector of fixed facility effects. Regression coefficients are shown in online appendix table 1. *** p≤0.001 ** 0.001<p≤0.01 * 0.01<p<0.05
    unique: PMC2517273/PMC2517273.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517272.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517273.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517273.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517273.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Analysis of the impact of number of actions (N) taken
  footer_text: Based on linear combinations of coefficients from estimated model: QMit=α+βt+γPi+δ1PiNi+δ2PiNi2+∑iφiDi where P = 1 post publication, N = number of actions taken in response to publication, and D is a vector of fixed facility effects. Regression coefficients are shown in online appendix table 2. *** p≤0.001 ** 0.001<p≤0.01 * 0.01<p<0.05
    unique: PMC2517273/PMC2517273.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Analysis of the impact of specific actions
  footer_text: Based on linear combinations of coefficients from estimated model: QMit=α+βt+γPi+∑k=120δkPiAik+∑iφiDi where P = 1 post publication, Ak = 1 if action k was taken, and D is a vector of fixed facility effects. Regression coefficients are shown in online appendix table 3. *** p≤0.001 ** 0.001<p≤0.01 * 0.01<p<0.05
    unique: PMC2517273/PMC2517273.xml::T4-0

PMC0025XXXXX/PMC2517420.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Demographic and clinical characteristics of patients with preterm labor and intact membranes (PTL) and patients with preterm prelabor rupture of membranes (PROM)
  footer_text: IAI: intra-amniotic infection; Values are expressed as median (range) or numbers (percent); * p<0.05; a p comparison between PTL who delivered preterm without IAI and PTL with IAI; b p comparison between PTL who delivered at term without IAI and PTL with IAI; c p comparison between preterm PROM with and without IAI
    unique: PMC2517420/PMC2517420.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517273.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517420.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517420.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Demographic and clinical characteristics of women at midtrimester, women at term not in labor and women at term in labor
  footer_text: Values are expressed as median (range) or numbers (percent)
    unique: PMC2517420/PMC2517420.xml::T2-0

PMC0025XXXXX/PMC2517611.xml

PMC0025XXXXX/PMC2517849.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Percent of R01 clinical applications
  footer_text: Abbreviations: PI, principals investigator; A0, initial application, A1, first revision; A2, second revision of application; T1, new application; T2, competing renewal application
    unique: PMC2517849/PMC2517849.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Rate of submission of initial and revised applications.
  footer_text: Abbreviations: PI, principals investigator; A0, initial application, A1, first revision; A2, second revision of application; T1, new application; T2, competing renewal application
    unique: PMC2517849/PMC2517849.xml::T2-0

PMC0025XXXXX/PMC2518063.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Demographic and Metabolic Characteristics*
  footer_text: * Means ± standard deviations presented; for those without normal distributions, geometric means and standard deviations are presented. Exercise training adherence = Completed/prescribed miles per week*100 † Differs from other groups with Tukey’s post-hoc testing p<0.05 ** Differs from men with Tukey’s post-hoc testing p<0.05
    unique: PMC2518063/PMC2518063.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517849.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2517849.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518063.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518063.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Correlation Coefficients for Change in Insulin Sensitivity (SI [mU/L/min])
  footer_text: Data are presented as correlation coefficients (r) for the univariate relationship between the indicated variable and insulin sensitivity change. * P<0.05 † P<0.005
    unique: PMC2518063/PMC2518063.xml::T2-0

PMC0025XXXXX/PMC2518098.xml

PMC0025XXXXX/PMC2518124.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Association of SNPs for Mayo Clinic breast cancer cases and controls, stratified on menopausal status. The three SNPs that were genotyped in the two replication studies are “boxed”.
  footer_text: (1) = Adjusted for matching variables of age and area. (2) = Adjusted for age, area, parity/age at first child birth, and physical activity.
    unique: PMC2518124/PMC2518124.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Association of SNPs in the two replication studies, stratified on menopausal status.
  footer_text: (1) = Adjusted for HRT use and physical activity. (2) = Adjusted for physical activity and parity/age at first child birth.
    unique: PMC2518124/PMC2518124.xml::T2-0

PMC0025XXXXX/PMC2518165.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518124.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518165.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518205.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Esophageal cancer incidence among whites, nine Surveillance, Epidemiology, and End Results registries, 1975−79 to 2000−04
  footer_text: * Rates are per 100,000 person-years, age-adjusted to the 2000 US Standard Population. CI = Confidence Interval (Tiwari mod) are 95% for rates; NOS = not otherwise specified; — = Statistic could not be calculated because the rate was based on fewer than 10 cases.
    unique: PMC2518165/PMC2518165.xml::T1-0

PMC0025XXXXX/PMC2518205.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Features of Alzheimer’s Disease explained by the Metal Theory
  footer_text:
    unique: PMC2518205/PMC2518205.xml::T1-0

PMC0025XXXXX/PMC2518316.xml

PMC0025XXXXX/PMC2518320.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Phenotypic Data for Members of a Family with Autosomal Dominant Atrial Fibrillation.*
  footer_text: * AF denotes atrial fibrillation, JR junctional escape rhythm, LAE left atrial enlargement, LVDD left ventricular diastolic dimension, LVSD left ventricular systolic dimension, LVEF left ventricular ejection fraction, LVH left ventricular hypertrophy, NA not available, NSR normal sinus rhythm, PAF paroxysmal atrial fibrillation, SB sinus bradycardia, and ULN upper limit of the normal range for that patient in millimeters. Dashes denote not applicable. † Echocardiographic measurements in affected subjects were performed during effective ventricular rate control when atrial fibrillation was present. ‡ The normal value is 50% or more. § Echocardiography was performed before the onset of atrial fibrillation. ¶ Normal sinus rhythm was not documented but was reported in the subject’s medical history. || Subject III-8 had a ventricular pacemaker.
    unique: PMC2518320/PMC2518320.xml::T1-0

PMC0025XXXXX/PMC2518323.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Lipid peroxidation and protein oxidation in sciatic nerves from control and galactose-fed rats.
  footer_text: Data are mean ± SEM (N = 7–11 per group) and were analyzed with unpaired, two-tailed t-tests. Differences are not significant.
    unique: PMC2518323/PMC2518323.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Body weight, blood glucose and nerve sugar levels in control rats, diabetic rats and diabetic rats treated with the aldose reductase inhibitor, ICI 222155, or insulin for the last 4 weeks of an 8-week period of diabetes.
  footer_text: Data are presented as mean ± SEM (N = 8–16 per group) and were analyzed by one-way ANOVA, after which multiple comparisions were made with Dunnett’s post-hoc test. * p<0.05 vs untreated diabetic group.
    unique: PMC2518323/PMC2518323.xml::T2-0

PMC0025XXXXX/PMC2518404.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518320.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518323.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518323.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of individuals in the Polyp Prevention Trial of Aspirin and Folate who completed first year follow-up
  footer_text: ¥ 81 and 325 mg/day aspirin treatment groups combined * Total folate and total B6 = dietary + supplements † Total B2 from dietary sources only ‡ Total B12 from supplements only § using standard definitions by Polyp Prevention Study Group (28, 29) ** chi-square test # two sample t-test
    unique: PMC2518404/PMC2518404.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Association of vitamin B2, B6 and B12 baseline plasma levels and risk of colorectal adenomas
  footer_text: * Adjusted for age, sex, center, duration of follow-up, aspirin treatment group, and multivitamin use ¥ Adjusted for age, sex, center, duration of follow-up, aspirin treatment group, multivitamin use, and plasma B2, B6, B12 and folate as appropriate ¶ p-value for trend.
    unique: PMC2518404/PMC2518404.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Association of baseline intakes of vitamins B2, and B6 with risk of colorectal adenomas
  footer_text: * Adjusted for age, sex, center, duration of follow-up, aspirin treatment group, and multivitamin use ¥ Adjusted for age, sex, center, duration of follow-up, aspirin treatment group, multivitamin use, and intake of B2, B6 and folate as appropriate ¶ p-value for trend ** Ranges are based on 2000 calories/day
    unique: PMC2518404/PMC2518404.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518404.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518404.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518404.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Association of vitamin B2, B6 (PLP) and B12 baseline plasma levels and the risk of colorectal adenomas by folate treatment group, multivitamin and alcohol use at baseline
  footer_text: * Adjusted for age, sex, center, duration of follow-up, aspirin treatment group, multivitamin use and plasma B2, B6, B12 and folate as appropriate † Adjusted for age, sex, center, duration of follow-up, aspirin treatment group, and plasma B2, B6, B12 and folate as appropriate ** Quartiles for vitamin B2 (riboflavin): Q1: 2.1-8.9 nmol/L; Q2: 9.0-15.0 nmol/L; Q3: 15.1-27.5 nmol/L; Q4: 27.6-479.0 nmol/L *** Quartiles for vitamin B6 (PLP): Q1: 4.7-35.6 nmol/L; Q2: 35.7-53.3 nmol/L; Q3: 53.4-84.3 nmol/L; Q4: 84.7-857.0 nmol/L **** Quartiles for vitamin B12: Q1: 21.4-235.9 pmol/L; Q2: 236.4-300.3 pmol/L; Q3: 300.5-388.8 pmol/L; Q4: 389.2-2479 pmol/L ¥ p-value for interaction ¶ p-value for trend
    unique: PMC2518404/PMC2518404.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Selected gene-vitamin B interactions and risk of colorectal adenomas
  footer_text: * Adjusted for age, sex, center, duration of follow-up, aspirin treatment group, multivitamin use and plasma B2, B6, B12 and folate as appropriate ¥ p-value for interaction
    unique: PMC2518404/PMC2518404.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518404.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518404.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2518644.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Descriptive statistics of HHFS, morbidity, and feeding practices of infants at different ages
  footer_text: 1 Only infant feeding scales were standardized and expressed as a percentage of the value of the upper range of theoretical scales.
    unique: PMC2518644/PMC2518644.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Lagged model effects of HHFS and other infant, maternal, and household factors on the changes in IFP from 3–6, 6–9, and 9–12 mo of age
  footer_text: 1 Lagged morbidity, lagged feeding, birth weight, and sex of infants. 2 Lagged morbidity, lagged IFP, birth weight, and sex of infants, and maternal age, weight, education, and wealth index.
    unique: PMC2518644/PMC2518644.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Summary of lagged, dynamic, and difference model effects of HHFS and other infant and maternal factors on the changes in IFP from 3–6, 6–9, and 9–12 mo of age
  footer_text: 1 –, Variables were not included in the models.
    unique: PMC2518644/PMC2518644.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518644.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518644.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518644.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518983.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2518746.xml

PMC0025XXXXX/PMC2518964.xml

PMC0025XXXXX/PMC2518983.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Simulated surface tensions of aqueous solutions of NaCl and methanol.
  footer_text: All simulations were performed at 300 K for a total simulation time of Tsim. Symbols are: nio, the total number of solute and water molecules used in the simulations; Cso (x2o), the initial bulk solute concentrations; cs (x2), the final bulk solute concentrations. Typical estimated errors for the surface tension values are ±0.3 mN/m.
    unique: PMC2518983/PMC2518983.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Simulated and experimental surface adsorption data for aqueous solutions of NaCl and methanol.
  footer_text: All data correspond to 300 K. See text for symbol definitions. In the case of ∂γ/∂y, y = cs for NaCl and y = x2 for methanol. The values of the relative surface adsorptions correspond to those obtained from the fitted surface tension changes and bulk solution properties (a22 and η). Units are cs (M), η (M), ∂γ/∂y (mN/m/M for NaCl and mN/m for methanol), and Γ2,1 in ions or molecules/nm2.
    unique: PMC2518983/PMC2518983.xml::T2-0

PMC0025XXXXX/PMC2519027.xml

PMC0025XXXXX/PMC2519048.xml

PMC0025XXXXX/PMC2519054.xml

PMC0025XXXXX/PMC2519120.xml

PMC0025XXXXX/PMC2519143.xml

PMC0025XXXXX/PMC2519172.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2518983.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519612.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519612.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2519612.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Chemopreventive effects of methylselenocysteine on NMU-induced mammary carcinogenesis in female F344 rats.
  footer_text: † Tumor incidence was defined by number of tumor-bearing rats divided by total number of rats. †† Both tumor incidence and total number of tumors presented in this table are histologically confirmed adenocarcinomas. ‡ Multiplicity was defined by the total number of tumors divided by total number of tumor-bearing rats. § Tumor inhibition was calculated based on total number of tumors. * P<0.05
    unique: PMC2519612/PMC2519612.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Results of GoMiner Gene enrichment analysis of differentially expressed genes by selenium.
  footer_text:
    unique: PMC2519612/PMC2519612.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Pair-wised comparison of Per2 and DBP mRNA levels between mammary carcinomas and their adjacent normal tissues.
  footer_text:
    unique: PMC2519612/PMC2519612.xml::T3-0

PMC0025XXXXX/PMC2519872.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Group Characteristics
  footer_text: * mean ± standard error
    unique: PMC2519872/PMC2519872.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary of Statistical Significances Using Limited and Complete Models
  footer_text: Hypothesis testing: Intent to treat responses were used. Both models were repeated measures analysis of variance. Effects in the limited model were diet and visit (Month 1, 2, 3). Effects in the complete model were visit (Month 1, 2, 3), diet, gender, age, baseline measure of index being evaluated. Interactions of Visit × Diet and Diet × Gender. # Month 2 was different (Tukey’s test, P < 0.05) from month 1 and 3 * Linear effect from month 1 to month 3 was stronger (p=.0001) than using discrete time points (visits) (p=.0007)
    unique: PMC2519872/PMC2519872.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Clinical measures over time
  footer_text:
    unique: PMC2519872/PMC2519872.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519612.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519872.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519872.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519872.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Clinical measures over time by gender
  footer_text:
    unique: PMC2519872/PMC2519872.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Distribution of lost ligatures
  footer_text:
    unique: PMC2519872/PMC2519872.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Clinical measures under the assumption of intent to treat (Control n=32, experimental n=23)
  footer_text:
    unique: PMC2519872/PMC2519872.xml::T6-0

PMC0025XXXXX/PMC2519956.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of EXAFS Fitting Results for Copper RBP (Best Fit in Bold)
  footer_text: a Independent metal–ligand scattering environment. b Scattering atoms: O (Oxygen), N (Nitrogen), C (Carbon). c Metal–ligand bond length in Å. d Metal–ligand coordination number. e Debye–Waller factor in Å2 × 103. f Number of degrees of freedom weighted mean square deviation between data and fit. g Fit using only single scattering Feff 7 theoretical models. h Fit using both single scattering Feff 7 model with an additional multiple scattering Fe–N(Imidazole) model, generated based on crystallographic coordinates listed in ref 17,17 and labeled NIm in table atom designation. Details of fitting are described in the Experimental Section.
    unique: PMC2519956/PMC2519956.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519872.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519872.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519872.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2519956.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2522268.xml

PMC0025XXXXX/PMC2522309.xml

PMC0025XXXXX/PMC2522314.xml

PMC0025XXXXX/PMC2522366.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sample of Questions Related to Diabetes and Diabetic Eye Disease
  footer_text:
    unique: PMC2522366/PMC2522366.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Demographic Characteristics by Diabetes Status
  footer_text: a Differences significant at P<.05. b Question was not asked of the diabetic cohort.
    unique: PMC2522366/PMC2522366.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2522366.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2522366.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2522366.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2522366.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Diabetes Duration and Type of Treatment in Participants With Diabetes
  footer_text: a Refers to primary mode of treatment. b P<.05.
    unique: PMC2522366/PMC2522366.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Diabetes Knowledge by Level of Experience With Diabetesa
  footer_text: a Proportion of correct answers to the question, “What can a person with diabetes do to treat and control diabetes?”
    unique: PMC2522366/PMC2522366.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Predictors of Knowledge That Uncontrolled Diabetes Could Cause Eye Disease
  footer_text: Abbreviations: CI, confidence interval; OR, odds ratio. a P<.05.
    unique: PMC2522366/PMC2522366.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Predictors of Having a Dilated Eye Examination in the Past 2 Years in Persons With Diabetes
  footer_text: Abbreviations: CI, confidence interval; OR, odds ratio. a P<.05.
    unique: PMC2522366/PMC2522366.xml::T6-0

PMC0025XXXXX/PMC2522368.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: KD of the talin RM or smaller fragments binding to talin-PTB and talin-PTB mutants
  footer_text: a All binding affinities were calculated by two independent measurements using the BIAcore 3000 evaluation software (Biacore AB, Uppsala, Sweden). χ2 <10 were obtained for all the data, indicating good fit.
    unique: PMC2522368/PMC2522368.xml::T1-0

PMC0025XXXXX/PMC2522372.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2522366.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2522366.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2522368.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525452.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2525452.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Bias and Variance of Liver R1, R2 Calibration Curves
  footer_text: Bold type indicates statistically significant difference
    unique: PMC2525452/PMC2525452.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Bias and Variance of Heart R1, R2 Calibration Curves
  footer_text: Bold type indicates statistically significant difference
    unique: PMC2525452/PMC2525452.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Variability of Tissue Iron and Tissue NMR measurements
  footer_text:
    unique: PMC2525452/PMC2525452.xml::T3-0

PMC0025XXXXX/PMC2525512.xml

PMC0025XXXXX/PMC2525738.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525452.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525452.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525795.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525795.xml::T1-1'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525795.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525795.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525795.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2525795.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Inclusion and exclusion criteria for MOCOCS study
  footer_text:
    unique: PMC2525795/PMC2525795.xml::T1-0
    unique: PMC2525795/PMC2525795.xml::T1-1
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Sequence and description of color measurements of subjects’ craniofacial structures
  footer_text:
    unique: PMC2525795/PMC2525795.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table III
  caption_text: Summaries of color parameters of central incisors of 120 teeth (CIELAB units)
  footer_text:
    unique: PMC2525795/PMC2525795.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table IV
  caption_text: ANOVA summary for multiple linear regression of L*a*b* for central incisor
  footer_text:
    unique: PMC2525795/PMC2525795.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table V
  caption_text: Associated parameter estimates for central incisor of L*a*b*
  footer_text: ** Parameter estimates were developed using only statistically significant factors found in full model, as noted in text. *** For null hypothesis, population value = 0.
    unique: PMC2525795/PMC2525795.xml::T5-0

PMC0025XXXXX/PMC2525799.xml

PMC0025XXXXX/PMC2526058.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2525795.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2526058.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2526059.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Histologic Grading
  footer_text: Histologic evaluation of each study group. Note the histologic score was performed using standard Hematoxylin and Eosin staining. The Fibrosis score was a ranking of the density of fibrosis after Mason’s trichrome staining based on an arbitrary range of 0 to 5 for each of 4 quadrants of a cross-section of the distal colonic wall. The collagen density values represent the digitized areas of collagen staining as described in the Methods section. Note that ACE-I treatment resulted in a significant decrease in the amount of fibrosis. Abbreviations: DSS, dextran sulfate sodium. ACE-I, angiotensin converting enzyme inhibitor. * P<.05 (ANOVA), Control (Naïve mice, no DSS treatment) versus DSS+Placebo group # P<.05 (ANOVA), DSS+Placebo versus DSS+ACE-I treated group. Data are mean ± SD.
    unique: PMC2526058/PMC2526058.xml::T1-0

PMC0025XXXXX/PMC2526059.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Hepatic Gene Expression Analysis of Wild-type Compared to Fah−/− or Fah−/−, p21−/−Mice off NTBC
  footer_text: Gene expression levels on a logarithmic scale: 10E(number of ●, with ◖= ~0.5). Genes differentially expressed between Fah−/− and Fah−/−, p21−/− mice such as the mitosis regulators Cyclin A2 and B1 are highlighted in bold. The effect of NTBC on hepatic gene expression is restricted to Fah deficiency (data not shown). Hence, gene expression levels in wild-type mice on water represent findings in wild-type, Fah−/− and Fah−/−, p21−/− mice on NTBC. Raw microarray data is provided in Supplemental Figure 1A.
    unique: PMC2526059/PMC2526059.xml::T1-0

PMC0025XXXXX/PMC2526181.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sociodemographic and Health Related Profile and Cancer Screening Rates for Study Sample, Pooled 2003 and 2005 CHIS data, Unweighted, women aged 40-75, men aged 50-75
  footer_text: * Self-reported race/ethnic identity using UCLA CHPR categories; white, non-Hispanic excluded. † Respondents answering “yes” to question: “Was there ever a time when you would have gotten better medical care if you had belonged to a different race or ethnic group?” ‡ Endoscopy: sigmoidoscopy or colonoscopy.
    unique: PMC2526181/PMC2526181.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2526181.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2526181.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527026.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527026.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Weighted Colorectal and Breast Cancer Screening Rates by Ethnicity and Medical Discrimination*
  footer_text: * Unless otherwise indicated, all the comparisons between no reported vs. reported discrimination are statistically significant (p < 0.001). † Not statistically significant ‡ Predictor variables included in the sociodemographics model were age, education, household income, ethnicity and survey year. § Predictor variables included in the sociodemographics and health factors model were age, education, household income, ethnicity, survey year, health insurance, health status, having a usual source of care, and having a previous diagnosis of cancer.
    unique: PMC2526181/PMC2526181.xml::T2-0

PMC0025XXXXX/PMC2527026.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sample characteristics of participants
  footer_text: + For HRV measures, geometric means are presented with SD of the logged values
    unique: PMC2527026/PMC2527026.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Cross sectional associations between HRV (1 SD decrease) and cognitive function (odds of lowest quintile).
  footer_text: + Odds ratios are adjusted for age, sex and highest educational attainment
    unique: PMC2527026/PMC2527026.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Prospective association between HRV at phase 5 (1 SD decrease) and cognitive function at phase 7 (odds of lowest quintile).
  footer_text: + Odds ratios are adjusted for age, sex and highest educational attainment
    unique: PMC2527026/PMC2527026.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527026.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527026.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527026.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527026.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Prospective association between HRV at phase 5 (1 SD decrease) and decline in cognitive function between Phase 5 and Phase 7 (odds of lowest quintile of change).
  footer_text: + Odds ratios are adjusted for age, sex and highest educational attainment and time interval between Phase 5 and Phase 7
    unique: PMC2527026/PMC2527026.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Cross sectional associations between HRV (1 SD decrease) and cognitive function (odds of lowest quintile) among participants with coronary heart disease.
  footer_text: + Odds ratios are adjusted for age, sex and highest educational attainment
    unique: PMC2527026/PMC2527026.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Prospective association between HRV at phase 5 (1 SD decrease) and cognitive function at phase 7 (odds of lowest quintile) among participants with coronary heart disease.
  footer_text: + Odds ratios are adjusted for age, sex and highest educational attainment and time interval between Phase 5 and Phase 7
    unique: PMC2527026/PMC2527026.xml::T6-0

PMC0025XXXXX/PMC2527051.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: General characteristics of a sample of normal-weighta seventh-grade students participating in the Teens Eating for Energy and Nutrition at Schools (TEENS) study, by sex
  footer_text: a Defined as body mass index between 5th and <85th percentile. b Defined as any past 30 days use of diet pills, vomiting, laxatives, or diuretics.
    unique: PMC2527051/PMC2527051.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527051.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527051.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527051.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527051.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527055.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Unadjusted associations between seventh grade predictorsa and overweight status during eighth grade, for participants in the Teens Eating for Energy and Nutrition at Schools (TEENS) study, by sex (n = 1,728)
  footer_text: a Based on data collected from classroom surveys. Detailed description of scales and items used in the TEENS study are provided elsewhere (24). b NA = not applicable. The sample size was too small for analysis. * P<0.05.
    unique: PMC2527051/PMC2527051.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Predictors of becoming overweight during eighth gradea, based on data collected as part of the Teens Eating for Energy and Nutrition at Schools (TEENS) study (n = 1,728)
  footer_text: a Adjusted for socioeconomic status variables, race, and intervention condition. Detailed description of scales and items used in the TEENS study are provided elsewhere (24). * P<0.05.
    unique: PMC2527051/PMC2527051.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Predictors of becoming overweight during eighth gradea among boys and girls in the fifth to 75th percentiles for body mass index (n=1,456) in the Teens Eating for Energy and Nutrition at Schools (TEENS) study (n=1,456)
  footer_text: a Adjusted for socioeconomic status variables, race, and intervention condition. Detailed description of scales and items used as predictors in the TEENS study are provided elsewhere (24). * P<0.05.
    unique: PMC2527051/PMC2527051.xml::T4-0

PMC0025XXXXX/PMC2527055.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Radiation Chemical Yields in nmol/J for Free Base Release in pUC18 Plasmid DNA Films and Calculation of the Multiplicity of Single-Strand Breaks
  footer_text: a G(sc-loss) values were reported under G total(ssb) in Table I of ref. (13). b Free base release multiplicity = m(fbr) = G(fbr)/G(sc-loss).
    unique: PMC2527055/PMC2527055.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Comparative Radiation Chemical Yields in nmol/J for Trapped Deoxyribose Radicals, Free Base Release and Direct SSBs
  footer_text: a A yield of 70 nmol/J (5) was applied to the water target mass, which consists of the water lying beyond the hole transfer layer: Γ-10 = target mass = 12.5 waters/nucleotide for Γ = 10. b Gdir(fbr) ≥ G(fbr) − G(●OH) and ≤G(fbr). c Values from ref. (12). d Gdir(ssb) = G(fbr) − 2 × G(dsb), assuming each SSB of the DSB gives a free base release. e SSB multiplicity = m(ssb) = Gdir(ssb)/G(sc-loss). f GdRib(fr) values were reported in Table I of ref. (13). g Shortfall = G(diff) = Gdir(ssb) − GdRib(fr).
    unique: PMC2527055/PMC2527055.xml::T2-0

PMC0025XXXXX/PMC2527207.xml

PMC0025XXXXX/PMC2527209.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Quantitative mass spectrometry of purified ribosome-channel complexes
  footer_text: The samples were divided into 6 aliquots which were analyzed and averaged. The appropriate tryptic peptide fragment for proteins marked with an asterisk (*) could only be detected reliably in 5 of the runs.The range of values for each component in the experiments is shown on the right in parenthesis.
    unique: PMC2527209/PMC2527209.xml::T1-0

PMC0025XXXXX/PMC2527442.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Crystal Data and Summary of Data Collection and Refinement for Clusters 3, 4, and 5a
  footer_text: a Collected using Mo Kα radiation (λ = 0.71073 Å) at 193 K. b R1 = Σ [(Fo − Fc)]/Σ (Fo). c wR2 = {Σ [w(Fo2 − Fc2)2/Σ[w(Fo2)2]}1/2. d I >2σ(I). e All data.
    unique: PMC2527442/PMC2527442.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527055.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527209.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527442.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Selected Interatomic Distances (Å)a and Angles (deg) of [Fe7S6(PEt3)5Cl2]
  footer_text: a Averaged under idealized Cs symmetry. b Bond distance notation: Fe(m)–S(x,y) is the mean of Fe(m)–S(x) and Fe(m)–S(y); Fe(m,n)–S(x,y) is the mean of Fe(m)–S(x) and Fe(n)–S(y). c Displacement (Å) of Fe atom from S3 plane.
    unique: PMC2527442/PMC2527442.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Selected Interatomic Distances (Å) and Angles (deg) of [Fe8S8(Pri2NHCMe2)6]
  footer_text: a Fe4S4, range of 12. b S(2,3,4) or Fe(2,3,4), range of 9.
    unique: PMC2527442/PMC2527442.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: 57Fe Mössbauer Parameters for [Fe4S4]0 and [Fe8S8]0 Clusters
  footer_text: a Referenced to Fe metal at room temperature; ±0.02 mm/s. b ±0.03 mm/s. c Reference 23. d Reference 22. e References 6, 9. f Spectrum analyzed as four equally intense doublets with the same isomer shift.
    unique: PMC2527442/PMC2527442.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Selected Interatomic Distances (Å) and Angles (deg) of [Fe4S4(Pri2NHCMe2)4]
  footer_text:
    unique: PMC2527442/PMC2527442.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Comparison of Structural Parameters of Cubane-Type [Fe4S4]0 Clusters
  footer_text: a Reference 23. b Reference 10. c Reference 8.
    unique: PMC2527442/PMC2527442.xml::T6-0

PMC0025XXXXX/PMC2527485.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527442.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527442.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527485.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527485.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Primers used in this study
  footer_text: * Genomic DNA was used as the template † Plasmid containing Rv1086 was used as the template
    unique: PMC2527485/PMC2527485.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: X-ray data
  footer_text: * These data were twinned, for the APO the twin fraction was refined for CITPP the data were detwinned. The twined data have been deposited as well as the de-twinned. † The completeness was limited by radiation damage. Thus the resolution limits for these data sets are nominal.
    unique: PMC2527485/PMC2527485.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Summary of protein activity
  footer_text:
    unique: PMC2527485/PMC2527485.xml::T3-0

PMC0025XXXXX/PMC2527511.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Affect of RNAi Depletion of Different Factors on the Chromatin Architecture at Hsp70
  footer_text: 1 Knockdown confirmed by Western to be 5–20% of LacZ RNAi levels. 2 Nucleosomes on the body of the gene are better positioned. 3 DNA at the 1st and 2nd nucleosomes after the TSS is less protected. 4 Resembles a NHS profile. 5 Resembles a 1’ HS profile. 6 DNA at the 1st nucleosome after the TSS is more protected.
    unique: PMC2527511/PMC2527511.xml::T1-0

PMC0025XXXXX/PMC2527598.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527485.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527511.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Selected statistical data from the four main groups of mice
  footer_text:
    unique: PMC2527598/PMC2527598.xml::T1-0

PMC0025XXXXX/PMC2527650.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Prevalence of Selected Axis I Lifetime Diagnoses Among G1 and G2 Participants
  footer_text: Note: G1 = generation 1; G2 = generation 2; MDD = major depressive disorder; ANX = any anxiety disorder; SUD = any substance use disorder. a G1 n = 260; G2 n = 84. b G1 n = 267; G2 n = 183. c G1 N = 527; G2 N = 267. * χ2 significant gender difference at p < .001.
    unique: PMC2527650/PMC2527650.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Univariate and Multivariate Associations Between G2 MDD and G3 CBCL Scales
  footer_text: Note: N = 267. All scores are t scores. G2 = generation 2; MDD = major depressive disorder; G3 = generation 3; CBCL = Child Behavior Checklist; sr = semipartial correlation. a Adjusted for G2 CBCL rater status and G2 and G3 age and sex (n = 267, df = 261). b Adjusted for G2 Marital Status, Education, and Income (n = 254, df = 245). c Adjusted for G2 Dyadic Adjustment, O'Leary Porter, Major Life Events and Daily Hassles (n = 206, df = 193). † p = .06. * p < .05. ** p < .01.
    unique: PMC2527650/PMC2527650.xml::T2-0

PMC0025XXXXX/PMC2527731.xml

PMC0025XXXXX/PMC2527781.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Odds of reporting arthritis, diabetes, or hypertension in older Mexican women compared to men. (n = 7,792)
  footer_text: † ≤.10 * ≤ .05 ** ≤ .01 *** ≤ .001
    unique: PMC2527781/PMC2527781.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527598.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527650.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527650.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527781.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527817.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527817.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2527817.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Prevalence of malnutrition at the national level in children with cystic fibrosis1
  footer_text: 1 HTp, height percentile; BMIp, BMI percentile; %IBW, percentage of ideal body weight; CFF, Cystic Fibrosis Foundation. 2 Weight-for-height percentile was used instead of BMIp for children <2 y old. 3 Corrected classification refers to the elimination of %IBW as an indicator of underweight.
    unique: PMC2527817/PMC2527817.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Nutritional failure rates in children with cystic fibrosis (CF) among 113 CF centers1
  footer_text: 1 CFF, Cystic Fibrosis Foundation; HTp, height percentile; BMIp, BMI percentile; %IBW, percentage of ideal body weight. 2 x̄ ± SD (all such values). 3 Criterion: HTp < 5th, BMIp < 10th, or %IBW < 90. Weight-for-height percentile was used instead of BMIp for children <2 y old. 4 Correction: %IBW < 90 was eliminated as an indicator of underweight. 5 Criterion: HTp < 5th or BMIp < 10th. Weight-for-height percentile was used instead of BMIp for children <2 y old.
    unique: PMC2527817/PMC2527817.xml::T2-0

PMC0025XXXXX/PMC2527838.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Frequency and proportion of cases of breast cancer recurrence and matched controls within group strata (I) expressing the estrogen receptor and receiving at least one year of tamoxifen therapy (ERP+/TAM+), or (II) not expressing the estrogen receptor, never receiving tamoxifen therapy, and surviving at least one year after diagnosis (ERP−/TAM−)
  footer_text: † Variable included in risk set sampling to match controls to cases
    unique: PMC2527838/PMC2527838.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527838.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527838.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2527838.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Number of cases and controls receiving any prescription for each SSRI, and total number of prescriptions for each SSRI within group strata (I) expressing the estrogen receptor and receiving at least one year of tamoxifen therapy (ERP+/TAM+), or (II) not expressing the estrogen receptor, never receiving tamoxifen therapy, and surviving at least one year after diagnosis (ERP−/TAM−)
  footer_text: † In the analysis, we defined citalopram exposure as any prescription for Citalopram (N06AB04) or its s-stereoisomer Escitalopram (N06AB10).
    unique: PMC2527838/PMC2527838.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Association between SSRI prescription and breast cancer recurrence within strata of (a) Group I, women with tumors that expressed the estrogen receptor and who received at least one year of tamoxifen therapy (ERP+/TAM+), or (b) Group II, women with tumors that did not express the estrogen receptor, and who never received tamoxifen therapy, and who survived at least one year after diagnosis (ERP−/TAM−).
  footer_text: † Adjusted for age category and other CYP2D6 inhibiting medications (see the Supplementary On-line Material for a complete list of these medications and the frequency of their use in the study population).
    unique: PMC2527838/PMC2527838.xml::T3-0

PMC0025XXXXX/PMC2527972.xml

PMC0025XXXXX/PMC2528022.xml

PMC0025XXXXX/PMC2528059.xml

PMC0025XXXXX/PMC2528060.xml

PMC0025XXXXX/PMC2528248.xml

PMC0025XXXXX/PMC2528831.xml

PMC0025XXXXX/PMC2528843.xml

PMC0025XXXXX/PMC2528953.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Blood Ethanol Elimination Rates
  footer_text:
    unique: PMC2528953/PMC2528953.xml::T1-0

PMC0025XXXXX/PMC2528955.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Subject Characteristics
  footer_text: Data are mean ± S.D. BMI is body mass index. FM is fat mass. FFM is fat-free mass. WC is waist circumference. *** represents P < 0.001.
    unique: PMC2528955/PMC2528955.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Metabolic data
  footer_text: Data are mean ± S.D. Younger, n = 10; Older, n = 10. RQ is respiratory quotient. REE is resting energy expenditure. Cox is basal carbohydrate oxidation. Fox is basal fat oxidation. Pox is basal protein oxidation. VO2max is maximal oxygen uptake during exhaustive exercise. HRmax is maximum heart rate recorded during exhaustive exercise. * represents P < 0.05 *** represents P < 0.001.
    unique: PMC2528955/PMC2528955.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Blood chemistry
  footer_text: Data are mean ± S.D. FPG is fasting plasma glucose; divide mg/dl by 18 to convert to mmol/l. FSI is fasting serum insulin. HOMA-IR is insulin resistance according to Matthews et al. (1985). TG is triglycerides. T-Chol is total cholesterol.
    unique: PMC2528955/PMC2528955.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Bivariate correlations between age and other variables
  footer_text: Abbreviations and units of measurement follow the same legend as for previous tables. ** represents P < 0.01 *** represents P < 0.001.
    unique: PMC2528955/PMC2528955.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Bivariate correlations between fat oxidation and other variables
  footer_text: Abbreviations and units of measurement follow the same legend as for previous tables. * represents P < 0.05 ** represents P < 0.01.
    unique: PMC2528955/PMC2528955.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2528953.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2528955.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2528955.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2528955.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2528955.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2528955.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2529146.xml

PMC0025XXXXX/PMC2529228.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Plasma Levels of TSP1 and Cytokines in Patients with RA
  footer_text: Italicized value represents statistical trends (when p value is between 0.1 and 0.05)
    unique: PMC2529228/PMC2529228.xml::T1-0

PMC0025XXXXX/PMC2529257.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline characteristics of hemodialysis patients by serum phosphate quartile at baseline (n=707)
  footer_text: * P Value is from χ2 tests for each categorical variable and serum phosphate quartiles.
    unique: PMC2529257/PMC2529257.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2529228.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2529257.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2529257.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Cross-sectional association of baseline serum phosphate (per 1 mg/dl) with baseline systolic, diastolic and pulse blood pressure in all patients and patient subgroups, adjusted for patient characteristics in the subpopulation of patients with compete data on all variables (n= 669)
  footer_text: * β is mmHg higher of blood pressure per 1 mg/dl higher serum phosphate at baseline adjusted for all characteristics in table as well as serum albumin, log(C-reactive protein), dialysis non-adherence, and any β-blocker, Ca channel blocker or ACE inhibitor use. # Adjusted for the above patient characteristics except for the indicated variable.
    unique: PMC2529257/PMC2529257.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Association of 1 mg/dl higher in serum phosphate at baseline with blood pressure at different follow-up intervals, adjusted for patient characteristics.
  footer_text: * β is mmHg higher of blood pressure per 1 mg/dl higher serum phosphate at baseline adjusted for age, sex, race, baseline blood pressure, ICED score, albumin, log(C-reactive protein), DM, baseline CVD, dialysis non-adherence, and any β-blocker, Ca channel blocker or ACE inhibitor use.
    unique: PMC2529257/PMC2529257.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Association of 1 mg/dl higher average serum phosphate measurements up to 3 months with blood pressure at different follow-up intervals, adjusted for patient characteristics.
  footer_text: * β is mmHg increase of blood pressure per 1 mg/dl higher serum phosphate at baseline adjusted for age, sex, race, baseline blood pressure, ICED score, albumin, log(C-reactive protein), DM, baseline CVD, dialysis non-adherence, and any β-blocker, Ca channel blocker or ACE inhibitor use.
    unique: PMC2529257/PMC2529257.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Association of different percentage of serum phosphate measurements greater than 5.5 mg/dl from 0 to 3 months with blood pressure at different follow-up intervals using 0% of serum phosphate >5.5mg/dl as reference, adjusted for patient characteristics.
  footer_text: * β is mmHg increase of blood pressure comparing to the category that no phosphate measurement is above 5.5 mg/dl at 0–3 months adjusted for age, sex, race, baseline blood pressure, ICED score, albumin, log(C-reactive protein), DM, baseline CVD, dialysis non-adherence, and any β-blocker, Ca channel blocker or ACE inhibitor use. + none = no serum phosphate measurements >5.5 mg/dl; some = >0%,<100% of serum phosphate measurements >5.5 mg/dl; all =100% of serum phosphate measurements >5.5 mg/dl within the first 3 months of enrollment.
    unique: PMC2529257/PMC2529257.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2529257.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2529257.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2529257.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2531245.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2531069.xml

PMC0025XXXXX/PMC2531214.xml

PMC0025XXXXX/PMC2531245.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of the angles and axial spacings/separations between the three levels in fish skeletal and the rabbit heart myosin filaments
  footer_text: The rabbit values in the current work are the averages of the values plotted in Fig. 4, whereas those for fish (AL-Khayat et al., 2006) are based on single projections.
    unique: PMC2531245/PMC2531245.xml::T1-0
    unique: PMC2531245/PMC2531245.xml::T1-1

PMC0025XXXXX/PMC2531249.xml

PMC0025XXXXX/PMC2531266.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of crystallographic data for anthrax-P4H
  footer_text: R sym = [ ( ∑ h ∑ i ∣ I h i − 〈 I h 〉 ∣ ) ∕ ∑ h ∑ i 〈 I h 〉 ] × 100 % * The numbers in parentheses represent highest resolution shell data.
    unique: PMC2531266/PMC2531266.xml::T1-0

PMC0025XXXXX/PMC2531280.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: X-ray data collection statistics for HADH. Values in parentheses are for the last resolution shell
  footer_text:
    unique: PMC2531280/PMC2531280.xml::T1-0

PMC0025XXXXX/PMC2532495.xml

PMC0025XXXXX/PMC2532513.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2531245.xml::T1-1'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2531266.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2532521.xml

PMC0025XXXXX/PMC2532600.xml

PMC0025XXXXX/PMC2532757.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Characteristics of Study Participants at Randomizationa
  footer_text: Abbreviations: BMI, body mass index, calculated as weight in kilograms divided by height in meters squared; NRTI, nucleoside reverse transcriptase inhibitor; NNRTI, nonnucleoside reverse transcriptase inhibitor. a Data are reported as mean (95% confidence interval) unless otherwise indicated. P > .05 for all baseline comparisons by t test for continuous variables and χ2 test for categorical variables. b For growth hormone group, n = 26. c Patients were self-identified as current smokers but did not provide information on packs per day.
    unique: PMC2532757/PMC2532757.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532757.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532757.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532757.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Effects of Growth Hormone vs Placebo on Body Composition, Lipid Profiles, Biochemical Parameters, and Cardiovascular and Immune Functiona
  footer_text: Abbreviations: BMI, body mass index, calculated as weight in kilograms divided by height in meters squared; BP, blood pressure; CI, confidence interval; HDL, high-density lipoprotein; HIV, human immunodeficiency virus; IGF-1, insulinlike growth factor 1; IMT, intima-media thickness; MOS-HIV, Medical Outcomes Study HIV Health Survey; NA, not applicable; SAT, subcutaneous adipose tissue; VAT, visceral adipose tissue. SI conversions: To convert triglycerides to mmol/L, multiply by 0.0113; to convert total and HDL cholesterol to mmol/L, multiply by 0.0259; to convert IGF-1 to nmol/L, multiply by 0.131; to convert glucose to mmol/L, multiply by 0.0555; to convert insulin to pmol/L, multiply by 6.945. a Baseline results are reported for all participants for whom at least 1 follow-up result was obtained. Treatment effects are reported as net difference between the change in growth hormone and placebo. For triglycerides, results are reported as median (interquartile range) using the Wilcoxon rank sum test. The 95% CI could not be calculated for triglycerides given the use of a nonparametric analysis. All baseline comparisons are P > .05 by t test (analysis of variance), except for diastolic BP. b Aggregate change over 18 months for growth hormone vs placebo. See the “Statistical Analysis” section for description of statistical methods used. c Number of patients analyzed was 1 less than the total number (ie, n = 20 for VAT with growth hormone at month 18). d n = 23. e Scale of 0 to 100, with higher number indicating better quality of life. For growth hormone group, n = 23 at baseline and month 6; n = 19 at month 12; n = 17 at month 18; and for placebo group, n = 25 at baseline and month 6; and n = 24 at months 12 and 18.
    unique: PMC2532757/PMC2532757.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Summary of Adverse Events
  footer_text: Abbreviation: CI, confidence interval. a By χ2 test.
    unique: PMC2532757/PMC2532757.xml::T3-0

PMC0025XXXXX/PMC2532844.xml

PMC0025XXXXX/PMC2532854.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Participant Characteristics and Correlations With Family History Density (n = 72)
  footer_text: * p < 0.05.
    unique: PMC2532854/PMC2532854.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Neurocognitive Scores and Correlations With Family History Density (n = 72)
  footer_text:
    unique: PMC2532854/PMC2532854.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Regions Activated to SWM Relative to Vigilance Conditions (Clusters > 943 μl, p < 0.025, n = 72)
  footer_text: + , clusters activated preferentially to the SWM condition; − , clusters activated preferentially to the vigilance condition. a Divided from the largest cluster.
    unique: PMC2532854/PMC2532854.xml::T3-0

PMC0025XXXXX/PMC2532855.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532854.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532854.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532854.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532855.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Participant characteristics at baseline and year 31
  footer_text: 1 ucOC, percentage of undercarboxylated osteocalcin; CRP, C-reactive protein; OPG, osteoprotegerin. 2 x̄ ± SD; range in parentheses (all such values). 3 Significantly different between groups at baseline, P < 0.05 (independent samples t test). 4 Significant treatment × time effect, P < 0.001 (repeated-measures ANOVA).
    unique: PMC2532855/PMC2532855.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Cross-sectional associations at baseline between measures of vitamin K status and circulating cytokines in men and women aged 60-80 y (n = 379, 59% F)1
  footer_text: 1 ucOC, percentage of undercarboxylated osteocalcin. 2 Also adjusted for triacylglycerols. 3 Adjusted for sex and age. 4 Adjusted for sex, age, statin use, and antiinflammatory use. 5 Adjusted for sex, age, statin use, antiinflammatory use, BMI (in kg/m2), physical activity, and smoking.
    unique: PMC2532855/PMC2532855.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Correlations between change in bone mineral density (BMD) and change in circulating cytokine concentration in men and women aged 60-80 y (n = 379) after 3 y of follow-up1
  footer_text: 1 Partial correlation coefficients were adjusted for age, sex, treatment, baseline cytokine concentration, baseline BMD, statin medication use, antiinflammatory medication use, BMI (in kg/m2), smoking, and physical activity. IL-6, interleukin-6; CRP, C-reactive protein; OPG, osteoprotegerin.
    unique: PMC2532855/PMC2532855.xml::T3-0

PMC0025XXXXX/PMC2533126.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: 28 SNPs from IL1A and IL1B were genotyped in 1314 NARAC RA cases and 1103 controls. The allele that is more frequent in cases is shown in bold capital letters and the allele frequency and odds ratio are given for this allele. Genotype counts: (homozygotes of the allele more frequent in cases, heterozygotes, homozygotes of the alternate allele). P-values are from chi-squared analysis performed on the allele counts for single markers in RA patients versus controls. Allelic Polymorphism in IL1 in Cases vs. Controls: NARAC
  footer_text:
    unique: PMC2533126/PMC2533126.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532855.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2532855.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533126.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533126.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: RA3 and RA4 were genotyped in two independent replication case-control sample sets. First, they were genotyped in 948 CCP-positive cases from the WRDDB/NICRAP/SONORA cohort and 1455 controls from the NYCP. Next, they were genotyped in 525 RA cases and 504 controls from Northern Spain. Frequencies and odds ratios are shown for the allele that is capitalized and in bold. Genotype counts: (homozygotes of the allele capitalized and in bold, heterozygotes, homozygotes of the alternate allele). Chi-squared analysis of allele counts was performed for cases versus controls. Allelic Polymorphism in RA3 and RA4 in Cases vs. Controls: Replication Sets
  footer_text:
    unique: PMC2533126/PMC2533126.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: 24 SNPs from IL1A and IL1B were genotyped in 712 RA patients. A chi-squared analysis was performed comparing IL1 allele counts in the 403 of these patients that had erosions on plain radiographs of the hands versus the 309 that did not. Frequencies and odds ratios are shown for the allele that is capitalized and in bold. Genotype counts: (homozygotes of the allele capitalized and in bold, heterozygotes, homozygotes of the alternate allele). Chi-squared analysis of allele counts was performed for cases versus controls. Allelic Polymorphism in IL1 in Patients With vs. Without erosions: BRASS Cohort
  footer_text:
    unique: PMC2533126/PMC2533126.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: All of the SNPs within the 20kb region of IL1A were used to construct haplotypes for the NARAC cases and controls. Haplotypes of a frequency > 0.005 are shown. SNPs are ordered as in Table 1. OR = odds ratio and 95% CI = 95% confidence interval of the OR. IL1A Haplotype Association with NARAC Cases vs. Controls
  footer_text:
    unique: PMC2533126/PMC2533126.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: All of the SNPs genotyped from IL1A and IL1B were used to construct haplotypes for the NARAC cases and controls. Haplotypes with a frequency of > 0.01 are shown. SNPs are ordered as in Table 1. OR = odds ratio and 95% CI = 95% confidence interval of the OR. Extended IL1A-IL1B Haplotype Association with NARAC Cases vs. Controls
  footer_text:
    unique: PMC2533126/PMC2533126.xml::T5-0

PMC0025XXXXX/PMC2533156.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533126.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533126.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533156.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary Statistics.
  footer_text: Note: Percentages may not sum to 100% due to rounding error. N = 2,034 couples
    unique: PMC2533156/PMC2533156.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Beliefs, Attitudes, and Practices Regarding Relationship Behaviors, by Religious Participation.
  footer_text: Note: Means are significantly (p < .05) different from those in columns denoted by subscripted letters. N = 2,034 couples
    unique: PMC2533156/PMC2533156.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Seemingly Unrelated Regressions of Union Satisfaction on Religious Attendance.
  footer_text: Note: Model controls for age, education, race, and family structure at age 15. N = 2,034 couples * p < .05 ** p < .01 *** p < .001 (2 tail tests)
    unique: PMC2533156/PMC2533156.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Seemingly Unrelated Regressions of Union Satisfaction on Religious Attendance and Relationship Attitudes.
  footer_text: Note: Model controls for age, education, race, and family structure at age 15. N = 2,034 couples * p < .05 ** p < .01 *** p < .001 (2 tail tests)
    unique: PMC2533156/PMC2533156.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533156.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533156.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533156.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533156.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Seemingly Unrelated Regressions of Union Satisfaction on Religious Attendance and Adherence to Values.
  footer_text: Note: Model controls for age, education, race, and family structure at age 15. N = 2,034 couples * p < .05 ** p < .01 *** p < .001 (2 tail tests)
    unique: PMC2533156/PMC2533156.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Seemingly Unrelated Regressions of Union Satisfaction on Religious Attendance and Behaviors Conducive to Relationships.
  footer_text: Note: Model controls for age, education, race, and family structure at age 15. N = 2,034 couples * p < .05 ; ** p < .01 ; *** p < .001 (2 tail tests)
    unique: PMC2533156/PMC2533156.xml::T6-0
  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: Seemingly Unrelated Regressions of Union Satisfaction on Religious Attendance, Attitudes about Relationships, Adherence to Values, and Behaviors Conducive to Relationships.
  footer_text: Note: Model controls for age, education, race, and family structure at age 15. N = 2,034 couples * p < .05 ** p < .01 *** p < .001 (2 tail tests)
    unique: PMC2533156/PMC2533156.xml::T7-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533156.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533156.xml::T7-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533269.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533269.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533269.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2533269.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean OPTION Scores by Study Variable Groups
  footer_text:
    unique: PMC2533269/PMC2533269.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Regression Model for Physician, Practice Setting, and Visit Characteristics Predicting Shared Decision Making Behavior (OPTION Score)
  footer_text: Note: Group practice is the reference group for practice setting. Independent variables include the following: physician age, physician ethnicity, physician gender, practice setting (HMO, solo or private practice, academic, group), medical specialty (Internal Medicine, Family Practice), number of patients seen during a typical half day, and the duration of the office visit. The dependent variable is shared decision making behavior.
    unique: PMC2533269/PMC2533269.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Regression Model for Experimental Variables Predicting Shared Decision Making Behavior (OPTION Score) Controlling for Physician, Practice Setting, and Visit Characteristics
  footer_text: Notes: Variables included in the model include request type (brand-specific, general, no request), medical condition (major depression, adjustment disorder), and interaction terms (generated by crossing request type and medical condition); adjusted for physician, practice, and visit characteristics. The dependent variable is shared decision making behavior. Reference groups are no request (Request Type) and adjustment disorder with depressed mood (Medical Condition). Information about the physician, practice setting, and visit characteristics are not included in this Table.
    unique: PMC2533269/PMC2533269.xml::T3-0

PMC0025XXXXX/PMC2533376.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics* of US adults with and without diabetes by time period - NHIS 1997–2005 (N=255,966).
  footer_text: * Values are weighted percentages (Standard Error) † Based on family income and family size using the US Census Bureau’s poverty thresholds for the previous calendar year. “Poor” persons are defined as below the poverty threshold. “Near poor” persons have incomes of 100% to less than 200% of the poverty threshold. “Not poor” persons have incomes that are 200% of the poverty threshold or greater.
    unique: PMC2533376/PMC2533376.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Educational disparities in the prevalence of self-reported CVD over time among US adults with and without diabetes. NHIS 1997–2005.
  footer_text: RII: Relative Index of Inequality, PRR: Prevalence Rate Ratio, 95% CI: 95% confidence interval * Adjusted for age, sex, race/ethnicity, poverty status, comorbidity and survey year ¶ Interaction between education and diabetes status in the regression model: p<0.05
    unique: PMC2533376/PMC2533376.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533376.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533376.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2533517.xml

PMC0025XXXXX/PMC2533528.xml

PMC0025XXXXX/PMC2533638.xml

PMC0025XXXXX/PMC2533688.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic, CMR, and inter-rater variability data
  footer_text: Abbreviations: COV = coefficient of variability; EDV = end-diastolic volume; ESV = end-systolic volume; LV = left ventricle; RV = right ventricle; SD = standard deviation; SV = stroke volume
    unique: PMC2533688/PMC2533688.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Comparison between intra-class correlation coefficients of right and left ventricular measurements
  footer_text: Abbreviations: ICC = intra-class correlation coefficient; LV = left ventricle; RV = right ventricle; SD = standard deviation
    unique: PMC2533688/PMC2533688.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533688.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533688.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533688.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Comparison of intra-class correlations between patients with normal right ventricle and those with atrial septal defect or repaired tetralogy of Fallot
  footer_text: Abbreviations: ASD = atrial septal defect; ICC = intra-class correlation coefficient; TOF = tetralogy of Fallot
    unique: PMC2533688/PMC2533688.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Comparison between inter-observer coefficient of variations in this study and in selected published reports
  footer_text: Abbreviations: ASD = atrial septal defect; CHF = congestive heart failure; EDV = end-diastolic volume; EF = ejection fraction; ESV = end-systolic volume; FLASH = fast low-angle shot; LVH = left ventricular hypertrophy; SSFP= steady-state free precession; TOF = tetralogy of Fallot
    unique: PMC2533688/PMC2533688.xml::T4-0

PMC0025XXXXX/PMC2533707.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2533688.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535806.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535844.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2533764.xml

PMC0025XXXXX/PMC2535758.xml

PMC0025XXXXX/PMC2535806.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: RPE cell culture characteristics
  footer_text:
    unique: PMC2535806/PMC2535806.xml::T1-0

PMC0025XXXXX/PMC2535844.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Radial formation in human cells depleted of HR and NHEJ proteins Average percentage of GM639 cells containing radials following depletion of listed proteins and MMC treatment. Average percentage represents three independent trials. “None” represents a transfection with scrambled siRNA.
  footer_text:
    unique: PMC2535844/PMC2535844.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary of protein deficiencies leading to an increase in radial formation Loss of function or siRNA depletion of proteins listed here causes increased radial formation either spontaneously, following ICL-damage, or both. Five of these have been shown in the depletions in this manuscript. BLM is Bloom syndrome protein. DNA-PK is for the mouse Prkdc protein, the catalytic subunit of DNA-dependent protein kinase.
  footer_text: 1 (Schroeder et al. 1964; reviewed in D’Andrea and Grompe 2003) 2 shown in this manuscript. 3 (Bruun et al. 2003). 4 (Hemphill et al. 2008). 5 (German 1997). 6 (Niedernhofer et al. 2004). 7 (Houghtaling et al. 2005). * spontaneous radials without clastogen exposure.
    unique: PMC2535844/PMC2535844.xml::T2-0

PMC0025XXXXX/PMC2535846.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Characteristics for Participants and Non-Participants After 9 Years
  footer_text: * p<0.05 for participants vs non-participants † p<0.05 for participants vs non-participants from logistic regression analyses after adjusting for age and sex ** Non-participants included those who died or did not participate for other reasons Hypertension: SBP≥140 or DBP≥90 or Hx of treatment Diabetes: GHb>10 or self-reported hx of diabetes
    unique: PMC2535846/PMC2535846.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Age and Sex-Specific 9-Year Incidence of Hypertension and Diabetes
  footer_text: * Hypertension: SBP≥140 or DBP≥90 or Hx of treatment Diabetes: GHb>10 or self-reported hx of diabetes
    unique: PMC2535846/PMC2535846.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Relative Risks* for the 9-year Incidence of Hypertension
  footer_text: * Adjusted relative risk based on logistic regression model, including variables presented in this table. † p = 0.06 BMI = Body mass index; WHR = Waist-hip ratio; BP = Blood pressure BMI quartiles (< 23.3, ≥ 23.3 and < 26.3, ≥ 26.3 and < 29.8, ≥ 29.8) WHR quartiles (<0.87, ≥ 0.87 and < 0.92, ≥ 0.92 and < 0.97, ≥ 0.97)
    unique: PMC2535846/PMC2535846.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Relative Risks* for the 9-year Incidence of Diabetes
  footer_text: * Adjusted relative risk based on logistic regression model, including variables presented in this table. BMI = Body mass index; WHR = Waist-hip ratio BMI quartiles (< 23.3, ≥ 23.3 and < 26.3, ≥ 26.3 and < 29.8, ≥ 29.8) WHR quartiles (<0.87, ≥ 0.87 and < 0.92, ≥ 0.92 and < 0.97, ≥ 0.97)
    unique: PMC2535846/PMC2535846.xml::T4-0

PMC0025XXXXX/PMC2535850.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Descriptive Statistics
  footer_text:
    unique: PMC2535850/PMC2535850.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: General Linear Mixed Model Analysis of Estimated Marginal Means (EMM), Standard Errors (SE), and Simple Effects Analyses of the Effect of Time within Each Group
  footer_text: Note: N's represent the number of independent units of observation in each scale analyzed; MDI = metered dose inhaler skill.
    unique: PMC2535850/PMC2535850.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535846.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535846.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535846.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535846.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535850.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535850.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535850.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table III
  caption_text: Results of Tests of Fixed Effects in General Linear Mixed Effect Model Analyses for Each Measure
  footer_text:
    unique: PMC2535850/PMC2535850.xml::T3-0

PMC0025XXXXX/PMC2535851.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of study participants according to quartiles of systolic blood pressure response to cold pressor test
  footer_text: Mean ± standard deviation
    unique: PMC2535851/PMC2535851.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Multivariate regression analyses of blood pressure responses to dietary interventions according to quartile of blood pressure responses to cold pressor test
  footer_text: See Figure 2 legend for the cut-points of area-under-curve quartiles of blood pressure responses to the cold pressor test
    unique: PMC2535851/PMC2535851.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Multivariate-adjusted odds ratio and 95% confidence intervals of high salt-sensitivity and potassium-sensitivity according to quartiles of blood pressure responses to cold pressor test
  footer_text: See Figure 2 legend for the cut-points of area-under-curve quartiles of blood pressure responses to the cold pressor test
    unique: PMC2535851/PMC2535851.xml::T3-0

PMC0025XXXXX/PMC2535852.xml

PMC0025XXXXX/PMC2535853.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Household, women and infant characteristics by maternal age categorya
  footer_text: a Estimates represent mean (SD) for continuous variables and % for categorical variables. b Chi squared tests were used for comparison of categorical variables by age group and analysis of variance for continuous variables. c A total of 9 were missing latrine data d A total of 229 were missing electricity data e A total of 236 were missing cattle ownership data f A total of 229 were missing ethnicity data g A total of 220 were missing caste data h A total of 4 were missing literacy data i A total of 9 were missing occupation data j A total of 598 were missing night blindness data k A total of 1668 were missing birth weight data l A total of 80 were missing gestational age data m A total of 1716 were missing small for gestational age data
    unique: PMC2535853/PMC2535853.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535851.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535851.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535851.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535853.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535853.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535853.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535853.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Neonatal Mortality Rate (per 1000 live births) by maternal age and parity
  footer_text:
    unique: PMC2535853/PMC2535853.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Neonatal Mortality Rates (NMR), crude and adjusted Odds Ratios (OR) and their 95% Confidence Intervals, for neonatal mortality by maternal age category and other maternal characteristics
  footer_text: i A total of 598 were missing night blindness data a Adjusted for treatment received, maternal literacy, ethnic group, caste, latrine ownership, maternal occupation, electricity in the home, cattle ownership, parity and maternal nightblindness during pregnancy b A total of 229 were missing ethnicity data c A total of 220 were missing caste data d A total of 4 were missing literacy data e A total of 9 were missing latrine data f A total of 9 were missing occupation data g A total of 229 were missing electricity data h A total of 236 were missing cattle ownership data j A total of 1668 were missing birth weight data k A total of 80 were missing gestational age data l A total of 1716 were missing small for gestational age data
    unique: PMC2535853/PMC2535853.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Crude and adjusted Odds ratios (OR) and 95% Confidence Intervals for adverse birth outcomes by maternal age category
  footer_text: a Adjusted for treatment received, maternal literacy, ethnic group, caste, latrine ownership, maternal occupation, electricity in the home, cattle ownership, parity and maternal nightblindness during pregnancy b Same as a plus adjustment for low birth weight c Same as a plus adjustment for preterm birth d Same as a plus adjustment for small for gestational age e Same as a plus adjustment for preterm and small for gestational age f Same as a plus adjustment for 4 preterm birth and small for gestational age categories (term & not SGA, term & SGA, preterm & not SGA, both preterm & SGA)
    unique: PMC2535853/PMC2535853.xml::T4-0

PMC0025XXXXX/PMC2535854.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Strengthening conclusions to support estimates of treatment or intervention effects when assuming all “important” confounders are measured. Confounders are variables related to the probability of treatment assignment and to the outcomes of interest.
  footer_text: ¶ Assuming full compliance and no missing data.
    unique: PMC2535854/PMC2535854.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Assumptions needed when conducting an instrumental variables analysis. Applied to Ryan et al study Reference 14). Confounders are variables related to the probability of treatment assignment and to the outcomes of interest.
  footer_text:
    unique: PMC2535854/PMC2535854.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mechanisms and assumptions for missing data. Confounders are variables related to the probability of missing data and to the outcomes of interest.
  footer_text:
    unique: PMC2535854/PMC2535854.xml::T3-0

PMC0025XXXXX/PMC2535855.xml

PMC0025XXXXX/PMC2535900.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Electrode placement in EIM.
  footer_text: * Measurements were obtained on patients lying supine, with the arms lying passively at the sides of the body and a small bolster or pillow under the knees.
    unique: PMC2535900/PMC2535900.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Reference values for phase measured at 50 kHz
  footer_text: All measurements are in degrees (°)
    unique: PMC2535900/PMC2535900.xml::T2-0

PMC0025XXXXX/PMC2535904.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535854.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535854.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535900.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535900.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2535913.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sample Details Fifty-eight pre-treatment tumor samples from stage 4 without MYCN amplification were used. Of those, 29 survived without event for at least 3 years (denoted by a “+” in the outcome column) and 29 died of the disease (“−”). Patients were diagnosed between 1991 and 2002 (Diagnosis date), the age at date of diagnosis is given in days. Column “BP17” indicates presence (“yes”) or absence (“no”) of a breakpoint leading to a gain on chromosome 17; column “11q−BP” indicates a breakpoint leading to loss of genomic material on the q-arm of chromosome 11. BP, a chromosomal breakpoint. Columns “1” to “22” and “X”, “Y” indicate gain (“+”), loss (“−”) or no (“0“) whole chromosome change of the corresponding chromosome.
  footer_text:
    unique: PMC2535913/PMC2535913.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Association Analysis Association of localized loss of genomic material on 11q, localized gain on 17q and whole chromosome gains/losses with patient survival for (A) all samples and (B) the subset of samples from patients older than 500 days at time of diagnosis. Each column shows the number of samples with the corresponding characteristic separated for deceased/survived patients. In each column a p-value for association of the observed distribution with the patient’s death pdeceased or survival psurvived is given. BP, a chromosomal breakpoint.
  footer_text:
    unique: PMC2535913/PMC2535913.xml::T2-0

PMC0025XXXXX/PMC2535917.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Evolution of JFH-1 in chimpanzees
  footer_text: A Compared to the consensus JFH-1 sequences.
    unique: PMC2535917/PMC2535917.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535913.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535913.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535917.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535917.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Specific infectivity and virus secretion in Huh7-25 cells
  footer_text: The data are from day 3 after HCV RNA transfection of the Huh7-25 cells A P < 0.05 comparing JFH-1 WT and G838R
    unique: PMC2535917/PMC2535917.xml::T2-0

PMC0025XXXXX/PMC2535918.xml

PMC0025XXXXX/PMC2535920.xml

PMC0025XXXXX/PMC2535925.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text:
  footer_text:
    unique: PMC2535925/PMC2535925.xml::T1-0

PMC0025XXXXX/PMC2535930.xml

PMC0025XXXXX/PMC2536515.xml

PMC0025XXXXX/PMC2536528.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Summary of patient characteristics in each of the 3 groups1
  footer_text: 1 TPN, total parenteral nutrition; PaCO2, arterial carbon dioxide tension; PRISM, Pediatric Risk Mortality. The chi-square test indicated no significant group differences with respect to sex. 2 ANOVA indicated no significant group differences according to the overall F test for age, weight, BMI, pH, or PRISM scores and no significant differences between any 2 groups on the basis of post hoc Tukey tests (P > 0.10 for all). 3 x̄ ± SD (all such values). 4 PaCO2 production was significantly different in the TPN (P < 0.01) and enteral (P = 0.04) groups than in the glucose-electrolytes group.
    unique: PMC2536528/PMC2536528.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2535925.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536528.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536528.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536528.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Protein and energy intakes of study patients1
  footer_text: 1 TPN, total parenteral nutrition. 2 ANOVA indicated significant group differences according to the overall F test between the TPN and enteral feeding groups compared with the glucose-electrolytes group, P<0.001 (post hoc Tukey test). No significant differences were found between the TPN and enteral groups for protein (P=0.40) or energy (P = 0.35) intake. 3 x̄ ± SD (all such values).
    unique: PMC2536528/PMC2536528.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Rates of appearance of carbon dioxide (RaCO2), fractional recovery of 13CO2, and bicarbonate-predicted and measured rates of carbon dioxide production (V̇ CO2) in critically ill children receiving parenteral feedings, enteral feedings, or glucose-electrolytes1
  footer_text: 1 TPN, total parenteral nutrition. 2 ANOVA indicated no significant group differences according to the overall F test and no significant differences between any 2 groups according to post hoc Tukey tests (P > 0.60 for all). 3 x̄ ± SD (all such values).
    unique: PMC2536528/PMC2536528.xml::T3-0

PMC0025XXXXX/PMC2536564.xml

PMC0025XXXXX/PMC2536567.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Parameter estimates for intervention effects on scale change scores—caregiver data
  footer_text:
    unique: PMC2536567/PMC2536567.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Parameter estimates for intervention effects on scale change scores—child data
  footer_text:
    unique: PMC2536567/PMC2536567.xml::T2-0

PMC0025XXXXX/PMC2536601.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic Data

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536567.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536567.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536601.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536601.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  footer_text: Mean (SD) unless stated otherwise. SCZ=schizophrenia; WAIS-FSIQ=Wechsler Adult Intelligence Scale-revised, full-scale intelligence quotient; GAF=Global Assessment of Functioning Scale; Prodromal Age=age of onset of prodromal symptoms of schizophrenia * p≤0.05.
    unique: PMC2536601/PMC2536601.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Neuropsychological Assessment of Probands with and without Enuresis
  footer_text: SCZ=schizophrenia; WAIS-FSIQ=Wechsler Adult Intelligence Scale, full scale IQ; WRAT=Wide Range Achievement Test; WCST=Wisconsin Card Sorting Test; %PE=percentage of perseverative errors; CVLT=California Verbal Learning Test * p≤0.05.
    unique: PMC2536601/PMC2536601.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Voxel-wise Statistical Analysis of GM Maps of Decreased Gray Matter in Probands with (n=16) vs. without Enuresis (n=66), and in Healthy Controls with (n=11) and without Enuresis (n=91)
  footer_text: Peak coordinates listed rostral to caudal. * p value is p<0.001. kE is the number of voxels in the significant cluster.
    unique: PMC2536601/PMC2536601.xml::T3-0

PMC0025XXXXX/PMC2536612.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536601.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536612.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536612.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536612.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536613.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Number of rats used in the experimental paradigms
  footer_text:
    unique: PMC2536612/PMC2536612.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Complete information and immunogen of primary antibodies applied
  footer_text:
    unique: PMC2536612/PMC2536612.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Assessment of BDA volume, rostro-caudal diffusion and analyzed gray matter area of the spinal cord
  footer_text: Data expressed as mean ± SD
    unique: PMC2536612/PMC2536612.xml::T3-0

PMC0025XXXXX/PMC2536613.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Methods for assessment of diet/nutrition in epidemiologic studies
  footer_text:
    unique: PMC2536613/PMC2536613.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Selected epidemiologic studies relating dietary factors with lung function or airway hyperresponsiveness
  footer_text: NHANES: National Health and Nutrition Examination Survey CARET: Carotene and Retinol Efficacy Trial MORGEN: Monitoring Project on Risk factors for Chronic Diseases EPIC: European Prospective Investigation into Cancer and Nutrition Study
    unique: PMC2536613/PMC2536613.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536613.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536613.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536613.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536704.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536708.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Selected epidemiologic studies relating dietary factors with asthma, asthma-related symptoms, and atopy
  footer_text: RHINE – Respiratory Health in Northern Europe ISAAC – International Study of Asthma and Allergies in Childhood
    unique: PMC2536613/PMC2536613.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Studies of the association between maternal diet and nutrient status in pregnancy and immune markers, asthma, and asthma-related outcomes in childhood
  footer_text: SEATON – Study of Eczema and Asthma To Observe the effects of Nutrition ALSPAC – Avon Longitudinal Study of Pregnancy and Childhood
    unique: PMC2536613/PMC2536613.xml::T4-0

PMC0025XXXXX/PMC2536704.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characterization and proposed classification of BRCA2 SyVaL clones
  footer_text: NOTE: Numbers in parentheses represent mean percentage of untreated/treated cells with more than five RAD51 foci ± SE. Fold Δ refers to the ratio of the IC50 of cells having the hemizygous wt allele to the IC50 of cells having the mutated allele. Abbreviations: Pos, positive; Neg, negative; —, not done; Δ, change. * The extreme rarity of knockout clones may indicate an especially severe deleterious effect (21).
    unique: PMC2536704/PMC2536704.xml::T1-0

PMC0025XXXXX/PMC2536708.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Nucleotide sequences of the primers used for PCR
  footer_text:
    unique: PMC2536708/PMC2536708.xml::T1-0

PMC0025XXXXX/PMC2536719.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of E. coli inactivation of several compounds in aqueous solution
  footer_text: a Obtained from Sigma-Aldrich Co. b Oxidized for 2 hr under air saturation c Unless otherwise specified: pH = 8.0 (carbonate buffer), T = 21±0.5°C, air saturation indicates open system to atmosphere d From the data of Figure 2 e Prepared by photoreduction of silver ion in aqueous solution containing poly(ethylene oxide)–poly(propylene oxide)–poly(ethylene oxide) block copolymers (Supporting Information, S3)
    unique: PMC2536719/PMC2536719.xml::T1-0

PMC0025XXXXX/PMC2536720.xml

PMC0025XXXXX/PMC2536721.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Locomotor activity rhythms of cry excision strains under LL conditions. Period and power were calculated for all rhythmic animals as described in Materials and Methods. Activity was calculated for all flies that survived to the end of the experiment, as described in Materials and Methods. Homozygous deletions are shown in bold. n.a.; not applicable.
  footer_text:
    unique: PMC2536721/PMC2536721.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Locomotor activity rhythms of cry excision strains under DD conditions. Period and power were calculated for all rhythmic animals as described in Materials and Methods. Activity was calculated for all flies that survived to the end of the experiment, as described in Materials and Methods. Homozygous deletion strains are shown in bold.
  footer_text:
    unique: PMC2536721/PMC2536721.xml::T2-0

PMC0025XXXXX/PMC2536746.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536719.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536721.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536721.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Characteristics1 of 698 prostate cancer cases and 698 matched controls nested in the health professionals follow-up study
  footer_text: 1 Cases and controls were matched on age, time of day and year of blood draw, and PSA test prior to blood draw. Controls all had a PSA test after blood draw. Unless otherwise indicated, values are from the 1994 follow-up questionnaire. Red meat and fish intake are averages of reports in 1986, 1990, and 1994. Diabetes mellitus includes cases through 1994. 2 High grade was defined as Gleason sum ≥ 7. Low grade was defined as Gleason sum < 7. Gleason sum was not available for 65 cases. 3 For the hypothesis test of no difference in means (paired t-test) or proportions (McNemar's test) between total prostate cancer cases and controls. All tests are 2-sided. 4 For the hypothesis test of no difference in means (t-test) or proportions (Chi-square test) between high- and low-grade cases. All tests are 2-sided.
    unique: PMC2536746/PMC2536746.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Mean plasma cholesterol concentration, dietary cholesterol intake, and history of elevated cholesterol in prostate cancer cases and matched controls nested in the health professionals follow-up study
  footer_text: 1 High grade was defined as Gleason sum ≥ 7. Low grade was defined as Gleason sum < 7. Gleason sum was not available for 65 cases. 2 For the hypothesis test of no difference in means (paired t-test) or proportions (McNemar's test) between total prostate cancer cases and controls. All tests are 2-sided. 3 For the hypothesis test of no difference in means (t-test) or proportions (Chi-square test) between high- and low-grade cases. All tests are 2-sided. 4 Case-control pairs were run in 3 batches; the same assay method was used for the 1996 and 1998 batches and a different assay method was used for the 2000 batch. Means ± standard deviations in the cases and controls by batch were: 1996: case 218.5 ± 37.8, control 217.9 ± 39.8 mg/L; 1998: case 211.7 ± 38.0, control 213.9 ± 41.9 mg/L; and 2000 case 166.9 ± 32.1, control 166.1 ± 38.1 mg/L.
    unique: PMC2536746/PMC2536746.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table III
  caption_text: Odds ratio of prostate cancer by plasma cholesterol concentration, 698 matched pairs nested in the health professionals follow-up study
  footer_text: 1 Estimated from a conditional logistic regression model. 2 Estimated from a conditional logistic regression model and adjusted for family history of prostate cancer, height, vigorous physical activity, diabetes mellitus, vasectomy, cigarette smoking in the past 10 years, intake of energy, red meat, fish, and alcohol, intake of energy-adjusted lycopene, calcium, fructose, and α-linolenic acid, and supplemental vitamin E and selenium. 3 Estimated from a logistic regression model after excluding men who ever used cholesterol-lowering drugs and adjusted for age, PSA test before blood draw, family history of prostate cancer, height, vigorous physical activity, diabetes mellitus, vasectomy, cigarette smoking in the past 10 years, intake of energy, red meat, fish, and alcohol, intake of energy-adjusted lycopene, calcium, fructose, and α-linolenic acid, and supplemental vitamin E and selenium. 4 Cutpoints differed by analytical batch (see Material and methods for details): 1996 192.8 mg/dL, 1998 185.7 mg/dL, and 2000 140.1 mg/dL).
    unique: PMC2536746/PMC2536746.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536746.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536746.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536746.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2536749.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline clinical characteristics
  footer_text: NA intestinal or colonic transit could not be measured because of technical limitations, N normal,↑ increased, ↓ decreased
    unique: PMC2536749/PMC2536749.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Effects of drugs on bowel symptoms assessed by weekly diaries
  footer_text: a Worsening or improvement was defined as ≥1 point deterioration or improvement in symptom severity respectively on 5-point symptom severity scales for each symptom. Missing data for 1 subject who did not complete 8-week questionnaires
    unique: PMC2536749/PMC2536749.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Colonic motility findings
  footer_text: Prhalf pressure corresponding to half maximum volume during the pressure-volume relationship. Neostigmine increased the Prhalf, reflecting lower compliance, or a stiffer colon
    unique: PMC2536749/PMC2536749.xml::T3-0

PMC0025XXXXX/PMC2536753.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: NDP-MSH-Stimulated Signaling and Ligand Binding of WT and Mutant hMC3Rs
  footer_text: * ND, could not be detected. a significantly different from WT hMC3R, p<0.05 b significantly different from WT hMC3R, p<0.01 c significantly different from WT hMC3R, p<0.001 The data are expressed as the mean ± SEM of three or four independent experiments. The maximal response under NDP-MSH stimulation was 2308 ± 362 pmol cAMP/106 cells for WT hMC3R. Binding is shown as receptor occupancy (RO) that is a crude estimate of the relative maximal binding level.
    unique: PMC2536753/PMC2536753.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536749.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536749.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536749.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536753.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536753.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Ligand Binding and D-Trp8-γ-Stimulated cAMP Production of WT and Mutant hMC3Rs
  footer_text: a significantly different from WT hMC3R, p<0.05 b significantly different from WT hMC3R, p<0.01 c significantly different from WT hMC3R, p<0.001 The data are expressed as the mean ± SEM of three or four independent experiments. The maximal response under d-Trp8-γ-MSH stimulation was 2162 ± 338 pmol cAMP/106 cells for WT hMC3R.
    unique: PMC2536753/PMC2536753.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Ligand Binding and α-MSH-Stimulated cAMP Production of WT and Mutant hMC3Rs
  footer_text: a significantly different from WT hMC3R, p<0.05 b significantly different from WT hMC3R, p<0.01 c significantly different from WT hMC3R, p<0.001 The data are expressed as the mean ± SEM of three to five independent experiments. The maximal response under 〈-MSH stimulation was 1356 ± 180 pmol cAMP/106 cells for WT hMC3R.
    unique: PMC2536753/PMC2536753.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Ligand Binding and γ-MSH-Stimulated cAMP Production of WT and Mutant hMC3Rs
  footer_text: * ND, could not be detected. a significantly different from WT hMC3R, p<0.05 b significantly different from WT hMC3R, p<0.01 c significantly different from WT hMC3R, p<0.001 The data are expressed as the mean ± SEM of 3-5 independent experiments. The maximal response under γ-MSH stimulation was 1324 ± 309 pmol cAMP/106 cells for WT hMC3R.
    unique: PMC2536753/PMC2536753.xml::T4-0

PMC0025XXXXX/PMC2536754.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of the power functions under various hypotheses between the Poisson-based test ZPOIS and the weighted-least-squares based test ZWLS for two overlapping regions over disjoint time intervals, Region 1 (1980–1989) vs Region 2 (1990–1999). APC1 and APC2 are the annual percent changes in Regions 1 and 2, respectively.
  footer_text:
    unique: PMC2536754/PMC2536754.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536753.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536753.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536754.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536754.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Comparison of the power functions between the Poisson based ZPOIS and the weighted-least-squares based ZWLS for two overlapping regions over roughly the same time intervals, Region 1 (1980–1989) vs Region 2 (1983–1992). APC1 and APC2 are the annual percent changes in Regions 1 and 2, respectively.
  footer_text:
    unique: PMC2536754/PMC2536754.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Comparison of the power functions between the Poisson based ZPOIS and the weighted-least-squares based ZWLS for two overlapping regions over slightly overlapping time intervals, Region 1 (1980–1989) vs Region 2 (1987–1996). APC1 and APC2 are the annual percent changes in Regions 1 and 2, respectively.
  footer_text:
    unique: PMC2536754/PMC2536754.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Comparing APC of Breast Cancer Mortality Between CA and the US
  footer_text:
    unique: PMC2536754/PMC2536754.xml::T4-0

PMC0025XXXXX/PMC2536759.xml

PMC0025XXXXX/PMC2536764.xml

PMC0025XXXXX/PMC2536766.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: A Comparison of Reduction Potentials for Pt(IV) Compounds.
  footer_text: en = ethylenediamine; ipa = isopropylamine; a = amine; cha = cyclohexylamine; dach = diaminocyclohexane
    unique: PMC2536766/PMC2536766.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536754.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536754.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536766.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2536768.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Clinicopathological characteristics of study population
  footer_text:
    unique: PMC2536768/PMC2536768.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Association of Demographics with Gene Methylation (PMR) (P values)
  footer_text: 1 P values based on Kruskal-Wallis test. 2 P values based on Wilcoxon test. 3 Data grouped into the categories of Ta, CIS, T1, and T2-T4. 4 Data grouped into the categories of low grade (1-2) and high grade (3-4). 5 Data grouped into the categories of male and female. 6 Data grouped into the categories of ≤40, 41-50, 51-60, and 61-65 years at diagnosis. 7 Data grouped into the categories of never/irregular smokers and former/current smokers.
    unique: PMC2536768/PMC2536768.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Impact of Sex, Age, Tumor Stage, Tumor Grade, and Smoking History on RUNX3 Methylation (PMR ≥ 10%, N=304)
  footer_text: 1 p-value based on likelihood ratio test.
    unique: PMC2536768/PMC2536768.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536768.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536768.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2536768.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2536769.xml

PMC0025XXXXX/PMC2536792.xml

PMC0025XXXXX/PMC2536869.xml

PMC0025XXXXX/PMC2537462.xml

PMC0025XXXXX/PMC2537995.xml

PMC0025XXXXX/PMC2538376.xml

PMC0025XXXXX/PMC2538424.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of Filament Length and Filament Extension (Pitch) Measurements
  footer_text: All measurements are on M13mp18 cssDNA and lengths are in nm. For filament length measurements n=19 for wt, n=57 for E38K K72R and n=85 for K72R. For pitch measurements 50 individual pitches from 6-10 different molecules were measured for all conditions. * N.A. is not available since RecA K72R did not form filaments under these conditions. N.D. is not determined.
    unique: PMC2538424/PMC2538424.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538424.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538424.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538424.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538424.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: The Level of SOS Expression before and after UV Treatment
  footer_text: Shows the average of 1000-3000 total cells analyzed from three different experiments. N.D. is not determined.
    unique: PMC2538424/PMC2538424.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Summary of Sensitivity to UV light and Recombination Phenotypes of RecA Mutants
  footer_text: a UV Resistance is measured by % survival of strains after 10J of UV irradiation b Conjugation frequency reported as % transconjugants/100 donors
    unique: PMC2538424/PMC2538424.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Strains Used in this Work
  footer_text: a JC13509 has the following partial genotype: sulB103- lacMS286 Φ80dIIlacBK1 argE3 his-4 thi-1 xyl-5 mtl-1 rplS31 tsx. The lacMS286 Φ80dIIlacBK1 codes for two partial non-overlapping deletions of the lac operon. See (Konrad, 1977; Zieg and Kushner, 1977). b attλ∷sulApΩgfp-mut2 is abbreviated Ωgfp. c pKD46 expresses the Lambda Red proteins (Datsenko and Wanner, 2000). d P1 transduction with SS4660 as a recipient was carried out as normal with the exception that the strain was grown in Luria broth with ampicillin (50 μg/mL) and induced with 0.2% arabinose 1 hour before harvesting the culture.
    unique: PMC2538424/PMC2538424.xml::T4-0

PMC0025XXXXX/PMC2538429.xml

PMC0025XXXXX/PMC2538488.xml

PMC0025XXXXX/PMC2538554.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Functional roles of conserved catalytic motifs among motor ATPase families. Abbreviations: W-A = Walker A, W-B = Walker B, RF = arginine finger, CE = catalytic glutamate, H = H loop, D = D loop, Q = Q loop, C = C region or ABC signature motif, SI = sensor I, SII = sensor II. All other motifs are listed as roman numerals.
  footer_text:
    unique: PMC2538554/PMC2538554.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538554.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538563.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538563.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538566.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538575.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2538563.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Fragments Generated from Chymotryptic Digest of CaM+VLRRRRKRVN (D2NI3L)
  footer_text:
    unique: PMC2538563/PMC2538563.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Fragments Generated from Chymotryptic Digest of CaM+RIREFRQTFR (A2A−1)
  footer_text:
    unique: PMC2538563/PMC2538563.xml::T2-0

PMC0025XXXXX/PMC2538566.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Characteristics
  footer_text: * BNP was log transformed for analysis in determining p value. Age, BMI, and creatinine clearance values are expressed as mean (standard deviation). BNP values are expressed as median (interquartile range). All other values are given as frequency (%). BMI= body mass index, BNP= brain natriuretic peptide, COPD= chronic obstructive pulmonary disease, NYHA= New York Heart Association
    unique: PMC2538566/PMC2538566.xml::T1-0

PMC0025XXXXX/PMC2538575.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: KCNQ1 mutations in study patients
  footer_text: * p-value for the comparison between Caucasians and Japanese patients <0.05. † Splice site and in-frame deletion mutation-types were assumed haploinsufficiency.
    unique: PMC2538575/PMC2538575.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Characteristics of Caucasian and Japanese LQT1 patients
  footer_text: Plus-minus values are means±SD. † Denotes the number of patients who experienced at least one cardiac event during follow-up. Mean QTc values include 87 cases; 13 cases were missing: 6 male and 7 female. ICD = implantable cardioverter defibrillator.
    unique: PMC2538575/PMC2538575.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538575.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538575.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538575.xml::T3-1'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Multivariate analysis*
  footer_text: * The analysis involved 87 cases; 13 cases were omitted due to missing QTc values; virtually identical results were obtained when analysis were repeating with censoring of patients upon implantation of an ICD. † β-blocker therapy was analyzed as a time-dependent variable in the multivariate model.
    unique: PMC2538575/PMC2538575.xml::T3-0
    unique: PMC2538575/PMC2538575.xml::T3-1

PMC0025XXXXX/PMC2538577.xml

PMC0025XXXXX/PMC2538583.xml

PMC0025XXXXX/PMC2538606.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics by race
  footer_text: * Abbreviations: DVT=deep vein thrombosis; PE=pulmonary embolism; TIA=transient ischemic attack † P-values comparing characteristics by race
    unique: PMC2538606/PMC2538606.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538606.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538606.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Dosing algorithm for Caucasians in the multivariate linear regression model (outcome variable is log warfarin maintenance dose per day).*
  footer_text: * Dose (mg/day) = exp[2.74 −(0.01 X age) −(0.40 X VKORC1 1173CT) −(0.82 X VKORC1 1173TT) −(0.21 X CYP2C9 any*2) −(0.32 X CYP2C9 any*3) −(0.18 X BMI <25) −(0.19 X BMI 25 to 30) −(0.08 X number of medications that potentiate warfarin) +(0.03 X most alcoholic drinks on one occasion) +(0.21 X history of deep vein thrombosis) −(0.13 X female)] † Age, number of medications that potentiate warfarin, and most drinks on one occasion were entered as linear terms in the model and dummy variables (0=absent, 1=present) for the other variables.
    unique: PMC2538606/PMC2538606.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Dosing algorithm for African Americans in the multivariate linear regression model (outcome variable is log warfarin maintenance dose per day). *
  footer_text: * Dose (mg/day) = exp[2.66 −(0.01 X age) −(0.36 X VKORC1 1173CT or 1173TT) −(0.19 X Factor 7 −401GT) −(0.25 X Factor 7 −401TT) −(0.28 X APOE E2/E2 or E2/E3) −(0.21 X APOE E3/E3 or E2/E4) −(0.19 X BMI <25) −(0.25 X BMI 25 to 30) −(0.09 X number of medications that potentiate warfarin)] † Age and number of medications that potentiate warfarin were entered as linear terms in the model and dummy variables (0=absent, 1=present) for the other variables.
    unique: PMC2538606/PMC2538606.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Dosing algorithm for African Americans and Caucasians in the multivariate linear regression model (outcome variable is log warfarin maintenance dose per day).*
  footer_text: * Dose (mg/day) = exp[2.81 −(0.08 X African American) −(0.01 X age) −(0.39 X VKORC1 1173CT) −(0.82 X VKORC1 1173TT) −(0.11X Factor 7 −401GT) −(0.19X Factor 7 −401TT) −(0.16 X CYP2C9 any*2) −(0.30 X CYP2C9 any*3) −(0.18 X BMI <25) −(0.23 X BMI 25 to 30) –(0.08 X number of medications that potentiate warfarin) −(0.10 X female) +(0.06 X most alcoholic drinks on one occasion) −(0.03 X African American x most drinks on one occasion) +(0.58 X history of deep vein thrombosis) −(0.33 X African American x history of deep vein thrombosis)] † Age, number of medications that potentiate warfarin, and most drinks on one occasion were entered as linear terms in the model and dummy variables (0=absent, 1=present) for the other variables.
    unique: PMC2538606/PMC2538606.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Validation results of other algorithms in our cohort and cross validation of our models
  footer_text: * Gage et al. algorithm; dose (mg/day) = exp[0.385 −(0.0083 X age) +( 0.498 X BSA) – ( 0.208 X CYP2C9*2) −( 0.350 X CYP2C9*3) −( 0.341 X amiodarone) + ( 0.378 X Target INR) −( 0.125 X simvastatin) −(0.113 X race) −( 0.075 X female)] † Hillman et al. algorithm; dose (mg/week) =exp[1.654 + (0.429 X CYP2C9 *2 or *3) + (−0.274 X CYP2C9*3) + (0.221 X valve replacement) + (−0.035 X age) + (2.886 X BSA) + (0.936 X diabetes mellitus) + (0.0002 X age2) + (−0.604 X BSA2) + (−0.014 X age*diabetes mellitus) + (−0.305 X BSA*CYP2C9 *2 or *3) + (0.129 X diabetes mellitus*CYP2C9 *2 or *3)] ‡ Sconce et al. algorithm; vDose (mg/day)= 0.628 − 0.0135 (Age)−0.240 (CYP*2)− 0.370(CYP*3) − 0.241 (VKOR)+0.0162 (Height) § Gage et al. algorithm; Dose (mg/day) = exp[0.9751 −(0.3238 X VKORC1 −1639G/A) + (0.4317 X BSA) −(0.00745 X age) −(0.4008 X CYP2C9*3) −(0.2066 X CYP2C9*2) + (0.2029 X Target INR) −(0.2538 X amiodarone) + (0.0922 X smokes) −(0.0901 X African American race) + (0.0664 X DVT/PE)] || Anderson algorithm (mg/week); dose =1.64+exp[3.984+CYP2C9*1*1(0)+*1*2(−0.197)+*1*3(−0.360)+*2*3(−0.947)+*2*2(−0.265)+*3*3(−1.892)+Vk-CT(−0.304)+Vk-TT(−0.569)+Vk-CC(0)+age(−0.009)+male sex(0.094)+female sex(0)+weight in kg(0.003)] # See Table 1 ** See Table 2 †† See Table 3 ‡‡ R2 estimate in the race combined cohort
    unique: PMC2538606/PMC2538606.xml::T5-0

PMC0025XXXXX/PMC2538607.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic characteristics by HAART status of 4093 AIDS subjects included in study
  footer_text: † 8 cases missing; ‡ 78 cases missing
    unique: PMC2538607/PMC2538607.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538606.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538606.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538606.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538607.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Unadjusted association of mortality and risk factors by HAART status
  footer_text: † Opportunistic Infections (OI) include fever, diarrhea, thrush, and oral hairy leukoplakia. NA: the covariate was not considered for proportional hazard models.
    unique: PMC2538607/PMC2538607.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Adjusted association of mortality and risk factors by HAART status
  footer_text: 1 The initial full model included gender, age at AIDS diagnosis, marriage, education, and on HAART; 2 The initial full model included gender, age at AIDS diagnosis, marriage, education, number of OIs at HAART initiation, and CD4 counts at HAART initiation. 3 The initial full model included gender, age at AIDS diagnosis, marriage, education, and occupation. NA: the covariate was not considered for proportional hazard models. NS: the covariate was either insignificant, not entered into initial full model, or deleted from the model selection procedure.
    unique: PMC2538607/PMC2538607.xml::T3-0

PMC0025XXXXX/PMC2538608.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Experimental design. Initial letters denote the type of cues used each day. Suffixes denote whether the context was the same or different for days two, three, and four; no suffix is used for the first day because it had no preceding day. On day one, the initial alcohol cue reactivity hypothesis was Control < Single Context = Multiple Context. At the test trial, the alcohol cue reactivity hypothesis was Control > Single Context > Multiple Context.
  footer_text: Notes: N = Neutral Cues, A = Alcohol Cues; for day two on, suffix of S = Same as preceding day, suffix of D = different from preceding day.
    unique: PMC2538608/PMC2538608.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538607.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538607.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538608.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2538611.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Effect of immunization route and number and identity of priming immunogens on vaccine elicited protection in the rhesus macaque model.
  footer_text: # includes a subset of 3, non-Mamu A*01 + elite controllers exhibiting either undetectable or transient low level viremia; ongoing investigation of immune correlates IN = intranasal; IM = intramuscular; IV = intravenous; O = oral; IT = intratracheal; Ivag = intravaginal; IR = intrarectal
    unique: PMC2538611/PMC2538611.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538611.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538613.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538613.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538613.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2538613.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic Characteristics and Estimated IQ for Final Sample and Statistical Comparisons of Subsamples
  footer_text: Note. Total Sample N = 100; Community Sample n = 26; Student Sample n = 74. Statistics in bold indicate significant differences between the community and subject pool subsamples.
    unique: PMC2538613/PMC2538613.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Descriptive Statistics for the Psychopathic Personality Inventory and Statistical Comparisons of Subsamples
  footer_text: Note. Total Sample N = 100; Community Sample n = 26; Student Sample n = 74. Statistics in bold indicate significant differences between the community and subject pool subsamples.
    unique: PMC2538613/PMC2538613.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean Reaction Time and Total Error Rate by Load and Distractor Compatibility for the Perceptual Load Task and Cognitive Control Task
  footer_text: Note. Standard deviations are presented in parentheses. N = 98 for the Perceptual Load Task. N = 97 for the Cognitive Control Task.
    unique: PMC2538613/PMC2538613.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Correlations between Reaction Time Interference and PPI factors by Load Condition for Perceptual Load Task and Cognitive Control Task
  footer_text: Note. n = 98 for all perceptual load correlations. n = 97 for all working memory load correlations. PPI = Psychopathic Personality Inventory. ** indicates p < .01. * indicates p < .05. The letter a indicates the correlations between the factor scores (PPI-CU and PPI-II) and RT are significantly different, p = .017
    unique: PMC2538613/PMC2538613.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538613.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538615.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538615.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538615.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538615.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538615.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2538615.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean Gingival Index values at control and gingivitis sites§
  footer_text: § Data are expressed as median and range of eight subjects. Within columns, values that are statistically significant are denoted by * (P = 0.008, Wilcoxon Signed Rank test).
    unique: PMC2538615/PMC2538615.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mean Plaque Index values at control and gingivitis sites§
  footer_text: § The data are reported as median and range of eight subjects. Within columns, values that are statistically significant are denoted by * (P = 0.008, Wilcoxon Signed Rank test).
    unique: PMC2538615/PMC2538615.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean gingival crevicular fluid flow rate at control and gingivitis sites§
  footer_text: § The data are expressed as mean flow rate (in μl per 45 seconds) ± SEM. Baseline values at control and experimental gingivitis sites were very similar (P = 0.54). On day 24, there was a statistically significant difference between control and experimental gingivitis sites (^ denotes P <0.001). Within rows, significant differences from baseline are denoted (* P = 0.015, # P = 0.018, paired t tests adjusted for multiple comparisons).
    unique: PMC2538615/PMC2538615.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Mean clarithromycin levels in serum, healthy control gingiva and inflamed gingiva§
  footer_text: § Data are presented as mean ± SEM. Within rows, * denotes values that were significantly different from serum levels, while # indicates data in which all three pairwise comparisons yielded significant differences (P <0.05, Holm-Sidak test).
    unique: PMC2538615/PMC2538615.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Ratio of tissue clarithromycin concentration to serum clarithromycin concentration in healthy control gingiva and gingivitis sites§
  footer_text: § Data are expressed as mean ± SEM. Within rows, * denotes a significant difference between values (P ≤0.02, paired t test). * Periopaper, Oraflow Inc, Plainview, NY, USA. † Periotron 6000, Oraflow, Inc, Plainview, NY, USA. § Supelcosil, Sigma-Aldrich, St. Louis, MO, USA. ¶ United States Pharmacopeia, Rockville, MD, USA.
    unique: PMC2538615/PMC2538615.xml::T5-0

PMC0025XXXXX/PMC2538616.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The Calculated MP2 Energies of Models A-F
  footer_text: a Model A: extracted from the crystal structure; models B-D: ligand-rotated 90°, 180°, 270° relative to model A; model E: ligand-flipped orientation of model A; model F: ligand-rotated 180° relative to model E. b MP2 energies without BSSE. c ΔE1 and ΔE2 refer to the energy difference (kcal/mol) between model A and other models calculated at MP2/6−31G*, while ΔE3 and ΔE4 refer to the energy difference (kcal/mol) between model A and other models calculated at MP2/6−31G*(0.25). d MP2 energies with BSSE correction.
    unique: PMC2538616/PMC2538616.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: The Solvation Energies (kcal/mol) from MP2/6−31G*(0.25) and B3LYP/6−31G* Using the PCM Model
  footer_text: a ΔGsolvation(MP2) = EPCM-MP2 — EMP2, ΔGsolvation(DFT) = EPCM-DFT — EDFT b ΔEsolvation was the relative solvation energy of the models investigated at the MP2 level. c ΔE was the relative energy in aqueous solution of the models investigated at the MP2 level, which was computed as the sum of the relative energy in gas-phase (ΔE4 in Table 1) and relative solvation energy (ΔEsolvation). d The results were obtained using B3LYP/6−31G* and the UAKS radii scheme. e The results were obtained using B3LYP/6−31G* and the UAHF radii scheme.
    unique: PMC2538616/PMC2538616.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: The Binding Energies (kcal/mol) of Models A-F
  footer_text: a From MP2/6−31G*(0.25) calculations with BSSE. b Ecorr = Eint(MP2) — Eint(HF). c ECT was calculated from HF/6−31G**.
    unique: PMC2538616/PMC2538616.xml::T3-0

PMC0025XXXXX/PMC2538619.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Antiproliferative and Topoisomerase I Inhibitory Activities of 14-Substituted Aromathecin Analogues
  footer_text: a GI50 values are the concentrations corresponding to 50% growth inhibition. b Mean graph midpoint for growth inhibition of all human cancer cell lines successfully tested, ranging from 10−8 to 10−4 M. c Compound-induced DNA cleavage due to Top1 inhibition is graded by the following rubric relative to 1 μM camptothecin: 0, no inhibitory activity; +, between 20% and 50% activity; ++, between 50% and 75% activity; +++, between 75% and 95% of activity; ++++, equipotent. d 22-Hydroxyacuminatine was not tested in the National Cancer Institute assay. e These compounds were not selected for further testing; refer to text for details. f Currently undergoing fivedose testing.
    unique: PMC2538619/PMC2538619.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538616.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538616.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538616.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538619.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2538620.xml

PMC0025XXXXX/PMC2538621.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Variation of membrane and rhodopsin properties as a function of lipid chain length. The average order parameter (ΔSave), estimated hydrophobic thickness (d), rhodopsin molar ellipticity at λ= 222 nm [θ]222, increase in helical content relative to helical content in 14:0d27-14:1-PC (& relative to18:0d35-18:1-PC) , the ratio MII/MI after photoactivation at 37°C, Keq, apparent time constant of MII formation at 37°C, Tapp, and temperature of the midpoint of rhodopsin thermal denaturation, Td, as a function of lipid chain length.
  footer_text: * The hydrophobic thickness d, defined as the distance between acyl chain carbonyls of the two apposing monolayers was calculated as in (17). # Temperature was 27°C (all other CD, SRCD experiments were conducted at 21°C).
    unique: PMC2538621/PMC2538621.xml::T1-0

PMC0025XXXXX/PMC2538623.xml

PMC0025XXXXX/PMC2538624.xml

PMC0025XXXXX/PMC2538625.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: TCI-R correlates with putative measures of response distortion
  footer_text: Notes: MPQ = Multidimensional Personality Questionnaire; BIDR = Balanced Inventory of Desirable Responding. Ns vary from 651 to 654. *** p < .001, ** p < .01, * p < .05
    unique: PMC2538625/PMC2538625.xml::T1-0

PMC0025XXXXX/PMC2538626.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538621.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538625.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Pairwise all-atom root-mean-squared deviation values between IRE conformation cluster median snapshots. All values in Å.
  footer_text:
    unique: PMC2538626/PMC2538626.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Optimal parameters for the best-fit nonpolar solvent radii and associated quality of fit metrics (see text for definitions). Parameter 99% confidence intervals are presented in square brackets. The “SASA only” and related labels refer to the model of the nonpolar cavity creation term and are described in detail the manuscript text.
  footer_text:
    unique: PMC2538626/PMC2538626.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Parameters for specific nonpolar solvent radii and associated quality of fit metrics (see text for definitions). Parameter 99% confidence intervals are presented in square brackets. Parameters without a * are the best fit results for that σs; parameters with a * are from the previous work of Wagoner et al [47] and included to demonstrate the extent of parameter transferability between systems. The “SASA only” and related labels refer to the model of the nonpolar cavity creation term and are described in detail the manuscript text.
  footer_text:
    unique: PMC2538626/PMC2538626.xml::T3-0

PMC0025XXXXX/PMC2538627.xml

PMC0025XXXXX/PMC2538674.xml

PMC0025XXXXX/PMC2538677.xml

PMC0025XXXXX/PMC2538685.xml

PMC0025XXXXX/PMC2538687.xml

PMC0025XXXXX/PMC2538752.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Association of MUC4 expression pattern with types and grades of gastric cancer
  footer_text:
    unique: PMC2538752/PMC2538752.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538752.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538752.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2538752.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Association of MUC4 expression pattern with stages of gastric cancer
  footer_text: *** Fisher's Exact test. Information regarding the tumour stage was not available for all the spots.
    unique: PMC2538752/PMC2538752.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Incidence of tumours in animals injected with AGS-MUC4 and AGS-pSecTagC cells
  footer_text: *** Fisher's Exact test.
    unique: PMC2538752/PMC2538752.xml::T3-0

PMC0025XXXXX/PMC2538802.xml

PMC0025XXXXX/PMC2538952.xml

PMC0025XXXXX/PMC2539063.xml

PMC0025XXXXX/PMC2539065.xml

PMC0025XXXXX/PMC2542504.xml

PMC0025XXXXX/PMC2542582.xml

PMC0025XXXXX/PMC2542583.xml
  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: Number of children (out of seven) who produced fewer than five stops in a category during the middle 10 min of recording, by session.
  footer_text:
    unique: PMC2542583/PMC2542583.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542583.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542584.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2542584.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Types of collaboration and corresponding leadership characteristics
  footer_text:
    unique: PMC2542584/PMC2542584.xml::T1-0

PMC0025XXXXX/PMC2542876.xml

PMC0025XXXXX/PMC2542881.xml

PMC0025XXXXX/PMC2542884.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Experiment 1 Lexicon
  footer_text:
    unique: PMC2542884/PMC2542884.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Experiment 2 Lexicon
  footer_text:
    unique: PMC2542884/PMC2542884.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Experiment 3 Lexical Items
  footer_text:
    unique: PMC2542884/PMC2542884.xml::T3-0

PMC0025XXXXX/PMC2542896.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: NNK content in Quest cigarettes before and after spiking with [pyridine-D4]NNK
  footer_text: a Total NNK (the sum of [pyridine-D4]NNK and unlabeled NNK) measured by GC-TEA b Sum of [pyridine-D4]NNK and unlabeled NNK measured separately by GC-MS/MS
    unique: PMC2542896/PMC2542896.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary statistics for deuterated biomarkers analyzed in 20 study participants
  footer_text: a Free [pyridine-D4]NNAL plus [pyridine-D4]NNAL-Glucs b Urine samples were treated with NaBH4 and analyzed for [pyridine-D4]hydroxy acid
    unique: PMC2542896/PMC2542896.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Separate analysis of deuterated and unlabeled keto acid and hydroxy acid in 3 study participants
  footer_text: a Urine samples were treated with NaBH4 and analyzed for hydroxy acid b Urine samples were analyzed for hydroxy acid without NaBH4 reduction step. c The amount of keto acid was calculated by subtracting hydroxy acid from the sum of keto acid and hydroxy acid.
    unique: PMC2542896/PMC2542896.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542884.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542884.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542884.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542896.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542896.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542896.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Summary statistics for biomarker ratios
  footer_text: a [Pyridine-D4]keto acid plus [pyridine-D4]hydroxy acid
    unique: PMC2542896/PMC2542896.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Urinary excretion of NNK metabolites in mice, rats, primates, and humans
  footer_text: a Data for urinary metabolites excreted at low NNK doses (11) b From ref. 9 c Combined data from ref. 13, 17, and the current study (based on geometric means for deuterated metabolites), and assuming that there are no other NNK metabolic pathways contributing to urinary metabolites. d ND, not detected e NA, not analyzed
    unique: PMC2542896/PMC2542896.xml::T5-0

PMC0025XXXXX/PMC2542982.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The frequency of opening each door for all congruent trials, Violation-of-Solidity conflict trials and Stop-Early conflict trials. The first number in each cell indicates the number of times that particular door was chosen. The second number in each cell indicates the number of times that particular door represented the correct choice. The final number in each cell indicates the proportion between the number of times the door was chosen over the number of times the door was correct
  footer_text:
    unique: PMC2542982/PMC2542982.xml::T1-0

PMC0025XXXXX/PMC2543091.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Serum concentrations (in ng/mL) in 12 Faroese mothers (collected in 2000) and their 5 year old children (collected in 2005)
  footer_text:
    unique: PMC2543091/PMC2543091.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Serum concentrations (in ng/mL) in the Faroese 7-year-old children (n = 103, collected in 1993–1994) and in the 14-year-old children (n=79, collected in 2000–2001)
  footer_text:
    unique: PMC2543091/PMC2543091.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean serum concentrations (in ng/mL) in 79 Faroese adolescents at age 14 years (in 2000–2001) in relation to the monthly number of pilot whale dinners (numbers in parenthesis).
  footer_text: * p < 0.05; ** p < 0.01
    unique: PMC2543091/PMC2543091.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542896.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542896.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2542982.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2543091.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2543091.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2543121.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Plasma and hepatic lycopene isomer concentrations in rats fed diets with or without alcohol and lycopene for 11 wk1–4
  footer_text: 1 Values are means ± SEM, n = 9–10. Means in a row without a common superscript differ, P < 0.05 (1-way ANOVA followed by Tukey’s test for differences between means). 2 Lycopene (Lyc) was not detected in placebo-fed rats with or without alcohol. 3 P-values of main effects and the interaction were determined by 2-way ANOVA. 4 One outlier from each of the alcohol + low Lyc and alcohol + high Lyc groups was excluded from final analyses.
    unique: PMC2543121/PMC2543121.xml::T1-0

PMC0025XXXXX/PMC2543933.xml

PMC0025XXXXX/PMC2543936.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: CMS schedule
  footer_text: * Restricted movements consisted of placing rats into a mouse cage (24W×10L×9H cm) for 1 hr.
    unique: PMC2543936/PMC2543936.xml::T1-0

PMC0025XXXXX/PMC2543944.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2543091.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2543121.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2543936.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2543944.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Nomenclatures of genes and gene products analyzed in this study Human and mouse SynCAM proteins are encoded by the genes CADM 1–4 and Cadm 1–4, respectively. Different nomenclatures used for individual gene products are listed.
  footer_text:
    unique: PMC2543944/PMC2543944.xml::T1-0

PMC0025XXXXX/PMC2544468.xml

PMC0025XXXXX/PMC2546443.xml

PMC0025XXXXX/PMC2546465.xml

PMC0025XXXXX/PMC2546488.xml

PMC0025XXXXX/PMC2546489.xml

PMC0025XXXXX/PMC2546495.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The neuropeptide standards used for the off-line CE-MALDI MS experiments
  footer_text: CCAP, Crustacean Cardioactive Peptide; AST, Allatostatin; CabAST-B1, C. borealis B-type allatostatin 1; UP, Uremic Pentapeptide; Pk, Pyrokinin; Ag, Angiotensin; Ok, Orcokinin. q is net charge of peptide, M is molecular mass. Mf., the custom defined matching factor of the peptide for observed and predicted migration time in CE. The Mf. (c) and Mf. (d) values resulting from the linear fitting in Figure 2 (c) and (d). CI, confidence interval. a Outlier in statistical analysis due to the extra large Mf. value.
    unique: PMC2546495/PMC2546495.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546495.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546495.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546505.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546505.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Representative examples of the peptide assignment via off-line CE-MALDI MS
  footer_text: Mass underlined, the unidentified peptides. Samples are from tissue(s) of pericardial organs (PO), Brain (Br), commissural ganglia (CoG), respectively. The columns under PO: the N column, normal sample without isotopic formaldehyde labeling; the (p) column, peptides detected as pairs with+28/+32 Da mass shift upon labeling; the (s) column, peptides detected as unlabeled single peaks. “+” shows that the peptides are detected in the samples. Er., the mass error in ppm. Mf., the custom defined matching factor of the peptide for observed and predicted migration time in CE. AST -A, -B: Allatostatins A and B types. Orco-LP: Orcokinin-like peptide. See the text for the details of these data analysis.
    unique: PMC2546495/PMC2546495.xml::T2-0

PMC0025XXXXX/PMC2546505.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic factors associated with herpes simplex virus type-2 (HSV-2) seropositivity among 737 female sex workers (FSWs)
  footer_text: * Reference group
    unique: PMC2546505/PMC2546505.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: STIs and relevant symptoms associated with HSV-2 seropositivity among 737 FSWs
  footer_text: † Reference group
    unique: PMC2546505/PMC2546505.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Behavioural characteristics associated with herpes simplex virus type-2 (HSV-2) seropositivity among 737 female sex workers (FSWs)
  footer_text: * Reference group
    unique: PMC2546505/PMC2546505.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546505.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546505.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546574.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546574.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Multivariate analyses of risk and protective factors of herpes simplex virus type-2 (HSV-2) infection among 737 female sex workers (FSWs), based on the logistic regression model*
  footer_text: * To reduce residual confounding, years of education, duration of sex work and number of clients in the preceding week were entered into models as continuous variables. The following odds ratios and 95% confidence intervals were found for these risk factors: per increased year of education: 0.9 (0.87–0.98); per additional client: 1.1 (1.02–1.11) and per additional year in sex work: 1.1 (1.03–1.18)
    unique: PMC2546505/PMC2546505.xml::T4-0

PMC0025XXXXX/PMC2546523.xml

PMC0025XXXXX/PMC2546527.xml

PMC0025XXXXX/PMC2546574.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean values of participant characteristics. with standard deviations in parentheses.
  footer_text: * p < .05 ** p < .001 *** p < .0001 1 (poor = 1 – excellent = 5) 2 gender was not recorded for two participants. WAIS: Wechsler Adult Intelligence Scale III (Wechsler, 1997a) WMS: Wechsler Memory Scale III (Wechsler, 1997b)
    unique: PMC2546574/PMC2546574.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: High frequency triplets for Experiment 3 with their overall joint probability and cue-pair conditional probability.
  footer_text:
    unique: PMC2546574/PMC2546574.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Best fitting individual stepwise regression coefficients for cue-pair and single-cue conditional probabilities and each participant in Experiment 3.
  footer_text:
    unique: PMC2546574/PMC2546574.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2546574.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547116.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547125.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2546611.xml

PMC0025XXXXX/PMC2547116.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Infant (1–11 months) and childhood (5 years) parasite prevalence in Ngerenya from 1993 to 2005
  footer_text: Confidence intervals are exact binomial confidence intervals. * Personal communications. † Snow and others,1 August 1994 and March 1995 surveys. ‡ Mwangi and others15 1998–2001. § Personal comunications. ¶ Children 5 years of age (60–71 months) only are included to compare cross-sectional surveys in the lingitudinal cohort. This prevernts any child from appearing in more than one PR estimate. ** May cross-sectional surveys only to avoid any child from contributing to the denominator twice.
    unique: PMC2547116/PMC2547116.xml::T1-0

PMC0025XXXXX/PMC2547124.xml

PMC0025XXXXX/PMC2547125.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Molecular markers used to distinguish MN columnar identities
  footer_text: * SCIP has also been observed to label LMCm motor pools in the caudal brachial and caudal lumbar spinal cord (Dasen et al., 2005; Luria and Laufer, 2007). To avoid confusion with these LMCm MNs, our analyses examine SCIP expression only in the rostral portion of these spinal cord segments.
    unique: PMC2547125/PMC2547125.xml::T1-0

PMC0025XXXXX/PMC2547131.xml

PMC0025XXXXX/PMC2547133.xml

PMC0025XXXXX/PMC2547134.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Homology of MPV vCCI to CPV vCCI, RPV vCCI, VARV vCCI, and VV COP vCCI.
  footer_text:
    unique: PMC2547134/PMC2547134.xml::T1-0

PMC0025XXXXX/PMC2547144.xml

PMC0025XXXXX/PMC2547344.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Correlation of clinicopathological variables with TG2 overexpression in patients with invasive ovarian cancer
  footer_text:
    unique: PMC2547344/PMC2547344.xml::T1-0

PMC0025XXXXX/PMC2547354.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text:
  footer_text:
    unique: PMC2547354/PMC2547354.xml::T1-0

PMC0025XXXXX/PMC2547487.xml

PMC0025XXXXX/PMC2547489.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547134.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547344.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547354.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2547490.xml

PMC0025XXXXX/PMC2547491.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: CCA Risk Factors
  footer_text:
    unique: PMC2547491/PMC2547491.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Molecular Pathology of CCA
  footer_text:
    unique: PMC2547491/PMC2547491.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: TNM Classification and UICC Staging System for Intrahepatic CCA
  footer_text:
    unique: PMC2547491/PMC2547491.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Memorial Sloan-Kettering Cancer Center Staging System for Hilar CCA
  footer_text:
    unique: PMC2547491/PMC2547491.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Exclusion Criteria for Surgical Resection of Hilar CCA
  footer_text:
    unique: PMC2547491/PMC2547491.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Mayo Clinic Criteria for Liver Transplantation for Hilar CCA
  footer_text:
    unique: PMC2547491/PMC2547491.xml::T6-0

PMC0025XXXXX/PMC2547494.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Information on RNA probes used for in situ hybridization experiments. The size of the cDNA determines the region of the RNA from which they were derived, as their 3′ end is at the terminus of the transcript; except for ErbB4, where the insert encodes amino acids 326-633.
  footer_text:
    unique: PMC2547494/PMC2547494.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547491.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547491.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547491.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547494.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547494.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547494.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Information on the antibody reagents; details on the specificity controls are described in the Materials and Methods.
  footer_text:
    unique: PMC2547494/PMC2547494.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Quantification of numbers of cells that are positive for PLAP, DLX2 and both PLAP & DLX2 immunoreactivity in the E14.5 and E18.5 cortex of Lhx6PLAP/+ and Lhx6PLAP/PLAP, using confocal data from Figure 1. The numbers represent the areal density (positive cells per 1000 μm2 of the box surface area) in cortex subregions. MZ: marginal zone; CP: cortical plate; II–IV: layers II, III and IV; V: layer V; VI: layer VI; SVZ: subventricular zone; VZ: ventricular zone.
  footer_text:
    unique: PMC2547494/PMC2547494.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Quantification of numbers of cells positive for PLAP histochemistry in different cortical layers of E18.5 Lhx6PLAP/+ and Lhx6PLAP/PLAP, using light microscopic data from Figure 2 (20 μm section plane). Boxes 1, 2 & 3 correspond to different dorsoventral regions of the neocortex as indicated in Fig. 2C&D. The numbers represent the areal density (positive cells per 1000 μm2 of the box surface area) in cortex subregions. Abbreviations: see Table 3.
  footer_text:
    unique: PMC2547494/PMC2547494.xml::T4-0

PMC0025XXXXX/PMC2547848.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Strain differences in c-Fos expression in cortical and amygdaloid regions following extinction recall. 129S1 mice had fewer c-Fos positive cells in IL and BLA and more c-Fos positive cells in CeA than C57BL/6J after extinction recall. No other cortical or amygdaloid region examined differed between strains (n=8/strain). Baseline c-Fos expression did not differ between strains baseline in any brain region examined (n=4/strain). Data are Mean ±SEM c-Fos positive cells per 0.01 mm2. For each region, the abbreviation and plane of section relative to Bregma is given in parenthesis. *P<.01 C57BL/6J vs. 129S1/same condition; #P<.01 extinction recall vs. control.
  footer_text:
    unique: PMC2547848/PMC2547848.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Strain differences in Zif268 expression in cortical and amygdaloid regions following extinction recall. 129S1 mice had fewer Zif268 positive cells in IL, LA, BLA and Imp than C57BL/6J after extinction recall. No other cortical or amygdaloid region examined differed between strains (n=7−8/strain). Baseline Zif268 expression did not differ between strains in any brain region examined (n=4/strain). Data are Mean ±SEM Zif268 positive cells per 0.01 mm2. For each region, the abbreviation and plane of section relative to Bregma is given in parenthesis. *P<.01 C57BL/6J vs. 129S1/same condition; #P<.01 extinction recall vs. control. a whole nucleus counted.
  footer_text:
    unique: PMC2547848/PMC2547848.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547494.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547848.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547848.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Absence of strain differences in c-Fos or Zif268 expression in cortical and amygdaloid regions following fear recall. 129S1 and C57BL/6J mice did not differ in c-Fos or Zif268 positive cells in any brain region examined (n=10/strain). Data are Mean ±SEM c-Fos and Zif268 positive cells per 0.01 mm2. For each region, the abbreviation and plane of section relative to Bregma is given in parenthesis. awhole nucleus counted.
  footer_text:
    unique: PMC2547848/PMC2547848.xml::T3-0

PMC0025XXXXX/PMC2547880.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Nutrient composition of the study diets
  footer_text: 1 Diet high in monounsaturated fat. 2 Diet high in complex carbohydrate. 3 Complex carbohydrate refers to polysaccharides (starch), such as those in cereal products, vegetables, legumes, and nuts. Simple carbohydrate refers to monosaccharides or disaccharides, such as those in fruit, beverages, and desserts.
    unique: PMC2547880/PMC2547880.xml::T1-0

PMC0025XXXXX/PMC2547887.xml

PMC0025XXXXX/PMC2547984.xml

PMC0025XXXXX/PMC2547989.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Menstrual cycles observed in 89 chimpanzees.
  footer_text:
    unique: PMC2547989/PMC2547989.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547848.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547880.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2547989.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2547996.xml

PMC0025XXXXX/PMC2548276.xml

PMC0025XXXXX/PMC2548278.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Means and standard deviations for demographics and clinical symptoms among the three groups
  footer_text:
    unique: PMC2548278/PMC2548278.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Key activation in brain regions labeled in SPM analysis shown in Figure 10. SPM analysis is between-groups and for the attend minus ignore PPI condition differences
  footer_text: BA=Brodmann area, L=Left hemisphere, R=Right hemisphere
    unique: PMC2548278/PMC2548278.xml::T2-0

PMC0025XXXXX/PMC2548279.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548278.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548278.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: PCR primers.
  footer_text:
    unique: PMC2548279/PMC2548279.xml::T1-0

PMC0025XXXXX/PMC2548286.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Proposed Targets of Antiretinal Antibodies
  footer_text: Retinal proteins which are proposed to be targets of antiretinal antibodies are shown, as well as the assay method(s) used to detect their corresponding antiretinal antibodies. WB = Western blot, IHC = immunohistochemistry, ELISA = enzyme-linked immunosorbent assay.
    unique: PMC2548286/PMC2548286.xml::T1-0

PMC0025XXXXX/PMC2548289.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Classification of Iron Overload Syndromes
  footer_text:
    unique: PMC2548289/PMC2548289.xml::T1-0

PMC0025XXXXX/PMC2548291.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Monochlorophenols and dichlorophenols as substrates for hSULT2A1.
  footer_text: a Relative activity is expressed as a percentage based on the ratio of the rate of sulfation of the chlorinated phenol at 50 µM to the rate of sulfation of 50 µM DHEA under the same assay conditions.
    unique: PMC2548291/PMC2548291.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Tri-, tetra-, and pentachlorophenols as substrates for hSULT2A1.
  footer_text: a Relative activity is expressed as a percentage based on the ratio of the rate of sulfation of the chlorinated phenol at 50 µM to the rate of sulfation of 50 µM DHEA under the same assay conditions.
    unique: PMC2548291/PMC2548291.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548286.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548291.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548291.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2548298.xml

PMC0025XXXXX/PMC2548310.xml

PMC0025XXXXX/PMC2548317.xml

PMC0025XXXXX/PMC2548318.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Cell cycle progression in nocodazole blocked cells
  footer_text: Data represent the means ± SEM of two (PC3, HCT) and three (MDCK) independent experiments.
    unique: PMC2548318/PMC2548318.xml::T1-0

PMC0025XXXXX/PMC2548319.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Exploring Optimal Conditions for Formation and Cross Coupling of Organoindium Reagents
  footer_text: a Refers to isolated yields after column chromatography. b Methanol (10% by volume) was added to the DMF solution of the indium reagent just prior to the cross-coupling reaction.
    unique: PMC2548319/PMC2548319.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Reaction of Diverse Aryl Iodides with In•2LiCl: Scope and Cross-Coupling Reactions
  footer_text: a For the insertion reaction, conversions were assayed by GC–MS analysis of an aliquot quenched with HCl/H2O. b Refers to isolated yields after column chromatography, unless otherwise indicated. c Insertion reaction performed at 120 °C for 12 h. d Yield determined by GC–MS analysis. e Significant amounts of homodimer 4 also produced. f Catalyst for cross-coupling was Cl2Pd(PPh3)2.
    unique: PMC2548319/PMC2548319.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548318.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548319.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548319.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548319.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Reaction of in Situ Generated Organoindium Reagents with Acyl and Allylic Electrophiles.a
  footer_text: a Typical reaction conditions: a DMF solution of the indium reagent (~0.81 M) was added to R1-X (1.0 equiv) and palladium catalyst (5–10 mol %) and heated to 80 °C under argon for 2 h, at which time complete consumption of R1-X was observed by TLC. b A= 5 mol % Pd(PPh3)4; B= 10 mol % Pd(dba)2. c Refers to isolated yields after column chromatography.
    unique: PMC2548319/PMC2548319.xml::T3-0

PMC0025XXXXX/PMC2548320.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Probability Structure of the Weather Prediction Task
  footer_text: Note. On any trial, 1 of 14 possible combinations of four cues appeared with the probability indicated above [P(cue combination appearing)]. Each cue was associated with one of the two weather outcomes (1 = Sunshine vs. 2 = Rain) with a fixed probability. Across all 14 combinations of cues, Cue 1 was associated 75% of the time with Outcome 1 and 25% of the time with Outcome 2; Cue 2 was associated 56% of the time with Outcome 1 and 44% of the time with Outcome 2; Cue 3 was associated 44% of the time with Outcome 1 and 56% of the time with Outcome 2; Cue 4 was associated 25% of the time with Outcome 1 and 75% of the time with Outcome 2. Each combination of cues predicted Outcome 1 (Sunshine) with the probability shown above [P(feedback indicating Outcome 1 is correct)] and predicted Outcome 2 (Rain) with a probability of 1 − P.
    unique: PMC2548320/PMC2548320.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Artificial Grammar Task Test Items and Chunk Strengths (CS)
  footer_text:
    unique: PMC2548320/PMC2548320.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Demographic Characteristics for Schizophrenia (n = 59) and Control (n = 43) Groups
  footer_text:
    unique: PMC2548320/PMC2548320.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Correlations Within the Schizophrenia Group (n = 59)
  footer_text: Notes: WTAR: Wechsler Test of Adult Reading; HVLT: Hopkins Verbal Learning Test; PC: Probabilistic Classification; AG: Artificial Grammar; BPRS: Brief Psychiatric Rating Scale; SANS: Scale for the Assessment of Negative Symptoms. * p < .05.
    unique: PMC2548320/PMC2548320.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548320.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548320.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548320.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548320.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548321.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2548321.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Protein Solubility in Various Sample Buffers: Soluble (S), Partially Soluble (S/I), and Insoluble (I)
  footer_text:
    unique: PMC2548321/PMC2548321.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary of 2D Separation Methods
  footer_text:
    unique: PMC2548321/PMC2548321.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Comparison of Separation Methods According to the Number of Total Proteins, Unique Peptides, Total Peptides, Average Percent Sequence Coverage, Average Protein Scores (log E), and False Discovery Rate (FDR)
  footer_text:
    unique: PMC2548321/PMC2548321.xml::T3-0

PMC0025XXXXX/PMC2548323.xml

PMC0025XXXXX/PMC2548325.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Loss of individual mitochondrial fission or fusion genes does not cause inappropriate survival of cells that normally die in the anterior pharynx.
  footer_text: The number of extra cells in the anterior pharynx of the indicated animals was counted as described in Experimental Procedures. s.e.m., standard error of the mean. Unpaired two tailed t-test, compared with N2 animals: 1 P=0.0017, 2 P=0.0011. Others have P values > 0.05.
    unique: PMC2548325/PMC2548325.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548321.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548321.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548325.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548325.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548325.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: drp-1 and fis-2 have minor, independent roles during programmed cell death.
  footer_text: The number of extra cells in the anterior pharynx of the indicated animals was counted. All data involving the ced-3(n2438) strains were confirmed by multiple independent blind test analyses. s.e.m., standard error of the mean. Unpaired two tailed t-test, compared with ced-3(n2438) animals: 1 P=0.0012, 2 P=3.4×10−5, 3 P=6.3×10−5, 4 P=0.0018, 5 P=2.1×10−11, 6 P=2.7×10−9; compared with ced-4(n2273) animals: 7 P=0.006,, 8 P=0.043,, 9 P=3.0×10−9; compared with control(RNAi) treatment of the same strain: 10 P=8.8×10−5, 11 P=2.8×10−5, 12 P=1.3×10−5, 13 P=9.0×10−8, 14 P=6.3×10−6, 15 P=2.7×10−7, 16 P=8.7×10−6, 17 P=1.1×10−4. Others have P values > 0.05.
    unique: PMC2548325/PMC2548325.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: drp-1 and fis-2 function independently of ced-9 during programmed cell death.
  footer_text: The number of extra cells in the anterior pharynx of the indicated animals was counted as described in Table 1. All strains carried the dpy-4(e1166) allele. All data were confirmed by multiple independent blind test analyses. s.e.m., standard error of the mean. Unpaired two-tailed t-test, compared with ced-9(n2812); ced-3(n2438) animals: 1 P=0.0084; 2 P=3.3×10−4, 3 P=2.3×10−6.
    unique: PMC2548325/PMC2548325.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: drp-1 and fis-2 function downstream of, or in parallel to, egl-1 and ced-3, and independently of cps-6 and wah-1.
  footer_text: Phspegl-1 (smIs82) is an integrated transgene containing the Phspegl-1 constructs. EGL-1 expression was activated by heat-shock treatment and the number of cell corpses in the head region of 1.5-fold stage embryos was scored. Pegl-1acCED-3 (smIs111) is an integrated transgene containing the Pegl-1acCED-3 construct (Kokel et al., 2006). acCED-3 is therefore expressed in cells normally destined to die. The number of cell corpses was counted in the head region of the 4-fold stage embryos. RNAi experiments were carried out as described in Experimental Procedures. All strains were in the ced-1(e1735); ced-4(n1162) background and confirmed by multiple independent blind test analyses. s.e.m., standard error of the mean. Unpaired two tailed t-test, compared with Phspegl-1 animals: 1 P = 8.7×10−5; compared with Pegl-1acCED-3 animals: 2 P=1.2×10−6; compared with control(RNAi) treatment of the same strain: 3 P=0.00035, 4 P=0.0063, 5 P=1.7×10−5, 6 P=1.5×10−6. Others have P values > 0.05.
    unique: PMC2548325/PMC2548325.xml::T4-0

PMC0025XXXXX/PMC2548326.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of significant results emerging from whole-brain LORETA analyses contrasting learners (n = 16) and non-learners (n = 14) in their response to reward feedback after correctly identifying the stimulus associated with more frequent reward in the probabilistic reward task.
  footer_text: The anatomical regions, MNI coordinates, and Brodmann areas of extreme t-values are listed. Positive t-values are indicative of stronger current density for the learners than non-learners, and vice versa for negative t-values. The numbers of voxels exceeding the statistical threshold are also reported (p<0.02; minimum cluster size: 5 voxels). Coordinates in mm (MNI space), origin at anterior commissure; (X) = left (−) to right (+); (Y) = posterior (−) to anterior (+); (Z) = inferior (−) to superior (+).

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548325.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548326.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548329.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548403.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548403.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

    unique: PMC2548326/PMC2548326.xml::T1-0

PMC0025XXXXX/PMC2548329.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Oxidation degree of oxidized dextran determined from 1H NMR and number average of molecular weight (Mn) estimated by GPC.
  footer_text: a Calculated by integrating the anomeric proton peak at δ 4.8 ppm and the tert-butyl proton peak at δ 1.3 ppm. b Gelling time for 2.5 % solutions of Odex and 2.5% CEC solutions in 0.01 M PBS at 37 °C.
    unique: PMC2548329/PMC2548329.xml::T1-0

PMC0025XXXXX/PMC2548403.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Characteristics of FLOW Cohort of COPD vs. Referent Subjects
  footer_text:
    unique: PMC2548403/PMC2548403.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Pulmonary Function and Stage of COPD in the FLOW Cohort
  footer_text: Mean (sd)
    unique: PMC2548403/PMC2548403.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Impact of COPD on Functional Limitation: Lower Extremity Functioning, Exercise Performance, and Balance
  footer_text: All analyses control for age, sex, height, race, educational attainment, smoking The third column show results for all subjects. The fourth column shows results for more severe COPD only (GOLD Stage II or greater) vs. referent group (n=742 COPD cases vs. 302 referent subjects) The fifth column shows results for GOLD Stage II or greater vs. referent group, controlling for baseline covariates plus inclusion of cardiovascular comorbidities (congestive heart failure, coronary artery disease, myocardial infarction, or stroke) and diabetes
    unique: PMC2548403/PMC2548403.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Impact of COPD on Functional Limitation: Skeletal Muscle Strength
  footer_text: Muscle strength is measured in pounds of force; greatest of 3 repetitions on the dominant side All analyses control for age, sex, race, educational attainment, and smoking history The fourth column shows results for more severe COPD only (GOLD Stage II or greater) vs. referent group (n=742 COPD cases vs. 302 referent subjects); last column also controls for cardiovascular comorbidities and diabetes
    unique: PMC2548403/PMC2548403.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Impact of COPD on Self-reported Functional Limitation
  footer_text: Multivariate logistic regression analysis controlling for age, sex, race, height, smoking, education † “Unable to do” or “severe limitation” in a battery of basic physical activities (see Methods) †† Health limits “a lot” in performing moderate activities, such as moving a table, pushing a vacuum cleaner, bowling or playing golf The fourth column shows results for more severe COPD only (GOLD Stage II or greater) vs. referent group (n=742 COPD cases vs. 302 referent subjects). The fifth column shows the same group with additional statistical control for cardiovascular comorbidities and diabetes.
    unique: PMC2548403/PMC2548403.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548403.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548403.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2548403.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551310.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2548421.xml

PMC0025XXXXX/PMC2551310.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Better ear pure-tone average (BE-PTA) thresholds (at 0.5, 1, and 2 kHz) and age of identification for the children with HL
  footer_text: Note. The maximum measurable hearing loss (HL) is 120 dB. M = male; F = female; supp. = supplemental; ID = identification.
    unique: PMC2551310/PMC2551310.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Adjusted number of utterances (adjusted inversely proportional to the duration of recording) and syllable statistics
  footer_text: Note. NH = normal hearing.
    unique: PMC2551310/PMC2551310.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Adjusted number of consonants (adjusted inversely proportional to the duration of recording) and consonant statistics
  footer_text: Note. Em dashes indicate “not applicable.”
    unique: PMC2551310/PMC2551310.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551310.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551310.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551310.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: The number of measurements and standard deviations of the first two formant frequencies, F1 and F2
  footer_text:
    unique: PMC2551310/PMC2551310.xml::T4-0

PMC0025XXXXX/PMC2551315.xml

PMC0025XXXXX/PMC2551322.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: List of chromatin interacting proteins that are regulated by UV-B in B73 and/or mbd101 and chc101 RNAi lines clustered by SOM
  footer_text:
    unique: PMC2551322/PMC2551322.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551322.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551322.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551328.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551328.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Primers used for qRT-PCR
  footer_text: a Primers specifically designed to detected decreased transcript accumulation mediated by RNAi transformation
    unique: PMC2551322/PMC2551322.xml::T2-0

PMC0025XXXXX/PMC2551328.xml
  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: Data collection, refinement and geometry statistics
  footer_text: a ASU - Asymmetric unit b r.m.s.d. - root mean square deviation c Values in parenthesis for the highest resolution bin d Rsym = Σ|I − <I>| /Σ<I>, where I is the observed intensity, and <I> is the average intensity of multiple observations of symmetry-related reflections. e R = Σ ||Fobs|−|Fcalc||/ Σ |Fobs| where Fobs and Fcalc are the observed and calculated structure factors
    unique: PMC2551328/PMC2551328.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Kinetic Parameters of the Glycine Hinge Mutations
  footer_text: a No detectable protein produced b All mutants are able to be inhibited by serine to < 95%.
    unique: PMC2551328/PMC2551328.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Kinetic Parameters of the Serine Binding Residue Mutations
  footer_text: a Ki refers to substrate inhibition. b All mutants are able to be inhibited by serine to < 95%.
    unique: PMC2551328/PMC2551328.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551328.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551557.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551557.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2551557.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Results from Screen
  footer_text: a Number of gynogenetic diploid sib cohorts from F1 females with defective gene expression b Number of rag-1 negative sib cohorts c Number of αe1 negative sib cohorts
    unique: PMC2551557/PMC2551557.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Phenotypic characteristics of rag-1 deficient mutants
  footer_text: mc: microcephaly mo: microphthalmia
    unique: PMC2551557/PMC2551557.xml::T2-0

PMC0025XXXXX/PMC2551558.xml

PMC0025XXXXX/PMC2551618.xml

PMC0025XXXXX/PMC2551738.xml

PMC0025XXXXX/PMC2551742.xml

PMC0025XXXXX/PMC2551745.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Parameter estimates from the application of mixture model methods to HIV data.
  footer_text: * Mixture Probablity πi=eΣParameter Estimate1+eΣParameter Estimate ** Centered at Log10(70000)
    unique: PMC2551745/PMC2551745.xml::T1-0

PMC0025XXXXX/PMC2551751.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Serum corticosterone measurements in wild type (WT) and stress-sensitive (KO) mice showing continued stress response throughout the chronic stress paradigm (N = 6-7). Stressed mice (CVS) of each genotype were compared to unstressed littermates (CTRL). Samples taken prior to onset (Basal) and at completion (Stressed) of a 15 minute restraint stress. Values are expressed as mean ± SEM.
  footer_text:
    unique: PMC2551751/PMC2551751.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Active and passive cell characteristics in whole cell recordings of cells in ventromedial dorsal raphe (vmDR). Recordings were taken from serotonin (5-HT+) and non 5-HT (5-HT−) cells in wild type (WT) and stress-sensitive (KO) mice. Abbreviations are as follows: Vm, resting membrane potential; R, resistance; AHP, afterhyperpolarization; Amp, amplitude; AP, action potential. Values are expressed as mean ± SEM.
  footer_text: * significant difference across 5-HT+and 5-HT− cells, p ≤ 0.05. ‡ significant difference across genotypes, p ≤ 0.05.
    unique: PMC2551751/PMC2551751.xml::T2-0

PMC0025XXXXX/PMC2551756.xml

PMC0025XXXXX/PMC2551759.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: NMR data of calanquinone A (1)a
  footer_text: a Measured in CDCl3 (300 and 500 MHz, δ in ppm, J in Hz).
    unique: PMC2551759/PMC2551759.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551745.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551751.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551751.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551759.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Cytotoxicity of calanquinone A (1) isolated from C. arisanensis
  footer_text: a positive control
    unique: PMC2551759/PMC2551759.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Cytotoxicity of synthesized 1 and related intermediates
  footer_text: NA: no activity up to 20 µg/mL
    unique: PMC2551759/PMC2551759.xml::T3-0

PMC0025XXXXX/PMC2551761.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Computational predictions of toxin stabilitya
  footer_text: a Protein instability data for Pet and for the A chains of ricin, cholera toxin (CTA1), and pertussis toxin (PTS1) were obtained from the ProtParam function of ExPASy-SWISS-PROT. An instability index value greater than 40 is indicative of protein instability. The predicted A chain stabilities were consistent with experimental data from three studies which collectively indicated a relative stability order of ricin A > CTA1 > PTS1 (10-12). It should be noted that an interaction with negatively charged phospholipids is thought to further destabilize ricin A chain before its export from the ER to the cytosol (34).
    unique: PMC2551761/PMC2551761.xml::T1-0

PMC0025XXXXX/PMC2551765.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Primers used for library construction
  footer_text: The sequences underlined enable amplification or randomization of CDR repertoires. a Sub-groups of human antibody heavy chain genes. b All members in the groups.
    unique: PMC2551765/PMC2551765.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551759.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551759.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551761.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551765.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Primer pairings used for amplification of gene segments
  footer_text: a These products partially cover FRs. b All members in the group of VH germlines c Sub-group within the group of VH germlines.
    unique: PMC2551765/PMC2551765.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: CDR diversity of unique phage-displayed VHs selected against B5R after the third round of panning
  footer_text:
    unique: PMC2551765/PMC2551765.xml::T3-0

PMC0025XXXXX/PMC2552397.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Glide, Liaison and Scoring Function Training and Test Set Predictions for GGPPS Inhibition.
  footer_text: a structures of all inhibitors shown in Figure 1 b bold values indicated compounds not included in training set.
    unique: PMC2552397/PMC2552397.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551765.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2551765.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552397.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Receptor-Guided Alignment CoMSIA training and Test Set Predictions for GGPPS Inhibition.
  footer_text: N = number of components; n = Number of training set compounds a structures of all inhibitors shown in Figure 1 b bold values indicated compounds not included in training set.
    unique: PMC2552397/PMC2552397.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552397.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552397.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552397.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Data Collection and Refinement Statistics for GGPPS-Bisphosphonate Crystals.
  footer_text: a Values in the parenthesis are the highest resolution shells.
    unique: PMC2552397/PMC2552397.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Data collection and refinement statistics for GGPPS-bisphosphonate crystals.
  footer_text: a Values in the parenthesis are the highest resolution shells.
    unique: PMC2552397/PMC2552397.xml::T4-0

PMC0025XXXXX/PMC2552408.xml

PMC0025XXXXX/PMC2552409.xml

PMC0025XXXXX/PMC2552411.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: CHARACTERISTICS AND ODDS RATIOS FOR ESCC CASES AND CONTROLS
  footer_text: 1 Crude Odds Ratio. 95%CI = 95% confidence interval. ESCC = esophageal squamous cell carcinoma. NA = not applicable. OR = odds ratio. UGI = upper gastrointestinal.
    unique: PMC2552411/PMC2552411.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552411.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552411.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552411.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552975.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552975.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: ODDS RATIOS FOR SIGNIFICANT SNPs IN ESCC CASE-CONTROL STUDY (CASES n=300, CONTROLS n=300)
  footer_text: 1 SNP coding a nonsynonymous amino acid substitution Lysine 270 to Methionine. 2 SNPs identified from pilot study. 3 SNPs in linkage disequilibrium. 4 Permuted p value GLM (additive model). 5 Permuted Fishers p value (2×3). 6 P value (HWE) derived from 2×3 distributions. 2×3 = 2×3 frequency distribution table. ESCC = esophageal squamous cell carcinoma. GLM = general linear model (additive model). HWE = Hardy-Weinburg equilibrium. SNP = single nucleotide polymorphism. Homozygous common allele in controls is the reference genotype.
    unique: PMC2552411/PMC2552411.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table III
  caption_text: ODDS RATIOS FOR NUMBER OF PROTECTIVE ALLELES IN ESCC CASE-CONTROL STUDY (CASES n=300, CONTROLS n=300)
  footer_text: 1 Odds ratio GLM additive mode. 2 P value GLM additive model. SNPs and their corresponding alleles used for calculating combined effects of multiple protective alleles; rs1515366 (allele A), EPHB1; rs4264508 (allele T), PGLYRP2; rs52911 (allele C), PIK3C3; rs16853475 (allele T), SLC9A9. The single most protective SNP from each of our four targeted genes were evaluated to determine the combined effects of multiple protective alleles.Multiple protective alleles were examined in three ways: (i) as a continuous variable; (ii) categorized into four groups approximating quartiles as: group 1 (0-1 protective allele), group 2 (2 protective alleles), group 3 (3 protective alleles), and group 4 (4-6 protective alleles; there were no individuals with 7-8 protective alleles) and analyzed using indicator variables; and (iii) combined into a single ordinal variable to test for trend.
    unique: PMC2552411/PMC2552411.xml::T3-0

PMC0025XXXXX/PMC2552975.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Hypothetical Self-ratings for Traits in General and in Five Specific Roles
  footer_text: Note. For brevity, only 10 of 40 Big Five traits in the Trait-Role Questionnaire are shown.
    unique: PMC2552975/PMC2552975.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mean General-Specific Role Correlations and Associated Confidence Intervals for Each Role and Culture
  footer_text: Note. C.I. = confidence interval.
    unique: PMC2552975/PMC2552975.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Means and Standard Deviations for (In)Consistency (SD) Indices in Six Cultures

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552975.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552975.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  footer_text: Note. Larger values indicate greater cross-role variability (i.e., inconsistency). For each type of data, means with the same superscripts are not significantly different in between-culture comparisons (Scheffé post-hoc t-tests). Partial η2 values are for cultural main effects in analyses of variance (ANOVAs).
    unique: PMC2552975/PMC2552975.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Correlations and Standardized Beta Coefficients in Predicting SD Variability Index in Six Cultures
  footer_text: ** p<.01; * p<.05.
    unique: PMC2552975/PMC2552975.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Prediction of Adjustment Measures
  footer_text: Note. Where two values of β or R are separated by a slash (/), the first value is for the original data and the second value is for the ipsatized data. ** p<.01; * p<.05.
    unique: PMC2552975/PMC2552975.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2552975.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553012.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2553002.xml

PMC0025XXXXX/PMC2553012.xml
  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: Location estimates of current sources and current sinks. Actual locations refer to independent measurements of current injection electrode positions. The FWHM is twice the mean distance from a given extrema of the divergence to the half-maximum contour. FWHM = Full-Width at Half-Maximum
  footer_text:
    unique: PMC2553012/PMC2553012.xml::T1-0

PMC0025XXXXX/PMC2553033.xml

PMC0025XXXXX/PMC2553044.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Examples of pathogens that bind to sialic acids on human cell surfaces
  footer_text:
    unique: PMC2553044/PMC2553044.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Examples of pathogens that express sialic acids on their surfaces
  footer_text:
    unique: PMC2553044/PMC2553044.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Sialylation changes associated with malignant transformation and tumor progression
  footer_text: Abbreviations: N-CAM, neural cell adhesion molecule; Tn, Siaα2-3GalNAcα-Ser/Thr.
    unique: PMC2553044/PMC2553044.xml::T3-0

PMC0025XXXXX/PMC2553045.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Numbers of slices and the age range of animals from which they were taken for electrophysiological measurements.
  footer_text:
    unique: PMC2553045/PMC2553045.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Comparison of intrinsic electrical properties in wild type and jerker mice reveal no differences.
  footer_text: Values of resting potential (Vrest), input resistance (Rin), and membrane time constant (τ) are given as means ± SE. The Rin and τ were measured near the resting potential.
    unique: PMC2553045/PMC2553045.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553044.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553044.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553044.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553045.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553045.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2553221.xml

PMC0025XXXXX/PMC2553239.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patterns of use of tobacco among medical students in Damascus according to year of study at university (1st versus 5th)
  footer_text: * p<0.05 for comparisons across year of study (1st versus 5th)
    unique: PMC2553239/PMC2553239.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Correlates of smoking among medical students in Damascus, Syria
  footer_text: * increment of 1 year in age
    unique: PMC2553239/PMC2553239.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Multivariate logistic regression analysis for predictors of tobacco use among medical students in Damascus, Syria
  footer_text: * because of multi-colinearity, year at university and age were entered in the models separately.
    unique: PMC2553239/PMC2553239.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Beliefs & attitudes towards tobacco use among medical students in Damascus, Syria
  footer_text: * p < 0.05 for comparisons across smoking status for each tobacco use method
    unique: PMC2553239/PMC2553239.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553239.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553239.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553239.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553239.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553272.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2553250.xml

PMC0025XXXXX/PMC2553270.xml

PMC0025XXXXX/PMC2553272.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Biodistribution of 111In-labeled DO3A-BP in normal Balb/c mice (n = 4). Data are presented as %ID/g ± standard deviation. B/B: Bone/Blood; B/M: Bone/Muscle.
  footer_text:
    unique: PMC2553272/PMC2553272.xml::T1-0

PMC0025XXXXX/PMC2553276.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: List of the locations in the visual field that were represented by our injected SC sites across all experiments. The sites are sorted by brain hemisphere as well as by their retinotopic location and polar coordinates, as estimated from the maps of visually guided saccade latencies after muscimol injection (see Materials and Methods). The asterisk in the last column indicates that the site was also used later (after all muscimol experiments were completed) for a saline control injection
  footer_text:
    unique: PMC2553276/PMC2553276.xml::T1-0

PMC0025XXXXX/PMC2553351.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Distribution of MMP-1 (collagenase-1), MMP-8 (collagenase-2), and MMP-13 (collagenase-3)
  footer_text: Data reported as the percentage of total collagenase protein in GCF.
    unique: PMC2553351/PMC2553351.xml::T1-0

PMC0025XXXXX/PMC2553352.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553276.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553351.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553352.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of hamsters fed on regular chow vs. high fructose diet
  footer_text: Hamsters were fed regular chow or high fructose diet for 8 weeks, followed by the determination of body weight, fasting blood glucose levels, fasting plasma levels of insulin, FFA, triglyceride, cholesterol, HDL-cholesterol (HDL-c). Non-HDL-cholesterol (non-HDL-c) levels were calculated by subtracting HDL-c from total cholesterol levels in plasma. Glucose tolerance was performed after 7 weeks of fructose feeding for the determination of AUC of blood glucose profiles in response to glucose challenge. Hamsters were sacrificed at the end of study and liver tissues were used for the determination of hepatic lipid content, defined as mg of triglyceride per gram of wet liver tissue. * P<0.05 vs. control by ANOVA.
    unique: PMC2553352/PMC2553352.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Hepatic proteins with >2-fold alterations in response to high fructose feeding
  footer_text: Proteomic profiling of livers of hamsters fed on high fructose (n=6) and regular chow (n=6) were performed. Determination of changes in protein expression levels was performed on a total of 12 2-D gels from individual hamster livers in control and fructose_groups, using DeCyder software version 5 and calculated from the volume ratios of the normalized fluorescent signals. Protein spots with significant differences of greater than 2 fold (P<0.05) between high fructose- and regular chow-fed hamsters were identified. All identified proteins match the apparent molecular mass and pI values, based on the 2-D gels.
    unique: PMC2553352/PMC2553352.xml::T2-0

PMC0025XXXXX/PMC2553360.xml

PMC0025XXXXX/PMC2553361.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of common affects of FASN inhibition on PC-3, MCF-7 and SKOV-3 cancer cells, expressed as % of control
  footer_text: * P<0.05 (two-tailed unpaired Student’s t test) a 3 or more repeats b 2 repeats.
    unique: PMC2553361/PMC2553361.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553352.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553361.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553434.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553434.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2553395.xml

PMC0025XXXXX/PMC2553425.xml

PMC0025XXXXX/PMC2553434.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: FMRI image acquisition parameters for 3T and 4T datasets
  footer_text:
    unique: PMC2553434/PMC2553434.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Similar regions of coherent positive and negative BOLD signal changes in BT and 4T datasets determined by 2dTCA
  footer_text: Region number corresponds to numbers indicated in Figures 2A and 3A. MNI coordinates indicate center of one comparable activated duster in this region.
    unique: PMC2553434/PMC2553434.xml::T2-0

PMC0025XXXXX/PMC2553438.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Ranking experiment results showing the average number of top-10 ranked markers within a given distance of the true disease-predisposing locus.
  footer_text: Based on 100 simulated data sets each with 1000 case and 1000 control individuals. Columns denoted χ2 correspond to single-marker χ2-test results, while columns denoted “P” (respectively, “U”) correspond to Blossoc results using m = 5 for phased (respectively, unphased) data. GRR=“Genetic Relative Risk”. WR=“Wildtype Risk”.
    unique: PMC2553438/PMC2553438.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553438.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553438.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553438.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Ranking experiment results showing the fraction of data sets with at least one top-10 marker within a given distance of the true disease-predisposing locus.
  footer_text: Based on 100 simulated data sets each with 1000 case and 1000 control individuals. Columns denoted χ2 correspond to single-marker χ2-test results, while columns denoted “P” (respectively, “U”) correspond to Blossoc results using m = 5 for phased (respectively, unphased) data. GRR=“Genetic Relative Risk”. WR=“Wildtype Risk”.
    unique: PMC2553438/PMC2553438.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Percentage of data sets with the highest scoring marker within distance ε (in Kbp) from the disease-predisposing SNP, which is untyped.
  footer_text: Based on 100 simulated data sets for each setting, with 5% wild-type risk and ρ = 40. Columns denoted χ2 correspond to single-marker χ2-test results, while columns denoted “P” (respectively, “U”) correspond to Blossoc results using m = 5 for phased (respectively, unphased) data.
    unique: PMC2553438/PMC2553438.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Percentage of data sets with the highest scoring marker within distance ε (in Kbp) from the disease-predisposing SNP, for 1000 case and 1000 control individuals, and GRR= 2.0.
  footer_text: Based on simulated data sets from Minichiello and Durbin (2006); each data set was for a 1 Mbp region with ρ = 440 and 300 tagging SNPs. Columns denoted χ2 correspond to single-marker χ2-test results, while columns denoted “P” (respectively, “U”) correspond to results for phased (respectively, unphased) data. We used m = 5 in running Blossoc. The results for Margarita correspond to Figure 2E of Minichiello and Durbin (2006).
    unique: PMC2553438/PMC2553438.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553438.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553438.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553438.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553520.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Top 10 highest scoring SNPs in the Parkinson disease data set (Fung et al., 2006) analyzed using Blossoc.
  footer_text: Locations correspond to that of NCBI Build 36.1.
    unique: PMC2553438/PMC2553438.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Running times of Blossoc. See the main text for the computer spec.
  footer_text:
    unique: PMC2553438/PMC2553438.xml::T6-0

PMC0025XXXXX/PMC2553514.xml

PMC0025XXXXX/PMC2553520.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Average (mean) life span (years), maximum life span (years), average age at menopausal onset (years), and proportion of life spent in a nonreproductive state as a function of currently known average or maximum life spans in a variety of primate species.
  footer_text: a [128] b [129] c [35] d [130] e [130] f [62, 64, 65] g [131] h [131] i [77] j [132] k [55] l [133] m [134] n [81] o [42] p [135] q [40]
    unique: PMC2553520/PMC2553520.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Criterion-based operational definitions and dependent variables used to establish the existence of menopause.
  footer_text:
    unique: PMC2553520/PMC2553520.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553520.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553624.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553624.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2553624.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Correlations, Ranges, Means, and Standard Deviations of Stress, Distress and Demographic Variables
  footer_text: a Job Status: 0 = not employed; 1 = part time; 2 = full time. b Education: 1 = <11 years; 2 = high school; 3 = trade/tech school; 4 = college, not graduated; 5 = associate’s degree; 6 = college, graduated; 7 = some grad school, did not finish; 8 = Master’s/Terminal degree. c Income: 1 = less than 15K; 2 = 15K to 25K; 3 = 26K to 50K; 4 = 51K to 75K; 5 = 76K to 100K; 6 = > 100K. d Children: 0 = No; 1 = Yes. e Num. Children: coded as continuous variable. f Marital status: 0 = single, divorced, separated, or widowed; 1 = Married, living as if married, committed, not living together. g Neighborhood: 1 = all share ethnic background; 2 = most share background; 3 = half share background; 4 = very few share background; 5 = none share background. h Student status: 0 = Not a student; 1 = part time student; 2 = full time student. ** p < .01. *** p < .001.
    unique: PMC2553624/PMC2553624.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Path Coefficients, Standard Errors, and Significance Levels of Models
  footer_text: Note. RRS = Race-related stress; RRSE = race-related stress exposure; RRSA = race-related stress appraisal; GRS = gender-related stress; GRSE = gender-related stress exposure; GRSA = gender-related stress appraisal; GS = generic stress; GSE = generic stress exposure; GSA = generic stress appraisal. All p values are for the ratio of unstandardized estimates/SE. ** p < .01. *** p < .001.
    unique: PMC2553624/PMC2553624.xml::T2-0

PMC0025XXXXX/PMC2553626.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: ALS Genes and Loci1
  footer_text:
    unique: PMC2553626/PMC2553626.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: ALS-related Motor Neuron Disorders with upper and lower motor neuron involvement1
  footer_text: * No bulbar involvement. Long, slow progression, distal wasting with pyramidal signs and sensory loss, previously called axonal CMT with pyramidal signs. ** This is a disorder that appears to be proximal SMA IV (Finkel type) with some UMN findings.
    unique: PMC2553626/PMC2553626.xml::T2-0

PMC0025XXXXX/PMC2553682.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Descriptive Statistics by Treatment Condition for Study Outcome Measures
  footer_text: Note. CB = Cognitive-behavioral therapy; SD = standard deviation.
    unique: PMC2553682/PMC2553682.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Repeated Measures ANCOVA Pairwise Contrasts
  footer_text: Note. CB = Cognitive-Behavioral Therapy; Coeff = coefficient; SE = standard error; d = Cohen’s d; CI = confidence interval; p = p-value.
    unique: PMC2553682/PMC2553682.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553626.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553626.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553682.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553682.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553692.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553704.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2553687.xml

PMC0025XXXXX/PMC2553690.xml

PMC0025XXXXX/PMC2553692.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Functional differences between two populations of V1 neurons, difficulty-suppressed and difficulty-enhanced The width of the interspike interval distribution was measured at half of its amplitude and the peak as the time with the maximum value in the distribution (measured with a bin width = 1 ms). The contrast sensitivity was measured from the contrast response function as the contrast that generated half-maximum response or C50. Significance was measured with a Mann-Whitney test
  footer_text:
    unique: PMC2553692/PMC2553692.xml::T1-0

PMC0025XXXXX/PMC2553693.xml

PMC0025XXXXX/PMC2553704.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of the Study Participants.*
  footer_text: * Plus–minus values are means ±SD. BDNF denotes brain-derived neurotrophic factor, and BMI body-mass index. † Nominal P values are shown. ‡ Race or ethnic group was self-reported. § Data are for 33 parents of persons with heterozygous BDNF deletions and 27 parents of persons without BDNF deletions. ¶ There were differences in the sample size for BMI z scores because some participants had incomplete growth records and others were of young age. Multiple observations were obtained from each patient, but only one data point (if available) for each age-category analysis was used. ∥ Data are for 18 patients with heterozygous BDNF deletions and 9 patients without BDNF deletions. ** Data are for 18 patients with heterozygous BDNF deletions and 8 patients without BDNF deletions. †† Data are for 12 patients with heterozygous BDNF deletions and 8 patients without BDNF deletions. ‡‡ Data are for 5 patients with heterozygous BDNF deletions and 5 patients without BDNF deletions. §§ Data are for 19 patients with heterozygous BDNF deletions and 14 patients without BDNF deletions. Covariates for the adjusted current BMI z score were the BMI values of the parents.
    unique: PMC2553704/PMC2553704.xml::T1-0

PMC0025XXXXX/PMC2553708.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline characteristics of the study population by quartile (Q) of serum selenium concentrations (n = 5452)1
  footer_text: 1 Adjusted for age, sex, and race-ethnicity. 2 x̄ ± SE (all such values). 3 SE in parentheses (all such values).
    unique: PMC2553708/PMC2553708.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Difference (95% CI) in serum lipid and lipoprotein concentrations by quartile (Q) of serum selenium concentrations (n = 5452)1
  footer_text: 1 Apo B, apolipoprotein B; apo A-I, apolipoprotein A-I. 2 x̄ within each quartile (all such values). 3 Adjusted for age (continuous), sex (male, female), and race-ethnicity (non-Hispanic white, non-Hispanic black, Mexican American, other). 4 Further adjusted for education (≥12 y of school completed, <12 y of school completed), family income (≥$20 000,<$20 000), postmenopausal status for women (yes, no), cigarette smoking (current, former, never), serum cotinine (continuous), alcohol consumption (current, former, never), physical activity (0, 1-2, ≥3 times/wk), and body mass index (continuous). 5 Further adjusted for cholesterol-lowering medication use (yes, no), vitamin-mineral supplement use (yes, no), glomerular filtration rate (continuous), C-reactive protein (≥1.0 mg/dL, 0.3-0.9 mg/dL, <0.3 mg/dL), diabetes mellitus (yes, no), thyroid-stimulating hormone (continuous), and thyroxine (continuous). 6 Analysis based on subsample of 2589 participants because apo B and apoA-I were only measured during 1988-1991.
    unique: PMC2553708/PMC2553708.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Ratio (95% CI) of serum triacylglycerol concentrations by quartile (Q) of serum selenium concentrations (n = 5452)
  footer_text: 1 Geometric x within each quartile (all such values). 2 Adjusted for age (continuous), sex (male, female), and race-ethnicity (non-Hispanic white, non-Hispanic black, Mexican American, other). 3 Further adjusted for education (≥12 y of school completed, <12 y of school completed), family income (≥$20 000, <$20 000), postmenopausal status for women (yes, no), cigarette smoking (current, former, never), serum cotinine (continuous), alcohol consumption (current, former, never), physical activity (0, 1-2, ≥3 times/wk), and body mass index (continuous). 4 Further adjusted for cholesterol-lowering medication use (yes, no), vitamin-mineral supplement use (yes, no), glomerular filtration rate (continuous), C-reactive protein (≥1.0 mg/dL, 0.3-0.9 mg/dL, <0.3 mg/dL), diabetes mellitus (yes, no), thyroid-stimulating hormone (continuous), and thyroxine (continuous).
    unique: PMC2553708/PMC2553708.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: TABLE 4
  caption_text: Difference (95% CI) in the ratio of LDL cholesterol to HDL cholesterol (LDL cholesterol:HDL cholesterol) and in the ratio of apolipoprotein B to apolipoprotein A-I (apo B:apo A-I) by quartile (Q) of serum selenium concentrations (n = 5452)
  footer_text: 1 x̄ within each quartile (all such values). 2 Adjusted for age (continuous), sex (male, female), and race-ethnicity (non-Hispanic white, non-Hispanic black, Mexican American, other). 3 Further adjusted for education (≥12 y of school completed, <12 y of school completed), family income (≥$20 000, <$20 000), postmenopausal status for women (yes, no), cigarette smoking (current, former, never), serum cotinine (continuous), alcohol consumption (current, former, never), physical activity (0, 1-2, ≥3 times/wk), and body mass index (continuous). 4 Further adjusted for cholesterol-lowering medication use (yes, no), vitamin-mineral supplement use (yes, no), glomerular filtration rate (continuous), C-reactive protein (≥1.0 mg/dL, 0.3-0.9 mg/dL, <0.3 mg/dL), diabetes mellitus (yes, no), thyroid-stimulating hormone (continuous), and thyroxine (continuous). 5 Analysis based on subsample of 2589 participants because apo B and apo A-I were only measured during 1988-1991.
    unique: PMC2553708/PMC2553708.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553708.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553708.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553708.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553708.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2553710.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Area under the lives-saved-weighted ROC curve with spores falling in the Class A shape in an urban location and with k = ncases in equation (1) for each of the 7 methods
  footer_text: a Mixed effects Poisson models with signal lengths of exactly 1, 3, and 7 days b Space-and-time scan approaches with maximum signal lengths of 1, 3, and 7 days
    unique: PMC2553710/PMC2553710.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Area under the lives-saved-weighted ROC curve with spores falling in the Class A shape in an urban location and with the weight function as in equation (1) with k = the median cases saved for each of the 7 methods
  footer_text: a Mixed effects Poisson models with signal lengths of exactly 1, 3, and 7 days b Space-and-time scan approaches with maximum signal lengths of 1, 3, and 7 days
    unique: PMC2553710/PMC2553710.xml::T2-0

PMC0025XXXXX/PMC2553713.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553710.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553710.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553713.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2553713.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Results for parameter robustness checks. For each new parameter value in turn, 100 psychometric functions were generated. The numbers in the columns headed `Threshold' and `Slope' refer to the median of the values from those 100 runs. Values are given in units of % contrast. For details on the meaning of the individual parameters, and the abbreviations used, see the Methods section. For quick comparison, the equivalent results using the standard parameter values as given in the Methods section are included at the top of the table.
  footer_text:
    unique: PMC2553713/PMC2553713.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary of experimental results by subject. Values are the mean of the fitted parameters from the four visual field locations tested, given in units of % contrast, and the estimated false negative rate FN.
  footer_text:
    unique: PMC2553713/PMC2553713.xml::T2-0

PMC0025XXXXX/PMC2553753.xml

PMC0025XXXXX/PMC2553894.xml

PMC0025XXXXX/PMC2554670.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Torque and Muscle Activation (Mean ± SD) Produced With Protocols A and B
  footer_text: Abbreviations: CSA, cross-sectional area; MVIT, maximum voluntary isometric torque; NMES, neuromuscular electrical stimulation; TTI, torque time integral. * Significant difference between protocols (P<.05).
    unique: PMC2554670/PMC2554670.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Torque (Mean ± SD) Produced at the Start and the End of Protocol B*
  footer_text: * The decline in “starting” and “ending” torque between the first and tenth contractions was 31% and 50%, respectively. The tenth contraction showed a decline in torque by 24% from the beginning to the end of the contraction.
    unique: PMC2554670/PMC2554670.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2554670.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2554670.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2555965.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2555965.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2555965.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2555965.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2555965.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The history of developments observed in PBC diagnosis are well representative of the different discovery paces with the early major discoveries in PBC diagnosis and the slow progression of newer techniques for AMA testing. Putative developments for the expected upcoming phases are suggested.
  footer_text:
    unique: PMC2555965/PMC2555965.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: PBC natural history and treatment remain an unfinished business. The rapid pace of earlier discoveries well represent phase 1 and was followed by slower developments with combination treatments and the prognostic significance of ANA. Future developments in the third phase are hypothesized.
  footer_text:
    unique: PMC2555965/PMC2555965.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: PBC genetic and environmental bases recognize three bases with an earlier rapid development of descriptive data on familial PBC and twin concordance subsequently followed by a slower phase with unconclusive association studies while recapitulation of the role of sex chromosome, xenobiotics, and bacteria is awaited. Epigenetic studies may constitute the key to a awaited third phase.
  footer_text:
    unique: PMC2555965/PMC2555965.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: PBC immunobiology was characterized by earlier discoveries leading to the definition of AMA autoantigens and autoreactive T cells while a second phase is well represented by the study of T regulatory cells, apoptosis in cholangiocytes, and innate immune changes. The integration of these lines of evidence is the major awaited development in the third phase.
  footer_text:
    unique: PMC2555965/PMC2555965.xml::T4-0

PMC0025XXXXX/PMC2555970.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Strains Used in This Study
  footer_text:
    unique: PMC2555970/PMC2555970.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2555970.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2555970.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556036.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556036.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556039.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Primers Used in This Study
  footer_text:
    unique: PMC2555970/PMC2555970.xml::T2-0

PMC0025XXXXX/PMC2555987.xml

PMC0025XXXXX/PMC2556036.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Unrelated Donor (URD) Searches for African-Americans with Hematologic Malignancies
  footer_text:
    unique: PMC2556036/PMC2556036.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Preliminary Cord Blood Unit Searches for African-Americans with Hematologic Malignancies
  footer_text:
    unique: PMC2556036/PMC2556036.xml::T2-0

PMC0025XXXXX/PMC2556039.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characterization of splenic erythroblast maturation after Phenylhydrazine induced anemia and Erythropoietin treatment
  footer_text: All data are Mean ± SEM. * indicates P<0.05 by post hoc testing for comparison of treatment groups with respective baseline by one way ANOVA. The experimental n for baseline, post EPO and post PHZ, are: (WT)-11, 4 and 5, (Nix-/-)- 8, 4 and 5.
    unique: PMC2556039/PMC2556039.xml::T1-0

PMC0025XXXXX/PMC2556073.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Analysis of SMN RNA expression The relative ratio of newborn to adult SMN RNA was determined using Multi Gauge (Fugi Film). Each sample was subtracted from background and normalized against β-actin. Error bars reflect the standard deviation. Four independent amplifications of porcine adult and newborn tissues were used in these studies
  footer_text:
    unique: PMC2556073/PMC2556073.xml::T1-0

PMC0025XXXXX/PMC2556079.xml

PMC0025XXXXX/PMC2556081.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Simulation results with a constant hazard: n is the number of individuals, θ the frailty variance, m the number of individuals with at least one event, T̄ the mean follow-up time, N(T)‒ and median(N(T)) are the mean and median numbers of events for subjects with at least one event; E(U) and V(U) are the sample mean and variance of U for subjects with at least one event, with true values 0 and 1/12=0.083, respectively. In the last two columns the power of the test (5) and (6) at 5% level is given.
  footer_text:
    unique: PMC2556081/PMC2556081.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Simulation results with a decreasing hazard: n is the number of individuals, θ the frailty variance, m the number of individuals with at least one event, T̄ the mean follow-up time, N(T)‒ and median(N(T)) are the mean and median numbers of events for subjects with at least one event; E(U) and V(U) are the sample mean and variance of Ui, respectively, for subjects with at least one event. In the last two columns the power of the test (5) and (6) at 5% level is given.
  footer_text:
    unique: PMC2556081/PMC2556081.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Simulation results with an increasing hazard: n is the number of individuals, θ the frailty variance, m the number of individuals with at least one event, T̄ the mean follow-up time, N(T)‒ and median(N(T)) are the mean and median numbers of events for subjects with at least one event; E(U) and V(U) are the sample mean and variance of U, respectively for subjects with at least one event. In the last two columns the power of the test (5) and (6) at 5% level is given.
  footer_text:
    unique: PMC2556081/PMC2556081.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556081.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556081.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556081.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556081.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556081.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Results from the TTT method applied to the Swiss clinical study. The number of patients included in the study (n), the number of patients with at least one additional admission during follow-up (m), the average follow-up time in years, the mean and median number of events for the m patients with at least one event during follow-up. The sample mean and variance of Ui and the p-value for testing (5) and (6).
  footer_text:
    unique: PMC2556081/PMC2556081.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Results from the TTT method applied to Danish registry data 1994-1999. The number of patients included in the study (n), the number of patients with at least one additional admission during follow-up (m), the mean follow-up time in years (T̄), the mean and median numbers of events for the m patients with at least one event during follow-up. The sample mean and variance of Ui and the p-values for testing (5) and (6).
  footer_text:
    unique: PMC2556081/PMC2556081.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Results from a gap-time Γ frailty model stratified by sex, fitted to Danish registry data 1994-1999, further corrected for: calendar time, age at first admission, and polarity. Only patients with at least one additional admission after first discharge are included.
  footer_text:
    unique: PMC2556081/PMC2556081.xml::T6-0

PMC0025XXXXX/PMC2556153.xml

PMC0025XXXXX/PMC2556171.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of Peptide Modifications Found in 65 High Abundant Glycoproteins in Plasmaa
  footer_text: a FETUA_BOVIN was spiked in all samples. Bold-marked amino acids indicate the modification site. When a high number of modified peptides were found, only the total number of modified peptides is listed.
    unique: PMC2556171/PMC2556171.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary of Modifications Found in SiHa (Cervical Cancer) Cell Line and Comparison of Selected Modifications Found in the SiHa Cell Line Using an Unrestricted and Targeted Searcha
  footer_text: a Bold-marked amino acids indicate the modification site. b Spectra with XCorr values greater than 1.9, 2.2, and 3.8 for 1+, 2+, and 3+, respectively, were considered to be correct hits. All peptides found in the unrestricted search could be verified by the targeted search. See text for details.
    unique: PMC2556171/PMC2556171.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556081.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556171.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556171.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556171.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Validation of the Unrestricted Search Algorithm for Peptide Pairs in Homologous Proteins in the SiHa Cell Linea
  footer_text: a Bold-marked amino acids indicate the modification site. b Modification was detected (Y) or not detected (N) in unrestricted search. See text for more details.
    unique: PMC2556171/PMC2556171.xml::T3-0

PMC0025XXXXX/PMC2556173.xml

PMC0025XXXXX/PMC2556205.xml

PMC0025XXXXX/PMC2556206.xml

PMC0025XXXXX/PMC2556218.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Expression of daf-1 in Interneurons Is Sufficient to Rescue the Dauer Formation, Feeding Rate, and Fat Storage Phenotypes of daf-1(m40) Mutants daf-1::gfp was expressed under various promoters in daf-1(m40) mutants. Larval dauer formation, adult feeding rate and fat content were measured in each of the transgenic lines. Indicated results were consistent for at least three independent transgenic lines. Promoters used to drive daf-1::gfp are grouped based on anatomical expressions.
  footer_text: a % animals that entered dauer when placed on food plates as L1s at 25°C. Phenotypic example shown in Figure S1 b Average pumping rate of well-fed, young gravid adults. Standard deviations are shown. c Young, well-fed wild-type animals retained ~10 eggs on average. This phenotype is denoted as (+). Mutants such as daf-1(m40) retained excess eggs (~24), denoted as (+++). Intermediate egg retention is denoted as (++). Phenotypic examples are shown in Figure S1. d Expression of daf-1(+) by these promoters reduced the excess fat of daf-1(m40) to wild-type levels. Phenotypic examples shown in Figure 1B. e Statistically significant (p <0.001, determined by ANOVA with Bonferroni post-test) increases in feeding rate relative to daf-1(m40).
    unique: PMC2556218/PMC2556218.xml::T1-0

PMC0025XXXXX/PMC2556220.xml

PMC0025XXXXX/PMC2556223.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Hit identification through primary HTS and counterscreening
  footer_text: a structures of compounds lacking activity in counter-screening are not shown b values represent averages of two experiments ± range; highest concentration assessed 37.5 μM c values represent averages of two experiments ± range; highest concentration assessed 150 μM; ND: not determined d values represent averages of four experiments ± SD; highest concentration assessed 37.5 μM e CC50 not determined (ND) when EC50 >5 μM f CC50 not determined (ND) due to insufficient amount of compound available
    unique: PMC2556223/PMC2556223.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556218.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Assessment of accuracy of primary hit identification
  footer_text: a unmarked compounds represent the group-defining confirmed hit; (*) bona-fide hits (primary HTS score >1.9, passed visual inspection); (#) excluded (primary HTS score >1.9, excluded at visual inspection); (&) negatives (primary HTS score < 1.9); shading highlights compounds found to be “false negatives” b based on chemical structures c values represent averages of two experiments ± range; highest concentration assessed 37.5 μM d values represent averages of four experiments ± SD; highest concentration assessed 37.5 μM
    unique: PMC2556223/PMC2556223.xml::T2-0
    unique: PMC2556223/PMC2556223.xml::T2-1
    unique: PMC2556223/PMC2556223.xml::T2-2
    unique: PMC2556223/PMC2556223.xml::T2-3
    unique: PMC2556223/PMC2556223.xml::T2-4
    unique: PMC2556223/PMC2556223.xml::T2-5

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T2-1'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T2-2'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T2-3'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T2-4'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T2-5'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T2-6'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T2-7'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

    unique: PMC2556223/PMC2556223.xml::T2-6
    unique: PMC2556223/PMC2556223.xml::T2-7
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Assessment of cross-resistance with known MV inhibitors
  footer_text: a shading highlights compound identified in pre-screening as fusion inhibitor candidates b MV-Alaska variant adapted to grow in the presence of MV RdRp inhibitor AS-136A (Sun et al. 2007; White et al. 2007); values represent averages of two experiments ± range; highest concentration assessed 37.5 μM c MV-Ibd, naturally resistant to MV fusion inhibitor AS-48 (Plemper et al. 2004) values represent averages of two experiments ± range; highest concentration assessed 37.5 μM; only compounds identified as fusion inhibitor candidates were tested against MV-Ibd (ND: not determined) d for comparison, EC50 values against MV-Alaska (table 1) are shown
    unique: PMC2556223/PMC2556223.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Three distinct patterns of target specificity
  footer_text: a values represent averages of two experiments ± range; highest concentration assessed 37.5 μM b values represent averages of four experiments ± SD; highest concentration assessed 37.5 μM
    unique: PMC2556223/PMC2556223.xml::T4-0

PMC0025XXXXX/PMC2556234.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556223.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556234.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556243.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Effect of tyrosine phosphatases inhibitors on PTP1B activity from membrane fraction of HCE cells HCE cells were incubated with the inhibitor at the concentrations indicated for 30 min (bpV(phen), PAO, or SOV) or 60 min (CinnGEL 2Me). One µg of protein from the membrane fraction was used to determine the PTP1B activity as explained in Methods. The percentage of inhibition was calculated with respect to control without inhibitors. Values correspond to average of 12 samples ± SD of three different experiments.
  footer_text:
    unique: PMC2556234/PMC2556234.xml::T1-0

PMC0025XXXXX/PMC2556243.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Multivariate ANOVA results for relations between marijuana use frequency and social anxiety, marijuana-related problems, marijuana effect expectancies.
  footer_text: Note. Marijuana effect expectancies were measured using the Marijuana Effect Expectancy Questionnaire (MEEQ) (Aarons et al., 2001), social anxiety with the Social Interaction Anxiety Scale (Mattick & Clarke, 1998), and marijuana problems with the Marijuana Problems Scale (Stephens et al., 2000). Marijuana use frequency grouping: nonusers (those who never used marijuana; n = 105), infrequent users (less than weekly marijuana use; n = 122), and frequent users (weekly or more marijuana use; n = 109). a Means not significantly different from one another (p < .01). * p < .05 ** p < .01 *** p < .001.
    unique: PMC2556243/PMC2556243.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Multivariate ANOVA results for marijuana effect expectancies among current users (n = 150).
  footer_text: Note. Marijuana effect expectancies were measured using the Marijuana Effect Expectancy Questionnaire (Aarons et al., 2001), social anxiety with the Social Interaction Anxiety Scale (Mattick & Clarke, 1998). * p < .05 ** p < .01 *** p < .001.
    unique: PMC2556243/PMC2556243.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Logistic Regressions for Marijuana Use versus Nonuse.
  footer_text: Note. Marijuana effect expectancies were measured using the Marijuana Effect Expectancy Questionnaire (Aarons et al., 2001), social anxiety with the Social Interaction Anxiety Scale (Mattick & Clarke, 1998). * p < .05.
    unique: PMC2556243/PMC2556243.xml::T3-0

PMC0025XXXXX/PMC2556245.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556243.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556243.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556245.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556246.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table
  caption_text: Mean weight, energy density, energy content, and macronutrient content of the liquid and solid meal replacement products consumed by older adults in a study of postprandial appetite ratings
  footer_text: a Ingredients (from highest to lowest content in the liquid meal replacement product; quantities not provided on the manufacturer's label): water, sugar, corn syrup, maltodextrin (corn), calcium caseinate, high-oleic safflower oil, canola oil, soy protein isolate, whey protein concentrate, and corn oil (also 32 vitamins and mineral compounds). b Ingredients (from highest to lowest content in the solid meal replacement product; quantities not provided on the manufacturer's label): yogurt coating, high-fructose corn syrup, soy protein isolate, raisins, honey, crisp rice, toasted rolled oats, fructose, maltodextrin, fructooligosaccharides, whey protein concentrate, glycerone, guar gum, calcium caseinate, high-oleic sunflower oil, high-oleic safflower oil (also 26 vitamins and mineral compounds). c Data expressed as mean±standard error of the mean.
    unique: PMC2556245/PMC2556245.xml::T1-0

PMC0025XXXXX/PMC2556246.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Transferred EAE signs in wild type, ICAM-1 × C3−/− and C3−/− mice.
  footer_text: A Cumulative Disease Index is the mean of the sum of daily clinical scores observed between days 7 and 30. B Disease onset is defined as the first day of two consecutive days with a clinical score of two or more. C Disease incidence is defined as the percent of mice that displayed any clinical signs of disease. D EAE was significantly different between all three groups of mice as determined by one-way ANOVA (p<0.0001) and by Newman-Keuls multiple comparisons test: WT vs. ICAM-1 × C3−/− (p<0.01), WT vs. C3−/− (p<0.001) and ICAM-1 × C3−/− vs. C3−/− (p=0.05).
    unique: PMC2556246/PMC2556246.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Cytokine production by CD4 and CD8 T cells derived from spinal cords of wild type, ICAM-1 × C3−/− and C3−/− mice during EAE.
  footer_text: A Mean percent cytokine positive cells derived from mice at day 15 post-immunization. Cells were pooled from at least 2 mice per group from 2 independent experiments.
    unique: PMC2556246/PMC2556246.xml::T2-0

PMC0025XXXXX/PMC2556260.xml

PMC0025XXXXX/PMC2556278.xml

PMC0025XXXXX/PMC2556279.xml

PMC0025XXXXX/PMC2556280.xml

PMC0025XXXXX/PMC2556284.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556246.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556288.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556288.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2556288.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Experimentally measured local and global movements associated with the transition from the ground state to the activated state of rhodopsin.
  footer_text:
    unique: PMC2556288/PMC2556288.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Waiting times for the LUMI – META II transition for wild type rhodopsin and mutants. Waiting times tf and tb are for the completion of the forward and backward transitions, respectively. Means and standard errors were estimated from five simulations. As a rough approximation for the equilibrium population shift, we calculate the ratio of waiting times, K=tb/tf, which provides an estimate of the relative stability of the META II state over the LUMI state.
  footer_text:
    unique: PMC2556288/PMC2556288.xml::T2-0

PMC0025XXXXX/PMC2556289.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Means (and standard deviations) of predictor and cognitive functioning variables by cocaine exposure and gender
  footer_text: Note. BDI = Beck Depression Inventory; FCS = Family Chaos Scale; HOME = Home Observation for Measurement of the Environment; SEI = Social Environment Inventory; TANF = Temporary Assistance for Needy Families. Note. Neonatal medical problems, alcohol exposure, cigarette exposure, and marijuana exposure variables were each log transformed to correct for skew in all subsequent analyses. Note. Means with different superscripts indicate significant between group differences at p <.05. # p ≤ .10. * p ≤ .05. ** p ≤ .01. *** p ≤ .001.
    unique: PMC2556289/PMC2556289.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556289.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556289.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556289.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Pearson correlations among predictor and cognitive functioning variables (below diagonal = boys; above diagonal = girls)
  footer_text: Note. Cocaine exposure was entered as a dichotomous variable (0 = no exposure; 1 = exposed). # p ≤ .10. * p ≤ .05. ** p ≤ .01. *** p ≤ .001.
    unique: PMC2556289/PMC2556289.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Coefficients (and standard error; followed by 95% confidence intervals) from mixed model analyses predicting Stanford-Binet IV IQ and subscales
  footer_text: Note. Cocaine exposure was entered as a dichotomous variable (0 = no exposure; 1 = exposed). Age was coded such that 4-years is the referent to which the other ages are compared. # p ≤ .10. * p ≤ .05. ** p ≤ .01. *** p ≤ .001. (2-tailed).
    unique: PMC2556289/PMC2556289.xml::T3-0

PMC0025XXXXX/PMC2556292.xml

PMC0025XXXXX/PMC2556299.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Descriptive and Zero-Order Relations among Theoretically Relevant Variables
  footer_text: † Note: p < .05 * p < .01 ** p < .001. NA = Negative Affect subscale of PANAS; AS = ASI total; Cigs = Cigarettes smoked per day; DI = DIS total; PA = Panic Attack status during first hyperventilation challenge (yes/no); DT = Distress Tolerance during second hyperventilation challenge (i.e. time in minutes of voluntary hyperventilation)
    unique: PMC2556299/PMC2556299.xml::T1-0

PMC0025XXXXX/PMC2556306.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Nucleotide percentage identity cut-off values defining genotypes for 11 rotavirus gene segments.
  footer_text:
    unique: PMC2556306/PMC2556306.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Application of the proposed classification and nomenclature to the structural and non-structural protein encoding genes for known human, bovine, porcine, simian, avian, equine, lapine, murine and ovine rotavirus strains. Green, red, and orange were used for Wa-like, DS-1-like and AU-like gene segments, respectively, while yellow, blue, and purple were used for the avian PO-13-like rotavirus gene segments, some typical porcine VP4, VP7, and VP6 genotypes, and the SA-11-like gene segments, respectively. It should be noted that the genotypes of more than 60% of the isolates in this table are partial, requiring additional work.
  footer_text:
    unique: PMC2556306/PMC2556306.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556299.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556306.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556306.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Current members of the RCWG
  footer_text:
    unique: PMC2556306/PMC2556306.xml::T3-0

PMC0025XXXXX/PMC2556357.xml

PMC0025XXXXX/PMC2556377.xml

PMC0025XXXXX/PMC2556461.xml

PMC0025XXXXX/PMC2556506.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Town/Gown Education/Communication Activity Summary for the DOVE study.
  footer_text:
    unique: PMC2556506/PMC2556506.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Number and Percent of Home Visitor Personal Experience with Abuse.
  footer_text: * NOTE: Questionnaires with missing data on abuse items were excluded from some analysis
    unique: PMC2556506/PMC2556506.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556306.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556506.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556506.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556506.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Descriptive Information from the Home Visitors Completing the Survey.
  footer_text:
    unique: PMC2556506/PMC2556506.xml::T3-0

PMC0025XXXXX/PMC2556508.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: K-ras mutations in tumors from L2G7 and 5G8 treated mice.
  footer_text:
    unique: PMC2556508/PMC2556508.xml::T1-0

PMC0025XXXXX/PMC2556512.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Rotational and Translational Accuracy of Electromagnetic and Optoelectric Systems. Data are reported as (actual value − calculated value)
  footer_text:
    unique: PMC2556512/PMC2556512.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Bland-Altman test values for precision measurements. All measured differences were less than the measured accuracy of the systems.
  footer_text:
    unique: PMC2556512/PMC2556512.xml::T2-0

PMC0025XXXXX/PMC2556516.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556508.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556512.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556512.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556516.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Primary Antibody/Toxin Information
  footer_text: 1 mab: monoclonal 2 Sigma-Aldrich Co., St. Louis, Mo. 3 Molecular Probes-Invitrogen, Carlsbad, Ca. 4 Phosphosolutions, Aurora, Co. 5 Developmental Studies Hybridoma Bank. The 3A10 monoclonal antibody developed by Drs. T. Jessell and J. Dodd was obtained from the Developmental Studies Hybridoma Bank developed under the auspices of the NICHD and maintained by The University of Iowa, Department of Biological Sciences, Iowa City, IA 52242.
    unique: PMC2556516/PMC2556516.xml::T1-0

PMC0025XXXXX/PMC2556547.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Relapse Between Maximum Expansion (T3) and End of Treatment (T5)
  footer_text: The variation of N is explained by the fact that some patients had extraction of teeth so the number of measurements is reduce for those teeth.
    unique: PMC2556547/PMC2556547.xml::T1-0

PMC0025XXXXX/PMC2556550.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of UV-Melting Temperatures of Duplexes Containing 5 or MedC
  footer_text:
    unique: PMC2556550/PMC2556550.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556547.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556550.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556550.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556550.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556550.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556562.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Effect of Flanking Sequence Mismatches on ICL Formation from 5
  footer_text:
    unique: PMC2556550/PMC2556550.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: UV-Melting Temperatures of Triplexes
  footer_text:
    unique: PMC2556550/PMC2556550.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Interstrand Cross-Link (ISC) Yields from 1 and 5 in Triple Helical DNA
  footer_text: a % Yields are the average of at least two independent experiments. b NFT = no further treatment after reaction with NaIO4. c 90 °C for 20 min at pH 7.2. d 1.0 M Piperidine, 90 °C, 20 min.
    unique: PMC2556550/PMC2556550.xml::T4-0

PMC0025XXXXX/PMC2556562.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Responses to Tone
  footer_text: Values are means (± se), computed over 50 dB range above tone threshold. * = statistically significant difference (p = 0.05 or less); ns = not significant
    unique: PMC2556562/PMC2556562.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Responses to Noise
  footer_text: Values are means (± se), computed over 50 dB range above tone threshold. * = statistically significant difference (p = 0.05 or less); ns = not significant
    unique: PMC2556562/PMC2556562.xml::T2-0

PMC0025XXXXX/PMC2556566.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556562.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556566.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556596.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556596.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Effect of inhibitors on HO activity.
  footer_text: Mean HO activity (nmol CO/mg protein/h ± SEM, n = 5-31/condition) in cultures subjected to medium exchange (sham-wash, SW) only or treated for 30 minutes with indicated concentrations of TBB, DMAT, DRB, GF109203X, LY294002 and Wortmannin.
    unique: PMC2556566/PMC2556566.xml::T1-0

PMC0025XXXXX/PMC2556571.xml

PMC0025XXXXX/PMC2556596.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Characteristics of 150 Adolescents Aged 11 to 21 yr Evaluated for a Sexually Transmitted Infection (STI) at an Academic Ambulatory Care Facility
  footer_text: * Sexually transmitted infection. † Female greater than male; P value <0.01.
    unique: PMC2556596/PMC2556596.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Predictors of HIV Testing Among 150 Adolescents Aged 11 to 21 yr Evaluated For an STI At an Academic Ambulatory Care Facility, Baltimore, July 2003 to June 2004
  footer_text: * Adjusted for age, gender and insurance status. † P <0.05.
    unique: PMC2556596/PMC2556596.xml::T2-0

PMC0025XXXXX/PMC2556598.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Generation of ALS2−/− mice
  footer_text: NA = No information available.
    unique: PMC2556598/PMC2556598.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556598.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556598.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556598.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556855.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Behavioral phenotypes of ALS2−/− mice
  footer_text: NS = Not statistically significant; NA = data not available. 1 May relate to higher anxiety-induced reduction of exploratory activity.
    unique: PMC2556598/PMC2556598.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Pathological abnormalities of ALS2−/− mice
  footer_text: CSMN = Corticospinal motor neurons; CST = corticospinal track; SMN = spinal motor neuron; VR = ventral root. 1 Small caliber axons. 2 Calbindin-positive.
    unique: PMC2556598/PMC2556598.xml::T3-0

PMC0025XXXXX/PMC2556850.xml

PMC0025XXXXX/PMC2556855.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: The frequencies, bandwidths and isotope shifts of extracted resonance Raman bands of substrate-bound P450cam and its isotopicaly substituted analogues.
  footer_text: a Normal mode calculations for NiOEP, including all seven atoms for each ethyl group (C2h or S4 molecular symmetry),14,37 indicate the possibility for several modes between 350 and 450 cm−1, designated as δ(CβC1C2) or γ2 (A1u), whose d4 and d16 shifts are reasonably consistent with those observed here.
    unique: PMC2556855/PMC2556855.xml::T1-0

PMC0025XXXXX/PMC2556856.xml

PMC0025XXXXX/PMC2556858.xml

PMC0025XXXXX/PMC2556862.xml

PMC0025XXXXX/PMC2556863.xml

PMC0025XXXXX/PMC2556865.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of MCP participants in in-depth interviews (N=18)
  footer_text:
    unique: PMC2556865/PMC2556865.xml::T1-0

PMC0025XXXXX/PMC2556878.xml

PMC0025XXXXX/PMC2556881.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Dimensions of Channels and Other Microfeatures in the Original Design, the Brass Mold, and the Embossed Plastic Microfluidic Devices
  footer_text:
    unique: PMC2556881/PMC2556881.xml::T1-0

PMC0025XXXXX/PMC2556882.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556865.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556881.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556882.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Kappa Coefficients for Strategy Categories
  footer_text: Note. PF = problem-focused strategy; EF = emotion-focused strategy. * Strategies included in this category were not included in analyses of strategy type. 1 Based on 20% of the data. 2 Based on an additional 6 cases.
    unique: PMC2556882/PMC2556882.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Strategy Measures by Interpersonal and Instrumental Problem Domain: Mean, SD, Range
  footer_text: Note. PF= problem-focused strategy; EF = emotion-focused strategy. * Indicates strategy type excluded in analyses. 1 The mean proportion score for this strategy was .07 for older interacting pairs thus, it was included in the analysis of strategy type. 2 The mean proportion scores for younger nominal pairs was .07 and for interacting pairs was .09, thus, this strategy was included in the analysis of strategy type.
    unique: PMC2556882/PMC2556882.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Age Differences in Strategy Measures for Interpersonal Problems: Mean, SD, and F Statistics
  footer_text: Note. PF= problem-focused strategy; EF = emotion-focused strategy. * p < .05 ** p < .01 *** p < .001.
    unique: PMC2556882/PMC2556882.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556882.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556882.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556882.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556882.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556882.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Age Differences in Strategy Measures for Instrumental Problems: Mean, SD, and F Statistics
  footer_text: Note. PF=problem-focused strategy; EF=emotion-focused strategy. * p < .05 ** p < .01 *** p < .001.
    unique: PMC2556882/PMC2556882.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Percent Selecting Strategy as Most Effective by Age Group: Interpersonal Problems
  footer_text: Note. PF=problem-focused strategy; EF=emotion-focused strategy. Number of cases = 224 (38 interacting pairs each age group; 74 individuals each age group). * indicates z ≥ 1.96, p ≤ .05
    unique: PMC2556882/PMC2556882.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Percent Selecting Strategy as Most Effective by Age Group: Instrumental Problems
  footer_text: Note. PF= problem-focused strategy; EF = emotion-focused strategy. Number of cases = 224 (38 interacting pairs each age group; 74 individuals each age group). * indicates z ≥ 1.96, p ≤ .05
    unique: PMC2556882/PMC2556882.xml::T6-0

PMC0025XXXXX/PMC2556883.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean hit rates (with standard errors) as a function of source, frequency, and age.
  footer_text:
    unique: PMC2556883/PMC2556883.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556883.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556883.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556883.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556883.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556886.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mean non-zero imagination-frequency and performance-frequency responses (with standard errors) for imagined-only actions as a function of age and frequency of imagination.
  footer_text:
    unique: PMC2556883/PMC2556883.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean proportion of judged-imagined items that were also judged performed as a function of frequency and age (standard errors in parentheses)
  footer_text:
    unique: PMC2556883/PMC2556883.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Mean non-zero performance-frequency and imagination-frequency responses (with standard errors) for performed-only actions as a function of age and frequency of performance.
  footer_text:
    unique: PMC2556883/PMC2556883.xml::T4-0

PMC0025XXXXX/PMC2556884.xml

PMC0025XXXXX/PMC2556886.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Robustness of the model-free spectral density
  footer_text: a From Eq. (13) b Diffusion in a three identical well cosine potential with 1 kcal/mol barriers. c Torsion refers to the number of rotatable bonds before the methyl. d Stochastic jump model. Ratios in the model column refer to the expected equilibrium g-, g+, t rotamer population ratios calculated from the jump probabilities. e Motional asymmetry is defined through Eq. (17), as the difference between Oaxis2 calculated without and with assumption of azimuthal symmetry.
    unique: PMC2556886/PMC2556886.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Average values of structural correlates and their correlation with Oaxis2a
  footer_text: a Average values with standard deviation for several simple structural properties for the methyl groups of CaM. Difference represents the average pair-wise difference between the two properties. R2 represents the correlation of Oaxis2 at a site with the structural property at that site.
    unique: PMC2556886/PMC2556886.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556886.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556888.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556888.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556888.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556888.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2556888.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Means and Standard Deviations for Participant Characteristics
  footer_text: ** Matrix Reasoning, Ravens Advanced Progressive Matrices, and Operation Span scores were significantly different between the older and younger adults (p < .01), and were negatively correlated with age between ages 60-95. There were no other significant age differences.
    unique: PMC2556888/PMC2556888.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: ANOVA Results from the Complete Release-from-PI Operation Span Task
  footer_text:
    unique: PMC2556888/PMC2556888.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text:
  footer_text: * p < .05; ** p < .01
    unique: PMC2556888/PMC2556888.xml::T3-0
  ----------------------------------------
  id: T4
  label_text:
  caption_text: Stimuli from the Release-from-PI Operation Span
  footer_text:
    unique: PMC2556888/PMC2556888.xml::T4-0

PMC0025XXXXX/PMC2556890.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Xenograft tumor treatment groups.
  footer_text: * harvested at early time points (tumor size 200–400 mm3) ** harvested at later time points (tumor size ~1000 mm3)
    unique: PMC2556890/PMC2556890.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Gene sets associated with endocrine therapy resistance in MCF7 xenograft mouse models.
  footer_text:
    unique: PMC2556890/PMC2556890.xml::T2-0

PMC0025XXXXX/PMC2556891.xml

PMC0025XXXXX/PMC2556893.xml

PMC0025XXXXX/PMC2556897.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556890.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556890.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Zero-Order Correlations between Selected Independent Variables
  footer_text: Note. AEMaxPosAr, AEMaxSed = AEMax: Positive Arousing factor, Sedating factor, respectively; AEQGloPos, AEQSoc = AEQ: Global Positive Changes scale, Social scale, respectively; TotalDr ln = Total number of standard drinks over the past 30 days, log-transformed; DrinkOcc ln = Number of drinking occasions over the past 30 days, log-transformed; AveQuant ln = Average number of standard drinks per drinking occasion, log-transformed; HighestDr ln = Highest number of standard drinks per drinking occasion, log-transformed. * p < .05 ** p < .01 *** p < .001
    unique: PMC2556897/PMC2556897.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Zero-Order Correlations between Selected Independent Variables and TF2/SF2 (P300) scores
  footer_text: Note. P300*Neg, P300*Pos = TF2/SF2 factor scores in response to Alcohol/Negative-Sedating and Alcohol/Positive-Arousing conditions, respectively; AEMaxPosAr, AEMaxSed = AEMax: Positive Arousing factor, Sedating factor, respectively; AEQGloPos, AEQSoc = AEQ: Global Positive Changes scale, Social scale, respectively; TotalDr ln = Total number of standard drinks over the past 30 days, log-transformed; DrinkOcc ln = Number of drinking occasions over the past 30 days, log-transformed; AveQuant ln = Average number of standard drinks per drinking occasion, log-transformed; HighestDr ln = Highest number of standard drinks per drinking occasion, log-transformed. * p < .05 ** p < .01 *** p < .001
    unique: PMC2556897/PMC2556897.xml::T2-0
  ----------------------------------------
  id: T3
  label_text:
  caption_text:
  footer_text:
    unique: PMC2556897/PMC2556897.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556897.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556897.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556897.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2556898.xml

PMC0025XXXXX/PMC2556899.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Thermodynamic parameters for the interactions of the compounds in Figure 1 binding to nonalternating and alternating sequences at different lengths.
  footer_text: a Kmean values are from SPR experiments as described in Materials and methods and ΔG is obtained from the equation: ΔG = −RTlnKmean. b ΔH binding values are from ITC as described in Materials and methods Experimental error limits for SPR K values and ITC ΔH values are both approximately ±10%.
    unique: PMC2556899/PMC2556899.xml::T1-0

PMC0025XXXXX/PMC2556901.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: List of 37 deficits used in the analyses
  footer_text:
    unique: PMC2556901/PMC2556901.xml::T1-0

PMC0025XXXXX/PMC2556956.xml

PMC0025XXXXX/PMC2556977.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Characteristics and body composition of the study participants1
  footer_text: 1 All values are x̄ ± SEM. Significance of differences between groups was evaluated by using the Student’s t test for independent samples. IHTG, intrahepatic triglyceride; NAFLD, nonalcoholic fatty liver disease. 2 Data represent values obtained from 9 of the 10 subjects who had NAFLD, because technical problems precluded obtaining images of abdominal fat in 1 subject. 3 Significantly different from overweight subjects with normal IHTG content, P < 0.01. 4 Significantly different from overweight subjects with normal IHTG content, P < 0.001.
    unique: PMC2556977/PMC2556977.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Basic metabolic characteristics of the study participants1
  footer_text: 1 All values are x̄ ± 3 SEM. Significance of differences between groups was evaluated by using the Student’s t test for independent samples. IHTG, intrahepatic triglyceride; NAFLD, nonalcoholic fatty liver disease. 2–4 Significantly different from overweight subjects with normal IHTG content: 2 P < 0.05, 3 P < 0.001, 4 P < 0.01.
    unique: PMC2556977/PMC2556977.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556899.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556901.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556977.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556977.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2556978.xml

PMC0025XXXXX/PMC2556981.xml

PMC0025XXXXX/PMC2556983.xml

PMC0025XXXXX/PMC2556985.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Means and Standard Errors for the Study Variables
  footer_text:
    unique: PMC2556985/PMC2556985.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Percentage Perceiving Incident at Least Once in Past Year
  footer_text:
    unique: PMC2556985/PMC2556985.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Percentage Perceiving Incident at Least Once in Past Year
  footer_text:
    unique: PMC2556985/PMC2556985.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Perceived Discrimination as a Predictor of Depressive Symptoms
  footer_text: * p < .02, ** p < .01.
    unique: PMC2556985/PMC2556985.xml::T4-0
  ----------------------------------------
  id: T5

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556985.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556985.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556985.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556985.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556985.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556985.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556986.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  label_text: Table 5
  caption_text: Perceived Discrimination as a Predictor for Self-esteem
  footer_text: * p < .02, ** p < .01.
    unique: PMC2556985/PMC2556985.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Discrimination as a Predictor for Life Satisfaction
  footer_text: * p < .02, ** p < .01.
    unique: PMC2556985/PMC2556985.xml::T6-0

PMC0025XXXXX/PMC2556986.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Behavioral risks during Senior Year in High School, and Fall and Spring Semesters of Freshman Year
  footer_text: Notes. All variables were assessed over the 3 months prior to the assessment. Drinking variables and number of sexual partners were measured continuously. All other behavioral risks were measured on the following seven-point scale (0 = 0; 1 = 1; 2 = 2; 3 = 3−5; 4 = 6−10; 5 = 11−20; 6 = 21 or more). Means (SD) for multiple sexual partners represent values for students reporting two or more partners in the past 3 months. Means (SD) for all other behavioral risks represent values for those who report any participation in the behavior.
    unique: PMC2556986/PMC2556986.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Main Effects of HLM Model for Alcohol Use
  footer_text: Note. Coefficients for all residence groups represent contrasts relative to campus dorms, and coefficients for area of residence represent contrasts relative to individuals from suburban high schools. Family structure was coded 0 for two-parent households and 1 for households without two resident parents such that positive coefficients reflect increased risk in households without two resident parents.
    unique: PMC2556986/PMC2556986.xml::T2-0

PMC0025XXXXX/PMC2556987.xml

PMC0025XXXXX/PMC2556989.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Lyn kinase activity in various tumor cells
  footer_text: NOTE: Cell lysates (200 μg) were assayed for Lyn kinase activity by in vitro kinase assay.
    unique: PMC2556989/PMC2556989.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556986.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556989.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556990.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2556990.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557022.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2556990.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Description of the physical components of each context.
  footer_text: * Walls were modified using paper to cover the clear Plexiglas. + Floors were modified using an insert that was placed over the existing stainless steel bar floor.
    unique: PMC2556990/PMC2556990.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Assignment of training, extinction, and renewal test contexts for subjects in Experiment 2a and 2b.
  footer_text:
    unique: PMC2556990/PMC2556990.xml::T2-0

PMC0025XXXXX/PMC2557022.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Risk factors, demographics, and clinical characteristics, 2000-2006, Nueces County, Texas.
  footer_text: * Current Smoker 4 missing values Dicharge GCS, 3 missing values Insurance Status, 1 missing value Discharge Rankin, 2 missing values Length of Stay, 2 missing Time to Presentation, 5 missing values MA=Mexican American, NHW=non-Hispanic white, GCS=Glasgow Coma Scale, IQR=Interquartile range
    unique: PMC2557022/PMC2557022.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Seven year cumulative incidence and cumulative incidence risk ratios by age, ethnicity and gender, 2000-2006, Nueces County, Texas.
  footer_text: * Test of Homogeneity Across Age Strata, p-value = 0.91 ** Test of Homogeneity Across Age Strata, p=0.08 NHW=non-Hispanic white, MA=Mexican American
    unique: PMC2557022/PMC2557022.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Age and gender-specific seven-year cumulative incidence and risk ratios, 2000-2006, Nueces County, Texas.
  footer_text:
    unique: PMC2557022/PMC2557022.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Poisson regression model, adjusted for age, ethnicity and gender, of seven-year cumulative incidence, 2000-2006, Nueces County, Texas.
  footer_text: NHW=non-Hispanic white, MA=Mexican American
    unique: PMC2557022/PMC2557022.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557022.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557022.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557022.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557024.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557024.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2557024.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Training methods, indications for use, suggestions for competency assessment, and examples from research program
  footer_text:
    unique: PMC2557024/PMC2557024.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Evidence-based research team training plan (basic research topics )
  footer_text:
    unique: PMC2557024/PMC2557024.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Evidence based research team training plan (supplemental topics)
  footer_text: Keys: SD-self directed, I-independent, GD-group didactic, GI-group interactive, SB-simulation based, SV-supervisory iteration, TT-two tiered sign off GT-graded test, SM-seminar, CX-cross training, RA-research assistant
    unique: PMC2557024/PMC2557024.xml::T3-0

PMC0025XXXXX/PMC2557442.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: en-driven mCD8::GFP expression in antennal lobe glomeruli. Fluorescent glomeruli and their corresponding olfactory receptors are indicated in bold.
  footer_text:
    unique: PMC2557442/PMC2557442.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557024.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557442.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557553.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2557553.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Values of the parameters used in the creation of synthetic luteinizing hormone concentration-time series.
  footer_text:
    unique: PMC2557553/PMC2557553.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mean (± SEM) number of peaks known to be present in the synthetic luteinizing hormone concentration time series and the number recovered by analysis with AutoDecon and Cluster. For each group studied (i.e., early follicular, late follicular, mid-luteal and post-menopausal), values identified with different superscripts differ significantly (p < 0.001) by analysis of variance with Duncan’s Multiple Range test.
  footer_text:
    unique: PMC2557553/PMC2557553.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Performance characteristics of AutoDecon and Cluster based upon synthetic data which mimics normal human subjects at different phases of the menstrual cycle.
  footer_text:
    unique: PMC2557553/PMC2557553.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Mean (± SEM) LH burst mass, burst half-duration and luteinizing hormone (LH) half-life characterizing the synthetic data series and recovered by application of AutoDecon to the synthetic data series. In each case, and for all groups (i.e. early follicular, late follicular, mid-luteal and post-menopausal) AutoDecon returned values that are statistically indistinguishable from the values known to characterize the synthetic data series (p> 0.05).
  footer_text:
    unique: PMC2557553/PMC2557553.xml::T4-0

PMC0025XXXXX/PMC2558674.xml
  ----------------------------------------

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557553.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557553.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2557553.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2558674.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2558674.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  id: T1
  label_text: Table 1
  caption_text: Brain areas exhibiting activation during FIXATION (> PICTURE)
  footer_text: Height threshold at P < 0.05, FDR-corrected. For each activation foci, laterality (left, right), peak Montreal Neurologic Institute (MNI) atlas coordinates, cluster size (number of contiguous voxels), and Z-score are provided. IPL, Inferior Parietal Lobule; MTG , Middle Temporal Gyrus; STG, Superior Temporal Gyrus; PCC, Posterior Cingulate Cortex; ACC, Anterior Cingulate Cortex; L, left; R, right.
    unique: PMC2558674/PMC2558674.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Brain areas in which extent of activation during FIXATION is modulated by prior affective state
  footer_text: Brain regions that demonstrate an effect of prior emotional (Positive, Negative, Neutral) epoch on activation during FIXATION. Height threshold at P < 0.05, FDR-corrected. IPL, Inferior Parietal Lobule; FIX, FIXATION.
    unique: PMC2558674/PMC2558674.xml::T2-0

PMC0025XXXXX/PMC2559463.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic and clinical characteristics (mean ± SD) of the sample
  footer_text: NS = non-significant AA = African-American; AS = Asian; CC = Caucasian; and HS = Hispanic BDI = Beck Depression Inventory HDRS = Hamilton Depression Rating Scale CGAS = Children’s Global Assessment Scale
    unique: PMC2559463/PMC2559463.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Predictors of net peak salivary cortisol concentrations in response to the TSST in depressed adolescents and controls (N = 55)
  footer_text: * T = Tolerance (1−R2). A Tolerance value of less than 0.20 indicates significant inter-correlation among variables ** Ridge regression was performed to adjust for multicollinearity HDRS = Hamilton Depression Rating Scale Model 1: k = 0, F = 0.24, df = 3,51, NS; Model 2: k = 1.0, F = 1.35, df = 6,48, NS Model 3: k = 1.0, F = 2.57; df = 9,45, p ≤ .05
    unique: PMC2559463/PMC2559463.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Significant predictors of net peak salivary cortisol concentrations in response to the TSST in depressed adolescents and controls (N = 55)
  footer_text: * T = Tolerance (1−R2). A Tolerance value of less than 0.20 indicates significant inter-correlation among variables ** Ridge regression was performed to adjust for multicollinearity Model 1: k = 0; F = 4.95; df = 2, 52; p ≤ .05 Model 2: k = 0; F = 8.35; df = 4, 50; p ≤ .0001 Model 3: k = 2.0; F = 4.65; df = 5, 49; p ≤ .001
    unique: PMC2559463/PMC2559463.xml::T3-0

PMC0025XXXXX/PMC2559855.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559463.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559463.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559463.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559855.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Participant characteristics.
  footer_text: Note. There are no statistically significant differences between abstinent and relapsed women.
    unique: PMC2559855/PMC2559855.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Questions and responses on survey of postpartum women who had remained abstinent or relapsed to smoking (N = 36).
  footer_text: a Total N for this question is 35. One individual failed to answer this question.
    unique: PMC2559855/PMC2559855.xml::T2-0

PMC0025XXXXX/PMC2559856.xml

PMC0025XXXXX/PMC2559857.xml

PMC0025XXXXX/PMC2559858.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Data collection and refinement statistics of the hKAT II complex with α-oxoglutaric acid GOL, glycerol; 2OG, α-oxooglutaric acid; RMS, root mean square.
  footer_text: * The values in parentheses are for the highest resolution shell.
    unique: PMC2559858/PMC2559858.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559855.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559858.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559858.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Kinetic parameters of hKAT II towards amino acids and α-oxo acids The Km and kcat for oxo acids were derived by using various concentrations of individual oxo acids in the presence of 10 mM kynurenine; for amino acids, the results were derived by using various concentrations of individual amino acids in the presence of 30 mM glyoxylate. 3-HK, 3-HK, 3-hydroxy-kynurenine; α-KMB, α-oxo-γ-methiol-butyric acid. Results are means±S.E.M. (n=2).
  footer_text:
    unique: PMC2559858/PMC2559858.xml::T2-0

PMC0025XXXXX/PMC2559860.xml
  ----------------------------------------
  id: T1
tw(T1): {'id', 'orientation', 'position'}
  label_text: Table 1
  caption_text: Gating asymmetry ratio measurements
  footer_text: (Top) Effect of the chloride electrochemical gradient at zero proton electrochemical gradient (pHext 8.5, pHint 7.5, V = −58 mV, [Cl−]int = 120 mM). (Bottom) Effect of the proton electrochemical gradient (at symmetrical chloride concentration [Cl−]int = [Cl−]ext = 120 mM, and pHint 7.50). * One of the four patches with ΔGH = 2.7 kJ mol−1 and one of the eight patches with ΔGH = 4.6 kJ mol−1 was measured at pHint 7.00 and pHext 9.00. a ΔGCl was calculated according to equation 3. b ΔGH was calculated according to equation 2.
    unique: PMC2559860/PMC2559860.xml::T1-0

PMC0025XXXXX/PMC2559871.xml

PMC0025XXXXX/PMC2559912.xml

PMC0025XXXXX/PMC2559947.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: SE analysis of molecular mass as a function of pea PBGS protein concentration, assuming a single ideal species
  footer_text: 1 0.1 M BTP-HCl, pH 8.5, 0.1 mM DTT, 10 mM MgCl2 collected at 20°C. 2 The term, “global” refers to global fits across all speeds for a given concentration. The last row of this column represents an global fit to all three speeds and three concentrations simultaneously. 3 All molecular masses are reported in Daltons. The theoretical monomer molecular mass of pea PBGS is 36,693 Da. 4 The row labeled “all conc’ns” contains global fits across all concentrations for a given speed.
    unique: PMC2559947/PMC2559947.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559860.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559947.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559947.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559947.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Model analysis of pea PBGS from SE experiments with and without MgCl2, using an unweighted reduced χ2 as a measure of goodness of fit1
  footer_text: 1 0.1 M BTP-HCl, pH 8.5, 0.1 mM DTT, ±10 mM MgCl2, 20°C. Model analysis is based on global fitting to the three protein concentrations and three speeds, as reported in Table I. 2 When two values are presented, the first value assumes a non-equilibrating mixture model and the second value assumes an equilibrium model. In each model, the species are held fixed as appropriate multiples of the monomeric molecular mass. 3 Fitting of the data with inclusion of mass balance constraints reveals 65% octamer and 35% hexamer by weight. 4 Fitting of the data with inclusion of mass balance constraints reveals 25% octamer and 75% hexamer by weight.
    unique: PMC2559947/PMC2559947.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Molecular mass analysis of pea PBGS from SE experiments testing the effect of magnesium depletion on pea PBGS quaternary structure assemblies, assuming a single ideal species
  footer_text: 1 Samples of pea PBGS were dialyzed against 0.1 M BTP-HCl, pH 8.5, 0.1 mM DTT at 4°C prior to SE analysis and run at 20°C. 2 The term, “global” refers to global fits across all speeds for a given concentration. The last row of this column represents an global fit to all three speeds and three concentrations simultaneously. 3 All molecular masses are reported Daltons. 4 The row labeled “all conc’ns” contains global fits across all concentrations for a given speed.
    unique: PMC2559947/PMC2559947.xml::T3-0

PMC0025XXXXX/PMC2559948.xml

PMC0025XXXXX/PMC2559949.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The effect of nicotine administration on exploratory behavior during a 10 minute pre-exposure to the training context. Data presented as mean ± SEM.
  footer_text:
    unique: PMC2559949/PMC2559949.xml::T1-0

PMC0025XXXXX/PMC2559950.xml
  ----------------------------------------
  id: T1
tw(T1): {'id', 'orientation', 'position'}
  label_text: Table 1
  caption_text: The S. pombe SWI/SNF and RSC chromatin-remodeling complexes
  footer_text: Mass-spectrometry results showing the identification SWI/SNF and RSC components for each TAP-tagged subunit preparation. a Protein size in amino acids. b Sequence coverage (percentage of amino acids) for the respective protein. c Protein name indicates the TAP fusion used for purification.
    unique: PMC2559950/PMC2559950.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559949.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559950.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559950.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559951.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559951.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
tw(T2): {'id', 'orientation', 'position'}
  label_text: Table 2
  caption_text: Composition of S. pombe SWI/SNF and RSC complexes compared to those of S. cerevisiae and human
  footer_text: a Subunits of the respective complexes are listed in columns, with orthologous proteins grouped horizontally. b Paralogs in the same complex are grouped in the same row of the column.
    unique: PMC2559950/PMC2559950.xml::T2-0

PMC0025XXXXX/PMC2559951.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Participant Characteristics
  footer_text: Note. WAIS-R = Wechsler Adult Intelligence Scale-Revised vocabulary subtest (Wechsler, 1981), MMSE = Mini Mental State Exam (Folstein et al., 1975), GDS = Geriatric Depression Scale (Yesavage et al., 1983). a Expressed as WAIS-R vocabulary subtest raw scores.
    unique: PMC2559951/PMC2559951.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Treatment Descriptions and Mean (± SD) Hormone Levels Pre/Post-Treatment
  footer_text: Note. Hormone levels are from the day of cognitive testing before treatment, and again on the day of cognitive testing after approximately 6 weeks of treatment. Tx = treatment group. T-gel = Transdermal Testosterone Gel; a Estradiol measured in pg/mL. b Testosterone measured in ng/dL. c Free Testosterone measured in pmoles/L. * Hormone levels significantly differ from those of treatment group 4 in the older or younger men. † Hormone levels are significantly greater post-treatment compared to pre-treatment.
    unique: PMC2559951/PMC2559951.xml::T2-0

PMC0025XXXXX/PMC2559953.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Performance evaluation of serological assays used in the study
  footer_text: 1 Samples taken one year apart 2 Excluding equivocal results 3 --, concordant negative 4 -+, disconcordant 5 ++, concordant positive 6 Major outer membrane protein (MOMP), Enzyme-linked immunosorbent assay (ELISA), virus-like particle (VLP), HSV-2 specific glycoprotein (gG2)
    unique: PMC2559953/PMC2559953.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Correlation coefficients for prior sexually transmissible infections among nested controls in the PLCO Cancer Screening Trial, 1993-2001
  footer_text: 1 Values in regular font, whites; values in italic font, blacks 2 * PChi-Square ≤0.01; ** PChi-Square ≤0.001; *** PChi-Square ≤0.0001
    unique: PMC2559953/PMC2559953.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Self-reported baseline and clinical characteristics of prostate cancer cases and nested controls among whites and blacks in the PLCO Cancer Screening Trial, 1993 - 2001
  footer_text: * Statistically different from race-specific controls (PPearson-Correlation <0.05 or PChi-Square <0.05)
    unique: PMC2559953/PMC2559953.xml::T3-0
  ----------------------------------------
  id: T4

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559953.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559953.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559953.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559953.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559960.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559960.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  label_text: Table 4
  caption_text: Prior sexually transmissible infections and risk of prostate cancer among whites and blacks in the nested case-control study, PLCO Cancer Screening Trial, 1993 - 2001
  footer_text: 1 Using the total number of past infections, ranging from 0-7
    unique: PMC2559953/PMC2559953.xml::T4-0

PMC0025XXXXX/PMC2559954.xml

PMC0025XXXXX/PMC2559956.xml

PMC0025XXXXX/PMC2559959.xml

PMC0025XXXXX/PMC2559960.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sociodemographic Characteristics of the Sample (N = 78)
  footer_text: a PANSS, Positive and Negative Syndromes Scales b WHODAS-II, World Health Organization Disability Assessment Schedule, Participation in Society subscale
    unique: PMC2559960/PMC2559960.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Stepwise Regression of Stigma-Related Disability on Psychiatric and Depressive Symptoms and Cognitive Functioninga
  footer_text: a Overall model was significant: (F(3,70) = 19.4, p< .001). b df for F change is as follows: (1) 1,72; (2) 1,71; (3) 1,70
    unique: PMC2559960/PMC2559960.xml::T2-0

PMC0025XXXXX/PMC2559961.xml

PMC0025XXXXX/PMC2559962.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Breakdown of ethnicity of IPC patients and in the California population as a whole
  footer_text:
    unique: PMC2559962/PMC2559962.xml::T1-0

PMC0025XXXXX/PMC2559964.xml

PMC0025XXXXX/PMC2559965.xml

PMC0025XXXXX/PMC2559966.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Geometric means (95% confidence intervals) of plasma carotenoids across categories of baseline characteristics among 2895 women in Women's Health Study
  footer_text: 1 : p < 0.05 compared to the reference category using t-test. 2 : p < 0.01 compared to the reference category using t-test. 3 : p < 0.001 compared to the reference category using t-test.
    unique: PMC2559966/PMC2559966.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559962.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559966.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559966.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Adjusted geometric means (95% confidence intervals) of plasma carotenoids across categories of cardiovascular disease related biomarkers among 2895 women in Women's Health Study
  footer_text: 1 : Model adjusted for age and race for total cholesterol, additionally adjusted for total cholesterol for the other biomarkers. 2 : Model additionally adjusted for smoking (never, former, current <15 cigarettes/day, current ≥15 cigarettes/day), alcohol use (rarely/never, 1-3 drinks/mo, 1-6 drinks/wk, ≥1 drink/d), vigorous exercise (rarely/never, <1, 1-3, ≥4 times/wk), menopausal status (yes, no, uncertain), post-menopausal hormone use (never, former, current), multivitamin use (never, former, current), history of hypercholesterolemia (yes, no), hypertension (yes, no), and diabetes (yes, no), body mass index (continuous), and dietary intake of respective carotenoid (continuous). 3 : Linear trend was tested using the median values of each category as ordinal variable. 4 : p < 0.05 compared to the reference category using t-test. 5 : p < 0.01 compared to the reference category using t-test. 6 : p < 0.001 compared to the reference category using t-test.
    unique: PMC2559966/PMC2559966.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Linear regression coefficients on natural log transformed plasma carotenoids by one unit change in cardiovascular disease related biomarkers among 2895 women in Women's Health Study
  footer_text: 1 : Regression coefficients were standardized to the units specified in parenthesis for each biomarker. 2 : Model adjusted for age and race for total cholesterol, additionally adjusted for total cholesterol for the other biomarkers. 3 : The percentage changes presented in text were calculated by taking exponential of these regression coefficients (all such values). 4 : Model additionally adjusted for smoking (never, former, current <15 cigarettes/day, current ≥15 cigarettes/day), alcohol use (rarely/never, 1-3 drinks/mo, 1-6 drinks/wk, ≥1 drink/d), vigorous exercise (rarely/never, <1, 1-3, ≥4 times/wk), menopausal status (yes, no, uncertain), post-menopausal hormone use (never, former, current), multivitamin use (never, former, current), history of hypercholesterolemia (yes, no), hypertension (yes, no), and diabetes (yes, no), body mass index (continuous), and dietary intake of respective carotenoid (continuous).
    unique: PMC2559966/PMC2559966.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559966.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559969.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559972.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559972.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2559969.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of reproductive organ weights (mean ± SD) of adult cynomologus macaques, rhesus macaques and baboons
  footer_text:
    unique: PMC2559969/PMC2559969.xml::T1-0

PMC0025XXXXX/PMC2559971.xml

PMC0025XXXXX/PMC2559972.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of the study population, Singapore Chinese Health Study 1993-2005
  footer_text: * Included both never users and former users over lifetime.
    unique: PMC2559972/PMC2559972.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Characteristics of patients with histologically confirmed respiratory tract carcinomas, Singapore Chinese Health Study 1993-2005
  footer_text:
    unique: PMC2559972/PMC2559972.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Hazards ratio (HR) of respiratory tract carcinomas by incense use, Singapore Chinese Health Study 1993-2005
  footer_text: * Adjusted for age at recruitment, year of interview, gender, dialect group, level of education, body mass index, number of cigarettes/day, number of years of smoking, time since smoking cessation, alcohol consumption, dietary intakes of isothiocyanate, beta-cryptoxanthin, lutein, lycopene and summed Chinese preserved foods, and for women, number of children (see details in the Materials and Methods). † Including both never and former users of incense.
    unique: PMC2559972/PMC2559972.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Hazards ratio (HR) of respiratory tract carcinomas in relation to combined levels of cigarette smoking status, and frequency of incense use, Singapore Chinese Health Study 1993-2005
  footer_text: * Adjusted for age at recruitment, year of interview, gender, dialect group, level of education, body mass index, number of cigarettes/day, number of years of smoking, time since smoking cessation, alcohol consumption, dietary intakes of isothiocyanate, beta-cryptoxanthin, lutein, lycopene and summed Chinese preserved foods, and for women, number of children (see details in the Materials and Methods). † Including both never and former users of incense.
    unique: PMC2559972/PMC2559972.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Hazards ratio (HR) of respiratory tract carcinoma by histological subtype in relation to frequency of incense use, Singapore Chinese Health Study 1993-2005
  footer_text: * Adjusted for age at recruitment, year of interview, gender, dialect group, level of education, body mass index, number of cigarettes/day, number of years of smoking, time since smoking cessation, alcohol consumption, dietary intakes of isothiocyanate, beta-cryptoxanthin, lutein, lycopene and summed Chinese preserved foods, and for women, number of children (see details in the Materials and Methods) † No current use comprise never and ex-users of incense. ‡ The sum of all respiratory tract carcinomas may differ from the total number of cases listed in Tables 2 and 3 since the present table counted the first incident cancer for a given individual. § Non-squamous cell carcinoma included adenocarcinoma, small cell carcinoma, undifferentiated, other and unspecified carcinoma.
    unique: PMC2559972/PMC2559972.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559972.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559972.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559972.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559975.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2559974.xml

PMC0025XXXXX/PMC2559975.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: GAR and AICAR Tfase Inhibition (Ki, μM)
  footer_text: a Ref 18
    unique: PMC2559975/PMC2559975.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: In vitro Cytotoxic Activity
  footer_text:
    unique: PMC2559975/PMC2559975.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: In vitro Cytotoxic Activity in Mutant Cell Lines
  footer_text: a Ref 18
    unique: PMC2559975/PMC2559975.xml::T3-0

PMC0025XXXXX/PMC2559976.xml

PMC0025XXXXX/PMC2559977.xml

PMC0025XXXXX/PMC2559978.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559975.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559975.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2559978.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Relative Energies, E(kcal/mol) (Values Thermally Corrected to 298 K° Are Given in Parentheses) for the Acyclic conformers 1a (TTT) and 1b (CCT) of NH=CH−CH=CH−NH−BO and the cyclic conformer 1c (CCC) of (−NH=CH−CH=CH−NH−B−)O at the MP2(FC)/cc-pVDZ, MP2(FC)/aug-cc-pVDZ, and MP2(FC)/cc-pVTZ Computational Levels.
  footer_text:
    unique: PMC2559978/PMC2559978.xml::T1-0

PMC0025XXXXX/PMC2559979.xml

PMC0025XXXXX/PMC2560174.xml

PMC0025XXXXX/PMC2560175.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Protection of mice immunized with CAS or RAS against challenge with wild-type sporozoites
  footer_text: a Groups of mice were immunized with P. berghei ANKA (P.b.) or P. yoelii 17XNL (P.y.) control (vehicle-treated) sporozoites, CAS, or RAS as indicated, isolated from the same mosquito batches and were immunized at 7 day intervals. b Groups of mice were challenged with P. berghei ANKA or P. yoelii 17XNL wild-type sporozoites c Naïve, age-matched mice were used at the time of all immunizations and challenges. d Statistical analysis using Fisher exact test for comparison of Control and CAS groups gave p<0.002 for groups 1 and 3. e NA, not applicable. f Naïve, age-matched mice developed patent parasitemia 1.5 days p.i. in both the CAS and RAS groups. g All mice showed patent parasitemia 2 days p.i.
    unique: PMC2560175/PMC2560175.xml::T1-0

PMC0025XXXXX/PMC2560176.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patient characteristics by race/ethnicity.
  footer_text: Significance (p < .05) based on chi-square tests and ANOVAs with Bonferroni post-hoc comparisons, reference group = Non-Hispanic white: 1 Non-Hispanic black 2 Hispanic 3 Asian.
    unique: PMC2560176/PMC2560176.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560175.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560176.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560176.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560176.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Regression coefficients for race/ethnicity on hip fracture outcomes.
  footer_text: * F change p < .001. Reference group: non-Hispanic white. Model 1: race/ethnicity only. Model 2: adjusted for sociodemographic factors (gender, age, married, Medicare coverage). Model 3: adjusted for sociodemographic factors and case severity (sum of comorbidites, CMG tier, admission or discharge FIM, and LOS [except for model with LOS as dependent variable]).
    unique: PMC2560176/PMC2560176.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Odds ratios for home discharge based on race/ethnicity.
  footer_text: * p < .001 for block addition to model. Reference group: non-Hispanic white. Model 1: race/ethnicity only. Model 2: adjusted for sociodemographic factors (gender, age, married, Medicare). Model 3: adjusted for sociodemographic factors and case severity (sum of comorbidites, CMG tier, discharge FIM, and LOS). Model 4: adjusted for sociodemographic factors, case severity, and pre-hospitalization living setting (home vs. not home).
    unique: PMC2560176/PMC2560176.xml::T3-0

PMC0025XXXXX/PMC2560177.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: WHI RCT and GPRD STUDIES IN WOMEN WITH AN INTACT UTERUS TREATED WITH COMBINED HORMONE RECPLACEMENT THERAPY
  footer_text: a Reference (5), 21.5% of subjects > age 70 vs. 2.5% in GPRD study. b Reference (8) c Reference (10) d Reference (11) e Number of events f Hazard ratio (95% confidence interval) g Exposed, number of events h Unexposed, number of events i Cox adjusted hazard ratio (95% confidence interval) j Coronary Heart Disease (CHD) a combination of myocardial infarction and coronary death was the primary outcome in the WHI RCT; however the results for myocardial infarction alone were similar. Results in the GPRD studies are all acute myocardial infarctions (MI). k Cerebrovascular accident l Adjusted hazard ratio using Prior event rate ratio (PERR) = 1.40 (0.87 – 2.44) m Adjusted hazard ratio using PERR = 2.63 (1.38 – 7.43) n Adjusted hazard ratio using PERR = 0.77 (0.41–1.42) o Adjusted hazard ratio using PERR = 2.20 (1.12–5.45)
    unique: PMC2560177/PMC2560177.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: WHI RCT AND GPRD STUDIES in WOMEN WITH A PRIOR HYSTERECTOMY TREATED WITH ESTROGEN ONLY
  footer_text: a Reference (7), 24% of women were older than 70 years versus 5.2% of women in the GPRD study b Reference (8) c Reference (12) d Adjusted HR using PERR = 1.28 (0.69–2.56) e Adjusted HR using PERR = 3.06 (1.39 – 10.31) f Adjusted HR using PERR = .92 (.35–2.79) g Adjusted HR using PERR = 2.32 (.98–7.94)
    unique: PMC2560177/PMC2560177.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560177.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560177.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2560179.xml

PMC0025XXXXX/PMC2560982.xml

PMC0025XXXXX/PMC2560985.xml

PMC0025XXXXX/PMC2560987.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic features of US travelers to Mexico and risk factors for acquiring travelers' diarrhea
  footer_text: * Student t test: means ± SD.
    unique: PMC2560987/PMC2560987.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Comparison of PCR followed by genotyping versus ELISA for Cryptosporidium detection
  footer_text: * PCR followed by genotype sequencing. † Calculated as [number of true positives/(number of true positives + number of false negatives)]. ‡ Calculated as [number of true negatives/(number of true negatives + number of false positives)]. § Calculated as [number of true positives/(number of true positives + number of false positives)]. ¶ Calculated as [number of true negatives/(number of true negatives + number of false negatives)].
    unique: PMC2560987/PMC2560987.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Epidemiologic and clinical features of bacterial TD compared with Cryptosporidium TD
  footer_text: * Includes the cases of cryptosporidiosis only and cryptosporidiosis with bacterial co-infection. Cryptosporidiosis cases in which bacterial entero-pathogens were identified were counted once in the cryptosporidiosis group for analysis and were not included in the bacterial infection subgroup. † Student t test: mean (95% CI).
    unique: PMC2560987/PMC2560987.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560987.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560987.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2560987.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561069.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561069.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2560992.xml

PMC0025XXXXX/PMC2561069.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparisons on demographic, smoking history, and affective variables across preinclusion attrition status.
  footer_text: * Note: Denotes variables that have been transformed; No significant group differences were identified across demographic, smoking history, affective, or distress tolerance variables.
    unique: PMC2561069/PMC2561069.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Spearman Rank Correlations among Physical and Psychological Distress tolerance tasks
  footer_text: * p<.05; ** p<.01
    unique: PMC2561069/PMC2561069.xml::T2-0

PMC0025XXXXX/PMC2561072.xml

PMC0025XXXXX/PMC2561080.xml

PMC0025XXXXX/PMC2561171.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Primary analysis: Classification of blinded validation set of sera from asymptomatic colonoscopy-screened persons, based on analysis of spectra generated by a nano-electrospray ionization source using a QSTAR-XL mass spectrometer and the ProteomeQuest® algorithm
  footer_text: Sensitivity: 10/12= 83% Specificity: 9/25= 36% Accuracy: 51% (95% CI: 38% to 65%)
    unique: PMC2561171/PMC2561171.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Post-hoc analysis: classification of blinded validation set after hemolyzed specimens were excluded
  footer_text: Sensitivity: 7/9= 78% (95% CI: 40% to 96%) Specificity: 8/15= 53% (95% CI: 27% to 78%) Accuracy: 63% (95% CI: 53% to 72%)
    unique: PMC2561171/PMC2561171.xml::T2-0

PMC0025XXXXX/PMC2561180.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561171.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561171.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561180.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Distributions of demographic characteristics and established breast cancer risk factors among controls and luminal, HER2-overexpressing, and triple-negative cases
  footer_text:
    unique: PMC2561180/PMC2561180.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Age-adjusted odds ratios for body mass index (BMI) and weight by tumor subtype and current HT use
  footer_text:
    unique: PMC2561180/PMC2561180.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Age-adjusted odds ratios for quartiles of other anthropometric characteristics by tumor subtype
  footer_text: * Odds ratio (OR) adjusted for age and reference year. † p<0.05.
    unique: PMC2561180/PMC2561180.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561180.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561180.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561190.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561182.xml

PMC0025XXXXX/PMC2561188.xml

PMC0025XXXXX/PMC2561190.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of individual studies with information on involuntary smoking in International Head and Neck Cancer Epidemiology consortium pooled data v1.1
  footer_text: * Representative publication in which study methods are available. + All studies frequency matched controls to cases, minimally on age and sex. Additional frequency matching factors included center (Central Europe and Latin America studies), ethnicity (Tampa study), and neighborhood (Los Angeles study). ∥ Multicenter study.
    unique: PMC2561190/PMC2561190.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Selected characteristics of head and neck cancer cases and controls
  footer_text: # Information on ethnicity was not collected in the Central Europe and Latin America studies. In the Central Europe study, all subjects were classified as non-Hispanic White, since the large majority of these populations are expected to be White. In the Latin America study, we categorized subjects as ‘Latin American’. We adjusted for study center in all logistic regression models as a proxy variable for race/ethnicity since each center has an expected predominant ethnic group distribution.
    unique: PMC2561190/PMC2561190.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561190.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561190.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561190.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Involuntary smoking among never tobacco users, involuntary smoking among never tobacco users and never alcohol drinkers and the risk of head and neck cancer
  footer_text: * Adjusted for centers, age, sex, race/ethnicity, education and alcohol drinking (in drink-years; for never tobacco users only). ** Estimates from random effect models. 1 Included Central Europe, Tampa, Latin America, Los Angeles, and Houston studies. 2 Included Central Europe, Tampa, Latin America, Los Angeles, and Puerto Rico studies. 3 Included Central Europe, Tampa, and Latin America studies. 4 Included Central Europe, Tampa, Latin America, and Los Angeles studies. 5 Included Central Europe and Latin America studies.
    unique: PMC2561190/PMC2561190.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Involuntary smoking among never tobacco users and the risk of head and neck cancer, by cancer subsite
  footer_text: * Adjusted for centers, age, sex, race/ethnicity, education and alcohol drinking (in drink-years). § Estimates from random effect model. 1 Included Central Europe, Tampa, Latin America, Los Angeles, and Houston studies (no Tampa study for larynx). 2 Included Central Europe, Tampa, Puerto Rico, Latin America, and Los Angeles studies (no Tampa and Puerto Rico studies for larynx). 3 Included Central Europe, Tampa, Latin America, and Los Angeles studies (no Tampa study for larynx).
    unique: PMC2561190/PMC2561190.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Involuntary smoking among never tobacco users and never alcohol users and the risk of head and neck cancer, by cancer subsite
  footer_text: Note: Adjusted for centers, age, sex, race/ethnicity and education. 1 Included Central Europe, Tampa, Latin America, Los Angeles, and Houston studies (no Tampa study for larynx). 2 Included Central Europe, Tampa, Puerto Rico, Latin America, and Los Angeles studies (no Tampa and Puerto Rico studies for larynx). 3 Included Central Europe, Tampa, Latin America, and Los Angeles studies (no Tampa study for larynx).
    unique: PMC2561190/PMC2561190.xml::T5-0

PMC0025XXXXX/PMC2561192.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: TMS-induced changes in tangential forces
  footer_text: The data are shown for different external torques that required supination or pronation efforts. Δftht, Δfvft, and Δftotalt stand for the TMS-induced changes in the tangential forces of the thumb, virtual finger, and the total tangential force. Averages across subjects with standard errors are presented.
    unique: PMC2561192/PMC2561192.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: TMS-induced changes in the moment of force
  footer_text: The data are shown for different external torques that required supination or pronation efforts. ΔMn, ΔMt, ΔMtot stand for the changes in the moment of normal force, moment of tangential force and total moment of force. Averages across subjects with standard errors are presented.
    unique: PMC2561192/PMC2561192.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Timing of synergy restoration
  footer_text: The times of the initiation of the two stages of synergy restoration (in ms) are presented for the three characteristics of the hand mechanical action (means across the subjects and standard errors.)
    unique: PMC2561192/PMC2561192.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561190.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561192.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561192.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561192.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561197.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561197.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561196.xml

PMC0025XXXXX/PMC2561197.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Results from the Geometric Accuracy Test from T1-weighted Images. ACR specifies that lengths should be with ± 2 mm of actual length shown in first column.
  footer_text:
    unique: PMC2561197/PMC2561197.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: High Contrast Spatial Resolution Results from the T1- and T2-weighted Images from the Lower Right (LR) and Upper Left (UL) Grids at the Three Separate Spatial Resolutions 1.1, 1.0 and 0.9 mm provided in the ACR Phantom. ACR specifies that a 1 mm resolution should be regularly achieved with the settings employed for this test.
  footer_text:
    unique: PMC2561197/PMC2561197.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: MR QA Summary Statistics for the remaining five imaging tests. The ACR recommended specifications for the various test values are provided in the last column.
  footer_text:
    unique: PMC2561197/PMC2561197.xml::T3-0

PMC0025XXXXX/PMC2561208.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Peptide sequences used in these studies
  footer_text:
    unique: PMC2561208/PMC2561208.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: DNA immunization with a vector encoding RSV M2 protein lacking the immunodominant CTL epitope induces significant but reduced protection compared to immunization with the wild-type M2 genea
  footer_text: a BALB/c mice (n=5) were immunized with one of the immunogens at day 0, 14 and 21, and challenged with live RSV on day 28 (day 7 after the third immunization, the expected peak day of CTL activity). Lung titers were determined on day 4 following challenge (the expected peak day of viral replication). b No significant difference from values obtained for mice immunized with PBS. (P≥0.05) c Significantly different from values obtained for mice immunized with PBS (P<0.01). d Significantly different from values obtained for mice immunized with PBS (P<0.02).
    unique: PMC2561208/PMC2561208.xml::T2-0

PMC0025XXXXX/PMC2561223.xml

PMC0025XXXXX/PMC2561224.xml

PMC0025XXXXX/PMC2561228.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561197.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561208.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561208.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561228.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561228.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561228.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Dissociation constants for 8ec1 at 300 K in absence of calcium.
  footer_text:
    unique: PMC2561228/PMC2561228.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: 15Nε1 relaxation and dynamics parameters at pH 6.25, 281.5 K, and 14.1 T.
  footer_text: NOE and R1 measurements used 0.65 mM 8ec1. R2 measurements are reported for both 0.65 mM and 0.30 mM 8ec1 in the absence of calcium and for 0.3 mM 8ec1 in the presence of 5 mM calcium; R2 results for 0.3 mM 8ec1 are shown in square brackets. Values of S2 were obtained from the NOE and R1 data using τm = 12.8 ± 0.7 ns and 21.6 ± 0.5 ns, for monomer and dimer states, respectively, as discussed in the text.
    unique: PMC2561228/PMC2561228.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table III
  caption_text: 15Nε1 relaxation dispersion parameters at pH 6.25, 281.5 K.
  footer_text: Relaxation dispersion parameters obtained from fitting the Carver-Richards equation (Carver and Richards, 1972) to the relaxation dispersion profiles shown in Figure 6. Values reported with (*) refer to parameters fit at 14.1 T. The value of Rex is reported for a τcp = 1 ms CPMG pulsing rate.
    unique: PMC2561228/PMC2561228.xml::T3-0

PMC0025XXXXX/PMC2561229.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The velocity-amplitude relationships for horizontal vergence and vertical version for all subjects. The correlations were analyzed under logarithmic plots. All relationships are linearly positive (**p<0.0001). The bino-vg: vergence from binocular condition; bino-vs: version from binocular condition; mono-vg: vergence from monocular condition; mono-vs: version from monocular condition; divg: divergence; convg: convergence; vs: version.
  footer_text:
    unique: PMC2561229/PMC2561229.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Duration-amplitudes relationships for horizontal vergence and vertical saccades for all subjects. The correlations were analyzed under logarithmic plots. All relationships are linear (p<0.0001). The bino-vg: vergence from binocular condition; bino-vs: version from binocular condition; mono-vg: vergence from monocular condition; mono-vs: version from monocular condition; divg: divergence; convg: convergence; vs: version.
  footer_text:
    unique: PMC2561229/PMC2561229.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Relationships between the time of vergence velocity peaks and time of saccade velocity peaks for all subjects. R2: Correlation coefficients; S: slopes of the regression lines. All relationships of the subjects are linearly positive (**p<0.0001).
  footer_text:
    unique: PMC2561229/PMC2561229.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561229.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561229.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561229.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561229.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561229.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Parameters for relationships between peak velocity of horizontal vergence and peak velocity of vertical saccades for binocular viewing conditions. R2: Correlation coefficients; I: Intercepts; S: slopes of the regression lines. Positive relationships of the subjects are indicated with stars (* p<0.05; ** p<0.0001).
  footer_text:
    unique: PMC2561229/PMC2561229.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Relationships between peak velocity of horizontal vergence and peak velocity of vertical saccades for monocular viewing conditions. R2: Correlation coefficients. I: Intercepts. S: slopes of the regression lines. Positive relationships of the subjects are indicated with * and ** (* p<0.05; ** p<0.0001).
  footer_text:
    unique: PMC2561229/PMC2561229.xml::T5-0

PMC0025XXXXX/PMC2561244.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text:
  footer_text: Prevalence of the indirect and direct pathways for the synthesis of the aa-tRNA species listed in all three domains of life. The table was adapted from [132] and is reprinted with permission from Oxford University Press.
    unique: PMC2561244/PMC2561244.xml::T1-0

PMC0025XXXXX/PMC2561247.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Association between participant characteristics and nonsteroidal anti-inflammatory drug use among 63 809 participants in the Vitamins and Lifestyle cohort (2000–2005)*
  footer_text: * Values of some characteristics do not add up to total because of missing data (<5% of data are missing). NSAID = nonsteroidal anti-inflammatory drug; OR = odds ratio; CI = confidence interval; BMI = body mass index. † NSAID users are defined as participants who regularly used a NSAID (low-dose aspirin, regular- or extra-strength aspirin, or non-aspirin NSAIDs [ibuprofen, naproxen, or celecoxib or rofecoxib, or for women only, other prescription NSAIDs]) at least once a week for 1 year during the 10 years before baseline. ‡ Odds ratios were calculated by use of a logistic regression analysis that was adjusted for age and sex. § Cardiovascular disease variable was defined as report of bypass surgery, angioplasty, heart attack, or angina. || Met-h/wk is the metabolic equivalent hours per week and is also the energy expenditure expressed as kilocalories per kilogram per week. ¶ Smoking categories were defined as follows: never = never smoked daily for at least a year; current or recent = quit less than 10 years from baseline; former = quit 10 or more years from baseline.
    unique: PMC2561247/PMC2561247.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561244.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561247.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Association between nonsteroidal anti-inflammatory drug use and incident melanoma in the Vitamins and Lifestyle cohort (2000–2005)
  footer_text: * Adjustments were for age at baseline (timescale), sex (female or male), education (high school or fewer than 12 years, some college, or advanced degree), first-degree family history of melanoma (no or yes), personal history of nonmelanoma skin cancer (no or yes), ever had moles removed (no or yes), freckles between ages 10 and 20 years (no or yes), had three or more severe sunburns between ages 10 and 20 years (no or yes), natural red or blond hair between ages 10 and 20 years (no or yes), reaction to 1 hour in strong sunlight (tan or no sunburn, mild burning, painful sunburn, or severe sunburn with blistering), multivitamin use (none, <0 to 3, or ≥4 d/wk), chronic pain in last year (no or yes), arthritis (no or yes), cardiovascular disease (no or yes), and kidney disease or ulcer (no or yes). HR = hazard ratio; CI = confidence interval; NSAID = nonsteroidal anti-inflammatory drug. † Any NSAID use was defined as report of regular use of low-dose aspirin, regular- or extra-strength aspirin, or non-aspirin NSAIDs (ibuprofen, naproxen, or cele-coxib or rofecoxib or, for women only, other prescription NSAIDs). ‡ Nonusers of any NSAID (low-dose aspirin, regular- or extra-strength aspirin, or non-aspirin NSAIDs [ibuprofen, naproxen, or celecoxib or rofecoxib or, for women only, other prescription NSAIDs]) were the common reference for all exposure groups. § Dose for each exposure was computed as (days per week of use) multiplied by (years of use divided by 10 years). || Users of NSAIDs other than regular- or extra-strength aspirin were excluded from the referent group. ¶ Users of aspirin were excluded from the referent group.
    unique: PMC2561247/PMC2561247.xml::T2-0

PMC0025XXXXX/PMC2561248.xml

PMC0025XXXXX/PMC2561250.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of cortactin binding proteins that regulate actin cytoskeletal dynamics Summary of cortactin-binding proteins that interact directlvy with the actin cytoskeleton, including binding characteristics to cortactin and actin, as well as functional and physiological effects.
  footer_text:
    unique: PMC2561250/PMC2561250.xml::T1-0

PMC0025XXXXX/PMC2561252.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561247.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561250.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561256.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561253.xml

PMC0025XXXXX/PMC2561255.xml

PMC0025XXXXX/PMC2561256.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Custom Internal Size Standard Primers.
  footer_text: A single ROX-labeled forward primer and a series of 20 reverse primers were used to generate amplicons of varying length using the pcDNA3.1+ plasmid as a template for PCR. Amplicon lengths are indicated to the right of each reverse primer. PCR products were purified, normalized to 10ng/uL and pooled to generate a custom internal size standard for 3130xL capillary electrophoresis RSCA.
    unique: PMC2561256/PMC2561256.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: MHC class I screening panel sequences pooled based on reference strand specific migration rates.
  footer_text: The fourteen screening panel sequences exhibit distinct characteristic electrophoretic mobilities when hybridized to each of three reference strand sequences. Based on their relative mobilities, screening panel sequences were divided into two pools per reference strand, increasing the number of sequences that can be identified in a single run.
    unique: PMC2561256/PMC2561256.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: The concordance of RSCA genotyping for 12 previously screened Chinese rhesus macaques and the frequency of 14 MHC class I alleles in 37 Chinese rhesus macaques.
  footer_text: The concordance of RSCA genotyping with cDNA cloning and sequencing was determined for 12 Chinese rhesus macaques (upper panel). The frequencies of the 14 screening panel sequences were determined using an additional 25 Chinese rhesus macaques (bottom row). Nine macaques (ChRh13, 15, 23, 25, 32, 35, 37–39) did not express any of the 14 screening panel clones.
    unique: PMC2561256/PMC2561256.xml::T3-0

PMC0025XXXXX/PMC2561257.xml

PMC0025XXXXX/PMC2561258.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561256.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561261.xml

PMC0025XXXXX/PMC2561268.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Kinetic constants of wild-type and CCPGCC-insertion PTPs assayed with pNPP
  footer_text:
    unique: PMC2561268/PMC2561268.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Kinetic constants of wild-type and CCPGCC-insertion PTPs in the absence (−) and presence (+) of FlAsH when assayed with pNPP
  footer_text:
    unique: PMC2561268/PMC2561268.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Apparent inhibition constants (KIapp) of FlAsH for CCPGCC-insertion PTPs
  footer_text:
    unique: PMC2561268/PMC2561268.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Kinetic constants of wild-Type and CCPGCC-insertion PTPH1 and PTPα in the absence (−) and presence (+) of FlAsH when assayed with DADEpYLIPQQG
  footer_text:
    unique: PMC2561268/PMC2561268.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561268.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561268.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561268.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561268.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561269.xml

PMC0025XXXXX/PMC2561272.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The synergy of killing by sorafenib and vorinostat is dependent upon loss of c-FLIP-s expression Pancreatic (MiaPaca2) and hepatoma (HEP3B) cells were infected to express empty vector (CMV) or c-FLIP-s. Twenty four hours after infection cells were plated as single cells (250–1500 cells/well) in sextuplicate and 12h after plating treated with vehicle (VEH, DMSO), sorafenib (Sor., 3.0–6.0 µM) or vorinostat (Vor. 250–500 nM), or with both drugs combined, as indicated at a fixed concentration ratio to perform median dose effect analyses for the determination of synergy. Forty eight hours after drug exposure, the media was changed and cells cultured in drug free media for an additional 10–14 days. Cells were fixed, stained with crystal violet and colonies of > 50 cells / colony counted. Colony formation data were also entered into the Calcusyn program and combination index (CI) and fraction affected (Fa) values determined. A CI value of less than 0.90–1.00 indicates synergy; a CI value of 0.90–1.10 approximates to additive interactions between the drugs; a CI value of above 1.10 indicates antagonism (n = 2 independent studies).
  footer_text:
    unique: PMC2561272/PMC2561272.xml::T1-0

PMC0025XXXXX/PMC2561273.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Transcriptome changes (2-fold or greater; P values ≤ 0.05) associated with rgg nactivation during post-exponential growth
  footer_text: a SPy numbers designate open reading frames based on the SF370 S. pyogenes genome annotation (Ferretti et al., 2001). b Change in transcript level of rgg mutant compared to that of the wild-type. c rgg inactivation doesn’t affect transcript level. d Asterisks indicate genes similarly regulated in NZ131 strain (Dmitriev et al., 2006).
    unique: PMC2561273/PMC2561273.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561272.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561273.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561273.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Correlation between results obtained with DNA microarrays and quantitative TaqMan RT-PCR
  footer_text: a SPy numbers designate open reading frames based on the SF370 S. pyogenes genome annotation (Ferretti et al., 2001). b Gene designations are in italics, and the corresponding protein function is in parentheses. c Change in transcript level of rgg mutant compared to that of the wild-type.
    unique: PMC2561273/PMC2561273.xml::T2-0

PMC0025XXXXX/PMC2561277.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Human subject characteristics
  footer_text: a The postmortem time was the time lapsed between a subject’s death and the rheometric experiments, except for Subjects 1 and 2 who were total laryngectomy patients.
    unique: PMC2561277/PMC2561277.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Results of least-squares regressions for the parametric description of elastic shear modulus (G’), viscous shear modulus (G”), and dynamic viscosity (η’) of the human vocal fold cover according to Eqs. (25) - (27) (n = 7). R2 is the coefficient of determination indicating the goodness of curve-fitting
  footer_text:
    unique: PMC2561277/PMC2561277.xml::T2-0

PMC0025XXXXX/PMC2561279.xml

PMC0025XXXXX/PMC2561283.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Physico-chemical properties of fluorescent ferumoxides (FL FE)
  footer_text: [a] T1 Relaxation rate [b] T2 Relaxation rate
    unique: PMC2561283/PMC2561283.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: NMR Relaxivities of FE-Pro complex in a gel
  footer_text: [a] T1 Relaxation rate [b] T2 Relaxation rate
    unique: PMC2561283/PMC2561283.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561277.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561277.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561283.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561283.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561284.xml

PMC0025XXXXX/PMC2561285.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Group neurocognitive profile for the overall sample (N=85)
  footer_text: * Item in italics represents a score in the borderline range of functioning
    unique: PMC2561285/PMC2561285.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Group neurocognitive profile for the globally intact sample (n=54)
  footer_text:
    unique: PMC2561285/PMC2561285.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Incidence of absolute impairment in the globally intact group for each domain (N=54)
  footer_text:
    unique: PMC2561285/PMC2561285.xml::T3-0

PMC0025XXXXX/PMC2561289.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Pathology of the stomach and spleen, 6 weeks after injection of Th1, Th2 and Th17 effector T cells
  footer_text: Legend:parietal cell destruction (PCD) was scored as described above, with grade 5 indicating 25-50% PCD, grade 6 indicating 50-100% PCD. Cells within the stomach infiltrates, as well as fore-stomach and splenic lesions were rated either zero (-) or + to +++ for mild/moderate/high presence. Abreviations: Eos=eosinophils, GC=macrophage giant cells, GCH=germinal center hyperplasia, Ly=lymphocytes, PC=plasmocytosis
    unique: PMC2561289/PMC2561289.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561285.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561285.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561285.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561289.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561289.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Succeptibility of Teffector cells to Treg mediated suppression in vivo at 2, 4 and 6 weeks after injection
  footer_text: Legend: Δ= delta (Treg-mediated reduction of cell numbers per gLN expressed in %). All other values are given as cells per gLN × 1000.
    unique: PMC2561289/PMC2561289.xml::T2-0

PMC0025XXXXX/PMC2561294.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic characteristics and prevalence of Hurricane Katrina-related factors.
  footer_text: Abbreviation: SD – standard deviation, PTSD – Post-traumatic stress disorder † All p-values (except age, gender, and race) are adjusted for age, gender, and race
    unique: PMC2561294/PMC2561294.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Adjusted prevalence ratios of low adherence by different Hurricane Katrina-related factors for CoSMO participants from high and low affected areas.
  footer_text: Adjusted for age, race, gender, education and marital status. Abbreviation: PR = Prevalence ratio; CI = Confidence Interval
    unique: PMC2561294/PMC2561294.xml::T2-0

PMC0025XXXXX/PMC2561300.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Distribution of Less-than-perfect Intentional and Unintentional Medication Adherence by Socio-Demographic Characteristics and Damage to Residence in Sample of Patients (n= 210) in a New Orleans metropolitan area clinic from November 2005 to August 2006
  footer_text:
    unique: PMC2561300/PMC2561300.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561294.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561294.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561300.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561300.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561305.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Distribution of Post-Katrina Medication Issues by Socio-Demographic Characteristics in Sample of Patients (n= 86) in a New Orleans metropolitan area clinic from November 2005 to August 2006
  footer_text: * p< 0.05
    unique: PMC2561300/PMC2561300.xml::T2-0

PMC0025XXXXX/PMC2561305.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of Different Loading Conditions on the Crack Edge Area (CA) to Total Volume (V) of Multiaxial Confined Compression Specimens of Renew Dental Composite
  footer_text:
    unique: PMC2561305/PMC2561305.xml::T1-0

PMC0025XXXXX/PMC2561309.xml
  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: Constant, R2, and p-values, and residuals for each of the nine f2 frequencies.
  footer_text:
    unique: PMC2561309/PMC2561309.xml::T1-0

PMC0025XXXXX/PMC2561312.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Biodistribution of different anti-HER2 Affibody conjugates after iv injection in NMRI mice.
  footer_text: a data presented as average ± SD (n = 4) of per cent of injected activity per gram (% IA/g); b for intestine (together with content) and carcass, data presented as per cent of injected activity per whole sample (% IA); c significant difference (p < 0.05) with 111In-DOTA-Z2395-C at the same time point; d significant difference (p < 0.05) with 111In-CHX-A” DTPA-Z342 at the same time point;
    unique: PMC2561312/PMC2561312.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561309.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561312.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561312.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561312.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Biodistribution of 111In-CHX-A” DTPA-Z2395-C, 111In-DOTA-Z2395-C and 111In-CHX-A” DTPA-Z342 Affibody conjugates 4 h after iv injection in BALB/C nu/nu mice bearing SKOV-3 xenografts
  footer_text: a data presented as average ± SD (n = 4) of per cent of injected activity per gram (% IA/g); b for intestine (together with content) and carcass, data presented as per cent of injected activity per whole sample (% IA); c significant difference (p < 0.05) with 111In-DOTA-Z2395-C at the same time point; d significant difference (p < 0.05) with 111In-CHX-A” DTPA-Z342 at the same time point;
    unique: PMC2561312/PMC2561312.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Tumor-to-organ ratios in BALB/C nu/nu mice bearing SKOV-3 xenograftsa
  footer_text: a Data are presented as an average for four animals ± SD. b Significant difference (p < 0.05) between tumor-to-organ ratios at 1 and 4 h p.i. for 111In-CHX-A” DTPA-Z2395-C c Significant difference (p < 0.05) between tumor-to-organ ratios at 4 and 24 h p.i. for 111In-CHX-A” DTPA-Z2395-C d Significant difference (p < 0.05) between tumor-to-organ ratios 4 h p.i. for 111In-CHX-A” DTPA-Z2395-C and 111In-DOTA-Z2395-C; e Significant difference (p < 0.05) between tumor-to-organ ratios 4 h p.i. for 111In-CHX-A” DTPA-Z2395-C and 111In-CHX-A” DTPA-Z342 f Significant difference (p < 0.05) between tumor-to-organ ratios 4 h p.i. for 111In-DOTA-Z2395-C and 111In-CHX-A” DTPA-Z342
    unique: PMC2561312/PMC2561312.xml::T3-0

PMC0025XXXXX/PMC2561316.xml

PMC0025XXXXX/PMC2561321.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: BRIP1 sequence alterations
  footer_text: a Numbering based on RefSeq NT_010783.13 (for the intronic variant) and NM_032043 (for all the variants within the coding region). For exonic variants, numbering starts at codon 1. b Frequency of second allele listed.
    unique: PMC2561321/PMC2561321.xml::T1-0

PMC0025XXXXX/PMC2561336.xml

PMC0025XXXXX/PMC2561893.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561321.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561893.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561893.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561893.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561893.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  caption_text: Agreement between algorithm and three neonatologists on whether infant received a permissive hypercapnia strategy of care
  footer_text:
    unique: PMC2561893/PMC2561893.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Infant characteristics and incidence of intraventricular hemorrhage and death by normocapnia, permissive hypercapnia or unclassifiable strategy of care
  footer_text: Numbers are mean ± standard deviation or frequency (percent) unless otherwise noted * p < 0.05 for difference between permissive hypercapnia and normocapnia strategy † interquartile range ‡ Score for Neonatal Acute Physiology - II # positive inspiratory pressure § post-menstrual age ** intraventricular hemorrhage
    unique: PMC2561893/PMC2561893.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Odds ratios (OR) and 95% confidence intervals (CI) for intraventricular hemorrhage comparing infants with permissive hypercapnia and normocapnia treatment strategies
  footer_text: * Adjusted for gestational age, 1-minute Apgar score, sex, outborn status, receipt of antenatal steroids, and revised SNAP-II, p > 0.28 for all models based on Hosmer-Lemeshow goodness of fit test † intraventricular hemorrhage
    unique: PMC2561893/PMC2561893.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: TABLE 4
  caption_text: Odds ratios (OR) and 95% confidence interval (CI) for intraventricular hemorrhage comparing infants with a permissive hypercapnia and normocapnia strategy of care, by one-minute Apgar score
  footer_text: * adjusted for gestational age, sex, outborn status, antenatal steroids, and revised SNAP-II † Apgar score was missing for 5 infants
    unique: PMC2561893/PMC2561893.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: TABLE 5
  caption_text: Mean scores and crude and adjusted differences in mean scores for early childhood behavior and function scores for children with a permissive hypercapnia and a normocapnia strategy of care
  footer_text: * adjusted for gestational age, one-minute Apgar score, sex, outborn status, receipt of antenatal steroids, revised SNAP-II, maternal education, race, household income, single-parent household, and interviewer † higher scores indicate more problems ‡ higher scores indicate better function
    unique: PMC2561893/PMC2561893.xml::T5-0

PMC0025XXXXX/PMC2561895.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Genotype-phenotype correlations in colorectal neoplasia
  footer_text:

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561893.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561895.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

    unique: PMC2561895/PMC2561895.xml::T1-0

PMC0025XXXXX/PMC2561898.xml

PMC0025XXXXX/PMC2561900.xml

PMC0025XXXXX/PMC2561901.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Drugs Receiving Specific Recommendation from the PAC
  footer_text: Abbreviations: AM-T = antimicrobial/transplant; AP = allergy/pulmonary; CR = cardiorenal; GI = gastroenterology; M = metabolic; N = neurologic; P = psychiatric; Pa = pain; U = urologic.
    unique: PMC2561901/PMC2561901.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Drugs Returned to Routine Monitoring by the PAC
  footer_text: Abbreviations: AM-T = antimicrobial/transplant; AP = allergy/pulmonary; CR = cardiorenal; GI = gastroenterology; H = hematologic; M = metabolic; N = neurologic; O = ophthalmologic; Pa = pain; Oc = oncologic; R = reproductive; Rh = rheumatologic; U = urologic.
    unique: PMC2561901/PMC2561901.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561901.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561901.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561905.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561905.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561902.xml

PMC0025XXXXX/PMC2561905.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sequences of Lacl DNA operator ligandsa.
  footer_text: a lacO1 is one of the naturally occurring operators found in the lac operon (19) and controls transcription in the in vivo assays described previously (4). lacOsym and lacOdisC are engineered variants (16-18).
    unique: PMC2561905/PMC2561905.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Operator binding by LLhP variantsa.
  footer_text: a DNA binding data were determined from 3−4 independent measurements, using two different preparations of protein. Reported errors represent one standard deviation. Buffer used for DNA-binding measurements was 10 mM Tris-HCl, pH 7.4, 150 mM KCl, 5% DMSO, 0.1 mM EDTA, and 0.3 mM DTT. DNA concentration was 1.5 × 10−12 M. b For LLhP variants, low affinity conditions were in the absence of hypoxanthine. For Lacl, low affinity conditions were in the presence of 1mM IPTG. c For LLhP variants, high affinity conditions included a saturating concentration of hypoxanthine (see Materials and Methods). For Lacl, no effector was present. d Low affinity binding divided by high affinity binding. e Values from (9). Lacl measurements were also repeated in parallel with LLhP and showed similar results. f NR: No response to the addition of hypoxanthine. g NBD: Very little, if any, binding detected. h The same buffer as solution scattering experiments: 0.12 mM Hepes-KOH, pH 7.6, 200 mM KCl, 5% glycerol, 1 mM EDTA, and 0.3 mM DTT.
    unique: PMC2561905/PMC2561905.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Comparison of Experimental and Model Structural Parameters for LLhP Chimera and R3: Effects of DNA and Effector Binding
  footer_text: a Total quality estimate defined in GNOM (49), equal to 1.0 for an ideal solution. Model parameters are given for b Model of apo-LLhP (see Materials and Methods). c Model of DNA-bound LLhP (see Materials and Methods). d,e,f Parameters taken from reference (23) d is the model of the apo-Lacl dimer taken from the one homodimer of the tetrameric Lacl crystal structure (1lbg chains A and B; (41)) e is the Lacl R3 dimer model optimized by refinement against the scattering data that shows the extended configuration (as opposed to the folded hinge-helix) for the linker sequence connecting the DBD and regulatory domains f is the model for R3-lacO1 taken without modification from the 1LBG crystal structure (1lbg chains A, B, E, and F). Note that this latter structure is missing 4 base pairs from the DNA sequence (17 basepairs instead of 21) and 11 amino acid residues from the protein, resulting in a somewhat higher than ideal χ2 value. g No high-resolution structures are available for the Lacl-lacO1-IPTG complex.
    unique: PMC2561905/PMC2561905.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561905.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561905.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561918.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561918.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561918.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561918.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561918.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Operator capture by LLhP and variants (× 10−7 M hypoxanthine)a.
  footer_text: a The midpoints of the operator capture experiments were determined from 3−4 independent measurements, using two different preparations of protein. Reported errors represent one standard deviation. Buffer was 10 mM Tris-HCl, pH 7.4, 150 mM KCl, 5% DMSO, 0.1 mM EDTA, and 0.3 mM DTT. The DNA concentration was ∼2 × 10−12 M and hypoxanthine concentrations were varied. Protein concentrations were chosen so that the final conditions were in the range of 70−90% saturation on affinity binding curves determined in the presence of hypoxanthine: concentrations were 1.2 to 3.3 × 10−8 M I48S; 2 × 10−9 to 1.2 × 10−8 M I48V; 1.5 × 10−9 to 2.5 × 10−9 M Q55T; 3 × 10−9 to 3 × 10−8 M Q55V; and 6 × 10−9 M S61C and S61M. b Not determined, because affinity experiments showed no allosteric response and very weak affinity (Table 2).
    unique: PMC2561905/PMC2561905.xml::T4-0

PMC0025XXXXX/PMC2561909.xml

PMC0025XXXXX/PMC2561918.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Lowest bending (B), stretching (S) and twisting (T) frequencies in cm−1 for the sequence GACTn, n = 4,6,8,10 with a salt concentration of 0.05M and T=300K.
  footer_text:
    unique: PMC2561918/PMC2561918.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mechanical constants for various DNA sequences with a salt concentration of 0.05M and T=300K. The values reported in italics and bold correspond to stiffer and more flexible characteristics than random DNA, respectively
  footer_text:
    unique: PMC2561918/PMC2561918.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Lowest in plane bending, out of plane bending, and twisting frequencies in cm−1 for the 94-base-pair minicircle (TA94) with a salt concentration of 0.05M and T=300K.
  footer_text:
    unique: PMC2561918/PMC2561918.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Mechanical constants extracted from the results presented in Table 3
  footer_text:
    unique: PMC2561918/PMC2561918.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Mechanical constants for several 94bp sequences with a salt concentration of 0.05M and T=300K.
  footer_text:
    unique: PMC2561918/PMC2561918.xml::T5-0

PMC0025XXXXX/PMC2561920.xml

PMC0025XXXXX/PMC2561922.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Expression levels of CD19 and CD22 and the cytotoxicity of immunotoxins
  footer_text: * Flow cytometry was conducted with two-step staining. First FMC63 mAb or RFB4 mAb, then goat anti-mouse PE conjugated F(ab)’2. † Cytotoxicity was determined by WST-8 cell viability assay.
    unique: PMC2561922/PMC2561922.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Relationship between internalization of RFB4 and intracellular CD22 change
  footer_text: * CD22, cell surface CD22. † RFB4, internalized RFB4. † CD22, intracellular CD22. ‡† CD22, the decrease of intracellular CD22 = †CD22- †CD22 (with RFB4).
    unique: PMC2561922/PMC2561922.xml::T2-0

PMC0025XXXXX/PMC2561923.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Knockout of genes expressed in ectodermal appendages
  footer_text:
    unique: PMC2561923/PMC2561923.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mutations in human homeobox genes affecting development of ectodermal appendages
  footer_text:
    unique: PMC2561923/PMC2561923.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561922.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561922.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561923.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561923.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561942.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Means and standard deviations for demographic and sleep-related variables
  footer_text: a Numbers in parentheses represent standard deviations b Obstructive Apnea Index c Multiple Sleep Latency Test d trend, p = .06 e OAI analyses completed on log data due to skewed distribution, but raw data presented for clarity f Pediatric Sleep Questionnaire (PSQ) subscale * p < .05 ** p < .01 *** p < .001
    unique: PMC2561942/PMC2561942.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Means and standard deviations for behavioral and cognitive test scores
  footer_text: a Wechsler Abbreviated Scale of Intelligence (WASI) b Numbers in parentheses represent standard deviations c Wechsler Individualized Achievement Test (WIAT) d Trend for significance at p < .08 or better e Children’s Memory Test (CMS) f Integrated Visual and Auditory Continuous Performance Test (IVA), Full Scale Attention Quotient (FSAQ) and Full Scale Response Control Quotient (FSRCQ) g Connors’ Parent Rating Scale: Long Version (CPRS-R:L) * p < .05 ** p < .01 *** p < .001
    unique: PMC2561942/PMC2561942.xml::T2-0

PMC0025XXXXX/PMC2561946.xml

PMC0025XXXXX/PMC2561947.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561942.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561942.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Testing Criteria
  footer_text: * Percentage of expected positive results based on the experience of the BCCA HDGC program
    unique: PMC2561947/PMC2561947.xml::T1-0

PMC0025XXXXX/PMC2561951.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Comparison of clinical variables and demographics according to status of the Sentinel Node in patients with thin primary cutaneous melanoma.
  footer_text:
    unique: PMC2561951/PMC2561951.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Distribution of positive sentinel nodes according to tumor depth and intranodal tumor burden for patients with thin primary cutaneous melanoma.
  footer_text:
    unique: PMC2561951/PMC2561951.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Patterns of first recurrence for SN negative and SN positive patients with thin primary cutaneous melanoma.
  footer_text:
    unique: PMC2561951/PMC2561951.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: TABLE 4
  caption_text: Reported results of Sentinel Lymph Node Biopsy in patients with thin (≤1.0 mm) primary cutaneous melanoma and factors correlated with a tumor-positive Sentinel Node.
  footer_text:
    unique: PMC2561951/PMC2561951.xml::T4-0

PMC0025XXXXX/PMC2561954.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic and Alcohol Use Data
  footer_text: a The two studies involved different age groups; however, there were no differences whatsoever between the two original control groups on any of the dependent variables; therefore we combined the control groups into a single non-alcoholic control (NAC) group. Measures are reported mean ± standard deviation. N/A: Not applicable b Proportion of first degree relatives who are problem drinkers
    unique: PMC2561954/PMC2561954.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561951.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561951.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561951.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561951.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561954.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Psychological Measures and Psychiatric Symptom Counts
  footer_text: a summed across anxiety, mood and externalizing domains b mood + anxiety symptoms Effect is significant * p ≤ 0.05 ** p ≤ 0.01 *** p ≤ 0.001
    unique: PMC2561954/PMC2561954.xml::T2-0

PMC0025XXXXX/PMC2561956.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561954.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2561958.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of the subjects according to the gastric cancer risk area
  footer_text: Abbreviations: SD: standard deviation; NAG: non-atrophic gastritis; MAG: multifocal atrophic gastritis without metaplasia; IM: intestinal metaplasia; PCR: polymerase chain reaction a Cases with normal histology were not included. b This category includes s1m1 + s1 and m1/m2 + s1/s2 and m1 c Eight percent of missing values in high gastric cancer risk area.
    unique: PMC2561958/PMC2561958.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Eosinophil and mast cell quantification in antral gastric mucosa according to the gastric cancer risk area
  footer_text: Abbreviations: HPF: high power field (400x); IQR: interquartile range. a Muscularis mucosae not included
    unique: PMC2561958/PMC2561958.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561958.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561958.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561958.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561958.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561958.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Eosinophil density according to histopathological diagnosis by gastric cancer risk area
  footer_text: a This value is not a median, it is the eosinophil density of the only case in that category. Abbreviations: NAG: non-atrophic gastritis; MAG: multifocal atrophic gastritis without metaplasia; IM: intestinal metaplasia; IQR: interquartile range.
    unique: PMC2561958/PMC2561958.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Odds ratios (OR) and 95% confidence intervals (CI) for advanced gastric lesions (IM and dysplasia) according to selected percentiles of the eosinophil density by gastric cancer risk area
  footer_text: a Odds ratios adjusted for H. pylori genotypes.
    unique: PMC2561958/PMC2561958.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Odds ratios (OR) and 95% confidence intervals (CI) for advanced gastric lesions (IM and dysplasia) according to selected percentiles of the mast cell density
  footer_text: a Odds ratios adjusted for H. pylori genotypes.
    unique: PMC2561958/PMC2561958.xml::T5-0

PMC0025XXXXX/PMC2561962.xml

PMC0025XXXXX/PMC2561993.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Stimulus exemplars used in the attentional set-shifting task
  footer_text: Compound discriminations were based on fixed combinations of pairs of exemplars. The exemplar pairs from different dimensions were presented in random combination, but each sequence performed by a control mouse was matched by that of a COMT-Val-tg littermate. Neutral stimuli for the different dimensions were: no outer texture; sawdust bedding (Harlan Teklad); digging medium; and no odor. The digging medium was changed often so the mice would not use odor cues to locate the bowls baited with food pellets. For 500 ml of each medium, 10 ml of crushed food pellets (about 6g) were mixed with the medium to mask the smell of the hidden food pellet. For scented mixtures, an odor (0.7g) was mixed with 500 ml of the medium and crushed pellets. a Aspen bedding, Aquarium gravel, Moss, Kay-Kob, Repti Bark (PetSmart); Alpha-dri (Shepherd Specialty Papers); CareFresh, Ultra White CareFresh (International Absorbents); Crystalit (Pharmacal Research Laboratories); PaperChip (Shepherd Specialty Papers).
    unique: PMC2561993/PMC2561993.xml::T1-0

PMC0025XXXXX/PMC2561998.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Designation, sexes and allotypes of experimental rabbits
  footer_text:
    unique: PMC2561998/PMC2561998.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Leukocyte responses to immunizations among experimental rabbitsa
  footer_text: a The mean value of the 3rd,5th and 7th boosts is shown outside the parenthesis and the highest leukocyte response of the 3rd, 5th and 7th boosts is the value within parenthesis (WBC reference range in 1000s 4–10; reference range/μl Monocytes; 0–300, Eosinophils, 0–100; and Basophils, 0–500). Neutrophil and lymphocyte counts remained within the reference ranges (reference range/μl Neutrophils 1,200–7,000 and Lymphocytes 1,200–7,000).
    unique: PMC2561998/PMC2561998.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Summary of autoantibody response among experimental rabbitsa
  footer_text: a Numbers shown are highest values among the sera collected after 3rd, 5th, and 7th boosts and numbers in parentheses are the means of these values. Mean antibody response OD values were: GR MAP-8, 2.88 +/− 0.11; anti-dsDNA, 1.40 +/− 0.72; RNP, 0.73 +/− 0.49; Sm 0.72 +/− 0.56, and ANA 1.38 +/− 0.66. Shaded cells indicate responder rabbits with a highest OD value 1 standard deviation above mean antibody responses. For ANA IFA immunofluorescence, scores are shown for pre- and post 3rd, 5th, and 7th boosts and shaded areas indicate those sera with at least one 3+ score.
    unique: PMC2561998/PMC2561998.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Correlations between leukocyte, immune, and autoantibody responses among immunized rabbits.
  footer_text: * significant at 5% level ** Significant at 1% level
    unique: PMC2561998/PMC2561998.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561993.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561998.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561998.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561998.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2561998.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562002.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Baseline Characteristics and Testing Data for 72 subjects who completed Keep the Beat program participation
  footer_text:
    unique: PMC2562002/PMC2562002.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Baseline and 3 month data for 72 subjects who completed participation in Keep the Beat
  footer_text: * Women Only (N=58) ** Subset of Participants with Flow Cytometry Data (N=21)
    unique: PMC2562002/PMC2562002.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Covariates as predictors of change in brachial artery flow-mediated dilation following 3 months of program participation, initially found significant in the stepwise model, then re-run using the general linear model with Type III sums of squares so that the P-value of each covariate reflects adjustment for all other covariates. All analyses were performed using the SAS statistical analysis package, utilizing the STEPWISE, GLM, and MEANS procedures (SAS User's Guide: Statistics, Version 9 Edition: SAS Institute Inc, Cary, NC). All reported P-values are based on two-sided t-tests.
  footer_text:
    unique: PMC2562002/PMC2562002.xml::T3-0

PMC0025XXXXX/PMC2562003.xml

PMC0025XXXXX/PMC2562027.xml

PMC0025XXXXX/PMC2562028.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562002.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562002.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562002.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562028.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Characteristics of participants at their baseline examination in The Framingham Heart Study, Framingham, MA, 1948-1975
  footer_text:
    unique: PMC2562028/PMC2562028.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Cumulative incidence of an alcohol use disorder (ICD-9 code for 100% attributable disease) between ages 40 and 79, by sex and birth cohort from The Framingham Heart Study, Framingham, MA, 1948-1975
  footer_text:
    unique: PMC2562028/PMC2562028.xml::T2-0

PMC0025XXXXX/PMC2562037.xml

PMC0025XXXXX/PMC2562040.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Mean and standard deviations of the kinematic, kinetic and temporal data from all subjects (N = 10) Statistical analysis includes results of Bonferroni corrected post-hoc paired t-tests between natural and altered conditions. When repeated measures ANOVAs testing the main effect of condition were not significant (p>0.05), post-hoc tests were not conducted (NS). Bold text indicates significant differences (p<0.05).
  footer_text:
    unique: PMC2562040/PMC2562040.xml::T1-0

PMC0025XXXXX/PMC2562042.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562028.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562040.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562162.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Developmental phenotypes of Sphk and S1P receptor null mice
  footer_text:
    unique: PMC2562162/PMC2562162.xml::T1-0

PMC0025XXXXX/PMC2562164.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sample Characteristics
  footer_text: N = 25,957
    unique: PMC2562164/PMC2562164.xml::T1-0
    unique: PMC2562164/PMC2562164.xml::T1-1
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Complications and Death Rates
  footer_text: a Patients may have suffered from more than one complication. Note. Because of incomplete or missing data, N = 24,618.
    unique: PMC2562164/PMC2562164.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562162.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562164.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562164.xml::T1-1'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562164.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Most Common Complications and Death Rates by Tumor Type
  footer_text: Note. Because of incomplete or missing data, N = 24,618.
    unique: PMC2562164/PMC2562164.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Selected Complication Rates by Emergency Department Source of Admission
  footer_text: a p < 0.001 for all complications Note. Because of incomplete or missing data, N = 24,618.
    unique: PMC2562164/PMC2562164.xml::T4-0

PMC0025XXXXX/PMC2562167.xml

PMC0025XXXXX/PMC2562168.xml

PMC0025XXXXX/PMC2562170.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562164.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562164.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patient demographics (N = 133)
  footer_text: * Other includes Hispanic and Asian
    unique: PMC2562170/PMC2562170.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Location of tumors
  footer_text: N/A = Not applicable.
    unique: PMC2562170/PMC2562170.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Characteristics of Chemotherapy [Median- 3 cycles (range: 1–24 cycles)]
  footer_text: * Cyclophosphamide, vincristine, adriamycin, predinsone, Rituxmab
    unique: PMC2562170/PMC2562170.xml::T3-0

PMC0025XXXXX/PMC2562171.xml

PMC0025XXXXX/PMC2562173.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Demographic and clinical characteristics of 116 HIV-positive children at enrollment in an observational study of macronutrient intake1
  footer_text: 1 Enrollment is defined as the first qualifying dietary intake. CDC, Centers for Disease Control and Prevention; HAART, highly active antiretroviral therapy. 2 The initial CDC stage was missing for one child from the Boston cohort. 3 Medians; range in parentheses (all such values). 4 Years after the beginning of the study (14 February 1995) that a patient’s first qualifying dietary intake occurred. 5 n = 79 for the Boston cohort, and n = 12 for the Rochester cohort.
    unique: PMC2562173/PMC2562173.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Regression estimates of anthropometric and dietary characteristics among 116 HIV-positive children in 19951
  footer_text: 1 All values are means unless designated as proportions and expressed as percentages (see footnote 3); 95% CIs in parentheses (all such values). For some variables, the number of male/female subjects (observations) was different from that indicated in the table header. CD4: 45/60 (275/353); sugar: 46/62 (216/273); monounsaturated and saturated fat: 47/66 (284/341); polyunsaturated fat: 45/65 (275/331); dietary fiber: 48/66 (287/350); and cholesterol: 48/66 (290/353). Sex-specific means or proportions at the beginning of the study period with 50% weight on each center and their 95% CIs were estimated with generalized linear models including center, sex, years since the beginning of the study (14 February 1995), and the interaction between years and sex. HAART, highly active antiretroviral therapy; AMC, arm-muscle circumference; EER, estimated energy requirement; RDA, Recommended Dietary Allowance; AI, adequate intake; USDA, US Department of Agriculture. 2 Estimates were obtained by using generalized estimating equations with an exchangeable working correlation structure to account for potential correlations between repeated measurements on the same individuals. The estimated proportion was calculated using the logit link and applying backtransformation to the sex-specific intercepts. A working independence correlation structure was used to model the proportion of HAART-exposed children because of convergence problems with an exchangeable working correlation structure. P value for the 2-sided Wald test of no sex difference in the estimated mean or proportion at the beginning of the study period (no sex difference in intercepts in the generalized linear model). 3 Estimated proportion from the generalized linear model expressed as a percentage.
    unique: PMC2562173/PMC2562173.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Regression estimates of anthropometric and dietary characteristics among 116 HIV-positive children in 20041
  footer_text: 1 All values are means unless designated as proportions and expressed as percentages (see footnote 3); 95% CIs in parentheses (all such values). For some variables, the number of male/female subjects (observations) was different from that indicated in the table header. CD4: 45/60 (275/353); sugar: 46/62 (216/273); monounsaturated and saturated fat: 47/66 (284/341); polyunsaturated fat: 45/65 (275/331); dietary fiber: 48/66 (287/350); and cholesterol: 48/66 (290/353). Sex-specific means or proportions at the end of the study period with 50% weight on each center and their 95% CIs were estimated with generalized linear models including center, sex, years since the beginning of the study (14 February 1995), and the interaction between years and sex. HAART, highly active antiretroviral therapy; AMC, arm-muscle circumference; EER, estimated energy requirement; RDA, Recommended Dietary Allowance; AI, adequate intake; USDA, US Department of Agriculture. 2 Estimates were obtained by using generalized estimating equations with an exchangeable working correlation structure to account for potential correlations between repeated measurements in the same individuals. The estimated proportion was calculated by using the logit link and applying backtransformation to the sex-specific linear predictors at the end of the study period.A working independence correlation structure was used to model the proportion of HAART-exposed children because of convergence problems with an exchangeable working correlation structure. P value for the two-sided Wald test of no sex difference in the estimated mean or proportion at the end of the study period (no sex difference in linear predictors from the generalized linear model at the end of the study period). 3 Estimated proportion from the generalized linear model expressed as a percentage.
    unique: PMC2562173/PMC2562173.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562173.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562173.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562173.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562173.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: TABLE 4
  caption_text: Regression estimates of per-annum changes in anthropometric and dietary characteristics among 116 HIV-positive children from 1995 to 20041
  footer_text: 1 For some variables, the number of male/female subjects (observations) was different from that indicated in the table header. CD4 (%): 45/60 (275/353); sugar: 46/62 (216/273); monounsaturated and saturated fat: 47/66 (284/341); polyunsaturated fat: 45/65 (275/331); dietary fiber: 48/66 (287/350); cholesterol: 48/66 (290/353). OR, odds ratio; HAART, highly active antiretroviral therapy; AMC, arm-muscle circumference; EER, estimated energy requirement; RDA, Recommended Dietary Allowance; AI, adequate intake; USDA, US Department of Agriculture. 2 Sex-specific per-annum changes or ORs and their 95% CIs were estimated with generalized linear models including center, sex, years since the beginning of the study (14 February 1995), and the interaction between years and sex. Estimates were obtained by using generalized estimating equations with an exchangeable working correlation structure to account for potential correlations between repeated measurements in the same individuals. The logit link was used for proportions. A working independence correlation structure was used to model the proportion of HAART-exposed children because of convergence problems with an exchangeable working correlation structure. 3 P value for the 2-sided Wald test of no per-annum trend (zero sex-specific years effect in the generalized linear model). 4 P value for the 2-sided Wald test of no sex difference in per-annum trends (no interaction between years and sex in the generalized linear model). 5 Estimated per-annum OR from the generalized linear model.
    unique: PMC2562173/PMC2562173.xml::T4-0

PMC0025XXXXX/PMC2562174.xml

PMC0025XXXXX/PMC2562195.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Migratory behavior of myeloid cells varies with the tumor microenvironment
  footer_text: Velocity of c-fms+ cells were computed from four 1-hour-long time-lapse movies of 200×200 μm fields per microenvironment. Fields with normal epithelium and hyperplasia also contained some of the adjacent stroma. The distribution of myeloid cell velocities differed significantly between the microenvironments (P<0.0001, chi-squared test).
    unique: PMC2562195/PMC2562195.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Migratory behavior varies with dextran ingestion
  footer_text: Velocity of c-fms+, and 10 kDa and 2 MDa dextran-ingesting cells were computed from five fields of tumor-stroma border areas (hyperplasia, early and late carcinomas) in 1-hour-long time-lapse movies. The distribution of cell velocities differed significantly between the cell types (P<0.0001, chi-squared test).
    unique: PMC2562195/PMC2562195.xml::T2-0

PMC0025XXXXX/PMC2562217.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562195.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562195.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562217.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Percentage of retrogradely labeled neurons in different regions of the VNLL after BDA injections in the CNIC.
  footer_text: 1 Cases were classified as low-, mid- or high-frequency according to the location of retrogradely labeled cells in the contralateral cochlear nucleus (see Cant and Benson, 2006b for details).
    unique: PMC2562217/PMC2562217.xml::T1-0

PMC0025XXXXX/PMC2562219.xml

PMC0025XXXXX/PMC2562222.xml

PMC0025XXXXX/PMC2562225.xml

PMC0025XXXXX/PMC2562226.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Growth Inhibition of Pancreatic Cancer Cell Lines by PP and PSP Analogues Compared with Untreated Control
  footer_text:
    unique: PMC2562226/PMC2562226.xml::T1-0

PMC0025XXXXX/PMC2562228.xml

PMC0025XXXXX/PMC2562230.xml

PMC0025XXXXX/PMC2562231.xml

PMC0025XXXXX/PMC2562237.xml

PMC0025XXXXX/PMC2562238.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562226.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562239.xml

PMC0025XXXXX/PMC2562242.xml
  ----------------------------------------
  id: T4
  label_text: APPENDIX 1
  caption_text: ICD-9 CODES USED FOR IDENTIFICATION OF SUBJECTS
  footer_text:
    unique: PMC2562242/PMC2562242.xml::T4-0
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Characteristics of Admissions for Children With Severe TBI in the 6-State Cohort (N = 2117)
  footer_text:
    unique: PMC2562242/PMC2562242.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: State and HRR Characteristics
  footer_text:
    unique: PMC2562242/PMC2562242.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Regionalization of Severe Pediatric TBI According to Presence of High-Level or Level II Centers in HRRs
  footer_text:
    unique: PMC2562242/PMC2562242.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562242.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562242.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562242.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562244.xml

PMC0025XXXXX/PMC2562245.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Bland Altman comparison of 2D breath-hold and free-breathing measurements of left ventricular function.
  footer_text: SD = standard deviation, FB = free-breathing, BH = breath-hold, EDV = end-diastolic volume, ESV = end-systolic volume, EDM = end-diastolic mass, EF = ejection fraction.
    unique: PMC2562245/PMC2562245.xml::T1-0

PMC0025XXXXX/PMC2562246.xml
  ----------------------------------------
  id: T3
  label_text:
  caption_text:
  footer_text:
    unique: PMC2562246/PMC2562246.xml::T3-0
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Photophysical and physiological parameters used in the simulation
  footer_text: * On the basis of published reports 4, 5,16, we estimate that the mTHPC concentrations in murine tumors at 3, 6, 24 and 96 h following i.v. injection (0.3 mg kg-1) are 0.3, 0.42, 0.54, and 0.18 μg ml-1, assuming a tissue density of 1 g cm-3. Using these data and methods described in Wang et al.8, we calculate βPDT at 650 nm at the capillary wall to be 0.063, 0.045, 0.021 and 0.006 for the cases of nonuniform mTHPC distribution at 3, 6, 24 and 96 h drug-light intervals, respectively.
    unique: PMC2562246/PMC2562246.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562245.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562246.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562246.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562246.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text:
  footer_text: Mean recurrence-free survival of mTHPC- PDT-treated tumors illuminated with 100 mW cm-2 and 30 J cm-2 reproduced from Fig. 3 of Cramers et al.4 and Fig. 2A of Triesscheijn et al.5. The recurrence-free interval is defined by the time taken for a tumor diameter to increase 2 mm from its treatment size. Tumors that had not regrown within 120 days were defined as cured.
    unique: PMC2562246/PMC2562246.xml::T2-0

PMC0025XXXXX/PMC2562247.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean Percentage of Presented faces (SD in parentheses) Resulting in Name Errors (Occupation Correctly Remembered but Not Name) and Occupation Errors (Name Correctly Remembered but Not Occupation) for Young and Older Adults in Experiments 1 and 2
  footer_text:
    unique: PMC2562247/PMC2562247.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mean Percentage Correct (SD in parentheses) for Names and Occupations for Young and Older Adults in the Initial Testing Round for Experiments 1 and 2
  footer_text:
    unique: PMC2562247/PMC2562247.xml::T2-0

PMC0025XXXXX/PMC2562248.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Exogenous IGF-1 does not alter surface expression of CD80, CD86 or CD23 by GD or control B cells
  footer_text: PBMC were isolated and cultured with or without CpG (2 μg/ml) and IGF-1 (10 ng/ml) for 48 hours and assayed for expression of CD80, CD86, CD23 Each datum point represents percent positive-staining CD19+ B cells ± S.E.M. All comparisons of treatments compared to their respective controls were not significant
    unique: PMC2562248/PMC2562248.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562247.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562247.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562248.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562250.xml

PMC0025XXXXX/PMC2562252.xml

PMC0025XXXXX/PMC2562253.xml

PMC0025XXXXX/PMC2562255.xml
  ----------------------------------------
  id: T1
  label_text: Table
  caption_text: Distinguishing features of chromosomal translocations that activate cellular oncogenes or generate novel fusion genes
  footer_text:
    unique: PMC2562255/PMC2562255.xml::T1-0

PMC0025XXXXX/PMC2562256.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: List of measured INEE values for various detector systems and the normalized INEE for 150 μm × 150 μm pixel area.
  footer_text:
    unique: PMC2562256/PMC2562256.xml::T1-0

PMC0025XXXXX/PMC2562257.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562255.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562256.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562257.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562262.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Association studies of STAT4 with autoimmune diseases. Allele frequencies and association statistics are given for the disease-associated SNP rs7574865
  footer_text: * The 1039 SLE cases reported in Remmers et al. are a subset of the 1380 cases reported in Hom et al.
    unique: PMC2562257/PMC2562257.xml::T1-0

PMC0025XXXXX/PMC2562258.xml

PMC0025XXXXX/PMC2562262.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mass and fluoride concentrations (mean ± standard error) in saliva samples obtained overnight after use of a calcium lactate pre-rinse followed by a 228 μg/g F rinse, a 228 or 912 μg/g F rinse alone (with no pre rinse), or a distilled water rinse.
  footer_text: For saliva fluoride, means followed by different superscript letters have a statistically significant difference (Holm-Sidak pairwise multiple comparison test, p < 0.05). The 912 μg/g F rinse data was obtained 6 months later and hence was not included in the statistical analysis. * Data were obtained from centrifuged saliva.
    unique: PMC2562262/PMC2562262.xml::T1-0

PMC0025XXXXX/PMC2562263.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Redox Isomerization under Indium Trichloride Cocatalysis
  footer_text: Reactions were performed on 1 mmol scale at 0.25M with 5% catalyst 2 and 40% InCl3 in THF at reflux. For primary alcohols 5% NH4PF6 and 5% Et3NHPF6 was added. For secondary alcohols 10% Et3NHPF6 was added.
    unique: PMC2562263/PMC2562263.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Isomer ization under Indium Triflate Cocatalysis
  footer_text: a) Reactions were performed on 1 mmol scale in THF at reflux. Yield refers to isolated yields. b) The product in this case is 4- keto-n-decanal.
    unique: PMC2562263/PMC2562263.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562263.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562263.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562265.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562264.xml

PMC0025XXXXX/PMC2562265.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: 13C and 1H NMR data for compounds 1 and 2, δ in ppm (quantity, multiplicity and J/Hz).
  footer_text: a d6-acetone, 100.6 MHz. b d6-acetone, 400 MHz.
    unique: PMC2562265/PMC2562265.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Cytotoxicity assay of moromycins A (1) and B (2) in comparison with saquayamycin B (3) against human lung H-460 and human breast MCF-7 cancer cell lines (given are GI50, TGI and LC50 values in µmol). The data represent the average of three measurements.
  footer_text: GI50= 50% inhibition of cell growth; TGI=total growth inhibition; LC50=50% lethal concentration.
    unique: PMC2562265/PMC2562265.xml::T2-0

PMC0025XXXXX/PMC2562266.xml
  ----------------------------------------
  id: T4
  label_text:
  caption_text: Appendix Word lists used in the baseline and experimental categorization tasks. Each list contained equal numbers of words referring to people, food, and animals
  footer_text:
    unique: PMC2562266/PMC2562266.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562265.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562266.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562266.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562266.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Individual hearing thresholds (in dB HL) for the children with minimal HL as well as the average hearing thresholds (and standard deviation) for both the children with HL and the children with NH. The values in parentheses were not included in the calculation of averages. The amplification status of the children with minimal HL is also given (B=both ears, R=Right ear, L=Left ear, N=No amplification). Hearing losses are listed from mild to high-frequency to unilateral. The hearing losses of a few children were considered combinations of two configurations and are listed at the boundaries of each category.
  footer_text:
    unique: PMC2562266/PMC2562266.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Average baseline and experimental dot rates (dots per minute) for each multitasking condition for the children with normal hearing (NH) and the children with minimal hearing loss (HL). Values in parentheses are standard error. Numbers in italics are the result of paired samples t-tests (t, p, and Cohen’s d). Note that the same games were played in each listening condition and that the baseline dot rates were not obtained in noise.
  footer_text: * Significantly different from baseline as indicated by paired samples t-test (p ≤ 0.017, Bonferroni adjustment).
    unique: PMC2562266/PMC2562266.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Average word categorization (percent correct) for the baseline and multitasking conditions for the children with normal hearing (NH) and the children with minimal hearing loss (HL). Values in parentheses are standard error. Numbers in italics are the result of paired samples t-tests (t, p, and Cohen’s d)
  footer_text: * Significantly different from baseline as indicated by paired samples t-test (p ≤ 0.017, Bonferroni adjustment).
    unique: PMC2562266/PMC2562266.xml::T3-0

PMC0025XXXXX/PMC2562271.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562266.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562271.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562271.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562271.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562271.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Results of switching from injection to CSII therapy in non-randomized pediatric studies
  footer_text:
    unique: PMC2562271/PMC2562271.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Results of Randomized clinical trials comparing CSII and MDI in patients with type 1 DM
  footer_text: * p <0.05
    unique: PMC2562271/PMC2562271.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Indications for use of CSII in Pediatrics (adapted from Reference 66)
  footer_text:
    unique: PMC2562271/PMC2562271.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Pump Options and Features
  footer_text:
    unique: PMC2562271/PMC2562271.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Correction Factors and Carbohydrate Ratio Based on Age for Initial Pump Settings
  footer_text: * Often a lower carbohydrate ratio is needed for breakfast (-2 grams for breakfast carb ratio). For example for children <3, start breakfast carbohydrate ratio at 43 grams.
    unique: PMC2562271/PMC2562271.xml::T5-0

PMC0025XXXXX/PMC2562272.xml

PMC0025XXXXX/PMC2562273.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline characteristics of all patients.
  footer_text: Abbreviations: ECOG, Eastern Cooperative Oncology Group; UWCCC, University of Wisconsin Paul P. Carbone Comprehensive Cancer Center; WON, Wisconsin Oncology Network.
    unique: PMC2562273/PMC2562273.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Maximal severity of toxicities per phase I patient and type regardless of attribution to study drugs occurring in ≥ 20% patients.
  footer_text: * National Cancer Institute Common Toxicity Criteria version 2.0 Abbreviations: BID, twice daily; n, number; q, every; AM, morning; PM, evening.
    unique: PMC2562273/PMC2562273.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Maximal severity of toxicities per phase II patient and type regardless of attribution to study drug occurring in ≥ 20% of patients (n=30).
  footer_text: * National Cancer Institute Common Toxicity Criteria, version 2.0. ^ Two patients had cataracts & One patient was status/post cerebrovascular accident and another patient had cataracts. Abbreviations: n, number.
    unique: PMC2562273/PMC2562273.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562273.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562273.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562273.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562273.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Efficacy.
  footer_text: Abbreviations: TTP, time-to-progression; OS, overall survival; CI, confidence interval.
    unique: PMC2562273/PMC2562273.xml::T4-0

PMC0025XXXXX/PMC2562281.xml

PMC0025XXXXX/PMC2562285.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic characteristics of 180 syphilis patients and of the overall clinical cohort.
  footer_text: NOTE. Data are no. (%) of patients, unless otherwise indicated.
    unique: PMC2562285/PMC2562285.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Clinical characteristics of 231 cases of syphilis.
  footer_text: NOTE. Data are no. (%) of cases, unless otherwise indicated. IQR, interquartile range; RPR, rapid plasma reagin. a Includes primary syphilis, secondary syphilis, and early latent syphilis. b At the time of syphilis diagnosis. c Any time during follow-up.
    unique: PMC2562285/PMC2562285.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Multivariable predictors of serologic failure overall and by type of failure (4-fold increase in titers vs. lack of 4-fold decrease and early failure vs. late failure) among 180 HIV-infected patients.
  footer_text: NOTE. The multivariable model adjusted for sex, race, previous history of syphilis, baseline RPR titer, and type of syphilis therapy received. The Andersen-Gill method was used to adjust for the multiple failure-instance data (180 subjects had 231 cases of syphilis and 71 instances of serologic failure overall). NA, not applicable; Ref, reference; RPR, rapid plasma reagin test. a Early failure is defined as serologic failure occurring ≤365 days after therapy for early stage syphilis and ≤730 days after therapy for the late stages. b Late failure is defined as serologic failure occurring >365 days after therapy for early stage syphilis and >730 days after therapy for the late stages. c Defined as <400 copies/mL. d Defined as >50% increase in CD4 cell count from baseline measured as a continuous change during follow-up. e Ninety-seven percent of macrolide therapy involved the administration of azithromycin (mean dosage, 1100 mg/week); 3% involved clarithromycin (mean dosage, 7000 mg/week). f NA denotes a lack of 4-fold decrease, which, by definition, precludes seroreversion.
    unique: PMC2562285/PMC2562285.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562285.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562285.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562285.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562285.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562288.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Multivariable predictors of rapid plasma reagin (RPR) seroreversion in the HIV cohort.
  footer_text: NOTE. The multivariable model adjusted for sex, race, previous history of syphilis, type of syphilis therapy received. Ref, reference. a Early syphilis includes primary, secondary, and early latent stages of syphilis. b Defined as <400 copies/mL. c Ninety-seven percent of macrolide therapy involved the administration of azithromycin (mean dosage, 1100 mg/week); 3% involved clarithromycin (mean dosage, 7000 mg/week).
    unique: PMC2562285/PMC2562285.xml::T4-0

PMC0025XXXXX/PMC2562288.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Subjects and results for the current experiment.
  footer_text: * Independent sample t-test, two-tailed
    unique: PMC2562288/PMC2562288.xml::T1-0

PMC0025XXXXX/PMC2562290.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Clinical characteristics of affected men (n=542)
  footer_text: * Column subtotals do not sum to 542 due to missing data. † Median and [interquartile range]. ‡ Number and (percentage) of men with prostate cancer who underwent radical prostatectomy.
    unique: PMC2562290/PMC2562290.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Major allele frequencies and FBAT results (n=403 families)
  footer_text: Note: rs4430796 and rs7501939 are in strong linkage disequilibrium (r2=0.68) * Based on the combined sample of men with and without prostate cancer and an additive genetic model for the major allele. † Number of informative families.
    unique: PMC2562290/PMC2562290.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Comparison of odds ratios (ORs) for 17q SNPs tested in the University of Michigan (UM), Gudmundsson et al., and the Cancer Genetic Markers of Susceptibility (CGEMS) studies
  footer_text: Note: Odds ratios were computed under an additive genetic model. * Before conducting the conditional logistic regression analyses, we excluded 38 men (from 10 families) who were not brothers of the index case, resulting in a reduced sample size of 977 men and 604 DSPs. † Logistic regression as reported by Gudmundsson et al. (2007), all samples combined (1,501 cases and 11,289 controls) ‡ Logistic regression, unadjusted for covariates (1,155 cases and 1,106 controls)
    unique: PMC2562290/PMC2562290.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562290.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562290.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562290.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562291.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562291.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562291.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562291.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Recurrent versus non-recurrent diarrhea in relation to height and weight gains.
  footer_text: * >30% prevalence over subsequent 2 cm ** p=0.1 (21% less) *** p=0.01 (43% less) Data from Schorling and Guerrant (1990)29 and Schorling et al. (1990)39
    unique: PMC2562291/PMC2562291.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Emerging causes of persisting diarrhea in shantytowns in Fortaleza northeastern Brazil.
  footer_text: * p<0.05 ** p<0.02 Data from Steiner et al. (1998),12 Lima et al. (2000),61 Fang et al. (1995),195 and Moore et al. (2000)196
    unique: PMC2562291/PMC2562291.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Effect of malnutrition on both the incidence and duration of diarrhea.
  footer_text: * Wilcoxon rank sum test. Also valid for moderate MN (<90% HAZ) Data from Guerrant et al. (1992)11 and Schorling et al. (1990)39
    unique: PMC2562291/PMC2562291.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Effects from early childhood diarrhea/enteric infections on lasting disability.
  footer_text: Abbreviations: AASS, age at starting school; AFG, age for grade; EAEC, enteroaggregative E. coli; HAZ-2, height for age Z score at 2 years; HST, Harvard Step Test scores; TONI, Test of Nonverbal Intelligence; WISC, Wechsler Intelligence Scale for Children; →, predisposes to.
    unique: PMC2562291/PMC2562291.xml::T4-0

PMC0025XXXXX/PMC2562292.xml

PMC0025XXXXX/PMC2562294.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562291.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562295.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562299.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562295.xml
  ----------------------------------------
  id: T1
  label_text: Table
  caption_text: Disaccharide composition analysis of CS-A, CS-C, and chondro-4-sulfatase-treated CS-A Unsaturated disaccharides generated by digestion with cABC were analyzed by anionexchange HPLC after labeling with the fluorophore 2AB as described in Materials and Methods section. The values obtained from 3 independent experiments were used to calculate the percentage of each unsaturated disaccharide (mean ± SD).
  footer_text: a ΔDi-0S=DHexUA-GalNAc; ΔDi-6S=DHexUA-GalNAc(6-O-sulfate); ΔDi-4S=DHexUA-GalNAc(4-O-sulfate); ΔDi-2,6S=DHexUA(2-O-sulfate)-GalNAc(6-O-sulfate); ΔDi-4,6S=DHexUA-GalNAc(4,6-O-disulfate); ΔDi-2,4,6S=DHexUA(2-Osulfate)-GalNAc(4,6-O-sulfate).
    unique: PMC2562295/PMC2562295.xml::T1-0

PMC0025XXXXX/PMC2562297.xml

PMC0025XXXXX/PMC2562299.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Effects of Eribulin and ER-076349 on Centromere Dynamics
  footer_text: Between 6 and 11 pairs of centromeres from between 5 and 7 cells were measured for each condition. *, **, *** Values were significantly different from control values at the 95%, 98%, or 99% confidence level, respectively (Student’s t test). § The mean for all tracings of the two maximal separations (peaks) or the two minimal separations (valleys) during each 5-min tracing for each condition.
    unique: PMC2562299/PMC2562299.xml::T1-0

PMC0025XXXXX/PMC2562300.xml
  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: The time scales τi (ns), for models with 120, 6 and 14 states, calculated using τ = 100 ps.
  footer_text:
    unique: PMC2562300/PMC2562300.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562300.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562300.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562301.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562316.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: TABLE II
  caption_text: The characterization of the Markov models with 2, 4 and 6 states in terms of the dihedral angle conformations. The lifetimes of the states, from eq (32), are in bold.
  footer_text: a This macrostate contains two microstates (the two black points in Figures 3a and 3b), which have very similar values for all the five dihedrals, μi ≈ (−170°, 160°, −95°, 75°, −100°).
    unique: PMC2562300/PMC2562300.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE III
  caption_text: Populations (%) and lifetimes (ns) of the 14-state Markov model, normalized separately for conformations with χ3 ≈ −90° (states 1 to 7), and χ3 ≈ 90° (states 8 to 14). The states with χ1 ≈ 60° are indicated with a star.
  footer_text: a Used in Figures 3 and 4.
    unique: PMC2562300/PMC2562300.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: TABLE IV
  caption_text: Parameters used in the simulation of the ESR spectra from the MD and the Markov chain trajectories.
  footer_text: a Twice as many points were used with the Markov trajectories. b Four times more points were used with the Markov trajectories.
    unique: PMC2562300/PMC2562300.xml::T4-0

PMC0025XXXXX/PMC2562301.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Relationship Between PPy Film Thickness and Charge Passed per Area
  footer_text: * Calculated from Equation [4] (Stankovic, et al. 1994).
    unique: PMC2562301/PMC2562301.xml::T1-0

PMC0025XXXXX/PMC2562302.xml

PMC0025XXXXX/PMC2562305.xml

PMC0025XXXXX/PMC2562314.xml

PMC0025XXXXX/PMC2562316.xml
  ----------------------------------------
  id: T5
  label_text: Table A1
  caption_text: Substance use patterns, by substance
  footer_text: Moderate/heavy alcohol use = 1 if respondent reported being drunk several times or more often in the last 12 months. Moderate/heavy marijuana (or other illicit drug) use = 1 if caregiver reported using marijuana (or other illicit drug) several times or more often in the last 12 months.
    unique: PMC2562316/PMC2562316.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table A2
  caption_text: Relative Risk Ratios from Models in Table 2
  footer_text: a -Numbers in [] show the marginal effect compared to women with light/no use in both waves. Thus, women with increased use are 8 percentage points more likely to be detached compared to women with light/no use in both waves. * = p < .10 ** = p < .05 *** =p<.01
    unique: PMC2562316/PMC2562316.xml::T6-0
  ----------------------------------------
  id: T7
  label_text: Table A3
  caption_text: Odds Ratios from models in Table 3
  footer_text: a Numbers in [] show the marginal effect compared to women with light/no use in both waves. Thus, women who reduced substance use between waves are 22 percentage points more likely to lose insurance compared to women with light/no use in both waves. * = p < .10 ** = p < .05 *** =p<.01
    unique: PMC2562316/PMC2562316.xml::T7-0
  ----------------------------------------
  id: T8
  label_text: Table A4
  caption_text: Odds Ratios from models in table 4
  footer_text: BSI=Brief Symptom Inventory, CBCL=Child Behavior Checklist, TANF=Temporary Assistance to Needy Families. a Numbers in [] show the marginal effect compared to women with light/no use in both waves. Thus, women who increased substance use between waves are 18 percentage points less likely to report that child behavior improved between waves. * = p < .10 ** = p < .05 *** =p<.01
    unique: PMC2562316/PMC2562316.xml::T8-0
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of Female Caregivers at Wave 1 and Wave 2
  footer_text: a Weights make population representative of Boston, Chicago, and San Antonio neighborhoods sampled. b Races other than Black or White accounted for 2.7% of the sample, and no women in the study were of black race and Hispanic ethnicity. c Education is reported for wave 2 only because measured education is not directly comparable between waves 1 and 2, as described in footnote 17 of the survey documentation publication, “Welfare, Families, and Children: A Three-City Study,” Fomby, P., Estacion, A. and Moffit, R., Johns Hopkins University, 2003, (available at http://web.jhu.edu/threecitystudy/images/CharacteristicsReport.pdf). d BSI=Brief Symptom Inventory, CBCL=Child Behavior Check List.
    unique: PMC2562316/PMC2562316.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562316.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562316.xml::T7-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562316.xml::T8-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562316.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Wave 2 work and income assistance according to change in substance use between waves 1 and 2
  footer_text: * = p < .10 ** p < .05, ***p<.01 for test of share in this category compared with the “Light/no use” category in multinomial logit models controlling for black race, Hispanic ethnicity, and high school degree, marital and cohabitation status, and age (<30 or 40+) at wave 2 interview and wave 1 work and TANF status.
    unique: PMC2562316/PMC2562316.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Health insurance and patterns of substance use between waves 1 and 2
  footer_text: * = p < .10 ** p < .05 *** p<.01 for test of difference between this category compared with the “No change No/light use” category in logistic regression models controlling for high school degree, marital and cohabitation status, black race, Hispanic ethnicity, and age (<30 or 40+) at wave 2 and wave 1 work and TANF status. Estimate of “lost health insurance” applies to 1150 caregivers with health insurance in wave 1, while “gained health insurance” model applies to 473 caregivers without health insurance in wave 1.
    unique: PMC2562316/PMC2562316.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Well-being and patterns of substance use between waves 1 and 2
  footer_text: * = p < .10 ** = p < .05 *** =p<.01 for test of difference between this category compared with the “No change No/light use” category in logistic regression models controlling for high school degree, marital and cohabitation status, black race, Hispanic ethnicity, and age (<30 or 40+) at wave 2 interview and wave 1 work and TANF status.
    unique: PMC2562316/PMC2562316.xml::T4-0

PMC0025XXXXX/PMC2562318.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Means and Standard Deviations for the Big Five T Scores by Age Categories
  footer_text: Note: BHPS = British Household Panel Study; GSEOP = German Socio-Economic Panel Study; T scores were created by standardizing scores to the mean and SD for individuals ages 30 to 34 within each sample.
    unique: PMC2562318/PMC2562318.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Regression Models Linking Age to the Big Five
  footer_text: Note: Unstandardized coefficients reported. Standard errors reported inside parentheses. Age was mean-centered within each sample (Age in BHPS = 45.50; Age in GSOEP = 46.09). More complicated models involving age polynomials were selected only when the inclusion of the higher order term improved overall model fit at F > 25.00. Coefficients for age were reported from the final selected model within each sample. See text for complete details and justification of the model selection strategy.
    unique: PMC2562318/PMC2562318.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562316.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562316.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562316.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562318.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562318.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562318.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562322.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Effect Sizes for Gender and Education Differences by Age Categories
  footer_text: Note: BHPS = British Household Panel Study; GSEOP = German Socio-Economic Panel Study. Effect sizes for gender were calculated so that positive scores indicated that women scored higher than men. Effect sizes for education were calculated so that positive scores indicated that more educated individuals scored higher than less educated individuals.
    unique: PMC2562318/PMC2562318.xml::T3-0

PMC0025XXXXX/PMC2562322.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Kinetic and thermodynamic fitting parameters for wild-type E:THF:NADP+ 15N R2 relaxation dispersion curves at different pH and temperatures
  footer_text: 1 not determined; although conformational exchange is still apparent in the cofactor binding cleft, the R2 relaxation dispersion curves are not of sufficient quality to determine Δw, kex or pApB values
    unique: PMC2562322/PMC2562322.xml::T1-0

PMC0025XXXXX/PMC2562323.xml

PMC0025XXXXX/PMC2562325.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Leakage due to the voxel-shift operation (see Figure 4). The percentages represent the relative deviation of the reconstructed peak-areas from their nominal values based on the spatial overlap of a center voxel of the imaging grid with the phantom partitions. The “–” sign indicates “leakage out” and the “+” —“ leakage in”.
  footer_text:
    unique: PMC2562325/PMC2562325.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Leakage due to interpolation and voxel-shift operations (see Figure 5). The percentages represent the relative deviation of the reconstructed peak-areas from their nominal values based on the spatial overlap of a center voxel of the imaging grid with the phantom partitions. The “–” sign indicates “leakage out” and the “+” —“ leakage in”.
  footer_text:
    unique: PMC2562325/PMC2562325.xml::T2-0

PMC0025XXXXX/PMC2562329.xml

PMC0025XXXXX/PMC2562332.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562325.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562325.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562336.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562336.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562336.xml::TA1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562336.xml::TA2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562336.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: List 2 recall by age group, condition, and experiment. Values in brackets represent standard deviations
  footer_text:
    unique: PMC2562336/PMC2562336.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Intrusion Errors as a Function of List, Age and Cue
  footer_text:
    unique: PMC2562336/PMC2562336.xml::T2-0
  ----------------------------------------
  id: TA1
  label_text:
  caption_text:
  footer_text:
    unique: PMC2562336/PMC2562336.xml::TA1-0
  ----------------------------------------
  id: TA2
  label_text:
  caption_text:
  footer_text:
    unique: PMC2562336/PMC2562336.xml::TA2-0

PMC0025XXXXX/PMC2562337.xml

PMC0025XXXXX/PMC2562338.xml

PMC0025XXXXX/PMC2562339.xml

PMC0025XXXXX/PMC2562340.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sample Demographic and Diabetes-Related Characteristics (N=81)
  footer_text: Note: For diabetes quality of life, parenting style, conflict, and parent responsibility-sharing, higher scores indicate higher levels of that particular dimension; for example, greater quality of life, greater conflict, greater parent responsibility.
    unique: PMC2562340/PMC2562340.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Correlation of demographic and disease characteristics, diabetes-specific parent-child behaviors, and diabetes quality of life
  footer_text: * P ≤ .05; ** P < .01; † P < .10
    unique: PMC2562340/PMC2562340.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Multiple regression of diabetes quality of life at baseline and 12-month follow-up on baseline parenting style
  footer_text: ‡ Standardized beta coefficients.
    unique: PMC2562340/PMC2562340.xml::T3-0

PMC0025XXXXX/PMC2562341.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562340.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562340.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562340.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic and context data for 305 persons who lived and/or worked around nonhuman primates, Asia*
  footer_text: * SFV+, simian foamy virus positive. † Predominant form of human-nonhuman primate contact at the time of the study.
    unique: PMC2562341/PMC2562341.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Persons at high risk for SFV, Asia*
  footer_text: * WB, Western blot; SFV, simian foamy virus; NA, not applicable. † 65/213 serum samples were bioplex reactive and further screened with glutathione S-transferase-Gag ELISA.
    unique: PMC2562341/PMC2562341.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Exposure characteristics of SFV-positive persons who had had contact with nonhuman primates, Asia*
  footer_text: * SFV, Simian foamy virus; NA, not applicable. All persons were confirmed SFV positive by Western blot.
    unique: PMC2562341/PMC2562341.xml::T3-0

PMC0025XXXXX/PMC2562342.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Numbers and characteristics of monkeys included in the study at each site
  footer_text: CR: Caloric restriction group; AL: Ad libitum control group
    unique: PMC2562342/PMC2562342.xml::T1-0

PMC0025XXXXX/PMC2562343.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562341.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562341.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562341.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562342.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Concentrations of Chemokines and Cytokines in Conditioned Media Samples from Mono- and Co-cultures Based on Multiplexed Antibody Bead Assays
  footer_text: The illustrated results are from one experiment and are representative of results from three experiments. Values are the means of triplicate samples. (−) designates undetectable levels. (**) designates p value<0.01. (*) designates p value<0.05.
    unique: PMC2562343/PMC2562343.xml::T1-0

PMC0025XXXXX/PMC2562344.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patterns of Correspondence Across Scores (Kendall’s tau, N = 17)
  footer_text: ~ trend (p < .10), * p ≤ .05 level, ** p ≤ .01 level
    unique: PMC2562344/PMC2562344.xml::T1-0

PMC0025XXXXX/PMC2562345.xml

PMC0025XXXXX/PMC2562346.xml

PMC0025XXXXX/PMC2562347.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562343.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562344.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562347.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562348.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Spectral karyotyping analysis of neu-expressing cell lines TUBO, Bam1a, Bam IR-5, D2F2/neu, and D2F2. Clonal chromosome aberrations (CCAs), non-clonal chromosome aberrations (NCCAs), and chromosome fragments were summarized
  footer_text: t = translocation i = isochomosome
    unique: PMC2562347/PMC2562347.xml::T1-0

PMC0025XXXXX/PMC2562348.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of the patient demographics, treatment, tumor site, histopathology, and culture information. All 13 tissue samples were adenocarcinomas isolated from patients with resectable colorectal hepatic metastases. Long-term cultures were established from most tumor cell samples. Long-term cultures were those ranging from several passages to more than 10 passages. In vitro differentiation was defined as the presence of pleiomorphic maturation and the expression of lineage markers. ND: not determined and chemo: chemotherapy treatment.
  footer_text:
    unique: PMC2562348/PMC2562348.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Percentage of cells exhibiting the chromosomal aberrations found in parental and clonal cultures of Tu-12 and Tu-21. Twenty metaphase cells were analyzed per tumor culture. Structural changes that were seen more than once, numerical gains of chromosomes at least seen twice, and numerical chromosome loss seen three or more times were reported in this table. Add, additional unidentifiable chromatin material attached to and replacing the chromatin distal to that breakpoint; del, deletion of a chromosome segment; i, isochromosome; "+1~5 mar", at least two of the cells studied from that sample contained between one and five unidentifiable marker chromosomes. Clonally abnormal chromosomes in all three related cultures confirm the relationship between the parent and her descendants. These would be the chromosomal aberrations found in all three samples. While the nomenclature describing the del(5q) and the marker chromosomes appear the same for the two unrelated tumors, we do not believe that they are actually identical abnormalities in the two tumors at the molecular level (See Supplementary Material for more information).
  footer_text:
    unique: PMC2562348/PMC2562348.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562348.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562352.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562349.xml

PMC0025XXXXX/PMC2562350.xml

PMC0025XXXXX/PMC2562352.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Antiviral Activities vs. Yellow Fever Virus and Cytotoxicities of the Original Hits and Second Generation Compounds
  footer_text: a Note: The EC50 is the concentration of the compound resulting in a 50% inhibition in virus production. b The CC50 is the concentration of the compound causing a 50% growth inhibition of uninfected BHK cells. c TI is the therapeutic index and is equal to CC50/EC50. d A short dash indicates that the value was not determined.
    unique: PMC2562352/PMC2562352.xml::T1-0

PMC0025XXXXX/PMC2562353.xml

PMC0025XXXXX/PMC2562354.xml

PMC0025XXXXX/PMC2562356.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Significant genes with expression that was associated with gemcitabine or AraC cytotoxicity (IC50 values). R values represent correlation coefficients. Q values represent the false discovery rate.
  footer_text:
    unique: PMC2562356/PMC2562356.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Intracellular metabolites determined by HPLC in lymphoblastoid cells after incubation with (A) AraC or (B) gemcitabine. Metabolites are μM/5 × 106 cells.
  footer_text: * = indicates p < 0.05 between sensitive and resistant cell lines.
    unique: PMC2562356/PMC2562356.xml::T2-0

PMC0025XXXXX/PMC2562419.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of isolated clones and overexpression phenotypes. Phenotype categories: AD: Anterior Defects, CED: Convergent Extension Defects, DD: Dorsal Defects, GD: Gastrulation Defects, K: Kinked, NM: Neural Mispatterning, PD: Pigmentation Defects, SA: Secondary Axis, SB: Spina Bifida, TD: Trunk Defects, V: Ventralized.
  footer_text:
    unique: PMC2562419/PMC2562419.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562356.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562356.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562419.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562423.xml

PMC0025XXXXX/PMC2562426.xml

PMC0025XXXXX/PMC2562427.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Arrestin levels in mutant backgrounds Values determined by densitometry of Western blots (mean ± SD, normalised to levels in wild type using tubulin as standard), see methods and Supplemental Figure 1 for further details.
  footer_text:
    unique: PMC2562427/PMC2562427.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mutants used
  footer_text:
    unique: PMC2562427/PMC2562427.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562427.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562427.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562438.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562438.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562431.xml

PMC0025XXXXX/PMC2562438.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Primers used in Vamp1 PCR experiments
  footer_text: Forward and reverse primers used for the identification of Vamp1 variants in the brain and cochlear nucleus. The rat Vamp1nv (specific) primer set spanned introns and generated a 110bp sequence unique to this variant.
    unique: PMC2562438/PMC2562438.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Primer-Probe Sequences used in Vamp1 Splice Variant Taqman® Real-Time RT-PCR experiments
  footer_text: Primer-probe sets used for real-time RT-PCR experiments. These were used to identify the relative levels of each variant among the subdivisions. Primers were designed around the unique splice sites to be specific for each variant.
    unique: PMC2562438/PMC2562438.xml::T2-0

PMC0025XXXXX/PMC2562451.xml

PMC0025XXXXX/PMC2562456.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Ar-Bb interaction energies (kJ·mol-1)
  footer_text: † interaction energies between the aromatic side chain and the Ac-N1H group (Figure 1a, Scheme 1S). ‡ interaction energies between the aromatic side chain and the Gly-Gly-NHMe and the C1=O groups (Figure 1a, Scheme 1S).
    unique: PMC2562456/PMC2562456.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562456.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562456.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562456.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562504.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Bb-Bb interaction energies (kJ·mol-1)
  footer_text: † the peptide bonds are modeled as acetamide (Figure 1b). ‡ interaction energies of H-bonds are shown in bold. § a bifurcated H-bond where the C0 carbonyl oxygen is the acceptor atom and the N3 and N4 hydrogens are the donor atoms; a special fragmentation was used (Supplementary material, Figure 2S).
    unique: PMC2562456/PMC2562456.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Intramolecular interaction energies (kJ·mol-1) in FGG, WGG and YGG
  footer_text: † weakly polar interaction energy ‡ includes the energy of a Pb1-Pb2 H-bond calculated by the rotation method (Supplementary material, Figure 3S). § includes the energy of a bifurcated H-bond calculated by a special fragmentation (Supplementary material, Figure 2S).
    unique: PMC2562456/PMC2562456.xml::T3-0

PMC0025XXXXX/PMC2562504.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Prediction and conserve of sumoylation residues in papillomavirus E2
  footer_text:
    unique: PMC2562504/PMC2562504.xml::T1-0

PMC0025XXXXX/PMC2562522.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic Characteristics stratified by Source of Recipient Data (Number in parenthesis is %, unless otherwise noted)
  footer_text:
    unique: PMC2562522/PMC2562522.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Donor Characteristics (n=512)
  footer_text: 1 ECD defined as donor age >60; or donor age >50 with any 2 of the following donor criteria: (1) terminal serum creatinine >1.5 mg/dl, (2) hypertension, or (3) death due to CVA.
    unique: PMC2562522/PMC2562522.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Outcomes post-transplantation By Source of Recipient Information
  footer_text:
    unique: PMC2562522/PMC2562522.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Adjusted and unadjusted association with DGF for inflammation and apoptosis related Polymorphisms [ND1]
  footer_text: Adjusted for cold ischemia time, recipient race, extended criteria donor, donor cause of death, donor race, and source of DGF information (medical record or CMS claims or UNOS forms). The (GT)n SNP is categorized as short (S for ≤ 27 repeats) vs long repeats (L for >27 repeats * denotes p< 0.05 † rs3091257 has been merged into rs1800628.[ND3]
    unique: PMC2562522/PMC2562522.xml::T4-0

PMC0025XXXXX/PMC2562525.xml

PMC0025XXXXX/PMC2562531.xml

PMC0025XXXXX/PMC2562532.xml

PMC0025XXXXX/PMC2562533.xml

PMC0025XXXXX/PMC2562544.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562522.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562522.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562522.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562546.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Somatic signs of morphine withdrawal in Narp KO and WT mice Three days after morphine pump implantation, Narp KO and WT mice were administered a single dose of saline in a novel environment. The following day mice were administered a single dose of naltrexone 250ug/kg sc in the same chamber and were monitored for 30 minutes. The table shows the mean number of somatic morphine withdrawal signs for each genotype after saline and naltrexone administrations
  footer_text: Note: 1 Based on 2-way ANOVA that included Injection (Naltrexone versus Saline) and Genotype (WT versus KO) as within and between comparisons. Significant when p <0.05.
    unique: PMC2562546/PMC2562546.xml::T1-0

PMC0025XXXXX/PMC2562547.xml

PMC0025XXXXX/PMC2562548.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Risk of developing second primary breast cancer associated with ATM gene carrier status.
  footer_text: * Adjusted for exact age at diagnosis of the first primary and counter-matching weight. Common and Rare models also adjusted for carriers of other remaining ATM variants. † 95% CI is 95% confidence interval. ‡ Common variants are defined as those carried by greater than or equal to 1% of the WECARE Study participants. Rare variants are those carried by fewer than 1% of the participants.
    unique: PMC2562548/PMC2562548.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Risk of developing second primary breast cancer associated with rare ATM variants.
  footer_text: * Adjusted for exact age at diagnosis of the first primary, countermatching weight and for carriers of the other remaining ATM variants. † 95% CI is 95% confidence interval. ‡ Meeting one or more of the following criteria: (1) changes predicted to result in truncation of the ATM protein whether by direct termination or frameshifting, (2) changes affecting the two highly conserved nucleotides flanking exons that direct splicing, (3) changes predicted to result in amino acid substitutions for which there is documented evidence of both a deleterious effect on ATM function and identification in diagnosed A-T patients, or (4) changes documented as AT causing in the ATM Mutation Database. § Defined as by SIFT: Variants with normalized probabilities less than 0.05 are predicted to be deleterious, while those greater than or equal to 0.05 are predicted to be tolerated.. Results for missense variants are adjusted for other variants.
    unique: PMC2562548/PMC2562548.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562546.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562548.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562548.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562548.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Risk of developing second primary breast cancer associated with common ATM variants*
  footer_text: * Variants carried by more than 1% of the WECARE Study subjects. † Variants indicated relative to the reference sequence for the ATM Mutation Database (http://chromium.liacs.nl/lovd/refseq/ATM_codingDNA.html). Nomenclature as recommended by the Human Variome Project. ‡ rs numbers are provided for those SNPs currently listed in dbSNP. § Adjusted for exact age at diagnosis of the first primary, countermatching weight and for carriers of the other remaining ATM variants so that the rate ratio is relative to those for wildtype for ATM variants. ║ 95% CI is 95% confidence interval.
    unique: PMC2562548/PMC2562548.xml::T3-0

PMC0025XXXXX/PMC2562550.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Number (M of Four Tests ± SEM) of Contacts and Anogenital Sniffs
  footer_text: Note. Conducted in 45-min tests with WT controls and SF-1 KO animals without sex steroid replacement tested with stimulus females. WT = wild type; f = female; m = male; KO = knockout. * Significantly different between genotypes: p < .01. ** Significantly different between genotypes: p < .001.
    unique: PMC2562550/PMC2562550.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Number (M of Four Tests ± SEM) of Anogenital Sniffs
  footer_text: Note. Conducted in tests adjusted to 15 min with TP treated WT controls and SF-1 KO animals. WT = wild type; f = female; m = male; KO = knockout. * Significantly different between genotypes: p < .05. ** Significantly different between genotypes: p < .01. *** Significantly different between genotypes: p < .001.
    unique: PMC2562550/PMC2562550.xml::T2-0

PMC0025XXXXX/PMC2562556.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Meta-analyses of allelic association studies for 12 schizophrenia candidate genes
  footer_text: a Polymorphsims and their minor alleles were annotated on the SchizophreniaGene of the Schizophrenia Research Forum (http://www.schizophreniaforum.org/res/sczgene/default.asp). b Meta-analyses were performed for samples from all populations, Europeans, and Asians, respectively. c Numbers of Family-based (Fam, numbers of families are shown in the parentheses) and Case-Control (CC) association studies included in the meta-analyses. d Minor allele frequencies based on case-control association data, numbers of cases and controls are shown in the parentheses. e I2 was employed to assess between-study heterogeneity. I2 > 50% indicates evidence for significant between-study heterogeneity. f Overall Odds Ratios (OR) and their 95% Confidence Intervals (CI) were based on the random-effects model if I2 = 50%, otherwise based on the fix-effects model (I2 < 50%). g P(Z), Z test was used to detect the significance of the overall OR. P-values < 0.05 are shown in bold type. h Associations remain significant after correction for the number of meta-analyses for each gene. Underlined are obvious different results (significant gene-wide associations appear or disappear) of meta-analyses including or excluding family-based association data in Caucasian and all populations. The results excluding family data are similar to those of "all excluding HWE deviations" in the Schizophrenia Research Forum. Note that meta-analyses were performed for polymorphisms with at least one family-based association study, except for those in the DAOA gene, which have been reported recently (Shi et al., Schizophr. Res. 2008; 98: 89–97). NA: not applicable.
    unique: PMC2562556/PMC2562556.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562550.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562550.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562556.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562557.xml

PMC0025XXXXX/PMC2562558.xml

PMC0025XXXXX/PMC2562560.xml

PMC0025XXXXX/PMC2562562.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline characteristics of participants in the Women’s Health Study according to MTHFR 677C>T genotype (N=25,001) *
  footer_text: * data are expressed as percentages unless otherwise stated. † p-values for chi-square test for categorical variables, and Kruskal-Wallis test for continuous variables; comparing no history of migraine vs. any history of migraine. IQR: interquartile range. Proportions may not add up to 100 due to rounding or missing values.
    unique: PMC2562562/PMC2562562.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562562.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562562.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562562.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562562.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Age- and multivariable adjusted odds ratios (OR) and 95% confidence intervals (95% CI) for migraine according to MTHFR 677C>T polymorphism
  footer_text: * controlling for: age, body mass index, diabetes, physical activity, hormone replacement therapy, oral contraceptive use, history of hypertension, alcohol consumption, smoking categories, and family history of myocardial infarction. † controlling for: age, body mass index, diabetes, physical activity, hormone replacement therapy, oral contraceptive use, history of hypertension, alcohol consumption, smoking categories, family history of myocardial infarction, serum homocysteine levels, folate intake, vitamin B2 intake, vitamin B6 intake, and vitamin B12 intake.
    unique: PMC2562562/PMC2562562.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Multivariable-adjusted* hazard ratios (HR) and 95% confidence intervals (95% CI) for ischemic vascular events according to MTHFR 677C>T polymorphism (n=25,001)
  footer_text: * controlling for: age, body mass index, diabetes, physical activity, hormone replacement therapy, oral contraceptive use, history of hypertension, alcohol consumption, smoking categories, family history of myocardial infarction, serum homocysteine levels, folate intake, vitamin B2 intake, vitamin B6 intake, and vitamin B12 intake.
    unique: PMC2562562/PMC2562562.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Multivariable-adjusted Hazard Ratios for Cardiovascular Events according to Migraine Status Stratified by MTHFR 677C>T genotype in the Women’s Health Study (N=25,001)
  footer_text: * defined as the first of any of these events: nonfatal ischemic stroke, nonfatal myocardial infarction, or death due to ischemic cardiovascular cause. † controlling for: age, body mass index, diabetes, physical activity, hormone replacement therapy, oral contraceptive use, history of hypertension, alcohol consumption, smoking categories, family history of myocardial infarction, serum homocysteine levels, folate intake, vitamin B2 intake, vitamin B6 intake, and vitamin B12 intake.
    unique: PMC2562562/PMC2562562.xml::T4-0

PMC0025XXXXX/PMC2562567.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Glossina fuscipes fuscipes mitochondrial haplotype frequency distribution.
  footer_text:
    unique: PMC2562567/PMC2562567.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562567.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562567.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562567.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562568.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562578.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Number of haplotypes shared (upper diagonal) and genetic differentiation (FST) among samples (lowest diagonal).
  footer_text: CAR-lab, Central African Republic laboratory strain.
    unique: PMC2562567/PMC2562567.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Indices of molecular variation in Glossina fuscipes fuscipes including haplotype (HS) and nucleotide (πS) diversities. Kenyan samples were pooled for tests for selective neutrality (R2) and demographic equilibrium (Fs).
  footer_text: * Test according to Ramos-Onsins & Rozas (2002). † Test according to Fu (1997). ‡ Between field-collected samples: Student’s t = 13.12, P < 0.006. § Between field-collected samples: t = 1.99, P = 0.19. ¶ P < 0.001. CAR-lab, Central African Republic laboratory strain.
    unique: PMC2562567/PMC2562567.xml::T3-0

PMC0025XXXXX/PMC2562568.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Coculture of OCI-AML3 cells with MSC feeder layers increases the apoptotic EC50 of traditional chemotherapeutic drugs.
  footer_text:
    unique: PMC2562568/PMC2562568.xml::T1-0

PMC0025XXXXX/PMC2562576.xml

PMC0025XXXXX/PMC2562578.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patient samples used in the comparison of the colon crypt proteomes of FAP patients and controls (distal mucosa from sporadic cancer cases).
  footer_text:
    unique: PMC2562578/PMC2562578.xml::T1-0

PMC0025XXXXX/PMC2562581.xml

PMC0025XXXXX/PMC2562587.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sample Characteristics Overall and by Race/Ethnicity/Language (N=1137)
  footer_text: Chi-square test for association; age (p=0.003), number of co-morbidities 0.001, breast cancer stage p=0.186, surgery (p=0.007), radiation (p=0.177), all else <0.001 percents in the table are unweighted
    unique: PMC2562587/PMC2562587.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Percent of Women Who Received Treatment and Survivorship-Related Information, and Wanting More Information by Race/Ethnicity
  footer_text: * Restricted to those who received radiation therapy † Restricted to those who received chemotherapy ‡ Restricted to those who are married or living with someone significant p-values: received information: recovery (p=0.047), nutrition (p=0.004), relationship (p<0.001), sexual function (p=0.002) wanted more information: all p’s <0.001 percents are weighted to account for differential selection by race, ethnicity, and nonresponse.
    unique: PMC2562587/PMC2562587.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Adjusted Odds of Wanting More Information by Sociodemographic Characteristics, Controlling for Clinical, and Treatment Related Factors*
  footer_text: * Adjusted for age, race, education, marital status, # of comorbidities, breast cancer stage and treatment; † Restricted to women who received radiation therapy; ‡ Restricted to women who received chemotherapy percents are weighted to account for differential selection by race, ethnicity, and nonresponse. N/A re: desire for more information on “relationships,” was restricted to those who were married or with a partner
    unique: PMC2562587/PMC2562587.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562587.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562587.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562587.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562590.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562590.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Odor sets used for the habituation/spontaneous discrimination task. Numerical values depict vol/vol liquid dilutions in mineral oil theoretically producing a vapor phase partial pressure of 1.0 Pa.
  footer_text:
    unique: PMC2562590/PMC2562590.xml::T1-0

PMC0025XXXXX/PMC2562591.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mouse strains, genotypes, and disease status.
  footer_text:
    unique: PMC2562591/PMC2562591.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Expression of selected genes in Fli-1+/+ (n = 5) versus Fli-1+/− (n = 5) MRL/lpr B cells. One triplicate experiment per gene.
  footer_text:
    unique: PMC2562591/PMC2562591.xml::T2-0

PMC0025XXXXX/PMC2562592.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Spearman correlation coefficients between estrogens and estrone metabolites among controls*
  footer_text: * N ranges from 460 (estrone) to 675 (2-OH, 16α-OH, 2:16α-OH ratio)
    unique: PMC2562592/PMC2562592.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562591.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562591.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562592.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562592.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562592.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Characteristics (Mean (SD) or %) of breast cancer cases and matched controls, Nurses' Health Study
  footer_text: * Among parous women only ** Among women with natural menopause or bilateral oophorectomy only
    unique: PMC2562592/PMC2562592.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Median (range*) of hormones among breast cancer cases and matched controls
  footer_text: * From the median of the bottom quartile (12.5 percentile) to the median of the top quartile (87.5 percentile)
    unique: PMC2562592/PMC2562592.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Multivariate* relative risks and 95% confidence intervals of breast cancer according to quartiles of estrogen metabolites
  footer_text: * Multivariate models controlled for body mass index at age 18 y (<21, 21-22.9, 23-24.9, or ≥25 kg/m2), family history of breast cancer (yes or no), age at menarche (<12, 12, 13, or ≥14 y), age at first birth and parity (nulliparous; 1-4 children, first birth <25 y; 1-4 children, first birth 25-29 y; 1-4 children, first birth ≥30 y; ≥5 children, first birth <25 y; or ≥5 children, first birth ≥25 y), age at menopause (<46, 46-50, 51-55, or ≥56 y), and duration of past postmenopausal hormone use (continuous); unconditional multivariate models (for ER/PR analyses) additionally controlled for matching factors (age [<55, 55-59, 60-64, ≥65], date of blood draw [6-m groups], time of blood draw [1-8am, 9am-12pm, 1pm-12am], fasting status [<10 versus ≥10 h]). ** p-heterogeneity between ER+/PR+ and ER-/PR- were: 0.02 for 2-OH estrone, 0.81 for 16α-OH estrone, and 0.005 for 2:16α OH estrone ratio
    unique: PMC2562592/PMC2562592.xml::T4-0

PMC0025XXXXX/PMC2562593.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562592.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562594.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: BARRIERS TO STUDY PARTICIPATION*
  footer_text: * Both studies include interviews, neuropsychological testing, MRI brain scans, and phlebotomy † MRI= magnetic resonance imaging without intravenous contrast ‡ Defined as 90 minutes or longer
    unique: PMC2562594/PMC2562594.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: MOTIVATORS FOR STUDY PARTICIPATION*
  footer_text: * Both studies include interviews, neuropsychological testing, MRI brain scans, and phlebotomy. Includes all participants who did not refuse study participation
    unique: PMC2562594/PMC2562594.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: SOLUTIONS TO MAXIMIZE STUDY PARTICIPATION (N=50)
  footer_text:
    unique: PMC2562594/PMC2562594.xml::T3-0

PMC0025XXXXX/PMC2562596.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Body Weight and Fluid Intake
  footer_text: * indicate significant main effects of Age ** indicates significant Age × Solution interaction
    unique: PMC2562596/PMC2562596.xml::T1-0

PMC0025XXXXX/PMC2562597.xml

PMC0025XXXXX/PMC2562598.xml

PMC0025XXXXX/PMC2562603.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562594.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562594.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562594.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: Origins of the alternans patterns in Fig. 4.
  footer_text:
    unique: PMC2562603/PMC2562603.xml::T1-0

PMC0025XXXXX/PMC2562606.xml

PMC0025XXXXX/PMC2562609.xml

PMC0025XXXXX/PMC2562610.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Means for Suicidal Ideation (Equivalent to Percent Reporting Suicidal Ideation¹) Within Observed Combinations of Spell and Period
  footer_text: Note: ns are reported in parenthesizes following the means. a For example, of the 23 men in Spell 3, Period 8 (i.e., 2 reported occurrences of suicidal ideation, and 7 years since it was last reported), 9% reported suicidal ideation in the past week. b Complete data are not shown for the one individual represented in the Spell 10, Period 1 cell as he progressed to Spell 13, Period 3.
    unique: PMC2562610/PMC2562610.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Results of Multiple-Spell Discrete-Time Event-History Analysis: Prediction of Suicidal Ideation from Period, Spell, Parental Depressive Symptoms, and Participants’ Alcohol/Substance Use and Depressive Symptoms (N = 3347)
  footer_text: Notes. Exp(B) = exponentiated B; Parent Dep = parental depressive symptoms; Alc/Sub = 1-year lagged alcohol/substance use; Dep = 1-year lagged depressive symptoms; Dep2 = 1-year lagged quadratic depressive symptoms; −2LL = −2 log likelihood; R2 refers to Nagelkerke R2. † p < .10. * p < .05. ** p < .01. *** p < .001.
    unique: PMC2562610/PMC2562610.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562610.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562610.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562611.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562611.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean (± standard error of the mean) plasma concentrations of corticosterone (B), estradiol (E2), progesterone (P4) and allopregnanolone (3α,5α-THP) of ovariectomized wildtype (WT) or estrogen receptor β knockout (βERKO) mice administered subcutaneous vehicle (far left), E2 (middle), and DPN (far right). NB: Because it is not clear if the E2 antibody utilized binds DPN, analyses of E2 levels from mice treated with DPN are not included.
  footer_text: * indicates a significant (P ≤ 0.05) effect of treatment, which is attributable to higher levels vs. vehicle.
    unique: PMC2562611/PMC2562611.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Behavior (mean ± sem) of vehicle-administered WT (n=12) or estrogen receptor β knockout (βERKO; n=18) mice, E2-administered WT (n=16) or βERKO (n=14) mice, or DPN-administered WT (n=18) or βERKO (n=12) mice.
  footer_text: * indicates a significant (P ≤ 0.05) effect of treatment, which is attributable to higher levels vs. vehicle. ^ indicates a significant (P ≤ 0.05) effect of genotype. ** indicates a significant (P ≤ 0.05) interaction.
    unique: PMC2562611/PMC2562611.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562611.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562612.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562616.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562616.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562612.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Absolute and relative comparison of energy dissipated, maximum force, and pulling length in Na buffer, Ca buffer and La buffer, corresponding to the data presented in figure 3.
  footer_text:
    unique: PMC2562612/PMC2562612.xml::T1-0

PMC0025XXXXX/PMC2562615.xml

PMC0025XXXXX/PMC2562616.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patient characteristics and asthma related function of total sample and risk groups
  footer_text: Asterisks denote the statistical significance of the comparison between high- and low-risk groups for each by Chi Square or T-test: *** p < 0.001 ** p < 0.01 * p < 0.05. In the comparison of high-risk groups from each definition, p-values are shown or NS denotes the difference is not significant at the level of p<0.05. CHS-A = Child Health Survey — Asthma.
    unique: PMC2562616/PMC2562616.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Number of youth captured by high-risk definition criteria (N=769)
  footer_text: ED: ≥1 emergency department visits for asthma Inpatient: ≥1 inpatient hospitalizations for asthma OS: ≥1 oral steroid prescriptions for asthma Rx: ≥4 prescriptions for asthma medication Visits + Rx: ≥4 ambulatory visits for asthma and ≥2 prescriptions for asthma medication
    unique: PMC2562616/PMC2562616.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Health care cost and utilization for total sample and risk groups
  footer_text: Asterisks denote the statistical significance of the comparison between high- and low-risk groups within each definition by T-test: In the comparison of high-risk groups from each definition, p-values are shown or NS denotes the difference is not significant at the level of p<0.05 *** p < 0.001 ** p < 0.01 * p < 0.05
    unique: PMC2562616/PMC2562616.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562616.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562642.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562620.xml

PMC0025XXXXX/PMC2562630.xml

PMC0025XXXXX/PMC2562634.xml

PMC0025XXXXX/PMC2562635.xml

PMC0025XXXXX/PMC2562638.xml

PMC0025XXXXX/PMC2562640.xml

PMC0025XXXXX/PMC2562642.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of different false positive reduction scheme
  footer_text:
    unique: PMC2562642/PMC2562642.xml::T1-0

PMC0025XXXXX/PMC2562647.xml

PMC0025XXXXX/PMC2562649.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Clinical Phenotype, Including Behavior Problems, Ataxia, and Seizures, in 33 Adolescent and Adult SSADH Deficiency Patients (mean age: 12.1±7.6 years, range: 2.2-39.6 years; 48% females)
  footer_text: SSADH=succinic semialdehyde dehydrogenase.
    unique: PMC2562649/PMC2562649.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Follow-up Assessment of Language, Cognition, and Gross and Fine Motor Performance in 24 Adolescent and Adult SSADH Deficiency Patients (mean age: 18.1±7.0 years, age range: 10.6–40.0 years; 50% females)
  footer_text: The mean follow-up period was 11. ±4.6 years. (range: 5.3-21.4 years.) All performances were classified by an experienced physician in relative units from 1 (severe deficit) to 5 (normal). SSADH=succinic semialdehyde dehydrogenase.
    unique: PMC2562649/PMC2562649.xml::T2-0

PMC0025XXXXX/PMC2562655.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Number of classes, number of images, format, size and microscopy of the datasets of IICBU-2008.
  footer_text:
    unique: PMC2562655/PMC2562655.xml::T1-0

PMC0025XXXXX/PMC2562658.xml

PMC0025XXXXX/PMC2562668.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562649.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562655.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: List of strains used in the MLST analysis; their toxin subtype designation, sequencing types and alleles for 73 strains for the 7 selected housekeeping genes
  footer_text: a * represents the initial 30 strains used in housekeeping genes screening study. b Strain names refer to Eric A. Johnson’s laboratory’s stocks. c ST: Sequencing type. d A1 has BoNT/A1 gene (see NCBI publication number AF461539); A2 has the BoNT/A2 gene (see NCBI publication number AY953275), A(B) has BoNT/A1 gene and a silent BoNT/B gene (see NCBI publication number NCTC 2916), A3 has the BoNT/A3 gene (see NCBI publication number DQ185900), and A4 has the BoNT/A4 gene (see NCBI publication number DQ185901) and BoNT/B genes (see NCBI publication number EU341304). ha−/orfx+ A1 produces BoNT/A1 but with an ORFX cluster, sporo: Clostridium sporogenes
    unique: PMC2562668/PMC2562668.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562668.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562668.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562668.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562681.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562681.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Details on primer sequences and the PCR conditions of 7 housekeeping genes used in MLST analysis
  footer_text: a F: forward; R: reverse; aroE: shikimate dehydrogenase gene; hsp6: heat shock gene; mdh: malate dehydrogenase gene; recA: RecA gene; aceK: isocitrate dehydrogenase gene; rpoB: RNA polymerase subunit B gene; oppB: oligopeptide/dipeptide ABC transporter gene.
    unique: PMC2562668/PMC2562668.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Genetic variability of 7 genes in 24 STs. The number of variable sites ranges from 39 to 73. The synonymous rate of substitution (dS) and non-synonymous rate of substitution (dN) range among alleles and average to 5.40 and 0.69 among all sites. Estimates of dN /dS and CI were calculated by method of Pond and Frost (2005). Both oppB and aroE have larger dN/dS suggestion these alleles are under more relaxed selection.
  footer_text:
    unique: PMC2562668/PMC2562668.xml::T3-0

PMC0025XXXXX/PMC2562671.xml

PMC0025XXXXX/PMC2562681.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Possible causes and solutions of the young driver problem and strength of evidence of efficacy of the proposed solutions
  footer_text: Note. This table was created using the references reviewed by the authors in the text.
    unique: PMC2562681/PMC2562681.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Descriptions of the Checkpoints and the Safe Drivers Wanted parent management programs
  footer_text: DMV = department of motor vehicles.
    unique: PMC2562681/PMC2562681.xml::T2-0

PMC0025XXXXX/PMC2562683.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The dependence of HF on θF: parameters of the best-fit sigmoid functions (given by Expression 2).
  footer_text: f, spatial frequency in cycles/°; B, offset in degrees; Amax, amplitude in degrees; Pc, center point of curve in degrees; K, decay constant in degrees−1; r2, coefficient of determination; 90%, value of θF at which HF was 90%.
    unique: PMC2562683/PMC2562683.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: The dependence of VF on θF: parameters of the best-fit exponential functions (given by Expression 3).
  footer_text: f, spatial frequency in cycles/°; B, offset in degrees; S, slope in degrees; τ, decay constant in degrees−1; r2, coefficient of determination.
    unique: PMC2562683/PMC2562683.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: The dependence of HF on log spatial frequency for various values of θF: parameters of the best-fit Gaussian functions.
  footer_text: Cardinal axis (horizontal), indicates that spatial frequency is specified with respect to the horizontal; Orthogonal axis, indicates that spatial frequency is specified orthogonal to the orientation of the grating; θF, folded direction of the orthogonal disparity vector; Apeak, amplitude of the peak in degrees; fo, spatial frequency of the peak in cycles/°; σ, standard deviation in °/cycle (log units to the base 10); r2, coefficient of determination.
    unique: PMC2562683/PMC2562683.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: The dependence of VF on log spatial frequency for various values of θF: parameters of the best-fit Gaussian functions.
  footer_text: Cardinal axis (vertical), indicates that spatial frequency is specified with respect to the vertical. Other abbreviations as for Table 3.
    unique: PMC2562683/PMC2562683.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562683.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562683.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562683.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562683.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562686.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: One mole of ApbC binds two moles of iron and two moles sulfur atoms.a
  footer_text: a ApbC was reconstituted with a five-fold excess of S and Fe as described in material and methods. Iron and sulfide were quantified as described elsewhere (35). Values shown for individual reconstitutions are the average two independent measurements. Errors are reported as standard deviations. b Below Detectable Limit
    unique: PMC2562686/PMC2562686.xml::T1-0

PMC0025XXXXX/PMC2562688.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Effects of cdh6MOs injection on zebrafish development
  footer_text: * Only one of the seven embryos showed thorax edema and curved body, and the gross defects in the remaining six embryos (much smaller and truncated body) were different from the cdh6 morphants.
    unique: PMC2562688/PMC2562688.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Effects of cdh6MOs injection on expression of transcription factors and notch-delta genes in the retina
  footer_text: n, number of eyes examined; %, percentages of greatly reduced or altered staining (staining area and/or staining intensity), compared to the majority of control embryos. For cdh6 morphants, only those with obvious gross morphological defects were used. Abbreviation: ND, analysis not done.
    unique: PMC2562688/PMC2562688.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Effects of cdh6MOs injection on zebrafish retinal development revealed by immunostaining
  footer_text: n, number eyes examined; n1 and n2, the numbers of eyes from embryos injected with cdh6MO1 and cdh6MO2, respectively. %, percentages of greatly reduced staining (staining area and/or intensity) compared to the majority of control embryos. * The retinal defects in these embryos were milder than those from morphants with obvious gross morphological defects. Abbreviations: Hu, anti-HuC/HuD immunostaining; Hu & zpr-1, anti-HuC/HuD and zpr-1 double immunostaining; ND, analysis not done; Parv, anti-parvalbumin immunostaining; Pax6, anti-Pax6 immunostaining; tub, anti-acetylated tubulin immunostaining; zn5, zn5 immunostaining.
    unique: PMC2562688/PMC2562688.xml::T3-0

PMC0025XXXXX/PMC2562689.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Descriptive statistics for WS and TD groups
  footer_text: 1 Data for one child missing from analysis.
    unique: PMC2562689/PMC2562689.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562686.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562688.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562688.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562688.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562689.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: TRC raw score and percent correct on spatial items for WS and TD groups matched for relational vocabulary size at various levels of stringency
  footer_text:
    unique: PMC2562689/PMC2562689.xml::T2-0

PMC0025XXXXX/PMC2562694.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Change in WHEL dietary components and plasma carotenoids from baseline to one year by cluster
  footer_text:
    unique: PMC2562694/PMC2562694.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562689.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562694.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Intensity and frequency of the first phase of the WHEL tailored intervention
  footer_text:
    unique: PMC2562694/PMC2562694.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Differences in cluster membership by baseline characteristics and health behaviors
  footer_text:
    unique: PMC2562694/PMC2562694.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Differences in cluster membership by introductory call variables
  footer_text:
    unique: PMC2562694/PMC2562694.xml::T4-0

PMC0025XXXXX/PMC2562695.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Variance (in pixels) associated with each category in the experiment
  footer_text:
    unique: PMC2562695/PMC2562695.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mean accuracy in Experiment 1 across all participants for each of the four conditions. Accuracy is given by percent correct across all 10 experimental blocks
  footer_text:
    unique: PMC2562695/PMC2562695.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Goodness-of-fit values (-2ln L) for the prototype and exemplar models in Experiment 1
  footer_text:
    unique: PMC2562695/PMC2562695.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Mean accuracy in Experiment 2 across all participants for each of the four conditions. Accuracy is given by percent correct across all 10 experimental blocks
  footer_text:
    unique: PMC2562695/PMC2562695.xml::T4-0

PMC0025XXXXX/PMC2562697.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562694.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562694.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562694.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562695.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562695.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562695.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562695.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562699.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The Ten-Point Surgical Apgar Score The Surgical Apgar Score is calculated at the end of any general or vascular surgery operation, from the estimated blood loss, lowest mean arterial pressure and lowest heart rate entered in the anaesthesia record during the operation. The score is the sum of the points from each category.
  footer_text: * Occurrence of pathologic bradyarrhythmia, including sinus arrest, atrioventricular block or dissociation, junctional or ventricular escape rhythms, and asystole also receive 0 pts for lowest heart rate
    unique: PMC2562699/PMC2562699.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Characteristics of patients, procedures, and outcomes, by Surgical Apgar Score
  footer_text: * Hypothesis testing employed Cochrane-Armitage chi-square trend tests for categorical variables, and Spearman correlation coefficients for continuous variables, except for length of stay, for which we used the Kruskal-Wallis test.
    unique: PMC2562699/PMC2562699.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562699.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562699.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Postoperative outcomes, by preoperative risk stratum and Surgical Apgar Score Using a detailed preoperative risk prediction model, patients were stratified by quintiles of likelihood of a major postoperative complication. The predicted and observed incidence of major postoperative complications are presented.
  footer_text: * Cochrane-Armitage chi-square trend test
    unique: PMC2562699/PMC2562699.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Complication rates and adjusted and unadjusted likelihood ratios for levels of the Surgical Apgar Score
  footer_text:
    unique: PMC2562699/PMC2562699.xml::T4-0

PMC0025XXXXX/PMC2562701.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of the equilibrium and kinetic parameters [42]
  footer_text: L=[ET]/[ER] is a unitless parameter. The K values are in μM and S, I and A are substrate (PEP), inhibitor (Phe) and activator (fructose-bis-phosphate, FBP) respectively. The k values are expressed as relative activity, 1.0 being equal Vmax.
    unique: PMC2562701/PMC2562701.xml::T1-0

PMC0025XXXXX/PMC2562705.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Data Collection and Refinement Statistics
  footer_text: a Numbers in parentheses indicate values for the highest resolution shell.
    unique: PMC2562705/PMC2562705.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562699.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562699.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562701.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562705.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Kinetic Constants for the RhamD Reactiona
  footer_text: a Assay conditions are given in the Materials and Methods section.
    unique: PMC2562705/PMC2562705.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Kinetic Constants for the 2-Keto-3-Deoxy-L-Rhamnonate Aldolase Reactiona
  footer_text: a Assay conditions are given in the Materials and Methods section.
    unique: PMC2562705/PMC2562705.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Kinetic constants of Mutants for the RhamD Reactiona
  footer_text: a Assay conditions are given in the Materials and Methods section. b No detectable activity
    unique: PMC2562705/PMC2562705.xml::T4-0

PMC0025XXXXX/PMC2562707.xml

PMC0025XXXXX/PMC2562708.xml
  ----------------------------------------
  id: T1
  label_text:
  caption_text:
  footer_text:
    unique: PMC2562708/PMC2562708.xml::T1-0
  ----------------------------------------
  id: T2
  label_text:
  caption_text:
  footer_text:
    unique: PMC2562708/PMC2562708.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562705.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562705.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562705.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562708.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562708.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562708.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562709.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
tw(T3): {'id', 'orientation', 'position'}
  label_text: TABLE I
  caption_text: SNR AND CNR VERSUS POD.
  footer_text:
    unique: PMC2562708/PMC2562708.xml::T3-0

PMC0025XXXXX/PMC2562709.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Neisseria gonorrhoeae strains used in this study.
  footer_text: * Pro: requires proline; Proto; Prototrophic; PAU: requires proline, arginine and uracil; PAHU: requires proline, arginine, hypoxanthine and uracil; AHU: requires arginine, hypoxanthine and uracil
    unique: PMC2562709/PMC2562709.xml::T1-0

PMC0025XXXXX/PMC2562710.xml

PMC0025XXXXX/PMC2562711.xml

PMC0025XXXXX/PMC2562714.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Data
  footer_text:
    unique: PMC2562714/PMC2562714.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562714.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562714.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562714.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562714.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562726.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Correlation Matrix of Behavioral Antecedents and Outcome Behaviors
  footer_text: * Note: p < .05; ** p > .01
    unique: PMC2562714/PMC2562714.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Predictors for Protected Vaginal Sex
  footer_text:
    unique: PMC2562714/PMC2562714.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Predictors for Unprotected Vaginal Sex
  footer_text:
    unique: PMC2562714/PMC2562714.xml::T4-0

PMC0025XXXXX/PMC2562726.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Effect of ethanol pretreatment of P-selectin-coated Protein A beads All measurements at 100 s-1 with untreated neutrophils.
  footer_text:
    unique: PMC2562726/PMC2562726.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Neutrophil rolling on P-selectin-coated surface. (N=3 donors)
  footer_text: * p<0.001 comparing untreated vs ethanol-treated samples.
    unique: PMC2562726/PMC2562726.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table III
  caption_text: Neutrophil rolling on IL-1 stimulated endothelial cells. (N=3 donors)
  footer_text: * p<0.001 comparing untreated vs ethanol-treated samples.
    unique: PMC2562726/PMC2562726.xml::T3-0

PMC0025XXXXX/PMC2562728.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Results of analyses for antibodies to West Nile virus in horse sera from Connecticut and New York State by plaque reduction neutralization tests (PRNT) and a polyvalent enzyme-linked immunosorbent assay (ELISA) containing recombinant envelope protein antigen.
  footer_text: * Positive by PRNT when at least 95% neutralization of plaque-forming units was detected. Positive ELISA titers (≥ 1 in 160). Note: unknown history refers to blood samples drawn from ill horses in 1995−1996 prior to the 1999 outbreak of human and horse cases of West Nile encephalitis in northeastern United States. All tests were performed on one serum sample per animal at The Connecticut Agricultural Experiment Station.
    unique: PMC2562728/PMC2562728.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Frequency distributions of serum antibody titers for horse sera positive by a polyvalent enzyme-linked immunosorbent assay (ELISA) or in plaque reduction neutralization tests (PRNT).
  footer_text: * Positive antibody titers by an ELISA were 1 ≥ 160. Seropositive PRNT indicate 95% neutralization of plaque-forming units at all specified serum dilutions but not tested beyond 1 in 320. NA = not applicable. All tests were performed at The Connecticut Agricultural Experiment Station.
    unique: PMC2562728/PMC2562728.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Comparison of serologic test results for 43 horse sera (group C) from subjects with undiagnosed illnesses prior to 1999 and tested for antibodies to West Nile virus, Anaplasma phagocytophilum, and/or Borrelia burgdorferi by separate polyvalent enzyme-linked immunosorbent assays.
  footer_text: * Recombinant envelope E protein antigen was used in an ELISA for West Nile virus (WNV) antibodies, whereas recombinant protein 44 and whole-cell antigens of A.. phagocytophilum (AP) and B. burgdorferi (BB), respectively, were incorporated separately in an ELISA. All tests were performed at The Connecticut Agricultural Experiment Station.
    unique: PMC2562728/PMC2562728.xml::T3-0

PMC0025XXXXX/PMC2562732.xml
  ----------------------------------------
  id: T1

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562726.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562726.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562728.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562728.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562728.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  label_text: Table 1
  caption_text: Measurements of Postmortem Tongues
  footer_text: Asteriks indicate significant differences between groups A and B and between groups C and D (non-paired t tests). * p < 0.05 ** p < 0.01 *** p < 0.001.
    unique: PMC2562732/PMC2562732.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Measurements of Tongue Casts
  footer_text: * Comparisons before and after the surgery (paired t tests) * p < 0.05 ** p < 0.01 *** p < 0.001 # Comparisons between the two groups (non-paired t tests). # p < 0.05 ## p < 0.01 ### p < 0.001
    unique: PMC2562732/PMC2562732.xml::T2-0

PMC0025XXXXX/PMC2562733.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline predictions for moderate glucose control and expected benefits of intensive glucose control in older patients with no comorbid illnesses or functional impairments.*
  footer_text: * Moderate glucose control= glycosylated hemoglobin 7.9%. Intensive glucose control=glycosylated hemoglobin 7.0%. Inc.= remaining lifetime incidence. ARR= absolute risk reduction. QAD= quality-adjusted days. CI= confidence interval. Virtual patients with duration of diabetes in ranges 0–5 years and 5–10 years had results that were intermediate between patients with new onset diabetes and 10–15 years of diabetes at the start of simulations.
    unique: PMC2562733/PMC2562733.xml::T1-0

PMC0025XXXXX/PMC2562736.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: TGCT incidence in Kitl (Sl) and Kit (W) heterozygous mutant mice*
  footer_text: * L.C. Stevens and D.S. Varnum (Ref. 6; Sl/+ data, personal communication). † The relative numbers of wild-type and mutant mice were not published or available for these crosses. Therefore, statistical significance was not calculated.
    unique: PMC2562736/PMC2562736.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Increased incidence of spontaneous TGCTs in grizzle-belly (Slgb) males
  footer_text:
    unique: PMC2562736/PMC2562736.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562732.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562733.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562736.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562736.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562736.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Parent-of-origin effect revealed by Slgb reciprocal crosses
  footer_text: * NS = not significant
    unique: PMC2562736/PMC2562736.xml::T3-0

PMC0025XXXXX/PMC2562746.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: The main effects for and interactions between calibration method, stimulus level and frequency on the absolute change in DPOAE level between deep and shallow insertions after correcting for the incidental difference due to a change in ear-canal volume. The asterisk (*) denotes statistical significance for p < 0.05.
  footer_text:
    unique: PMC2562746/PMC2562746.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Means and standard deviations of the absolute change in DPOAE level between insertions after correcting for the expected, incidental change. The first five rows are averaged across frequency for each calibration method, and the sixth row is also averaged across level.
  footer_text:
    unique: PMC2562746/PMC2562746.xml::T2-0

PMC0025XXXXX/PMC2562749.xml

PMC0025XXXXX/PMC2562756.xml

PMC0025XXXXX/PMC2562759.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562746.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562746.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Samples used for analysis The table shows the source of samples analyzed (Clinical Study), the mutations detected by the ViroSeq system, and the HIV-1 subtype (pol region).
  footer_text: * Note that the mutations K103R and V179D are associated with NVP resistance only when they occur together.
    unique: PMC2562759/PMC2562759.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: NVP resistance mutations detected in clones Fifty HIV-1 clones were analyzed by AmpliSeq from each infant sample. The number of clones with 0, 1, or 2 mutations is shown. Mutations shown in bold were detected using the ViroSeq HIV-1 Genotyping System (population sequencing). The following amino acid polymorphisms (not shown in Table 2) were also detected in the samples at codons in HIV-1 reverse transcriptase that are the sites of NVP resistance mutations: 147770: V179A (1 clone), V106S+V108S (1 clone). 147858: V181H (1 clone). 274581: L100V+A98C (1 clone). 288407: K103R (50 clones), V179E (26 clones). 289005: V179I (49 clones), V179M (1 clone), K103E+A98S (2 clones). 324698: K101R (1 clone).
  footer_text: * Note that the mutations K103R and V179D are associated with NVP resistance only when they occur together.
    unique: PMC2562759/PMC2562759.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Codons detected in clones at positions in HIV-1 reverse transcriptase associated with NVP resistance Fifty HIV-1 clones were analyzed from each of the six infant samples (300 clones total). Sample numbers are indicated on the left. NVP resistance mutations occur at codons 98, 100, 101, 103, 106, 108, 179, 181, 188, and 190 in HIV-1 reverse transcriptase. The table shows the nucleotide sequences and corresponding amino acids detected in clones from each infant sample at each position. The number of clones with each nucleotide sequence is indicated. Reference sequences / amino acids (those found in reference strain HXB2) are shaded. Sequences / mutations associated with NVP resistance are shown in bold.
  footer_text: * Note that the mutations K103R and V179D are associated with NVP resistance only when they occur together.
    unique: PMC2562759/PMC2562759.xml::T3-0
    unique: PMC2562759/PMC2562759.xml::T3-1

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562759.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562759.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562759.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562759.xml::T3-1'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562761.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562761.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562774.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562761.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of Mean Stiffness and Hardness in Mytilus Cuticle, the Byssal Thread Core, and Synthetic Epoxies
  footer_text:
    unique: PMC2562761/PMC2562761.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Repeat Sequence Motifs from mfp1s of Seven Marine Mussel Species (Italicized P and Y denote Pro and Tyr residues targeted for hydroxylation)
  footer_text:
    unique: PMC2562761/PMC2562761.xml::T2-0

PMC0025XXXXX/PMC2562772.xml

PMC0025XXXXX/PMC2562774.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Selected Bond Lengths (Å) and Angles (°) for Fe3(SPh)6(CO)6,24 Fe3(S2C3H6)3(CO)4(PEt3)2, and PBnPh3[Fe3(S2C3H6)4(CO)4] (Fe(1) is Terminal and Fe(2) is Central).
  footer_text:
    unique: PMC2562774/PMC2562774.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Selected Crystallographic Data for PBnPh3[Fe3(S2C3H6)4(CO)4]•3THF and Fe3(S2C3H6)3(CO)4(PEt3)2.
  footer_text:
    unique: PMC2562774/PMC2562774.xml::T2-0

PMC0025XXXXX/PMC2562775.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic data on child survey participants and non-participants
  footer_text:
    unique: PMC2562775/PMC2562775.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Results for model for use of bronchodilator
  footer_text: Notes: Model A (Exchangeable single latent trait) Model B (General single latent trait) Model C (Direct dependence single latent trait) Model D (Direct dependence bivariate latent trait) Model E (Correlated bivariate latent trait)
    unique: PMC2562775/PMC2562775.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Simulations based on n = 1500 subjects, two informants based on a 5-item questionnaire with correlation of 0.4. Rows correspond to different patterns of missingness, with logit(Pr(missing))=γ0+γ1∑Xvib+γ2Y. Table entries show the mean of the estimates of α1 from 1000 simulated datasets fit using model (E), where the true value of α1 is 2. Corresponding standard errors are given in parentheses.
  footer_text:
    unique: PMC2562775/PMC2562775.xml::T3-0

PMC0025XXXXX/PMC2562777.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Selected EPR Parameters for [Fe2(S2CXH2x)(CO)2L(dppv)]BF4 (Spectra Recorded at 110 K (−163 °C), in 1:1 CH2Cl2:toluene).
  footer_text: a For [3pdt]+ the two species are present in at 2:1 ratio.
    unique: PMC2562777/PMC2562777.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Selected EPR Parameters for [Fe2(S2CxH2x)(μ-CO)(CO)3L(dppv)]BF4 (Spectra Recorded at 110K (−163 °C), in 1:1 CH2Cl2:toluene)
  footer_text:
    unique: PMC2562777/PMC2562777.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562775.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562775.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562775.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562777.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562777.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Selected Structural Parameters for [Fe2(S2C3H6)(CO)3L(dppv)]BF4 (L = PMe3, Pi-Pr3).
  footer_text:
    unique: PMC2562777/PMC2562777.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Details of Data Collection and Structure Refinement for Crystallography.
  footer_text: a R1 = Σ|Fo|−|Fc|/Σ|Fo| b wR2 = {[w(|Fo|−|Fc|)2]/Σ[wFo2]}1/2, where w = 1/σ2 (Fo)
    unique: PMC2562777/PMC2562777.xml::T4-0

PMC0025XXXXX/PMC2562863.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic characteristics by mortality status for respective final testing wave.
  footer_text: Note. Standard deviations appear in parentheses. Subjects rated their health relative to same-aged peers on a 5-point scale ranging from (0) very good to (4) very poor.
    unique: PMC2562863/PMC2562863.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mortality and age group mean T-scores for cognitive and speeded measures at last testing wave.
  footer_text: Note. Standard deviations appear in parentheses; ISD = intraindividual standard deviation. a These measures were not administered for Sample 1Wave 1.
    unique: PMC2562863/PMC2562863.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Cox regressions predicting mortality status as a function of demographic and cognitive covariates.
  footer_text: Note. Statistical models were computed separately for each cognitive and speed measure. Results represent parameters for a given regression block controlling for the influence of all predictors on previous blocks. Values in column 1 reflect unstandardized regression coefficients, whereas values in column 2 are odds ratios denoting percentage change in morality risk per unit increase of predictor. Mortality status was coded as either 0 (survivor) or 1 (decedent). CI = confidence interval; CVD = cardiovascular disease. Subjects rated their health relative to same-aged peers on a 5-point scale ranging from (0) very good to (4) very poor. CVD conditions represent self-reported presence of 4 cardiovascular diseases (heart disease, stroke, arteriosclerosis, and high blood pressure) for any wave of testing. CVD medications reflect self-reported use of medications prescribed to treat cardiovascular symptoms and disease (heart, chest, high blood pressure, and anticoagulants). ISD = intraindividual standard deviation. a N = 707 for all measures except computation span and listening span (n = 635).
    unique: PMC2562863/PMC2562863.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562777.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562777.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562863.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562863.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562863.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562863.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562869.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562875.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562875.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Change in speed inconsistency as a function of time to death, age group, and mortality status.
  footer_text: a Note. A significant Age group × Mortality status interaction was observed for this variable; associated mortality coefficients are reported separately for each age group in the text. γ00 = inconsistency for Young-Old Survivors at the sample midpoint for time remaining in the study (M = 7.24 years); γ10 = average rate of change in inconsistency per additional year of time remaining in the study for Young-Old Survivors; γ11 = average difference in rate of inconsistency change between Young-Old and Old-Old adults partialing the influence of mortality status; γ12 = average difference in rate of inconsistency change between Survivors and Decedents controlling for age group differences; SE = standard error; t = t-ratio. * p< .05 ** p < .01
    unique: PMC2562863/PMC2562863.xml::T4-0

PMC0025XXXXX/PMC2562869.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: ELISA and Multiplex Cost Comparison
  footer_text: * Cost per sample is determined by taking the commercial cost of the immunoassay kit and dividing by the number of samples that can be analyzed in duplicate (between 36 and 40, for most immunoassays depending on number of standards and controls run in each assay).
    unique: PMC2562869/PMC2562869.xml::T1-0

PMC0025XXXXX/PMC2562875.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of study population
  footer_text: * Louisiana, Arkansas, Oklahoma, New Mexico
    unique: PMC2562875/PMC2562875.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Risk factors of pancreatic cancer and association of pancreatic cancer with HBV or HCV infection: Univariable and Multivariable logistic regression analysis
  footer_text: Abbreviations: +, positive; −, negative; anti-HBc, anti-hepatitis B core antigen; anti-HBs, anti-hepatitis B surface antigen; HBV, hepatitis B virus; HBsAg, hepatitis B surface antigen; HCV, hepatitis C virus. * Never exposed; † Chronic carrier of HBV; ‡ Past exposure to HBV; § Past exposure to HBV with natural immunity; ¶ Possible chronically infected and have an undetectable level of HBsAg present in the serum.
    unique: PMC2562875/PMC2562875.xml::T2-0

PMC0025XXXXX/PMC2562879.xml

PMC0025XXXXX/PMC2562884.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Pre- and Postsupplementation Debrisoquine Urinary Recovery Ratios
  footer_text: CI = confidence interval, HDEB = 6-hydroxydebrisoquine, DEB = debrisoquine † = geometric mean of postsupplementation/presupplementation ratios and 90% CI * = p < 0.05
    unique: PMC2562884/PMC2562884.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Phytochemical analysis and disintegration times for botanical dosage forms.
  footer_text:
    unique: PMC2562884/PMC2562884.xml::T2-0

PMC0025XXXXX/PMC2562890.xml

PMC0025XXXXX/PMC2562891.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of demographic variables, vascular risk factors, and Hamilton Depression Rating Scale (HAM) score between persons with and without incident Alzheimer’s disease. Washington Heights- Inwood Columbia Aging Project 1992-2003.
  footer_text:
    unique: PMC2562891/PMC2562891.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562884.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562884.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562891.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562891.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Comparison of Hamilton Dementia Rating Scale Scores by the presence of vascular risk factors. Washington Heights- Inwood Columbia Aging Project 1992-2003.
  footer_text:
    unique: PMC2562891/PMC2562891.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Hazard ratios (HR) and 95% confidence intervals relating Hamilton Depression Rating Scale (HAM) scores to incident Alzheimer’s disease (AD). Model 1 is adjusted for age and gender. Model 2 is adjusted also for ethnic group, education, APOEε4, diabetes, hypertension, heart disease, current smoking, and stroke. Washington Heights- Inwood Columbia Aging Project 1992-2003.
  footer_text:
    unique: PMC2562891/PMC2562891.xml::T3-0

PMC0025XXXXX/PMC2562897.xml

PMC0025XXXXX/PMC2562898.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Digoxin pharmacokinetic parameters before and after supplementation/drug phases (mean ± s.d.)
  footer_text: AUC = area under the concentration-time curve, Cmax = maximum serum concentration, * = p < 0.05
    unique: PMC2562898/PMC2562898.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Phytochemical analysis and disintegration times for botanical dosage forms (n = 6).
  footer_text:
    unique: PMC2562898/PMC2562898.xml::T2-0

PMC0025XXXXX/PMC2562902.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562891.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562898.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562898.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562902.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562902.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1:
  caption_text: Mean Knowledge Score by Occupation
  footer_text: a. * ANOVA p.= < 0.000 b. ** Dunnet test p= <0.0000 Doctor was the control
    unique: PMC2562902/PMC2562902.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2:
  caption_text: Beliefs and Attitudes About Diagnosis and Care of HIV/AIDS Patients and Health Care Settings
  footer_text:
    unique: PMC2562902/PMC2562902.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3:
  caption_text: Feelings and Views Towards Care of HIV/AIDS Patients in Different Health Care Settings *Total score on feelings and views towards care of HIV/AIDS patient item.
  footer_text: * Maximum score = 48.
    unique: PMC2562902/PMC2562902.xml::T3-0
{'tfoot'}
  ----------------------------------------
  id: T4
  label_text: Table 4:
  caption_text: Comparison of Means of Total Knowledge Score by Source of Information
  footer_text: a. School > radio p< 0.05 b. School > health talks/seminars p < 0.05
    unique: PMC2562902/PMC2562902.xml::T4-0

PMC0025XXXXX/PMC2562904.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patient information for cases included in this study.
  footer_text: * The numeric values here represent a rank ordering of fracture severity amongst the twenty cases from 1 (indicating least severe) to 20 (most severe).
    unique: PMC2562904/PMC2562904.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562902.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562904.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562912.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562912.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Correlations between observed empathic and nonempathic responses, self-reported spouse responses to pain, marital satisfaction, and perceived spousal support
  footer_text: Note: * p < .05 ** p < .01. I-S = Invalidation by Spouse, V-S = Validation by Spouse, V-PP = Validation by Person with Pain, I-PP = Invalidation by Person with Pain. For the following variables, PP = Report by Person with Pain; S = Spouse Report: PR = Punishing Responses, SR = Solicitous Responses, DR = Distracting Responses, DAS = Dyadic Adjustment Scale, PSS = Perceived Spousal Support
    unique: PMC2562912/PMC2562912.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Pattern Matrix for Exploratory Factor Analysis on Self-Report Spouse Responses and Observations of Validation and Invalidation
  footer_text: a Solution accounts for 57% of the variance. The correlation between factors = -.17. PP = Person with Pain. * p < .05. ** p < .01.
    unique: PMC2562912/PMC2562912.xml::T2-0

PMC0025XXXXX/PMC2562926.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Estimates of β for the ACTG 175 data. Unadjusted is Ȳ(1)−Ȳ(0); Change scores is Ȳ(1)−Ȳ(0) − the difference in sample mean baseline CD4; Forward-1 is β̂ in (17) with treatment-specific regression models developed using forward selection allowing linear terms only in elements of X; Forward-2 is the same but allowing linear, quadratic, and two-way interaction terms; ANCOVA is β̂ANCOV A1 using all elements of X; and Koch is β̂KOCH using all elements of X. SE is estimated standard error calculated as described in the text. Test Stat. is the Wald test statistic; and Rel. Eff. is (SE for the Unadjusted estimator)2 divided by (SE for the indicated estimator)2.
  footer_text: * Row calculated using usual least squares SE
    unique: PMC2562926/PMC2562926.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Results for the simulation scenario based on the ACTG 175 data using 5000 Monte Carlo data sets. Estimators are as in Table I; Benchmark is the proposed estimator found by fitting the true treatment-specific regressions to obtain predicted values. MC SD is Monte Carlo standard deviation, Ave SE is the average of standard error estimates, Cov. Prob. is coverage probability of a 95% Wald confidence interval, and Rel. Eff. is the Monte Carlo mean square error for the Unadjusted estimator divided by that for the indicated estimator.

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562912.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562926.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562926.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562926.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562926.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  footer_text: * Row calculated using usual least squares SE
    unique: PMC2562926/PMC2562926.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table III
  caption_text: Results for the second simulation scenario data using 5000 Monte Carlo data sets. All entries are as in Table II.
  footer_text:
    unique: PMC2562926/PMC2562926.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table IV
  caption_text: Proportion of 5000 Monte Carlo data sets for which the null hypothesis β = 0 is rejected in favor of the alternative β > 0 using the test statistic based on each estimator and level of significance 0.025. Each of the two simulation scenarios in the text is considered with n = 400, δ = 0.50, and the intercept of the true E(Ȳ |Z = k, X), k = 0, 1, adjusted so that the true value of β is that indicated.
  footer_text:
    unique: PMC2562926/PMC2562926.xml::T4-0

PMC0025XXXXX/PMC2562929.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Effect on the BRCAPRO carrier probability of excluding vs. including all non-breast/ovary cancers into BRCAPRO for families based on figure 1. Non-breast/ovary cancers are included as per the methods of section 2.4.
  footer_text:
    unique: PMC2562929/PMC2562929.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Characteristics of the BRCAPRO predictions that exclude surviving all non-breast/ovary cancers versus including surviving all non-breast/ovary cancers. The first three columns are for predicting BRCA1 or BRCA2 mutations, the second for predicting solely BRCA1 mutations, the third column for predicting solely BRCA2 mutations. The postive/negative predictive values (PPV,NPV), sensitivity, and specificity are all for a 10% carrier probability threshold. The p-value column tests if the difference between including and excluding is zero for each statistic.
  footer_text:
    unique: PMC2562929/PMC2562929.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table III
  caption_text: Calibration of the BRCAPRO predictions that exclude surviving all non-breast/ovary cancers versus including surviving all non-breast/ovary cancers. The first two columns are for predicting BRCA1 or BRCA2 mutations, the second for predicting solely BRCA1 mutations, the third for predicting solely BRCA2 mutations. The rows are for all the data (overall), those with carrier probability < 10%, and with carrier probability > 10%, computing the ratio of observed to expected (O/E) and the left/right endpoints of its 95% confidence interval.
  footer_text:
    unique: PMC2562929/PMC2562929.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562929.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562929.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562929.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562935.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562935.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2562934.xml

PMC0025XXXXX/PMC2562935.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Frequency of CD4+ and CD8+ T-Cell Responses to Gag, Pol, Nef, Reg, and Env Among 71 HIV-1–Infected Women in South Africa
  footer_text:
    unique: PMC2562935/PMC2562935.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Peptide Pools Eliciting CD4+ and CD8+ T-Cell Responses Among 71 HIV-1–Infected Women in South Africa
  footer_text:
    unique: PMC2562935/PMC2562935.xml::T2-0

PMC0025XXXXX/PMC2562941.xml

PMC0025XXXXX/PMC2562949.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Test set of coiled-coil dimers of known orientation
  footer_text: Data for seven bZIP coiled coils without structures not included in averages. a Fraction exposed is the ratio of the solvent-accessible surface area (SASA) of the coiled coil as observed in the crystal structure to the SASA of the isolated coiled coil. SASA calculated using NACCESS.68 b RMSD to the closest ideal Crick backbone is the difference between the crystal structure and the best-fitting Crick ideal structure. Data for all structure is shown in Supplemental Figure S1.
    unique: PMC2562949/PMC2562949.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Summary of pair terms used in ISM models
  footer_text: A prime (’) designates a residue on the opposite helix. All interaction pairs listed involve structurally adjacent sites on opposite helices. For edge interactions where there may be some ambiguity as to what pair is indicated, the interactions are as follows: g-e’ pairs in parallel coiled coils are between a g residue and the e residue of the next (mor C-terminal) heptad of the opposite helix; n antiparallel coiled coils g-g’ pairs are between a g residue and the g residue of the previous (more N-terminal) heptad of the opposit helix and e-e’ pairs are between an e residue and the e residue of the next (more C-terminal) heptad of the opposite helix.
    unique: PMC2562949/PMC2562949.xml::T2-0

PMC0025XXXXX/PMC2562989.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562949.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2562949.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2563044.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2563044.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2563044.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Summary of UO2 Synthesis and Main Characteristics of the Study Materials
  footer_text: a Courtesy of Dan Schwarz and David Clark, Los Alamos National Laboratory. b Multipoint N2-BET. c Calculated from particle morphology visualized by scanning electron microscopy (SEM). d Derived from high-resolution transmission electron microscopy (HR-TEM) and synchrotron-based powder diffraction (SR-PD). e Lower value calculated from SSA, higher value taken from SEM images (upper limit). f Based on SEM images.
    unique: PMC2563044/PMC2563044.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Comparison of UO2 Dissolution Rates Measured under Reducing, Carbonate-Free Conditions (Rm and Rn are means Calculated by eqs 2 and 3; the Rate Constant k is Obtained from the Dissolution Model (eq 5) Assuming Steady-State Was Reached; All Rates Account for the Time-Dependent Loss of Solid while Dissolution)
  footer_text: a A thin film of 0.5 g UO2.0 was used in this work. b If no reference given, data are from the present work.
    unique: PMC2563044/PMC2563044.xml::T2-0

PMC0025XXXXX/PMC2563421.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of recommendations
  footer_text:
    unique: PMC2563421/PMC2563421.xml::T1-0

PMC0025XXXXX/PMC2563799.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2563421.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2563799.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2563799.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2563957.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sequences of the Ib-IX-derived TM peptides used in this study
  footer_text: a The TM sequence is indicated in bold and Cys residues underlined. b Residue C148 in the Ibβ cytoplasmic domain was changed to Ser (the residue in the rat sequence). c Residue C154 in the IX cytoplasmic domain was changed to Asn (the residue in the rat sequence).
    unique: PMC2563799/PMC2563799.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: The effect of detergents on production of the αβ2 peptide complex in thiol-disulfide exchange reactions. The molar ratio of Ibα-TM, Ibβ-TM, IX-TM (if included) and detergent was 1:2:1:200 in all reactions. The amount of αβ2 is measured through integration of the corresponding HPLC peak and expressed as the percentage of total Ibβ-TM in the reaction
  footer_text:
    unique: PMC2563799/PMC2563799.xml::T2-0

PMC0025XXXXX/PMC2563805.xml

PMC0025XXXXX/PMC2563957.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Modification of Composition of Flora Within Biofilm With the Introduction of P. gingivalis to Healthy Tissues, Baseline Periodontitis, and Subsequent RvE1 Treatment in a Rabbit Model of Experimental Periodontitis
  footer_text: Copyright 2007. The American Association of Immunologists.7 * Chemiluminescence units (scale of 0 to 5 with 0 indicating no signal): 1 = undetectable <104 bacteria; 2 = 105 bacteria; 3 = >105 but <106 bacteria; 4 = 106 bacteria; and 5 = >106 bacteria. † P <0.05 compared to healthy. ‡ Previously T. forsythensis.
    unique: PMC2563957/PMC2563957.xml::T1-0

PMC0025XXXXX/PMC2563959.xml

PMC0025XXXXX/PMC2563962.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: MAD Data Collection Statistics
  footer_text:
    unique: PMC2563962/PMC2563962.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2563962.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2563962.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564287.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Data Collection and Refinement Statistics
  footer_text: Numbers in the parentheses represent the statistics of the highest resolution shell.
    unique: PMC2563962/PMC2563962.xml::T2-0

PMC0025XXXXX/PMC2564285.xml

PMC0025XXXXX/PMC2564287.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic and Lifestyle Characteristics of men with and without Benign Prostate Hyperplasia in the Prostate Cancer Prevention Trial (PCPT)†.
  footer_text: a) from t-test b) from chi-square test † All men in this study were in the placebo arm of the PCPT.
    unique: PMC2564287/PMC2564287.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Definitions of BPH events in the Prostate Cancer Prevention Trial (n=704)
  footer_text: a) Events were selected hierarchically in the order listed. b) International Prostate Symptom Score’s range from 0 to 30, with 0–7 indicating mildly symptomatic, 8–19 moderately symptomatic; and 20–35 severely symptomatic. * Included in definition of “clinical BPH”.
    unique: PMC2564287/PMC2564287.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Associations of IGF1, IGFBP3 and IGF1:IGFBP3 with risk of BPH in the PCPT
  footer_text: 1 Adjusted Adjusted for age at baseline and race 2 Adjusted for age at baseline, race and BMI 3 Polytomous logistic regression adjusting for age at baseline, race and BMI € The models for “all BPH” include all cases; the models for “clinical BPH” and “symptomatic progression BPH” are models for the two subtypes of BPH Quartile 1 is the referent for all models
    unique: PMC2564287/PMC2564287.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Associations of IGF1, IGFBP3 and IGF1:IGFBP3 with Risk of Clinical BPH, stratified by age in the PCPT
  footer_text: 1 Adjusted for BMI and race. Quartile 1 is the referent for all models
    unique: PMC2564287/PMC2564287.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Associations of IGF1, IGFBP3 and IGF1:IGFBP3 with Risk of Clinical BPH, stratified by Body Mass Index (BMI) in the PCPT
  footer_text: 1 Restricted to clinical cases only. 2 Adjusted for age and race Quartile 1 is referent for all models
    unique: PMC2564287/PMC2564287.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564287.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564287.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564287.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564287.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564288.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564288.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564288.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564288.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2564288.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Study 1. Factor Loadings for the 3-Factor Structure
  footer_text: N = 412; factor loadings over .40 in bold; Disengage = Disengagement Factor, Negative/Dissatis. = Negativity/Dissatisfaction Factor, Positiv./Closeness = Positivity/Closeness Factor. Items reordered for ease of presentation.
    unique: PMC2564288/PMC2564288.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Study 2. Descriptive Statistics: Means and Standard Deviations across Samples
  footer_text: Note. RDI = Relational Distance Index. Dating sample: N = 203 for all variables except RDI; for RDI scales, n = 63. Marital sample (husbands and wives): N = 77 couples. Physically victimized women: N = 42. All means and standard deviations were converted to their respective response scales.
    unique: PMC2564288/PMC2564288.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Study 2. Factor Loadings on the 1-Factor Romantic Disengagement Scale across Samples
  footer_text: Note. A complete list of items included in initial and revised item pools may be obtained from first author. Based on our proposed conceptualization, items 1–7 represent emotional distance, items 8 and 9 represent cognitive distance, and items 10–18 represent behavioral distance; however, factor analyses did not distinguish components. All factor loadings were significant at p < .001. Items were reordered in this table for ease of presentation.
    unique: PMC2564288/PMC2564288.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Study 2. Bivariate Correlations between the Romantic Disengagement Scale and Variables Included to Support Discriminant and Incremental Validity
  footer_text: Note. RDI = Relational Distance Index. * p < .05. ** p < .01.
    unique: PMC2564288/PMC2564288.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Study 2. Hierarchical Regression Analyses Demonstrating Incremental Validity of the Romantic Disengagement Scale (RDS) over Hess’s Relational Distancing Index (RDI)
  footer_text: Note. RDI = Relational Distancing Index. + p < .10. * p < .05. ** p < .01.
    unique: PMC2564288/PMC2564288.xml::T5-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564288.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564601.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564601.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564605.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2564601.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of Abused and Non-abused Low-Income Rural Pregnant Women (N = 50)
  footer_text:
    unique: PMC2564601/PMC2564601.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Stressors Reported by Abused and Non Abused Rural Women to Research Nurses (N = 50)
  footer_text:
    unique: PMC2564601/PMC2564601.xml::T2-0

PMC0025XXXXX/PMC2564605.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Stability of Affinity Grids in the presence of detergents as assessed by visual inspection of the specimens in the electron microscope.
  footer_text: * according to Anatrace Inc. (Maumee, OH); **according to Sigma Chemical Company (St. Louis, MO) ++ No apparent degradation of the lipid monolayer (continuous lipid monolayer) + Minor degradation of the lipid monolayer (appearance of some small holes in the lipid monolayer and of some small lipid vesicles) − Major degradation of the lipid monolayer (presence of many small holes in the lipid monolayer and of many small lipid vesicles) − − Almost complete degradation of the lipid monolayer (large grid areas without lipid monolayer
    unique: PMC2564605/PMC2564605.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Stability of Affinity Grids in the presence of glycerol as assessed by visual inspection of the specimens in the electron microscope.
  footer_text: ++ No apparent degradation of the lipid monolayer (continuous lipid monolayer) + Minor degradation of the lipid monolayer (appearance of some small holes in the lipid monolayer and of some small lipid vesicles) − Major degradation of the lipid monolayer (presence of many small holes in the lipid monolayer and of many small lipid vesicles) −− Almost complete degradation of the lipid monolayer (large grid areas without lipid monolayer)
    unique: PMC2564605/PMC2564605.xml::T2-0

PMC0025XXXXX/PMC2564794.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of physiological parameters between QC and SC fibers and their responses to pruritic stimuli (cowhage and histamine)
  footer_text: QC fibers had significantly smaller mechanical and heat thresholds, and the responses to cowhage were significantly larger, with a significantly higher intraburst frequency and a significantly smaller interburst interval. Histamine responses did not differ between QC and SC fibers. * p < 0.01, Mann-Whitney U test (QC vs SC); ** p < 0.01, unpaired t test (QC vs SC); *** p < 0.001, unpaired t test (QC vs SC).
    unique: PMC2564794/PMC2564794.xml::T1-0

PMC0025XXXXX/PMC2564798.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Clinical characteristics of POH and other GNAS-based disorders of superficial heterotopic ossification (HO).
  footer_text: All (+) or no (−) patients within the diagnostic category displayed the indicated characteristic. a Deep HO refers to the extension of superficial (dermal) HO to deep tissues as described in the text. b AHO features included the following characteristics: short stature, obesity, round face, brachydactaly, and neurobehavioral abnormalities. The presence of heterotopic ossification was common to all presentations and excluded here. c An endocrine evaluation included a survey of calcium, phosphorus, TSH, and intact PTH blood levels. Two POH patients had endocrine abnormalities: one had a high TSH, and another had high calcium and phosphate levels. One POH/AHO patient had a high phosphate level. All POH/PHP 1a/1c and PHP 1a/1c patients had PTH resistance or PTH and thyroid hormone resistance. Differences found to be statistically significant when compared to POH are d p value < 0.0001 e p value = 0.0002. Abbreviations are as defined in the text.
    unique: PMC2564798/PMC2564798.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: AHO features among patients with POH and other GNAS-based disorders of superficial heterotopic ossification.
  footer_text:
    unique: PMC2564798/PMC2564798.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564605.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564794.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564798.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564798.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2564809.xml

PMC0025XXXXX/PMC2564811.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: An example of the overall fit indices inferred by the SEM for Model 1 at two voxels (with Talaraich coordinates in units of mm) in one subject’s brain. Voxel A was selected from the red region of Figure 4, and Voxel B was selected from outside that region.
  footer_text:
    unique: PMC2564811/PMC2564811.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: The region of peak activation value (determined by AGFI) detected by six models at two hemispheres. The Talaraich coordinates of regions, standardized path weights and AGFIs in the models, were inter-subject averaged. The numbers of subjects represent how many of the seven subjects’ data showed activity in this area. The values are presented as: Mean ± Standard Deviation. The unit of coordinates in Talaraich space is mm.
  footer_text:
    unique: PMC2564811/PMC2564811.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: The ROIs used in SEM analysis at two hemispheres. The ROIs were defined by a series of t-tests and anatomic landmarks, as described in Methods and Materials. Talaraich coordinates of peak activity (determined by p-value) in the region were averaged among seven subjects. The time courses of each ROI were tested by a corresponding structural equation model (referred as “Tested Model” in table). The last column is the inter-subject averaged AGFI derived from the model. The values are presented as: Mean ± Standard Deviation. The unit of coordinates in Talaraich space is mm.
  footer_text:
    unique: PMC2564811/PMC2564811.xml::T3-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564811.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564811.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564811.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564827.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2564827.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Biographical data for the subjects tested.
  footer_text:
    unique: PMC2564827/PMC2564827.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Percent correct agreement between the channels selected by ACE and the channels selected by IdBM in different background conditions.
  footer_text:
    unique: PMC2564827/PMC2564827.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Average performance, in terms of hits and false alarm rates6, of three SNR estimation algorithms that were used to compute the binary mask.
  footer_text:
    unique: PMC2564827/PMC2564827.xml::T3-0

PMC0025XXXXX/PMC2564854.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Intended and Unintended Damage for All Experimental Groups
  footer_text: Data are the estimated percentage of normal volume as assessed from MR images. Areas 11, 12, 13, and 14 – cytoarchitectonic subregions of the macaque frontal lobe as defined by Carmichael and Price (1994); Ia – agranular insular area as defined by Carmichael and Price (1994); ERh – entorhinal cortex and PRh – perirhinal cortex as defined by Amaral and colleagues (Amaral et al., 1987; Insausti et al., 1987); L – percentage of damage to the left hemisphere; R – percentage of damage to the right hemisphere; Avg – average of L and R; W = (L × R)/100 [weighted index as defined by Hodos and Bobko (1984)]; X – group mean.
    unique: PMC2564854/PMC2564854.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564827.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564827.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564854.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564854.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564857.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564857.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564857.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Behavioral Ethogram
  footer_text: List of all behaviors recorded along with brief definitions. All behaviors were analyzed for frequency (total number of occurrences). * Behavior for which total duration was also measured. NOTE: An additional general category of Facial Expressions was also analyzed, which included Lipsmack, Fear Grimace, Mild Threat and Full Threat.
    unique: PMC2564854/PMC2564854.xml::T2-0

PMC0025XXXXX/PMC2564857.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographics of Doxycycline Treated and Control Study Populations
  footer_text:
    unique: PMC2564857/PMC2564857.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Study Parameters at Baseline
  footer_text:
    unique: PMC2564857/PMC2564857.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Procedural parameters and peri-procedural demographic data
  footer_text:
    unique: PMC2564857/PMC2564857.xml::T3-0

PMC0025XXXXX/PMC2564858.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Effects of the various treatment conditions on food-reinforced responding Rats were trained to respond under a multiple, alternating schedule of cocaine (0.25 mg/kg/infusion) and food reinforcement. Values represent the means (± S.E.M.) for N=8. None of the treatments (except for extinction conditions) significantly altered food-maintained responding from values seen when the vehicle was administered.
  footer_text: * p<0.05 compared to all other treatment conditions.
    unique: PMC2564858/PMC2564858.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564858.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564858.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564858.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564858.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564867.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Effects of the various treatment conditions on food-reinforced responding Rats were trained to respond under a multiple, alternating schedule of food and either 0.125 mg/kg/infusion (left side) or 0.5 mg/kg/infusion (right side) cocaine reinforcement. Values represent the means (± S.E.M.) for N=8. None of the treatments (except for extinction conditions) significantly altered food-maintained responding from values seen when the vehicle was administered.
  footer_text: * p<0.05 compared to all other treatment conditions.
    unique: PMC2564858/PMC2564858.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Effects of the various treatment conditions on plasma corticosterone (ng/ml) Rats were trained to respond under a multiple, alternating schedule of cocaine (0.25 mg/kg/infusion) and food reinforcement. Values represent the means (± S.E.M.) for N=8.
  footer_text:
    unique: PMC2564858/PMC2564858.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Effects of the various treatment conditions on plasma corticosterone (ng/ml) Rats were trained to respond under a multiple, alternating schedule of food and either 0.125 mg/kg/infusion (left side) or 0.5 mg/kg/infusion (right side) cocaine reinforcement. Values represent the means (± S.E.M.) for N=8. None of the treatments significantly altered plasma corticosterone from values seen when the vehicle was administered.
  footer_text:
    unique: PMC2564858/PMC2564858.xml::T4-0

PMC0025XXXXX/PMC2564867.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patient demographic characteristics
  footer_text: * Data presented is not mutually exclusive; patients may have reported more than one work status. FM, fibromyalgia
    unique: PMC2564867/PMC2564867.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Patient clinical characteristics
  footer_text: * One participant reported being diagnosed six months ago. FM, fibromyalgia
    unique: PMC2564867/PMC2564867.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564867.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564871.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564891.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Key fibromyalgia domains identified by patients with fibromyalgia*
  footer_text: * Not ranked by order of importance
    unique: PMC2564867/PMC2564867.xml::T3-0

PMC0025XXXXX/PMC2564871.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Probabilities for formation of structural elements within subsets of conformations sampled during kinetic folding simulations
  footer_text: a The average fraction of native contacts formed for various structural elements was computed for conformations in kinetic simulations with 18 Å < Rg < 20 Å and 0.29 < QTotal < 0.42= 0.37, and similarly for the regions of conformational space specified in columns 3–5. b Dashes are used to denote native contacts between two elements of secondary structure: e.g., between strands 1 and 2 (β1–β2) or between helix 1 and the rest of the protein (α1–rest).
    unique: PMC2564871/PMC2564871.xml::T1-0

PMC0025XXXXX/PMC2564891.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Data-collection, phasing and refinement statistics Values in parentheses are for the outermost shell.
  footer_text: † Rmerge = Σhkl Σi |Ii(hkl) − 〈I(hkl)〉|/Σhkl Σi Ii, where 〈I(hkl)〉 is the mean intensity of all symmetry-related reflections Ii(hkl). ‡ Rcryst = (Σ|Fobs −Fcalc|)/ΣFobs. Rfree as for Rcryst but using a random subset of the data (5%) not included in the refinement.
    unique: PMC2564891/PMC2564891.xml::T1-0

PMC0025XXXXX/PMC2564994.xml

PMC0025XXXXX/PMC2564996.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Clinical characteristics of patients enrolled on study
  footer_text:
    unique: PMC2564996/PMC2564996.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Summary of median time to low T and normalization of T and DHT
  footer_text:
    unique: PMC2564996/PMC2564996.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Cox proportional hazards model† for factors associated with T rise in cycle 1 and cycle 2
  footer_text: * Groups with delayed T rise listed first; † The final model, resulting from backward elimination, is presented. Factors included in the initial models, but which did not meet criteria to remain in the final model were baseline T in cycle 1 (for both models in cycle 1), and prior RT (for both models in cycle 2).
    unique: PMC2564996/PMC2564996.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Clinical characteristics of patients proceeding to cycle 2
  footer_text:
    unique: PMC2564996/PMC2564996.xml::T4-0

PMC0025XXXXX/PMC2565494.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564996.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564996.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2564996.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2565496.xml

PMC0025XXXXX/PMC2565508.xml

PMC0025XXXXX/PMC2565509.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sociodemographic Characteristics of the Sample (N=126)
  footer_text:
    unique: PMC2565509/PMC2565509.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Means of Symptom Control for Variables for Each Class
  footer_text: Notes: - WCA Well-Controlled Accurate Group; IG Inaccurate Group; PWC Poorly-Controlled Accurate Group - a=WCA vs. IG-1; b=WCA vs. IG-2; c=WCA vs. PCA; d=IG-1 vs. IG-2; e=IG-1 vs. PCA; f=IG-2 vs. PCA
    unique: PMC2565509/PMC2565509.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Means of Psychosocial Factors in Three Groups
  footer_text: Notes: - WCA Well-Controlled Accurate Group; IG Inaccurate Group; PWC Poorly-Controlled Accurate Group - a=WCA vs. IG; b=WCA vs. PCA; c=IG vs PCA
    unique: PMC2565509/PMC2565509.xml::T3-0

PMC0025XXXXX/PMC2565510.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Clinical data (mean and standard deviation) of the subjects
  footer_text:
    unique: PMC2565510/PMC2565510.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Prevalence and high load (≥106/sample) of the periodontopathogens Aggregatibacter actinomycetemcomitans, Porphyromonas gingivalis, Tannerella forsythia, Treponema denticola, and Prevotella intermedia in gingival crevicular fluid obtained from periodontitis patients as well as healthy controls
  footer_text:
    unique: PMC2565510/PMC2565510.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565509.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565509.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565510.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565510.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565510.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Correlation coefficients (Spearman test) between periodontopathogenic species and myeloperoxidase (MPO) as well as antimicrobial peptides
  footer_text: * P < 0.05 ** P < 0.01.
    unique: PMC2565510/PMC2565510.xml::T3-0

PMC0025XXXXX/PMC2565570.xml

PMC0025XXXXX/PMC2565585.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: EXAFS Curve Fitting Results for 3H and DCH Mutantsa
  footer_text: a Distances (angstroms) and disorder parameters [in parentheses, σ2 (×10−3 Å2)] derive from integer coordination number fits to Fourier-filtered EXAFS data. b Multiple scattering paths represent combined scattering paths described in Experimental Procedures. c Goodness of fit (Rf for fits to filtered data, Ru for fits to unfiltered data) defined as 1000Σi=1N {[Re(χicalc)]2 + [Im(χicalc)]2}/| Σi=1N {[Re(χiobs)]2 + [Im(χiobs)]2}, where N is the number of data points. d For 3H-BcII at pH 6, k = [1.2, 13.5]; R = [0.8, 2.0] for first-shell fits; and R = [0.1, 4.4] for ms fits. e For 3H-BcII at pH 8, k = [1.2, 13.1]; R = [0.8, 2.0] for first-shell fits; and R = [0.1, 4.4] for ms fits. f For DCH-BcII, k = [1.2, 13.5]; R = [0.8, 2.2] for first-shell fits; and R = [0.1, 4.4] for ms fits.
    unique: PMC2565585/PMC2565585.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Kinetic Parameters for Hydrolysis of Nitrocefin, Cefotaxime, Benzylpenicillin, and Imipenem by WT BcII, 3H-BcII, and DCH-BcIIa
  footer_text: a Parameters were determined by fitting initial reaction rates against substrate concentration. The experiments were carried out in 10 mM HEPES (pH 7.5), 200 mM NaCl, 50 μg/mL BSA, and 20 μM Zn(II) in the case of WT BcII and DCH-BcII. In the case of 3H-BcII, the experiments were carried out in 10 mM HEPES (pH 7.5), 200 mM NaCl, and 50 μg/mL BSA. For 3H-BcII, the same kcat/KM values were obtained with increasing Zn(II) concentrations (from 20 to 100 μM).
    unique: PMC2565585/PMC2565585.xml::T2-0

PMC0025XXXXX/PMC2565587.xml

PMC0025XXXXX/PMC2565601.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565585.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565585.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565601.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565601.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Botanicals Tested with Globo H-KLH vaccines, Source, Dose, and Active Ingredients
  footer_text:
    unique: PMC2565601/PMC2565601.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: ELISA Antibody Titers after Vaccination with Globo H-KLH plus or minus Botanicals
  footer_text: * Reciprocal antibody titer. Number in parentheses is the number of mice with that titer, if more than 1. ** Groups in bold are significantly (p<0.05) higher than the no adjuvant control group.
    unique: PMC2565601/PMC2565601.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Summary of ELISA Results of Individual Experiments and of Meta-analysis
  footer_text: * Positive experiment = p value for higher titers induced by indicated botanical compared to no adjuvant or low dose GPI-0100 controls <0.05. ** Compared to mice receiving no adjuvant *** Botanical induced antibody titers that were significantly lower than the controls in these individual experiments.
    unique: PMC2565601/PMC2565601.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: ELISA Antibody Titers after Vaccination with GD3-KLH plus or minus Botanicals
  footer_text: * Reciprocal antibody titer. Number in parentheses is the number of mice with that titer, if more than 1. ** Groups in bold are significantly (p<0.05) higher than the no adjuvant control group. *** Extraction in the indicated percent Ethanol was performed and the precipitate (ppt) and solute (sol) tested.
    unique: PMC2565601/PMC2565601.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565601.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565601.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565802.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565802.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2565602.xml

PMC0025XXXXX/PMC2565685.xml

PMC0025XXXXX/PMC2565802.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic Variables
  footer_text: Differences in age and education were evaluated using an ANOVA; differences in gender and race were evaluated using a chi-square analysis. a F3,184=3.4, p=.02; SCZ>CON-SIB (p=.005), CON (p=.01). b χ2(3) = 34.9, p<.001; c F3,184=3.0, p=.03; SCZ<CON-SIB (p=.026), CON (p=.004).
    unique: PMC2565802/PMC2565802.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mean Scores on the Dimensions of the TCI
  footer_text: Values are least square means (standard errors) as assessed in a mixed model with age and gender as covariates. a F3,73=12.7, p<.001; SCZ>SCZ-SIB (p=.05), CON-SIB (p<.001), CON (p<.001). SCZ>CON-SIB (p=.002), CON (p<.001). b F3,67=7.9, p<.001; SCZ<SCZ-SIB (p<.001), CON-SIB (p=.02), CON (p=.02). c F3,76=7.5, p<.001; SCZ<SCZ-SIB (p<.001), CON-SIB (p=.004), CON (p<.001). d F3,72=3.8, p=.01; SCZ<SCZ-SIB (p=.002), CON-SIB (p=.04), CON (p=.02). e F3,67=5.7, p<.01; SCZ>CON-SIB (p=.006), CON (p<.001); SCZ-SIB>CON-SIB (p=.02), CON (p=.004).
    unique: PMC2565802/PMC2565802.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Analysis of Temperament and Character Configurations
  footer_text: Generalized linear model estimated marginal means (standard errors); these means can be interpreted as an expected fraction after controlling for age, gender, and sibling correlation. a χ2(3) = 24.9, p<.001; SCZ>SCZ-SIB (p=.017), CON-SIB (p<.001), CON (p<.001). b χ2(3) = 12.3, p=.006; SCZ<CON-SIB (p=.001), CON (p<.001); SCZ-SIB<CONSIB (p=.027). c χ2(3) = 7.9, p=.047; SCZ<CON (p=.02). d χ2(3) = 16.3, p=.001; SCZ<SCZ-SIB (p=.013), CON-SIB (p=.004), CON (p<.001). e The model does not converge due to n=0 in one or more cells. f χ2(3) = 15.7, p=.001; SCZ<SCZ-SIB (p=.001), CON-SIB (p<.001), CON (p<.001).
    unique: PMC2565802/PMC2565802.xml::T3-0

PMC0025XXXXX/PMC2565861.xml

PMC0025XXXXX/PMC2565862.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565802.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565862.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2565862.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Predominant features of acute and chronic graft-versus-host disease (Filipovich et al, 2005)
  footer_text:
    unique: PMC2565862/PMC2565862.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Histopathologic studies of minor glands and clinical findings of GVHD salivary gland disease
  footer_text:
    unique: PMC2565862/PMC2565862.xml::T2-0

PMC0025XXXXX/PMC2565865.xml

PMC0025XXXXX/PMC2566523.xml
  ----------------------------------------
  id: T1
tw(T1): {'id', 'orientation', 'position'}
  label_text: Table 1
  caption_text: Single SNP association results for single nucleotide polymorphisms selected for replication from Finnish case–control cohort
  footer_text:
    unique: PMC2566523/PMC2566523.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566523.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566523.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566523.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Demographic factors of the Finnish case and control groups
  footer_text: Other; migraine aura symptoms not fulfilling the International Headache Society aura criteria, but classified as migraine with aura by a clinical neurologist.
    unique: PMC2566523/PMC2566523.xml::T2-0
  ----------------------------------------
  id: T3
tw(T3): {'id', 'orientation', 'position'}
  label_text: Table 3
  caption_text: Replication cohort sizes for individuals successfully genotyped
  footer_text:
    unique: PMC2566523/PMC2566523.xml::T3-0
  ----------------------------------------
  id: T4
tw(T4): {'id', 'orientation', 'position'}
  label_text: Table 4
  caption_text: Replication association analysis results
  footer_text:
    unique: PMC2566523/PMC2566523.xml::T4-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566523.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566523.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566523.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566531.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T5
tw(T5): {'id', 'orientation', 'position'}
  label_text: Table 5
  caption_text: Allele frequency data for rs1431656 and rs7076100 interaction
  footer_text:
    unique: PMC2566523/PMC2566523.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Breakdown of candidate gene categories
  footer_text:
    unique: PMC2566523/PMC2566523.xml::T6-0

PMC0025XXXXX/PMC2566531.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Selected baseline characteristics (mean (standard deviation), or percent) of the ARIC study cohort in relation to baseline exposure status
  footer_text:
    unique: PMC2566531/PMC2566531.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Baseline characteristics (mean (standard deviation), or percent) of the ARIC cohort stratified by menopausal and exposure status
  footer_text:
    unique: PMC2566531/PMC2566531.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566531.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566531.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566546.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566546.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Association of HDL-cholesterol and breast cancer incidence. ARIC study cohort, 1987–2000
  footer_text: HR: hazard ratio, 95% CI: 95 percent confidence interval, SD: standard deviation, P-years: person-years * Regression model adjusted for age, race_by_ARIC center, age at menarche, body mass index, cigarette smoking status, reproductive hormone use, age at menopause (total sample and post-menopausal women only).
    unique: PMC2566531/PMC2566531.xml::T3-0

PMC0025XXXXX/PMC2566540.xml

PMC0025XXXXX/PMC2566546.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Average (+/−SEM) Associative Decision Times (ms) on Correct & Incorrect Trials
  footer_text:
    unique: PMC2566546/PMC2566546.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Design of Experiment 2
  footer_text:
    unique: PMC2566546/PMC2566546.xml::T2-0

PMC0025XXXXX/PMC2566547.xml

PMC0025XXXXX/PMC2566585.xml

PMC0025XXXXX/PMC2566635.xml

PMC0025XXXXX/PMC2566738.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Primary Antibodies Used in This Study
  footer_text:
    unique: PMC2566738/PMC2566738.xml::T1-0

PMC0025XXXXX/PMC2566740.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of single point energies (kcal/mol) calculated for reactants, transition states, intermediates and product structures of reference uncatalyzed reaction (geometries were optimized at IEFPCM(εr=78.4)/B3LYP/6-31G(d,p) level, see Methods for details and Supporting information for structures labeled R, TS1, I1, TS2, I2, TS3, P, and P′ endo/exo) at MPW1K/6-31+G(d,p) and extrapolated CCSD(T)/CBS levels, corresponding errors of the MPW1K functional, solvation terms and the corrections to Gibbs energies at IEFPCM(εr=78.4)/B3LYP/6-31G(d,p) level, and extrapolated total Gibbs energies in water solution at the CCSD(T)/CBS level.
  footer_text: a differences between CCSD(T)/CBS and MPW1K/6-31+G(d,p) energies. b solvation term calculated as the difference between IEFPCM(εr=78.4)/B3LYP/6-31G(d,p) and gas phase B3LYP/6-31G(d,p) SCF energies. c the corrections to Gibbs energies were calculated at the IEFPCM(εr=78.4)/B3LYP/6-31G(d,p) level.
    unique: PMC2566740/PMC2566740.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: The distances (in Å) between C75(N4) and G1(O1P) for various structures. Precursor, transition, and product states are labeled R, TS, and P, respectively. The labels PD, HD, and HS stand for different structural arrangements in the HDV ribozyme active site (see text and Figure 4).
  footer_text:
    unique: PMC2566740/PMC2566740.xml::T2-0

PMC0025XXXXX/PMC2566746.xml

PMC0025XXXXX/PMC2566750.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566738.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566740.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566740.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566750.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic and behavioral characteristics of the sample (N = 30)
  footer_text: a On average, 62.4% of participants' male partners were aware of their bisexuality b On average, 43.5% of participants' female partners were aware of their bisexuality
    unique: PMC2566750/PMC2566750.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Participant relationship characteristics within the past 12 months (N = 30)
  footer_text: a M = male relationship, F = female relationship b Participant 23 did not specify a number for casual male partners. He used “many” to describe them c Participant 30 had not had sex with his current male partner
    unique: PMC2566750/PMC2566750.xml::T2-0

PMC0025XXXXX/PMC2566776.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Participant baseline characteristics by baseline depression status stratified by gender
  footer_text: a p<0.05 comparing difference between depressed and not depressed for overall sample based on χ2 test or t-test b p<0.05 comparing difference between depressed and not depressed for males based on χ2 test or t-test c p<0.05 comparing difference between depressed and not depressed for females based on χ2 test or t-test
    unique: PMC2566776/PMC2566776.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566750.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566776.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566776.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566776.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Regression coefficients for self-reported BMI (kg/m2) at 12-month visit, stratified by gender.
  footer_text: a Income categories: < $25,000, $25,000–34,999, $35,000–49,999, $50,000–74,999, $75,000–99,999, ≥$100,000) b Education categories: less than high school graduate, high school graduate, some college, college graduate or further c Race/ethnic categories: Black or Pacific Islander, other d Pubertal stage categories: Stage 1 or 2, Stage 3, Stage 4 or 5 e Based on self-reported height and weight; modeled as a continuous variable
    unique: PMC2566776/PMC2566776.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean (SD) baseline and 12-month BMI (kg/m2) calculated from self-reported and measured height and weight values, stratified by baseline depressive symptom status and gender
  footer_text: a Boys b Girls
    unique: PMC2566776/PMC2566776.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Regression coefficients for measured BMI at 12-months stratified by gender
  footer_text: a Income categories: < $25,000, $25,000–34,999, $35,000–49,999, $50,000–74,999, $75,000–99,999, ≥$100,000) b Education categories: less than high school graduate, high school graduate, some college, college graduate or further c Race/ethnic categories: Black or Pacific Islander, other d Pubertal stage categories: Stage 1 or 2, Stage 3, Stage 4 or 5 e Based on measured height and weight; modeled as a continuous variable
    unique: PMC2566776/PMC2566776.xml::T4-0

PMC0025XXXXX/PMC2566783.xml

PMC0025XXXXX/PMC2566784.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Real-time PCR primers: The primer sequences are reported in 5’→3’ orientation.
  footer_text: * The accession number used for designing primers for each gene is indicated in the first column in parenthesis.
    unique: PMC2566784/PMC2566784.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566776.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566784.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566790.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2566790.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Patient demographics
  footer_text:
    unique: PMC2566790/PMC2566790.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Differentially expressed genes in three overrepresented biological processes associated with celecoxib pre-treatment
  footer_text: NOTE: Fold change represents the difference in expression in celecoxib pre-treated patients versus patients receiving no drug pretreatment. * P-value represents the likelihood that the number of differentially expressed genes belonging to the biological process occurred by chance as determined by the Fischer’s exact test.
    unique: PMC2566790/PMC2566790.xml::T2-0

PMC0025XXXXX/PMC2566819.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean subjective effects and psychomotor values in which a significant Group (light [LD] vs. moderate drinking [MD] history) x Nitrous Oxide Concentration (0, 20, 30, 40%) x Sample Drug (placebo [PLC], nitrous oxide [N2O]) interaction was found.
  footer_text: For the sake of clarity the 0% nitrous oxide condition is omitted. Numbers in bold font indicate that values differ significantly from placebo as determined by Tukey post hoc testing. a Endpoints of 100-mm VAS: 0=not at all; 100=extremely. b Measures assessed at 5 min into the sampling period in which subjects were asked to rate their response based on how they currently felt. c Tukey post hoc testing revealed significant differences existed between light drinkers (LD) and moderate drinkers (MD). d Responses were made on a 100-mm bipolar VAS. For “drug liking” and “odor liking,” 0=dislike a lot; 50=neutral; 100=like a lot, and for “inhale again,” 0=definitely would not; 50=neutral (don’t care); 100=definitely would. e Dependent measure assessed 5 min after sampling periods; numbers represent mean number of statements endorsed out of a possible 10.
    unique: PMC2566819/PMC2566819.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566790.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566819.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566821.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2566821.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean (SD) Paw Withdrawal Latencies (in seconds) by Group at Baseline and Following Exercise
  footer_text: * Notes: p < .05 ** p < .01.
    unique: PMC2566821/PMC2566821.xml::T1-0

PMC0025XXXXX/PMC2566849.xml

PMC0025XXXXX/PMC2566857.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Demographic information about the three CAH subgroups and the control group.
  footer_text: BMI = Body Mass Index.
    unique: PMC2566857/PMC2566857.xml::T1-0

PMC0025XXXXX/PMC2566897.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sources, Types, and Examples of Chemicals Identified as Potential Endocrine Disruptors (Adapted [2])
  footer_text:
    unique: PMC2566897/PMC2566897.xml::T1-0

PMC0025XXXXX/PMC2566905.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566857.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566897.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566905.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Probe list with numbers of in situ hybridization tests per developmental stage group. Genes (accession number and sequence) for Wnt ligands, Frizzled receptors, and Wnt antagonists analyzed in this study on inner ear tissue from chicken embryos ranging from stage (s)24 to 41 (according to Hamburger and Hamilton, 1951) embryonic day (E)4 to 15.
  footer_text: Shaded in gray are genes that were not detected in ventral inner ear tissue (Wnt1, Wnt2b, and Cer). Those three probes were not tested beyond s38 (E12).
    unique: PMC2566905/PMC2566905.xml::T1-0

PMC0025XXXXX/PMC2566937.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Percent inhibition of [3H]muscimol binding to well-washed membranes from rat cortex and cerebellum by 100 μM and 1 mM of test compounds. Given are the means ± S.D. with the number of experiments in brackets. Compound 17a was insoluble at 1 mM and therefore not tested at this concentration. Structure I applies except were II is specifically indicated. Compounds for which an IC50 is reported in Table 2 are shaded grey.
  footer_text: * inactive.
    unique: PMC2566937/PMC2566937.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566937.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566937.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566937.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566937.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566937.xml::T5-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566937.xml::T6-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566937.xml::T7-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Binding parameters of selected compounds against 6 nM [3H]muscimol in crude membrane preparations of rat cortex and cerebellum determined by nonlinear regression. Given are the means ± S.E.M. of the decadic logarithm of the IC50 in μM, the corresponding pseudo-Hill coefficient η and the number of experiments n.
  footer_text:
    unique: PMC2566937/PMC2566937.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: GABA concentrations and the corresponding relative effective concentration that induces a response around the EC20 when applied to GABAA receptors αiβ3γ2 (i=1–6) transiently expressed in HEK 293 cells. Given are the mean ± S.E.M.
  footer_text:
    unique: PMC2566937/PMC2566937.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Maximal intrinsic activity of 1 mM 5d normalized to the approximate maximal GABA-induced current (I/ImaxGABA) and the 5d EC50 and Hill coefficient on αiβ3γ2 (i=1–6) GABAA receptors. Data are means ± S.E.M.
  footer_text: * marks values of an extrapolated dose-response curve.
    unique: PMC2566937/PMC2566937.xml::T4-0
  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Summary of dose-response data and 6a competition data using a GABA EC20 concentration from cysteine-substituted and wt α1β2 GABAA receptors.
  footer_text:
    unique: PMC2566937/PMC2566937.xml::T5-0
  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Extent of inhibition of GABA-induced currents after reaction with MTS reagent.
  footer_text: Inhibition (% ± S.E.M. (n)) for GABA EC50 currents after complete reaction with MTSES− and MTSEA-biotin on GABAA receptors containing the cited cys-engineered α1 subunit together with the β2 subunit expressed in Xenopus oocytes. n.d. = not determined.
    unique: PMC2566937/PMC2566937.xml::T6-0
  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: MTS-reagent reaction rates.
  footer_text:
    unique: PMC2566937/PMC2566937.xml::T7-0

PMC0025XXXXX/PMC2566943.xml

PMC0025XXXXX/PMC2566947.xml

PMC0025XXXXX/PMC2566953.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Behavioral data from the pilot study (n = 15). Mean RT (ms) and mean accuracy (% correct) with standard deviations (SD) for all experimental conditions
  footer_text:
    unique: PMC2566953/PMC2566953.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Behavioral data from the fMRI study (n = 15). Mean RT (ms) and mean accuracy (% correct) with standard deviations (SD) for all experimental conditions
  footer_text:
    unique: PMC2566953/PMC2566953.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Areas exhibiting significant activation differences in planned comparisons, thresholded at voxel level p < .025, cluster level p < .05 (≥ 51 contiguous voxels)
  footer_text: Note. Coordinates, indicating the maximum intensity voxel for each cluster, are in Talairach and Tournoux space. L = left. R = Right. BA = Brodmann’s area.
    unique: PMC2566953/PMC2566953.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Appendix
  caption_text:
  footer_text:
    unique: PMC2566953/PMC2566953.xml::T4-0

PMC0025XXXXX/PMC2566957.xml

PMC0025XXXXX/PMC2566960.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The set of labeled cells chosen for analysis, with their PSD95 densities.
  footer_text:
    unique: PMC2566960/PMC2566960.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566953.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566953.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566953.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566953.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566960.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2566962.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Properties and Assumptions of Continuous Autoregulation Monitoring Modalities
  footer_text: Licox indicates parenchymal oxygen tension monitor; CMRO2, cerebral metabolic rate of oxygen; and HCT, hematocrit.
    unique: PMC2566962/PMC2566962.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Physiologic Parameters (±SD) of the Piglets at Normal and Low CPP
  footer_text:
    unique: PMC2566962/PMC2566962.xml::T2-0

PMC0025XXXXX/PMC2566963.xml

PMC0025XXXXX/PMC2567021.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline subject characteristics (n = 132)
  footer_text: BMI, body mass index; NYHA, New York Heart Association; LV, left ventricle; ACE, angiotensin converting enzyme; ARB, angiotensin II receptor blocker; NT-proBNP, aminoterminal pro-B-type natriuretic peptide; eGFR, estimated glomerular filtration rate; ADMA, asymmetric dimethylarginine; SDMA, symmetric dimethylarginine; MMA, N-mono-methylarginine; IQR, inter-quartile range.
    unique: PMC2567021/PMC2567021.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Univariate correlations between plasma levels of methylated arginine and lysine metabolites and clinical and echocardiographic indices
  footer_text: ADMA, asymmetric dimethylarginine; SDMA, symmetric dimethylarginine; MMA, N-mono-methylarginine; BMI, body mass index; NT-proBNP, aminoterminal pro-B-type natriuretic peptide; eGFR, estimated glomerular filtration rate; LV, left ventricle; LA, left atrial; PV, pulmonary vein; RV, right ventricular.
    unique: PMC2567021/PMC2567021.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566962.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2566962.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567021.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567021.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567021.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Arginine metabolite levels in patients taking vs. not taking beta-blocker at baseline
  footer_text: Data expressed in median (inter-quartile range). ADMA, asymmetric dimethylarginine; SDMA, symmetric dimethylarginine; MMA, N-mono-methylarginine.
    unique: PMC2567021/PMC2567021.xml::T3-0
  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Univariate and multivariable hazard ratios for predicting death, transplant, or heart failure hospitalization for plasma levels of methylated arginine metabolites
  footer_text: a Hazard ratios per 1-SD increment [1-SD for ADMA = 0.14 μM; 1-SD for SDMA = 0.12 μM; 1-SD for MMA = 14 nM; 1-SD for all methylarginines (ADMA+SDMA+MMA) = 0.24 μM; 1-SD for methyl-lysine = 1.81 μM]. b Multivariable adjustments including age, eGFR, and LV ejection fraction (1-SD for LVEF = 5.99%; 1-SD for age = 13.3 years; 1-SD for eGFR = 20.9 mL/min per 1.73 m2). Hazard ratios per 1-SD increment ADMA = 0.14 μM.
    unique: PMC2567021/PMC2567021.xml::T4-0

PMC0025XXXXX/PMC2567049.xml
  ----------------------------------------
  id: T1
  label_text: Table I
  caption_text: Association of mtDNA markers with multiple sclerosis (MS) and systemic lupus erythematosus SLE. All p<0.05 are indicated. After correction for multiple testing, significant associations are observed for the mtDNA nt9055 variant of the ATP6 gene (in haplogroup K) in both MS and SLE, and for the nt4719 variant of the ND2 gene (in haplogroup T) in MS.
  footer_text:
    unique: PMC2567049/PMC2567049.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table II
  caption_text: Association of mtDNA haplotypes with multiple sclerosis (MS) and systemic lupus erythematosus (SLE).
  footer_text:
    unique: PMC2567049/PMC2567049.xml::T2-0

PMC0025XXXXX/PMC2567051.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of the genomes of a central African strain of monkeypox virus (Zaire-1979) and a west African strain of monkeypox (USA-2003)
  footer_text: Abbreviations: aa: amino acids; BR: cowpox virus strain Brighton Red; C-term: C-terminal fragment; COP: vaccinia virus, strain Copenhagen; CPV: cowpox virus; IL: Interleukin; MPV-Zar_1979_005: central African strain of monkeypox virus; MPV-USA_2003_039: west African strain of monkeypox virus; N-term: N-terminal fragment.
    unique: PMC2567051/PMC2567051.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567021.xml::T4-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567049.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567049.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567051.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Comparison of monkeypox virus and variola virus genomes A. Genes with known function present in monkeypox virus and absent/fragmented in variola virus
  footer_text: Abbreviations: aa: amino acids; BR: Cowpox virus strain Brighton Red; C-term: C-terminal fragment; COP: vaccinia virus, strain Copenhagen; CPV: cowpox virus; eIF: eukaryotic initiation factor; ER: endoplasmic reticulum; IFN: interferon; IL-1: Interleukin-1; MPV: central African strain of monkeypox virus Zaire_1979_005; N-term: N-terminal fragment; ORF: open reading frame; Ser/Thr: serine/threonine; VARV: variola virus strain Bangladesh75maj.
    unique: PMC2567051/PMC2567051.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Comparison of monkeypox virus and vaccinia virus genomes A. Genes with known function present in monkeypox virus and absent/fragmented in vaccinia virus (ACAM2000)
  footer_text: Abbreviations: aa: amino acids; ACAM2000: vaccine strain of vaccinia virus; BR: cowpox virus strain Brighton Red; C-term: C-terminal fragment; COP: vaccinia virus, strain, Copenhagen; CPV: cowpox virus; eIF: eukaryotic initiation factor; IFN: interferon; IL: interleukin; MPV: central African strain of monkeypox virus Zaire_1979_005; N-term: N-terminal fragment; ORF: open reading frame; TNF: tumor necrosis factor.
    unique: PMC2567051/PMC2567051.xml::T3-0

PMC0025XXXXX/PMC2567053.xml

PMC0025XXXXX/PMC2567056.xml

PMC0025XXXXX/PMC2567058.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567051.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567051.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567058.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567058.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Culture Medium
  footer_text:
    unique: PMC2567058/PMC2567058.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Comparison Between Mesenchymal Stem Cells (MSCs) and Nucleus Pulposus (NP) Cells
  footer_text:
    unique: PMC2567058/PMC2567058.xml::T2-0

PMC0025XXXXX/PMC2567059.xml

PMC0025XXXXX/PMC2567102.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Signal intensities of different tissues in the No-Tuning (NT), Anatomy (ANAT), and High-Tuning (HT) C-SENC images. High = signal intensities greater than 0.8 in normalized images; and Low = signal intensities less than 0.2 in normalized images.
  footer_text:
    unique: PMC2567102/PMC2567102.xml::T1-0

PMC0025XXXXX/PMC2567103.xml

PMC0025XXXXX/PMC2567118.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Comparison of cryoablation procedures for AVNRT with the 4 mm versus 6 mm cryoablation catheter tips
  footer_text: AVNRT: Atrioventricular nodal reentrant tachcyardia * Data encompasses all patients with intent to treat, including patients with cryoablation lesions lasting < 240 sec
    unique: PMC2567118/PMC2567118.xml::T1-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567102.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567118.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567118.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567123.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Comparison of patients with and without AVNRT recurrence following an initially successful cryoablation.
  footer_text: AV: atrioventricular AVNRT: atrioventricular nodal reentrant tachycardia
    unique: PMC2567118/PMC2567118.xml::T2-0

PMC0025XXXXX/PMC2567123.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: The Nine Items Translated “Without Complication”
  footer_text:
    unique: PMC2567123/PMC2567123.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: The Fifteen Items Translated “With Complication”
  footer_text:
    unique: PMC2567123/PMC2567123.xml::T2-0

PMC0025XXXXX/PMC2567124.xml

PMC0025XXXXX/PMC2567128.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Participant Characteristics at Enrollment
  footer_text:
    unique: PMC2567128/PMC2567128.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Mixed Linear Regression Results for Drinking Outcomes and Secondary Outcomes of Sleep Quality and Quality of Life†
  footer_text: † Mixed linear model including linear and quadratic change in the outcomes over time (measured at baseline 1-, 3-, and 6-month intervals), intervention difference at baseline, and intervention by linear and quadratic time interactions. *P <0.05 ** P < 0.01 *** P <0.001
    unique: PMC2567128/PMC2567128.xml::T2-0
  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Comparison of Study Medication Adherence and Side Effects, by Study Condition
  footer_text: * From daily sleep log data over the first 4 weeks (total N=121) † From 2-week follow-up data (total N=128) ‡ Log-transformed variable
    unique: PMC2567128/PMC2567128.xml::T3-0

PMC0025XXXXX/PMC2567130.xml

PMC0025XXXXX/PMC2567132.xml

PMC0025XXXXX/PMC2567141.xml

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567123.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567128.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567128.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567128.xml::T3-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

PMC0025XXXXX/PMC2567239.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: A comparison of the mass spectrometry-based phosphoproteomics methods that have been applied to quantify temporal dynamics in the ErbB signaling network.
  footer_text:
    unique: PMC2567239/PMC2567239.xml::T1-0

PMC0025XXXXX/PMC2567241.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Subject characteristics and cell yield for calcium imaging experiments
  footer_text:
    unique: PMC2567241/PMC2567241.xml::T1-0

PMC0025XXXXX/PMC2567282.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Baseline Characteristics of the Sample
  footer_text: IMED = Interim Medical History questionnaire; MAP = Mean Arterial Pressure; HAM-D = Hamilton Depression scale; CR = Care Recipient; CG = Caregiver
    unique: PMC2567282/PMC2567282.xml::T1-0
  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Parameter Estimates for Variables Predicting (log10) Beta Receptor Sensitivity
  footer_text: IMED = Interim Medical History questionnaire; MAP = Mean Arterial Pressure.
    unique: PMC2567282/PMC2567282.xml::T2-0

/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567239.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567241.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567282.xml::T1-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
/home/kimlab1/strokach/anaconda3/lib/python3.6/site-packages/tables/path.py:112: NaturalNameWarning: object name is not a valid Python identifier: 'PMC2567282.xml::T2-0'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)

In [51]:
table_df_dev

          Predictor            Average            Minimum            Maximum     % best results
0               NaN    Neutral Model I    Neutral Model I    Neutral Model I    Neutral Model I
1         Raw rates               33.0               24.8               43.7                  0
2   Empirical Bayes               17.2               9.63               27.4                  4
3   Poisson kriging               12.7               7.39               18.2                 16
4    Statistic Δsαβ               15.9               10.3               20.4                  0
5               NaN   Neutral Model II   Neutral Model II   Neutral Model II   Neutral Model II
6         Raw rates               34.0               26.5               45.1                  0
7   Empirical Bayes               18.5               10.7               29.1                  0
8   Poisson kriging               12.3               6.86               18.4                 68
9    Statistic Δsαβ               15.3               10.9               21.4                  0
10              NaN  Neutral Model III  Neutral Model III  Neutral Model III  Neutral Model III
11  Poisson kriging               13.2               7.00               19.5                  8
12   Statistic Δsαβ               13.2               6.84               20.3                  4

In [52]:
df = table_df_dev


def add_section_index(df):
    df = df.copy()

    index_ = []
    skiprows = []
    for i, row in enumerate(df.itertuples()):
        row_items = [v for v in row[1:] if pd.notnull(v)]
        print(row_items)
        if len(set(row_items)) == 1:
            index_.append(row_items[0])
            skiprows.append(row.Index)
        elif i > 0:
            assert index_
            index_.append(index_[-1])
        else:
            return df
    columns = ['section_index'] + list(df.columns)
    df['index_'] = index_
    df = df.drop(pd.Index(skiprows))
    return df[['index_'] + [c for c in df.columns if c != 'index_']]

In [67]:
add_section_index(df)

['Neutral Model I', 'Neutral Model I', 'Neutral Model I', 'Neutral Model I']
['Raw rates', '33.0', '24.8', '43.7', '0']
['Empirical Bayes', '17.2', '9.63', '27.4', '4']
['Poisson kriging', '12.7', '7.39', '18.2', '16']
['Statistic Δsαβ', '15.9', '10.3', '20.4', '0']
['Neutral Model II', 'Neutral Model II', 'Neutral Model II', 'Neutral Model II']
['Raw rates', '34.0', '26.5', '45.1', '0']
['Empirical Bayes', '18.5', '10.7', '29.1', '0']
['Poisson kriging', '12.3', '6.86', '18.4', '68']
['Statistic Δsαβ', '15.3', '10.9', '21.4', '0']
['Neutral Model III', 'Neutral Model III', 'Neutral Model III', 'Neutral Model III']
['Poisson kriging', '13.2', '7.00', '19.5', '8']
['Statistic Δsαβ', '13.2', '6.84', '20.3', '4']

               index_        Predictor Average Minimum Maximum % best results
1     Neutral Model I        Raw rates    33.0    24.8    43.7              0
2     Neutral Model I  Empirical Bayes    17.2    9.63    27.4              4
3     Neutral Model I  Poisson kriging    12.7    7.39    18.2             16
4     Neutral Model I   Statistic Δsαβ    15.9    10.3    20.4              0
6    Neutral Model II        Raw rates    34.0    26.5    45.1              0
7    Neutral Model II  Empirical Bayes    18.5    10.7    29.1              0
8    Neutral Model II  Poisson kriging    12.3    6.86    18.4             68
9    Neutral Model II   Statistic Δsαβ    15.3    10.9    21.4              0
11  Neutral Model III  Poisson kriging    13.2    7.00    19.5              8
12  Neutral Model III   Statistic Δsαβ    13.2    6.84    20.3              4

In [68]:
table_df
table_df_copy = table_df.copy()

In [69]:
importlib.reload(pmc_tables)

In [70]:
pmc_tables.process_dataframe(table_df_copy)

               index_        Predictor Average  Minimum  Maximum  % best results
1     Neutral Model I        Raw rates    33.0    24.80     43.7             0.0
2     Neutral Model I  Empirical Bayes    17.2     9.63     27.4             4.0
3     Neutral Model I  Poisson kriging    12.7     7.39     18.2            16.0
4     Neutral Model I   Statistic Δsαβ    15.9    10.30     20.4             0.0
6    Neutral Model II        Raw rates    34.0    26.50     45.1             0.0
7    Neutral Model II  Empirical Bayes    18.5    10.70     29.1             0.0
8    Neutral Model II  Poisson kriging    12.3     6.86     18.4            68.0
9    Neutral Model II   Statistic Δsαβ    15.3    10.90     21.4             0.0
11  Neutral Model III  Poisson kriging    13.2     7.00     19.5             8.0
12  Neutral Model III   Statistic Δsαβ    13.2     6.84     20.3             4.0

In [14]:
table_df_dev.columns

MultiIndex(levels=[['Model-1: σ', 'Model-2: c', 'Perf. Measures vs. noise level'], ['1', '10', '150', '30', '50', 'Unnamed: 0_level_1']],
           labels=[[2, 0, 0, 1, 1, 1], [5, 4, 2, 0, 1, 3]])

In [16]:
list(table_df_dev.columns)

[('Perf. Measures vs. noise level', 'Unnamed: 0_level_1'),
 ('Model-1: σ', '50'),
 ('Model-1: σ', '150'),
 ('Model-2: c', '1'),
 ('Model-2: c', '10'),
 ('Model-2: c', '30')]

In [17]:
df = table_df_dev

In [26]:
def parse_string_column(col):
    if col.startswith('Unnamed:'):
        return ''
    else:
        return col

    
def process_column_names(df):
    
    new_columns = []

    for column in df.columns:
        if isinstance(column, str):
            new_column = parse_string_column(column)
        else:
            new_column = ""
            for col in column:
                new_col = parse_string_column(col)
                if new_col:
                    new_column += ' / ' + new_col
            new_column = new_column.strip('/ ')
        new_columns.append(new_column)
        
    return new_columns

In [27]:
process_column_names(df)

['Perf. Measures vs. noise level',
 'Model-1: σ / 50',
 'Model-1: σ / 150',
 'Model-2: c / 1',
 'Model-2: c / 10',
 'Model-2: c / 30']

In [199]:
import re

count = 0


def caption_to_string(element):
    if element is None:
        return ""
    element_text = ET.tostring(element, encoding='utf8', method='text').decode('utf-8')
    element_text = element_text.strip().replace('\n', ' ')
    element_text = re.sub(' +', ' ', element_text)
    return element_text


for i, row in enumerate(manuscript_files.itertuples()):
    print('\n' + f"{row.File}")

    results = {}
    
    tree = ET.parse(MANUSCRIPT_DATA_DIR.joinpath(row.File))
    tables = tree.findall('.//table')
    table_wraps = tree.findall('.//table-wrap')
    
    for table_wrap in table_wraps:
        print("  " + "-" * 40)
        id_ = table_wrap.get('id')
        assert id_ is not None
        print(f"  id: {id_}")
        # Attrib
        attrib_set = set(table_wrap.attrib)
        if attrib_set - {'id', 'position'}:
            print(f"tw({id_}): {attrib_set}")
        # Label
        label = table_wrap.find('label')
        label_text = label.text if label is not None else ""
        print(f"  label_text: {label_text}")
        # Caption
        caption = table_wrap.find('caption')
        caption_text = caption_to_string(caption)
        print(f"  caption_text: {caption_text}")
        # Footer
        footer = table_wrap.find('table-wrap-foot')
        footer_text = caption_to_string(footer)
        print(f"  footer_text: {footer_text}")
        # Other children
        other_children = [
            c.tag for c in table_wrap.getchildren() 
            if c.tag not in ['label', 'caption', 'table', 'table-wrap-foot']
        ]
        if other_children:
            print(other_children)
        
        # Tables
        tables = table_wrap.findall('table')
        for i, table in enumerate(tables):
            unique = f"{row.PMCID}/{op.basename(row.File)}::{id_}-{i}"
            assert unique not in results
            print(f"    unique: {unique}")
            # Attrib
            attrib_set = {a for a in table.attrib if a not in ['frame', 'rules']}
            if attrib_set:
                print(attrib_set)
            # Children
            children_set = {c.tag for c in table.getchildren() if c.tag not in ['thead', 'tbody']}
            if children_set:
                print(children_set)
            # DataFrame
            table_bytes = ET.tostring(table)
            display(HTML(table_bytes.decode('utf-8')))
            table_dfs = pd.read_html(table_bytes, na_values=['', '-', '–'])
            assert len(table_dfs) == 1
            table_df = table_dfs[0]
            display(table_df)
        
    root = tree.getroot()
    a, b = get_tables(root)
    
    count += 1
    if count > 20:
        break

PMC0021XXXXX/PMC2136438.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Mean absolute error (MAE) of prediction for four alternate predictors. The average, minimum and maximum value calculated over 25 simulated rate maps are reported. The last column gives the percentage of simulations where the MAE for the geostatistical methods is lower than for the local empirical Bayes smoother.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T1-0

         Predictor  Average  Minimum  Maximum  % best prediction
0        Raw rates   0.6984   0.6413   0.7467                NaN
1  Empirical Bayes   0.2584   0.2252   0.2916                NaN
2  Poisson kriging   0.2345   0.1961   0.2740               92.0
3  E-type estimate   0.2348   0.1967   0.2750               92.0

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Average of the reference risk values and the estimates obtained using four alternate approaches. The average, minimum and maximum value of the statistic calculated over 25 simulated rate maps are reported.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T2-0

         Predictor  Average  Minimum  Maximum
0   Reference risk    7.209      NaN      NaN
1        Raw rates    7.210    7.083    7.295
2  Empirical Bayes    7.303    7.227    7.364
3  Poisson kriging    7.242    7.165    7.300
4  E-type estimate    7.242    7.164    7.300

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean absolute error (MAE) of prediction of the boundary statistic by five alternate estimators. The average, minimum and maximum MAE calculated over 25 simulated rate maps are reported. The last column gives the percentage of realizations where the MAE for the geostatistical methods is lower than for the local empirical Bayes smoother.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T3-0

         Predictor  Average  Minimum  Maximum  % best prediction
0        Raw rates   0.4556   0.4178   0.4907                NaN
1  Empirical Bayes   0.1027   0.0830   0.1199                NaN
2  Poisson kriging   0.0890   0.0809   0.0985               96.0
3   Statistic ΔEαβ   0.0890   0.0807   0.0982               96.0
4   Statistic Δsαβ   0.1074   0.0925   0.1287               28.0

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Average of the reference boundary statistic values and the estimates obtained using five alternate approaches. The average, minimum and maximum value of the statistic calculated over 25 simulated rate maps are reported.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T4-0

         Predictor  Average  Minimum  Maximum
0  Reference value   0.1019      NaN      NaN
1        Raw rates   0.5263   0.4826   0.5664
2  Empirical Bayes   0.1200   0.0954   0.1476
3  Poisson kriging   0.0937   0.0742   0.1187
4   Statistic ΔEαβ   0.0938   0.0743   0.1189
5   Statistic Δsαβ   0.1329   0.0990   0.1750

  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Average proportion of false positives necessary to the detection of all 67 target edges using three types of neutral models and four estimators for the boundary statistic. The average, minimum and maximum proportions calculated over 25 simulated rate maps are reported. The last column gives the percentage of simulations where the particular method yields the smallest proportion of false positives.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T5-0

          Predictor            Average  Minimum  Maximum  % best results
0               NaN    Neutral Model I      NaN      NaN             NaN
1         Raw rates               33.0    24.80     43.7             0.0
2   Empirical Bayes               17.2     9.63     27.4             4.0
3   Poisson kriging               12.7     7.39     18.2            16.0
4    Statistic Δsαβ               15.9    10.30     20.4             0.0
5               NaN   Neutral Model II      NaN      NaN             NaN
6         Raw rates               34.0    26.50     45.1             0.0
7   Empirical Bayes               18.5    10.70     29.1             0.0
8   Poisson kriging               12.3     6.86     18.4            68.0
9    Statistic Δsαβ               15.3    10.90     21.4             0.0
10              NaN  Neutral Model III      NaN      NaN             NaN
11  Poisson kriging               13.2     7.00     19.5             8.0
12   Statistic Δsαβ               13.2     6.84     20.3             4.0

  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Goodness statistic measuring the agreement between the actual proportion of false positives and the significance level used in tests based on three types of neutral models and four estimators for the boundary statistic. The average, minimum and maximum values calculated over 25 simulated rate maps are reported. The last column gives the percentage of simulations where the particular method yields the largest goodness statistic.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T6-0

          Predictor            Average  Minimum  Maximum  % best results
0               NaN    Neutral Model I      NaN      NaN             NaN
1         Raw rates              0.898    0.873    0.919             0.0
2   Empirical Bayes              0.676    0.605    0.713             0.0
3   Poisson kriging              0.554    0.450    0.628             0.0
4    Statistic Δsαβ              0.561    0.472    0.629             0.0
5               NaN   Neutral Model II      NaN      NaN             NaN
6         Raw rates              0.822    0.718    0.945             0.0
7   Empirical Bayes              0.877    0.814    0.927             0.0
8   Poisson kriging              0.772    0.691    0.817             0.0
9    Statistic Δsαβ              0.605    0.532    0.656             0.0
10              NaN  Neutral Model III      NaN      NaN             NaN
11  Poisson kriging              0.969    0.883    0.994            96.0
12   Statistic Δsαβ              0.914    0.857    0.953             4.0

  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: Average p-value for the tests conducted over the sets of target and non-target edges. The average, minimum and maximum values calculated over 25 simulated rate maps are reported. The last column reports the ratio of average p-values for non-target versus target edges.
  footer_text:
    unique: PMC2136438/PMC2136438.xml::T7-0

          Predictor       Target edges Non-target edges Contrast Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0
              Aver.               Min.             Max.    Aver.               Min.               Max. Unnamed: 6_level_1 Unnamed: 7_level_1
0               NaN    Neutral Model I              NaN      NaN                NaN                NaN                NaN                NaN
1         Raw rates              0.432            0.255    0.575              0.599              0.209              0.918               1.38
2   Empirical Bayes              0.496            0.216    0.883              0.801              0.381              0.966               1.62
3   Poisson kriging              0.573            0.275    0.872              0.856              0.516              0.961               1.49
4    Statistic Δsαβ              0.596            0.312    0.858              0.808              0.558              0.921               1.36
5               NaN   Neutral Model II              NaN      NaN                NaN                NaN                NaN                NaN
6         Raw rates              0.251            0.106    0.433              0.420              0.084              0.843               1.67
7   Empirical Bayes              0.308            0.049    0.756              0.657              0.206              0.920               2.13
8   Poisson kriging              0.351            0.088    0.727              0.723              0.292              0.883               2.06
9    Statistic Δsαβ              0.544            0.273    0.813              0.772              0.505              0.894               1.42
10              NaN  Neutral Model III              NaN      NaN                NaN                NaN                NaN                NaN
11  Poisson kriging              0.141            0.001    0.578              0.532              0.037              0.855               3.76
12   Statistic Δsαβ              0.159            0.001    0.428              0.399              0.079              0.494               2.51

PMC0021XXXXX/PMC2185066.xml
  ----------------------------------------
  id: T1
  label_text: TABLE I
  caption_text: Estimation Performance of the Rate Parameters When Different Noise Levels cin Are Added to the Input Function. The Results Are Calculated From 100 Simulation Runs
  footer_text:
    unique: PMC2185066/PMC2185066.xml::T1-0

    cin  bias(k2f)  bias(k2s)  CV(K2f)  CV(K2s)
0  0.01     0.0015     0.0033   0.0176   0.0191
1  0.05     0.0338     0.0299   0.0721   0.1070
2  0.10     0.1180     0.0390   0.0830   0.1100

  ----------------------------------------
  id: T2
  label_text: TABLE II
  caption_text: Estimation Performance of the Rate Parameters When Different Noise Level Is Added to the Voxel TACs. The Results Are Calculated From 100 Simulation Runs
  footer_text:
    unique: PMC2185066/PMC2185066.xml::T2-0

  Perf. Measures vs. noise level Model-1: σ Model-2: c Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0
                              50        150          1                 10                 30 Unnamed: 5_level_1
0                      bias(k2f)     0.0219     0.0617             0.0017             0.0038             0.0311
1                        CV(k2f)     0.0460     0.0797             0.0182             0.0367             0.0706
2                      bias(k2s)     0.0169     0.0345             0.0128             0.0356             0.0563
3                        CV(k2s)     0.0860     0.1781             0.0258             0.0816             0.1312

  ----------------------------------------
  id: T3
  label_text: TABLE III
  caption_text: Performance of Estimating the Factor Images, in Terms of CC and PM. in Each Parenthesis, the First Number Is the Mean, and the Second Number Is the Corresponding Standard Deviation of the Performance Measure CC or PM. Here, the Noise Level σ2 = 30
  footer_text:
    unique: PMC2185066/PMC2185066.xml::T3-0

  factor           fast           slow          input
0     CC  (0.962,0.041)  (0.996,0.005)  (0.980,0.016)
1     PM  (0.388,0.113)  (0.110,0.079)  (0.207,0.064)

PMC0022XXXXX/PMC2268633.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Distribution of deaths by sex and place of birth, NHW residents, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T1-0

          Place of birth    Male  Female    Total
0            NHW US-born  769405  710942  1480347
1            Anglo-Saxon   19753   23644    43397
2        Northern Europe    2543    2685     5228
3         Western Europe    5840    8135    13975
4        Southern Europe    5109    5879    10988
5         Eastern Europe    5305    5283    10588
6            Former USSR    4072    5595     9667
7            Middle East    7755    5834    13589
8       Arab Middle East    2801    1796     4597
9   Non-Arab Middle East    4954    4038     8992
10                 Total  827537  773831  1601368

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T2-0

  Coronary heart disease    Male   Female Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
          Place of birth     OBS      EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0            NHW US-born  241743      NaN                NaN             234780                NaN                NaN
1            Anglo-Saxon    6571  6628.10   0.99 (0.97–1.02)               7960            8039.60   0.99 (0.97–1.01)
2        Northern Europe     775   841.10   0.92 (0.86–0.99)                886             920.08   0.96 (0.90–1.03)
3         Western Europe    1870  1790.70   1.04 (1.00–1.09)               2524            2595.30   0.97 (0.93–1.01)
4        Southern Europe    1673  1691.20   0.99 (0.94–1.04)               2257            2167.70    1.04(1.00–1.09)
5         Eastern Europe    1957  1762.50   1.11 (1.06–1.16)               1964            1835.90   1.07 (1.02–1.12)
6            Former USSR    1556  1353.30   1.15 (1.09–1.21)               2314            2008.80   1.15 (1.11–1.20)
7            Middle East    2883  2414.20   1.19 (1.15–1.24)               2275            1827.20   1.25 (1.19–1.30)
8       Arab Middle East    1051   823.41   1.28 (1.20–1.36)                642             487.31   1.32 (1.22–1.42)
9   Non-Arab Middle East    1832  1590.80   1.15 (1.10–1.21)               1633            1339.90   1.22 (1.16–1.28)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T3-0

            All cancers    Male   Female Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
         Place of birth     OBS      EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0           NHW US-born  189613      NaN                NaN             168336                NaN                NaN
1           Anglo-Saxon    5207  5032.60   1.03 (1.01–1.06)               5960            5558.40   1.07 (1.05–1.10)
2       Northern Europe     791   693.66   1.14 (1.06–1.22)                753             621.27   1.21 (1.13–1.30)
3        Western Europe    1600  1516.40   1.06 (1.00–1.11)               2442            2128.00   1.15 (1.10–1.19)
4       Southern Europe    1529  1336.90   1.14 (1.09–1.20)               1183            1155.70   1.02 (0.97–1.08)
5        Eastern Europe    1470  1423.90   1.03 (0.98–1.09)               1295            1190.20   1.09 (1.03–1.15)
6           Former USSR    1117  1002.00   1.11 (1.05–1.18)               1338            1154.60   1.16 (1.10–1.22)
7           Middle East    2014  1947.90   1.03 (0.99–1.08)               1494            1500.80   1.00 (0.95–1.05)
8      Arab Middle East     720   746.62   0.96 (0.90–1.04)                534             560.09   0.95 (0.87–1.04)
9  Non-Arab Middle East    1294  1201.30   1.08 (1.02–1.14)                960             940.69   1.02 (0.96–1.09)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text: * Chronic obstructive pulmonary disease
    unique: PMC2268633/PMC2268633.xml::T4-0

                  COPD* Male\n Female\n Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
         Place of birth    OBS      EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0           NHW US-born  43590      NaN                NaN              43964                NaN                NaN
1           Anglo-Saxon   1097  1239.00   0.89 (0.83–0.94)               1441            1534.60   0.94 (0.89–0.99)
2       Northern Europe    106   158.82   0.67 (0.55–0.81)                 96             163.44   0.59 (0.48–0.72)
3        Western Europe    164   322.76   0.51 (0.43–0.59)                310             515.03   0.60 (0.54–0.67)
4       Southern Europe    186   311.31   0.60 (0.51–0.69)                146             336.12   0.43 (0.37–0.51)
5        Eastern Europe    146   330.93   0.44 (0.37–0.52)                142             330.92   0.43 (0.36–0.51)
6           Former USSR    101   246.25   0.41 (0.33–0.50)                132             335.55   0.39 (0.33–0.47)
7           Middle East    269   424.41   0.63 (0.56–0.71)                135             367.42   0.37 (0.31–0.43)
8      Arab Middle East     89   143.07   0.62 (0.50–0.77)                 28             119.35   0.23 (0.16–0.34)
9  Non-Arab Middle East    180   281.34   0.64 (0.55–0.74)                107             248.06   0.43 (0.35–0.52)

  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T5-0

  Cerebrovascular accidents   Male   Female Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
             Place of birth    OBS      EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0               NHW US-born  41050      NaN                NaN              62443                NaN                NaN
1               Anglo-Saxon   1192  1196.40   1.00 (0.94–1.05)               2074            2217.60   0.94 (0.90–0.98)
2           Northern Europe    142   141.97   1.00 (0.84–1.18)                207             253.49   0.82 (0.71–0.94)
3            Western Europe    277   291.30   0.95 (0.84–1.07)                634             700.55   0.91 (0.84–0.98)
4            Eastern Europe    343   302.58   1.13 (1.02–1.26)                501             506.65   0.99 (0.90–1.08)
5           Southern Europe    352   293.38   1.20 (1.08–1.33)                659             604.12   1.09 (1.01–1.18)
6               Former USSR    250   246.54   1.01 (0.89–1.15)                510             560.22   0.91 (0.83–0.99)
7               Middle East    397   406.20   0.98 (0.88–1.08)                444             499.36   0.89 (0.81–0.98)
8          Arab Middle East    125   123.06   1.02 (0.85–1.21)                127             127.99   0.99 (0.83–1.18)
9      Non-Arab Middle East    272   283.13   0.96 (0.85–1.08)                317             371.36   0.85 (0.76–0.95)

  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T6-0

    Pneumonia/influenza   Male  Female Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
         Place of birth    OBS     EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0           NHW US-born  33417     NaN                NaN              40822                NaN                NaN
1           Anglo-Saxon    941  936.97   1.00 (0.94–1.07)               1394            1387.60   1.00 (0.95–1.06)
2       Northern Europe    105  105.98   0.99 (0.81–1.20)                172             161.58   1.06 (0.91–1.24)
3        Western Europe    170  215.76   0.79 (0.67–0.92)                403             437.68   0.92 (0.83–1.02)
4        Eastern Europe    231  228.35   1.01 (0.89–1.15)                323             322.06   1.00 (0.90–1.12)
5       Southern Europe    206  225.82   0.91 (0.79–1.05)                369             396.26   0.93 (0.84–1.03)
6           Former USSR    185  198.03   0.93 (0.80–1.08)                326             361.35   0.90 (0.81–1.01)
7           Middle East    294  312.69   0.94 (0.84–1.05)                291             309.34   0.94 (0.84–1.06)
8      Arab Middle East     84   86.56   0.97 (0.77–1.20)                 61              75.26   0.81 (0.62–1.04)
9  Non-Arab Middle East    210  226.13   0.93 (0.81–1.06)                230             234.09   0.98 (0.86–1.12)

  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T7-0

               HIV/AIDS   Male  Female Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
         Place of birth    OBS     EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0           NHW US-born  26940     NaN                NaN                983                NaN                NaN
1           Anglo-Saxon    465  410.01   1.13 (1.03–1.24)                 15             17.834   0.84 (0.47–1.39)
2       Northern Europe     60   50.92   1.18 (0.90–1.52)                  7              2.315   3.02 (1.21–6.20)
3        Western Europe    285  243.59   1.17 (1.04–1.31)                 13             10.881   1.19 (0.64–2.04)
4       Southern Europe     90  117.41   0.77 (0.62–0.94)                  1              3.302   0.30 (0.00–1.53)
5        Eastern Europe     49  105.99   0.46 (0.34–0.61)                  2              3.840   0.52 (0.06–1.82)
6           Former USSR     12   88.64   0.14 (0.07–0.24)                  0              4.143                NaN
7           Middle East    122  298.09   0.41 (0.34–0.49)                  6             10.698   0.56 (0.20–1.21)
8      Arab Middle East     70  137.70   0.51 (0.40–0.64)                  4              4.837   0.83 (0.22–2.09)
9  Non-Arab Middle East     52  160.39   0.32 (0.24–0.43)                  2              5.860   0.34 (0.04–1.19)

  ----------------------------------------
  id: T8
  label_text: Table 8
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T8-0

                Suicide   Male Female Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
         Place of birth    OBS    EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0           NHW US-born  20441    NaN                NaN               5483                NaN                NaN
1           Anglo-Saxon    426  75.42   5.65 (5.12–6.21)                145              33.97   4.27 (3.60–5.02)
2       Northern Europe     61   9.75   6.25 (4.78–8.03)                 20               4.16   4.81 (2.94–7.43)
3        Western Europe    236  42.85   5.51 (4.83–6.26)                106              18.84   5.63 (4.61–6.80)
4       Southern Europe     82  21.51   3.81 (3.03–4.73)                 11               7.07   1.56 (0.78–2.78)
5        Eastern Europe    143  20.31   7.04 (5.93–8.29)                 43               7.51   5.73 (4.15–7.72)
6           Former USSR     95  21.48   4.42 (3.58–5.41)                 28               8.68   3.23 (2.14–4.66)
7           Middle East    143  58.50   2.44 (2.06–2.88)                 38              21.11   1.80 (1.27–2.47)
8      Arab Middle East     50  25.46   1.96 (1.46–2.59)                 13               8.53   1.52 (0.81–2.60)
9  Non-Arab Middle East     93  33.04   2.81 (2.27–3.45)                 25              12.58   1.99 (1.29–2.93)

  ----------------------------------------
  id: T9
  label_text: Table 9
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T9-0

               Diabetes   Male  Female Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
         Place of birth    OBS     EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0           NHW US-born  12057     NaN                NaN              12344                NaN                NaN
1           Anglo-Saxon    280  314.72   0.89 (0.79–1.00)                318             405.81   0.78 (0.70–0.87)
2       Northern Europe     28   42.10   0.67 (0.44–0.96)                 33              44.96   0.73 (0.51–1.03)
3        Western Europe     81   93.93   0.86 (0.68–1.07)                139             145.41   0.96 (0.80–1.13)
4       Southern Europe    107   82.34   1.30 (1.06–1.57)                174              90.47   1.92 (1.65–2.23)
5        Eastern Europe    106   86.98   1.22 (1.00–1.47)                103              88.05   1.17 (0.95–1.42)
6           Former USSR     75   62.78   1.19 (0.94–1.50)                101              89.20   1.13 (0.92–1.38)
7           Middle East    195  121.38   1.61 (1.39–1.85)                190             104.33    1.82(1.57–2.10)
8      Arab Middle East     86   45.48   1.89 (1.51–2.34)                 73              35.74   2.04 (1.60–2.57)
9  Non-Arab Middle East    109   75.90   1.44 (1.18–1.73)                117              68.58   1.71 (1.41–2.04)

  ----------------------------------------
  id: T10
  label_text: Table 10
  caption_text: Proportionate mortality ratio in first generation NHW immigrants, selected area of birth, California, 1989–1999
  footer_text:
    unique: PMC2268633/PMC2268633.xml::T10-0

               Homicide  Male  Female Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0
         Place of birth   OBS     EXP       PMR (95% CI)                OBS                EXP       PMR (95% CI)
0           NHW US-born  5519     NaN                NaN               1971                NaN                NaN
1           Anglo-Saxon    60  375.35   0.16 (0.12–0.21)                 43             126.05   0.34 (0.25–0.46)
2       Northern Europe     5   49.80   0.10 (0.03–0.23)                  2              16.17   0.12 (0.01–0.43)
3        Western Europe    57  170.49   0.33 (0.25–0.43)                 31              65.84   0.47 (0.32–0.67)
4       Southern Europe    25  104.56   0.24 (0.15–0.35)                 10              24.93   0.40 (0.19–0.74)
5        Eastern Europe    30  103.18   0.29 (0.20–0.41)                 13              27.29   0.48 (0.25–0.81)
6                  USSR    54   88.10   0.61 (0.46–0.80)                  7              27.73   0.25 (0.10–0.52)
7           Middle East   157  224.91    0.70(0.59–0.82)                 35              58.95   0.59 (0.41–0.83)
8      Arab Middle East    83   96.13   0.86 (0.69–1.07)                 12              25.05   0.48 (0.25–0.84)
9  Non-Arab Middle East    74  128.78   0.57 (0.45–0.72)                 23              33.90   0.68 (0.43–1.02)

PMC0022XXXXX/PMC2287164.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Sequence variants
  footer_text:
    unique: PMC2287164/PMC2287164.xml::T1-0

              Unnamed: 0  Homozygous    Heterozygous  Unnamed: 3      Unnamed: 4
0                    NaN  Synonymous  Non-synonymous  Synonymous  Non-synonymous
1  Number of alterations          26              25          11              16

PMC0022XXXXX/PMC2288569.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Oral health characteristics of cohort at age 32 years, by sex and SES
  footer_text: a One participant unable to be classified for the age-32 SES variable. * P < 0.05; ** P < 0.01; *** P < 0.001.
    unique: PMC2288569/PMC2288569.xml::T1-0

                                                                  \n                              Sex\n  SES at age 32 years a              \n              Unnamed: 4_level_0           Unnamed: 5_level_0
                                                                    Characteristic Male (n = 472) n (%) Female (n = 452) n (%) High/medium (n = 765) n (%) Low (n = 158) n (%) All combined (n = 924) n (%)
0                                                                    Dental caries                  NaN                    NaN                         NaN                 NaN                          NaN
1                                                                DMFS 12+ (median)           260 (55.1)             221 (48.9)                  318 (49.2)         162 (58.5)*                   481 (52.1)
2                                                              1+ Decayed surfaces           284 (60.2)          203 (44.9)***                  308 (47.7)       178 (64.3)***                   487 (52.7)
3                                                              Periodontal disease                  NaN                    NaN                         NaN                 NaN                          NaN
4                                                       1+ sites with CAL of 4+ mm           161 (34.1)          108 (23.9)***                  154 (23.8)         114 (41.2)*                   269 (29.0)
5                                                       2+ sites with CAL of 4+ mm           108 (22.9)            73 (16.2)**                  101 (15.6)        80 (28.9)***                   181 (19.6)
6                                                         Tooth loss due to caries                  NaN                    NaN                         NaN                 NaN                          NaN
7                                                                 1+ teeth missing           126 (26.7)             89 (19.7)*                  116 (18.0)        98 (35.4)***                   215 (23.3)
8   Self-rated oral health worse than average compared with others of the same age           231 (48.9)             216 (47.8)                  282 (43.7)       164 (59.2)***                   447 (48.4)
9                               Self-rated oral health worsened since age 26 years           161 (34.1)             147 (32.6)                  199 (30.8)         108 (39.1)*                   308 (33.4)
10                                             Usual reason for visiting a dentist                  NaN                    NaN                         NaN                 NaN                          NaN
11                                                                        Check-up           192 (40.7)             242 (53.5)                  305 (47.2)           93 (33.6)                   434 (47.0)
12                                                                         Problem           280 (59.3)          210 (46.5)***                  341 (52.8)       184 (66.4)***                   490 (53.0)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Distribution of responses to individual OHIP-14 items and mean item scores (n = 924)
  footer_text:
    unique: PMC2288569/PMC2288569.xml::T2-0

                                                                                                       \n               Distribution of responses (%)\n   \n                          Unnamed: 3_level_0 Unnamed: 4_level_0
   Dimension and description of item ‘Because of trouble with your teeth, mouth or dentures during the last 4 weeks, …’       Never (0)/hardly ever (1) Occasionally (2) Fairly often (3)/very often (4)          Mean (SD)
0                                                                                                 Functional limitation                             NaN              NaN                             NaN                NaN
1                                                                           Have you had trouble pronouncing any words?                            92.5              6.0                             1.5        0.26 (0.63)
2                                                                  Have you felt that your sense of taste has worsened?                            90.4              7.7                             1.9        0.37 (0.72)
3                                                                                                         Physical pain                             NaN              NaN                             NaN                NaN
4                                                                            Have you had painful aching in your mouth?                            72.8             22.9                             4.2        0.86 (0.95)
5                                                                     Have you found it uncomfortable to eat any foods?                            72.7             21.5                             5.7        0.86 (1.00)
6                                                                                              Psychological discomfort                             NaN              NaN                             NaN                NaN
7                                                                                         Have you been self-conscious?                            73.6             17.3                             9.1        0.85 (1.08)
8                                                                                                  Have you felt tense?                            83.9             12.1                             4.0        0.58 (0.89)
9                                                                                                   Physical disability                             NaN              NaN                             NaN                NaN
10                                                                                   Has your diet been unsatisfactory?                            65.6             25.6                             8.8        0.99 (1.08)
11                                                                                     Have you had to interrupt meals?                            85.2             10.8                             4.0        0.53 (0.89)
12                                                                                             Psychological disability                             NaN              NaN                             NaN                NaN
13                                                                                Have you found it difficult to relax?                            83.2             13.7                             3.0        0.60 (0.85)
14                                                                                     Have you been a bit embarrassed?                            80.8             14.5                             4.7        0.70 (0.94)
15                                                                                                    Social disability                             NaN              NaN                             NaN                NaN
16                                                                     Have you been a bit irritable with other people?                            83.4             13.6                             2.9        0.55 (0.85)
17                                                                       Have you had difficulty doing your usual jobs?                            93.9              4.5                             1.5        0.29 (0.65)
18                                                                                                             Handicap                             NaN              NaN                             NaN                NaN
19                                                              Have you felt that life in general was less satisfying?                            89.9              7.4                             2.7        0.39 (0.76)
20                                                                            Have you been totally unable to function?                            96.5              2.2                             1.3        0.17 (0.53)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Prevalence, extent and severity of impacts by OHIP-14 subscale and total score (n = 924)
  footer_text:
    unique: PMC2288569/PMC2288569.xml::T3-0

                  Dimension Prevalence: no. reporting 1+ impacts fairly/very often (%) Extent: mean no. of items reported fairly/very often (SD) Severity: mean OHIP-14 score (SD)
0     Functional limitation                                                   29 (3.1)                                               0.03 (0.20)                       0.63 (1.12)
1             Physical pain                                                   66 (7.1)                                               0.10 (0.38)                       1.72 (1.78)
2  Psychological discomfort                                                  95 (10.3)                                               0.13 (0.41)                       1.43 (1.77)
3       Physical disability                                                  99 (10.7)                                               0.13 (0.39)                       1.52 (1.69)
4  Psychological disability                                                   59 (6.4)                                               0.08 (0.31)                       1.29 (1.59)
5         Social disability                                                   34 (3.7)                                               0.04 (0.24)                       0.85 (1.39)
6                  Handicap                                                   27 (2.9)                                               0.04 (0.25)                       0.56 (1.16)
7       Total OHIP-14 score                                                 216 (23.4)                                               0.55 (1.44)                       8.00 (8.08)

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Prevalence of impacts (fairly/very often), by sex, oral disease prevalence, self-rated oral health and usual reason for visiting a dentist
  footer_text:
    unique: PMC2288569/PMC2288569.xml::T4-0

                                               \n               Males (n = 472)\n Females (n = 452)\n Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0
                                               \n                           n (%) Odds ratio (95% CI)            P-value              n (%) Odds ratio (95% CI)            P-value
0                                                 Dental caries               NaN                 NaN                NaN                NaN                 NaN                NaN
1                                                     DMFS < 12         34 (16.0)                1.00                NaN          44 (19.0)                1.00                NaN
2                                                      DMFS 12+         74 (28.5)    2.08 (1.32–3.28)              0.001          64 (29.0)    1.73 (1.12–2.69)              0.014
3                                                        DS = 0         22 (11.7)                1.00                NaN          38 (15.3)                1.00                NaN
4                                                         DS 1+         86 (30.3)    3.28 (1.97–5.47)             <0.001          70 (34.5)    2.92 (1.86–4.59)             <0.001
5                                           Periodontal disease               NaN                 NaN                NaN                NaN                 NaN                NaN
6                                     0 sites with CAL of 4+ mm         62 (19.9)                1.00                NaN          67 (19.5)                1.00                NaN
7                                    1+ sites with CAL of 4+ mm         46 (28.6)    1.61 (1.03–2.50)              0.034          41 (38.0)    2.53 (1.58–4.05)             <0.001
8                                    <2 sites with CAL of 4+ mm         75 (20.6)                1.00                NaN          76 (20.1)                1.00                NaN
9                                    2+ sites with CAL of 4+ mm         33 (30.6)    1.70 (1.05–2.75)              0.031          32 (43.8)    3.11 (1.84–5.27)             <0.001
10                                     Tooth loss due to caries               NaN                 NaN                NaN                NaN                 NaN                NaN
11                                              0 teeth missing         57 (16.5)                1.00                NaN          68 (18.7)                1.00                NaN
12                                             1+ teeth missing         51 (40.5)    3.45 (2.19–5.44)             <0.001          40 (44.9)    3.54 (2.16–5.80)             <0.001
13  Self-rated oral health compared with others of the same age               NaN                 NaN                NaN                NaN                 NaN                NaN
14                                          Better than average         31 (12.9)                1.00                NaN          31 (13.1)                1.00                NaN
15                                           Worse than average         77 (33.3)    3.39 (2.13–5.40)             <0.001          77 (35.6)    2.75 (1.76–4.30)             <0.001
16                    Self-rated oral health since age 26 years               NaN                 NaN                NaN                NaN                 NaN                NaN
17                                     Improved/stayed the same         47 (15.1)                1.00                NaN          53 (17.4)                1.00                NaN
18                                                    Got worse         61 (37.9)    3.43 (2.20–5.35)             <0.001          54 (36.7)    2.76 (1.74–4.38)             <0.001
19                          Usual reason for visiting a dentist               NaN                 NaN                NaN                NaN                 NaN                NaN
20                                                     Check-up         23 (12.0)                1.00                NaN          31 (12.8)                1.00                NaN
21                                                      Problem         85 (30.4)    3.20 (1.93–5.31)             <0.001          77 (36.7)    3.94 (2.46–6.31)             <0.001

  ----------------------------------------
  id: T5
  label_text: Table 5
  caption_text: Prevalence of impacts (fairly/very often), by SES at age 32 years, oral disease prevalence, self-rated oral health and usual reason for visiting a dentist
  footer_text:
    unique: PMC2288569/PMC2288569.xml::T5-0

                                               \n               High/medium SES (n = 765)\n Low SES (n = 158)\n Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0
                                               \n                                     n (%) Odds ratio (95% CI)            P-value              n (%) Odds ratio (95% CI)            P-value
0                                                 Dental caries                         NaN                 NaN                NaN                NaN                 NaN                NaN
1                                                     DMFS < 12                   52 (15.9)                1.00                NaN          26 (22.6)                1.00                NaN
2                                             DMFS 12+ (median)                   69 (21.7)    1.47 (0.99–2.19)               0.06          68 (42.0)    2.48 (1.45–4.24)              0.001
3                                                        DS = 0                   42 (12.4)                1.00                NaN          18 (18.2)                1.00                NaN
4                                                         DS 1+                   79 (25.6)    2.43 (1.61–3.67)             <0.001          76 (42.7)    3.35 (1.86–6.05)             <0.001
5                                           Periodontal disease                         NaN                 NaN                NaN                NaN                 NaN                NaN
6                                     0 sites with CAL of 4+ mm                   82 (16.7)                1.00                NaN          47 (28.8)                1.00                NaN
7                                    1+ sites with CAL of 4+ mm                   39 (25.3)    1.70 (1.10–2.62)               0.02          47 (41.2)    1.73 (1.05–2.87)               0.03
8                                    <2 sites with CAL of 4+ mm                   92 (16.9)                1.00                NaN          58 (29.4)                1.00                NaN
9                                    2+ sites with CAL of 4+ mm                   29 (28.7)    1.98 (1.22–3.22)              0.005          36 (45.0)    1.96 (1.15–3.35)              0.013
10                                 Tooth loss because of caries                         NaN                 NaN                NaN                NaN                 NaN                NaN
11                                              0 teeth missing                   80 (15.1)                1.00                NaN          45 (25.1)                1.00                NaN
12                                             1+ teeth missing                   41 (35.3)    3.08 (1.96–4.82)             <0.001          49 (50.0)    2.98 (1.77–5.01)             <0.001
13  Self-rated oral health compared with others of the same age                         NaN                 NaN                NaN                NaN                 NaN                NaN
14                                          Better than average                   42 (11.5)                1.00                NaN          20 (17.7)                1.00                NaN
15                                           Worse than average                   79 (28.0)    2.98 (1.97–4.51)             <0.001          74 (45.1)    3.82 (2.16–6.78)             <0.001
16                    Self-rated oral health since age 26 years                         NaN                 NaN                NaN                NaN                 NaN                NaN
17                                     Improved/stayed the same                   57 (12.8)                1.00                NaN          43 (25.6)                1.00                NaN
18                                                    Got worse                   64 (32.2)    3.24 (2.16–4.87)             <0.001          50 (46.3)    2.51 (1.50–4.19)             <0.001
19                          Usual reason for visiting a dentist                         NaN                 NaN                NaN                NaN                 NaN                NaN
20                                                     Check-up                   37 (10.9)                1.00                NaN          17 (18.3)                1.00                NaN
21                                                      Problem                   84 (27.5)    3.12 (2.04–4.77)             <0.001          77 (41.8)    3.22 (1.76–5.87)             <0.001

  ----------------------------------------
  id: T6
  label_text: Table 6
  caption_text: Logistic regression model for prevalence of impacts (‘fairly often’ or ‘very often’) at age 32 years (n = 923) Coeff. Odds ratio 95% CI for OR P-value
  footer_text: −2 Log-likelihood = 896.69; Cox & Snell R2 = 0.11; Nagelkerke R2 = 0.16; Hosmer and Lemeshow chi-squared test = 3.01, d.f. = 8, P = 0.93.
    unique: PMC2288569/PMC2288569.xml::T6-0

                                                    \n                Coeff.  Odds ratio 95% CI for OR P-value
0                                                           Constant  −2.611         NaN           NaN     NaN
1                                                             Female   0.313        1.37     0.98–1.91   0.065
2                                                            Low SES   0.451        1.57     1.12–2.21    0.01
3                                               Episodic dental user   0.840        2.32     1.60–3.36  <0.001
4                               Any decayed surface (DS) at 32 years   0.666        1.95     1.35–2.81  <0.001
5                   No. of teeth missing (due to caries) by 32 years   0.153        1.17     1.05–1.29   0.003
6  Case of periodontal disease (2+ sites with 4+ mm CAL at 32 years)   0.401        1.49     1.02–2.19    0.04

  ----------------------------------------
  id: T7
  label_text: Table 7
  caption_text: Poisson regression models for the extent and severity of impacts (n = 923)
  footer_text: a Ratio of geometric mean values.
    unique: PMC2288569/PMC2288569.xml::T7-0

                                                    \n               Extent: mean no. of OHIP items reported fairly/very often (pseudo-R2 = 0.13)\n Severity: mean total OHIP-14 score(pseudo-R2 = 0.09)\n Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0
                                                    \n                                                                                       Coeff.                                                   IRRa     95% CI for IRR            P-value             Coeff.               IRRa     95% CI for IRR            P-value
0                                                           Constant                                                                          −1.93                                                    NaN                NaN                NaN               1.54                NaN                NaN                NaN
1                                                             Female                                                                           0.30                                                   1.35          1.12–1.64              0.002               0.04               1.04          0.99–1.09              0.148
2                                                            Low SES                                                                           0.28                                                   1.33          1.09–1.62              0.005               0.11               1.11          1.06–1.17             <0.001
3                                               Episodic dental user                                                                           0.76                                                   2.14          1.68–2.71             <0.001               0.40               1.49          1.41–1.57             <0.001
4                               Any decayed surface (DS) at 32 years                                                                           0.63                                                   1.88          1.50–2.36             <0.001               0.29               1.34          1.27–1.41             <0.001
5               No. of teeth missing (because of caries) by 32 years                                                                           0.12                                                   1.12          1.09–1.15             <0.001               0.06               1.07          1.06–1.08             <0.001
6  Case of periodontal disease (2+ sites with 4+ mm CAL at 32 years)                                                                           0.14                                                   1.14          0.86–1.52              0.349               0.13               1.14          1.05–1.23              0.002

  ----------------------------------------
  id: T8
  label_text: Table 8
  caption_text: International comparisons of prevalence, extent and severity of overall impacts and selected dimensions among dentate adults
  footer_text: a Slade et al. (10). b Estimated for the UK and Australian samples by scrutinizing the data distributions.
    unique: PMC2288569/PMC2288569.xml::T8-0

                                                           \n                 United Kingdoma        Australiaa       New Zealand
0                                                       No. of participants              5270              3909               924
1                                                        % aged 30–39 years                24                21               100
2                                                       Median age (years)b                40             40–42                32
3                                                                  % Female                50                51                49
4   Prevalence: % of people reporting 1+ impacts fairly/very often (95% CI)  15.9 (14.9–16.8)  18.2 (16.2–20.2)  23.4 (22.0–24.8)
5             Extent: mean no. of items reported fairly/very often (95% CI)  0.36 (0.32–0.40)  0.46 (0.39–0.52)  0.55 (0.46–0.65)
6                                     Severity: mean OHIP-14 score (95% CI)               NaN               NaN               NaN
7                                                            All OHIP items               NaN               NaN               NaN
8                                                                Both sexes     5.1 (4.8–5.3)     7.5 (7.1–7.9)     8.0 (7.5–8.5)
9                                                     Male aged 25–34 years     5.1 (4.8–5.4)     6.9 (6.4–7.4)     8.3 (7.6–9.0)
10                                                  Female aged 25–34 years     5.3 (5.1–5.5)     7.9 (7.5–8.3)     7.7 (6.9–8.4)
11                           Physical pain/physical disability (both sexes)     2.1 (2.0–2.2)     3.4 (3.3–3.6)     3.2 (3.0–3.4)
12                                            Other dimensions (both sexes)     2.9 (2.8–3.1)     4.0 (3.8–4.3)     4.8 (4.4–5.1)

PMC0022XXXXX/PMC2293303.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Lifetime prevalence associations of gambling types with lifetime onset and persistence of CIDI/DSM-IV pathological gambling (PG)
  footer_text: * Significant at the .05 level, two-sided test. 1 Multivariate model controlling for sex, race-ethnicity, age of first gambling, years since first gambling, and 11 gambling types. 2 Multivariate model controlling for sex, race-ethnicity, aoo of first gambling, aoo of first problem, years since first problem, and 11 gambling types
    unique: PMC2293303/PMC2293303.xml::T1-0

                                                                    \n                                       Prevalence Lifetime Pathological Gambling (PG) among Gamblers1 Lifetime problem Gambling among Gamblers1 Lifetime Pathological Gambling (PG) among Problem gamblers2 Termination of Problem gambling2 Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0 Unnamed: 10_level_0
                                                                    \n                                                %                                                (se)                                        OR                                                   (95% CI)2                               OR          (95% CI)3                 OR          (95% CI)4                 OR           (95% CI)5
                                                                    \n               \n                \n                                                Unnamed: 2_level_2                        Unnamed: 3_level_2                                          Unnamed: 4_level_2               Unnamed: 5_level_2 Unnamed: 6_level_2 Unnamed: 7_level_2 Unnamed: 8_level_2 Unnamed: 9_level_2 Unnamed: 10_level_2
0                                                                  I. Sports betting                                NaN                                                 NaN                                       NaN                                                         NaN                              NaN                NaN                NaN                NaN                NaN                 NaN
1                                                                 Office sports pool                               44.3                                               (1.7)                                       1.7                                                   (0.4–6.5)                              0.6          (0.2–1.6)                0.6          (0.1–4.5)                0.3           (0.1–1.2)
2                                                 Sports with bookie or parlay cards                                5.8                                               (0.5)                                      3.3*                                                   (1.3–8.6)                             3.7*          (1.7–8.1)                2.8         (0.7–11.0)                1.6           (0.5–5.3)
3                                      Betting on horse/dog races or cock/dog fights                               25.0                                               (1.3)                                      3.2*                                                   (1.2–8.5)                              1.2          (0.4–3.7)                2.7          (0.8–9.1)                1.0           (0.4–2.6)
4                                                               Gambling at a casino                               44.7                                               (2.1)                                       1.4                                                   (0.5–4.3)                              2.5          (0.9–6.7)                1.2          (0.2–6.8)               4.8*          (1.5–15.5)
5   II. Other types of gambling that involve some aspect of mental or physical skill                                NaN                                                 NaN                                       NaN                                                         NaN                              NaN                NaN                NaN                NaN                NaN                 NaN
6                                         Games involving mental skill (e.g., cards)                               35.8                                               (1.2)                                     12.2*                                                  (3.1–47.7)                              1.4          (0.2–8.9)              23.6*        (2.3–239.3)                8.9         (0.7–114.6)
7                                        Games involving physical skill (e.g., pool)                               22.7                                               (1.1)                                       1.8                                                   (0.6–5.3)                              1.6          (0.8–3.4)                1.4          (0.2–9.1)                2.5           (0.8–7.7)
8                                               Speculating on high risk investments                                8.4                                               (0.7)                                       2.1                                                   (0.8–5.6)                              1.3          (0.6–2.6)               4.3*         (1.0–18.0)                0.6           (0.2–2.0)
9                                                                  Internet gambling                                1.0                                               (0.2)                                       3.2                                                  (0.7–14.8)                              2.3          (0.6–8.9)               49.2       (0.3–9595.7)                2.2           (0.5–9.3)
10              III. Types of gambling that largely involve chance rather than skill                                NaN                                                 NaN                                       NaN                                                         NaN                              NaN                NaN                NaN                NaN                NaN                 NaN
11                                                             Playing numbers/lotto                               62.2                                               (1.5)                                       0.6                                                   (0.2–2.4)                              0.5          (0.2–1.4)                1.2          (0.1–9.6)               0.2*           (0.1–0.8)
12                                             Gambling machines (e.g., video poker)                               26.1                                               (1.3)                                      3.3*                                                   (1.3–8.4)                             2.9*          (1.0–8.4)              15.6*        (2.3–104.9)                1.3           (0.4–4.1)
13                                                Slot machines, bingo, or pull tabs                               48.9                                               (1.8)                                       0.5                                                   (0.2–1.2)                              1.0          (0.4–2.1)               0.2*          (0.0–1.0)               0.3*           (0.1–0.8)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Lifetime comorbidity of CIDI/DSM-IV pathological gambling (PG) with other lifetime CIDI/DSM-IV disorders and temporal priorities in age of onset (AOO)
  footer_text: * Significant at the .05 level, two-sided test. 1 The percent of respondents with PG who also meet criteria for the other disorder. 2 The ORs are calculated in the total sample, including respondents who never gambled. The ORs were calculated controlling for age at interview so as to avoid confounding due to time at risk.
    unique: PMC2293303/PMC2293303.xml::T2-0

                          \n                                                                                                           Temporal priority in onset Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0 Unnamed: 10_level_0
                          \n                                      Prevalence1   \n                                            PG first                Other first          Same year Unnamed: 7_level_1 Unnamed: 8_level_1 Unnamed: 9_level_1 Unnamed: 10_level_1
                          \n                                                %               (se)                OR2           (95% CI)                          %               (se)                  %               (se)                  %                (se)
                          \n               \n                \n               Unnamed: 2_level_3 Unnamed: 3_level_3 Unnamed: 4_level_3         Unnamed: 5_level_3 Unnamed: 6_level_3 Unnamed: 7_level_3 Unnamed: 8_level_3 Unnamed: 9_level_3 Unnamed: 10_level_3
0                        I. Mood disorders                                NaN                NaN                NaN                NaN                        NaN                NaN                NaN                NaN                NaN                 NaN
1   Major depressive disorder or dysthymia                               38.6              (9.1)               2.5*          (1.1–5.7)                       20.5             (10.6)               73.5             (11.1)                6.1               (5.8)
2                        Bipolar disorder3                               17.0              (7.1)               4.6*         (1.5–14.2)                       29.2             (16.4)               46.3             (21.5)               24.5              (14.4)
3                        Any mood disorder                               55.6              (9.7)               3.7*          (1.5–9.0)                       23.1              (9.0)               65.1             (11.7)               11.7               (6.9)
4                    II. Anxiety disorders                                NaN                NaN                NaN                NaN                        NaN                NaN                NaN                NaN                NaN                 NaN
5                           Panic disorder                               21.9              (6.7)               4.9*         (2.2–10.8)                       10.7              (9.5)               81.8             (16.1)                7.5               (6.6)
6             Generalized anxiety disorder                               16.6              (7.0)               2.8*          (1.0–7.9)                        9.3              (9.4)               79.8             (14.3)               10.9              (10.8)
7                                   Phobia                               52.2              (8.8)               3.2*          (1.4–7.2)                        0.0                (-)              100.0              (0.0)                0.0                 (-)
8                                     PTSD                               14.8              (7.8)                2.3          (0.6–8.4)                       49.5             (27.3)               50.5             (27.3)                0.0                 (-)
9                    Any anxiety disorder4                               60.3              (9.1)               3.1*          (1.4–7.0)                       13.4              (7.3)               82.1              (7.9)                4.5               (4.3)
10          III. Impulse-control disorders                                NaN                NaN                NaN                NaN                        NaN                NaN                NaN                NaN                NaN                 NaN
11                                    ADHD                               13.4              (8.1)                1.8          (0.4–7.3)                        0.0                (-)              100.0              (0.0)                0.0                 (-)
12           Oppositional-defiant disorder                               15.4              (6.8)                1.9          (0.7–5.7)                        0.0                (-)              100.0              (0.0)                0.0                 (-)
13                        Conduct disorder                               24.9              (8.2)               3.1*          (1.2–7.8)                        0.0                (-)              100.0              (0.0)                0.0                 (-)
14         Intermittent explosive disorder                               27.0              (9.0)               3.1*          (1.1–8.3)                        0.0                (-)              100.0              (0.0)                0.0                 (-)
15            Any impulse control disorder                               42.3             (10.5)                2.2          (0.9–5.3)                        0.0                (-)              100.0              (0.0)                0.0                 (-)
16             IV. Substance use disorders                                NaN                NaN                NaN                NaN                        NaN                NaN                NaN                NaN                NaN                 NaN
17                   Alcohol or drug abuse                               46.2             (10.7)               4.5*         (1.8–11.0)                       18.7             (10.0)               70.9             (11.3)               10.4               (7.0)
18              Alcohol or drug dependence                               31.8              (9.4)               5.8*         (2.4–14.4)                       44.3             (16.7)               55.7             (16.7)                NaN                 (-)
19                     Nicotine dependence                               63.0              (9.0)               3.9*          (1.7–8.5)                       61.3             (11.5)               33.0             (10.8)                5.7               (4.2)
20              Any substance use disorder                               76.3              (7.9)               5.5*         (2.3–13.5)                       36.2             (12.2)               57.4             (11.6)                6.4               (4.5)
21                  V. Number of disorders                                NaN                NaN                NaN                NaN                        NaN                NaN                NaN                NaN                NaN                 NaN
22                            Any disorder                               96.3              (2.6)              17.4*         (4.2–73.0)                       23.5             (10.7)               74.3             (10.5)                2.2               (2.2)
23                    Exactly one disorder                               22.0             (10.2)              10.1*         (1.5–65.6)                        NaN                NaN                NaN                NaN                NaN                 NaN
24                   Exactly two disorders                                9.9              (6.5)               9.1*         (1.3–65.2)                        NaN                NaN                NaN                NaN                NaN                 NaN
25                 Three or more disorders                               64.4             (10.4)              30.0*        (7.6–118.7)                        NaN                NaN                NaN                NaN                NaN                 NaN

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Reciprocal time-lagged associations of temporally primary problem gambling predicting the subsequent first onset of other disorders and of temporally primary other disorders predicting the subsequent first onset of CIDI/DSM-IV PG1
  footer_text: * Significant at the .05 level, two-sided test. 1 Models are bivariate for each disorder and controlling for age, sex, and race-ethnicity. 2 There are no onsets of ADHD, ODD, CD that came after the PG onsets
    unique: PMC2293303/PMC2293303.xml::T3-0

                          \n               Problem gambling predicting others1 Others predicting PG1 Unnamed: 3_level_0 Unnamed: 4_level_0
                          \n                                                OR              (95% CI)                 OR           (95% CI)
                          \n                \n                \n                  Unnamed: 2_level_2 Unnamed: 3_level_2 Unnamed: 4_level_2
0                        I. Mood disorders                                 NaN                   NaN                NaN                NaN
1   Major depressive disorder or dysthymia                                 3.2            (1.0–10.5)               6.6*         (2.2–19.2)
2                         Bipolar disorder                                6.3*            (1.4–28.2)               9.1*         (2.4–33.9)
3                        Any mood disorder                                 1.1             (0.2–5.7)               5.0*         (2.0–13.0)
4                    II. Anxiety disorders                                 NaN                   NaN                NaN                NaN
5                           Panic disorder                                 5.3            (0.7–42.2)              12.6*         (5.4–29.5)
6             Generalized anxiety disorder                                 2.0            (0.4–11.0)               7.4*         (1.8–29.3)
7                                   Phobia                                0.0*                   (-)               6.9*         (3.1–15.5)
8                                     PTSD                                7.2*            (1.7–31.4)                3.5         (0.6–20.5)
9                    Any anxiety disorder3                                3.8*             (1.5–9.5)               5.0*         (2.3–11.0)
10          III. Impulse-control disorders                                 NaN                   NaN                NaN                NaN
11                                    ADHD                                 NaN                  (-)2                2.2          (0.5–9.1)
12           Oppositional-defiant disorder                                 NaN                  (-)2               3.3*         (1.1–10.3)
13                        Conduct disorder                                 NaN                  (-)2               4.4*         (1.6–12.0)
14         Intermittent explosive disorder                                 3.7            (0.6–23.4)               5.7*         (2.0–15.8)
15            Any impulse control disorder                                 1.1            (0.1–10.9)               3.6*          (1.5–8.7)
16             IV. Substance use disorders                                 NaN                   NaN                NaN                NaN
17                   Alcohol or drug abuse                                 3.5            (1.0–12.3)               5.4*         (1.8–16.3)
18              Alcohol or drug dependence                                9.8*            (3.7–25.7)               8.8*         (2.5–31.1)
19                     Nicotine dependence                                5.3*            (2.4–11.7)                1.9          (0.6–6.0)
20              Any substance use disorder                                7.7*            (3.6–16.3)               4.5*         (1.6–12.7)
21                  V. Number of disorders                                 NaN                   NaN                NaN                NaN
22                            Any disorder                                7.1*            (3.8–13.2)               5.4*         (1.9–15.1)
23                    Exactly one disorder                                 NaN                   (-)                1.0          (0.2–5.9)
24                   Exactly two disorders                                 NaN                   (-)                4.5         (0.7–30.6)
25                 Three or more disorders                                 NaN                   (-)              11.3*         (4.5–28.7)

PMC0023XXXXX/PMC2323355.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Selected genes identified by comparison of NE from patients with EAC (N with T) vs. without EAC (N without T). Threshold value set at 2.7; N with T: gene score in the group of patients with esophageal adenocarcinoma; N without T: gene score in the group of patients without esophageal adenocarcinoma. Gene identifiers and gene names are shown in the two leftmost columns.
  footer_text:
    unique: PMC2323355/PMC2323355.xml::T1-0

      Gene ID                                                       Gene Name N with T N without T
0    AB003476                                                          gravin  −0.7322      0.4707
1   NM_005319                              H1 histone family, member 2 (H1F2)   0.5907     −0.3797
2   XM_004416                            H2A histone family, member L (H2AFL)   0.5384     −0.3461
3   NM_003519                            H2B histone family, member C (H2BFC)   0.5062     −0.3254
4   NM_002273                                                keratin 8 (KRT8)   0.3834     −0.2465
5   NM_015902                                 progestin induced protein (DD5)  −0.3112      0.2001
6   NM_003516                            H2A histone family, member O (H2AFO)   0.2322     −0.1493
7   XM_009572                                       transglutaminase 3 (TGM3)  −0.2078      0.1336
8   NM_019111  major histocompatibility complex, class II, DR alpha (HLA-DRA)   0.1695      −0.109
9    AF107297                 mitotic checkpoint protein kinase BUB1B (BUB1B)  −0.0626      0.0402
10  NM_002083              glutathione peroxidase 2 (gastrointestinal) (GPX2)   0.0614     −0.0395

PMC0023XXXXX/PMC2365750.xml

PMC0023XXXXX/PMC2396881.xml

PMC0024XXXXX/PMC2423936.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Summary of mouse lines, their genotypes and designations
  footer_text: a Wild type mice were homozygous for Trsp and albumin Cre. b Trsp liver knockout mice lacked Trsp in their liver. c A34 transgenic mice carrying 2 copies of the T34→A34 mutant transgene. d G37 transgenic mice carrying 2 copies of the A37→G37 mutant transgene. e G37 transgenic mice carrying 16 copies of the A37→G37 mutant transgene. f Designations used in the text to denote each mouse line.
    unique: PMC2423936/PMC2423936.xml::T1-0

                           Mice                    Genotype Designation f
0                   Wild type a           Trsp+/+-AlbCre+/+          Trsp
1         Trsp liver knockout b         Trspfl/fl-AlbCre+/+         ΔTrsp
2   A34 transgenic (2 copies) c  Trspfl/fl-AlbCre+/+-A34t/t           A34
3   G37 transgenic (2 copies) d  Trspfl/fl-AlbCre+/+-G37t/t          G37L
4  G37 transgenic (16 copies) e  Trspfl/fl-AlbCre+/+-G37t/t          G37H

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Primers for assessing real-time PCRa
  footer_text: a Primers designed for determining real-time PCR of each mRNA examined are shown in the table.
    unique: PMC2423936/PMC2423936.xml::T2-0

       Gene              Forward Sequence              Reverse Sequence
0      Aox1    5′-GAAGCTGGACAACGCTTACA-3′    5′-CCACATTTGATTGCCACTTC-3′
1      Cd36    5′-GATTGTACCTGGGAGTTGGC-3′    5′-CATGAGAATGCCTCCAAACA-3′
2      Ces1    5′-CAGAAGACAGCTGCATCCAT-3′    5′-TCCAATCAAGTCCAGGAACA-3′
3      Ces2    5′-ATGTGAGGCTATGGATTCCC-3′    5′-TCCTCAGATGCCAACAACTC-3′
4    Cyp2A5    5′-GAGATTGATCGGGTGATTGG-3′    5′-CGAAACTTGGTGTCCTTGGT-3′
5       Ddc    5′-CTGAATGGTGTGGAGTTTGC-3′    5′-TGAATCCTGAGTCCTGGTGA-3′
6      Dmpk    5′-CGTGTTCGCCTATGAGATGT-3′    5′-ACGAATGAGGTCCTGAGCTT-3′
7     Ephx1     5′-GGGTCAAAGCCATCAGCCA-3′   5′-CCTCCAGAAGGACACCACTTT-3′
8     Gsta1    5′-CGCAGACCAGAGCCATTCTC-3′  5′-TTGCCCAATCATTTCAGTCAGA-3′
9     Gsta2    5′-CCCCTTTCCCTCTGCTGAAG-3′   5′-TGCAGCCACACTAAAACTTGA-3′
10    Gsta4    5′-TTGAAATCGATGGGATGATG-3′    5′-ATCATCATCAGGTCCTGGGT-3′
11    Gstm1    5′-CCAAACACACAGGTCAGTCC-3′    5′-CGTCACCCATGGTGTATCTC-3′
12    Gstm2   5′-CCTATGACACTAGGTTACTGG-3′   5′-CACTGGCTTCGGTCATAGTCA-3′
13    Gstm3  5′-TATGACACTGGGCTATTGGAAC-3′       5′-GGGCATCCCCCATGACA-3′
14    Gstt3    5′-GGCAGAAGATGATGTTCCCT-3′    5′-TCAGCCACAGAAATATGGGA-3′
15    Hmox1    5′-GCCACCAAGGAGGTACACAT-3′    5′-GCTTGTTGCGCTCTATCTCC-3′
16  Htatip2    5′-GGCCAGGAGTCCTACTGTGT-3′    5′-GTTCAGCATCGCTCTAACCA-3′
17    Ikbkg    5′-CCTGGTAGCCAAACAGGAAT-3′    5′-CCTTCTTCTCCACCAGCTTC-3′
18   Lgals1    5′-GCAACAACCTGTGCCTACAC-3′    5′-TGATGCACACCTCTGTGATG-3′
19    Srxn1    5′-CCAGGGTGGCGACTACTACT-3′    5′-CAAGTCTGGTGTGGATGCTC-3′
20     Ugdh    5′-TGCTGTCCAATCCTGAGTTC-3′    5′-ACCCAGTGCTCATACACAGC-3′
21  Ugt2b35    5′-AATGACCTTCTCGGTCATCC-3′    5′-CCACCATGTGTGCAATGTTA-3′

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Transcripts in elevated levels within liver of knockout mice relative to wild type mice a
  footer_text: a Genes elevated ≥ 2.0 fold in ΔTrsp mice compared to Trsp mice with a P-value ≤ 0.05 were assessed and shown in the table. The corresponding transcript levels were also analyzed in A34, G37L and G37H replacement mice relative to Trsp mice. Gene Unigene Accession Number, gene description, fold change with P value, and gene function(s) are shown. Four control and four experimental animals were used for comparing ΔTrsp, A34 and G37L with Trsp, while three control and three experimental animals were used for comparing G37H with Trsp. b Genes are grouped into classes according to function.
    unique: PMC2423936/PMC2423936.xml::T3-0

                                     \n                                                                                                                               ΔTrsp vs Trsp A34 vs Trsp G37L vs Trsp G37H vs Trsp \n             Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0                                                                                     Unnamed: 10_level_0
                                              UniGene                                                                                                     Description         Folds     P value        Folds      P value          Folds            P value              Folds            P value                                                                                  Function/Gene Ontology
0                 Defense stress and detoxification b                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
1                                            Mm.28191                                                                                       carboxylesterase 2 (Ces2)           3.8       0.020        -0.70         0.07           -0.5               0.17                0.5               0.53                                                                                Ester hydrolase activity
2                                           Mm.389848                                                  Cytochrome P450, family 2, subfamily a, polypeptide 5 (Cyp2a5)           8.2       0.010         3.00         0.30           -5.6               0.03                0.2               0.51                                                        Degradation of environmental toxins and mutagens
3                                            Mm.32550                                                          DnaJ (Hsp40) homolog, subfamily C, member 12 (Dnajc12)           2.2       0.000         0.40         0.51            5.5               0.11               -1.5               0.00                                                             Heat shock protein binding, protein folding
4                                           Mm.218639                                                                  sulfiredoxin 1 homolog (S. cerevisiae) (Srxn1)           3.3       0.030        -0.20         0.19            0.9               0.96               -1.6               0.00                                                      Antioxidant activity, response to oxidative stress
5                                                 NaN                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
6                                        Metabolism b                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
7                                            Mm.30085                                           aldo-keto reductase family 1, member A4 (aldehyde reductase) (Akr1a4)           2.4       0.000         1.30         0.03           -0.1               0.18                1.1               0.01                                                                                 Glycerolipid metabolism
8                                            Mm.26787                                                                                       aldehyde oxidase 1 (Aox1)           6.5       0.010         0.70         0.73           -1.8               0.00               -1.1               0.00                                                                                   Xenobiotic metabolism
9                                            Mm.24021                                                                                  Biliverdin reductase B (Blvrb)           3.4       0.010        -1.50         0.00           -2.1               0.00               -1.7               0.00                                                                    Porphyrin and chlorophyll metabolism
10                                           Mm.22720                                                                                       carboxylesterase 1 (Ces1)           8.0       0.010         2.80         0.09           -2.4               0.00                3.0               0.00                                                                                   Alkaloid biosynthesis
11                                           Mm.12906                                                                                        dopa decarboxylase (Ddc)           5.1       0.000        -0.50         0.15           -2.0               0.15               -1.1               0.00                                                             Amino acid and derivative metabolic process
12                                           Mm.22758                                                                            emopamil binding protein-like (Ebpl)           2.2       0.000         0.60         0.48            1.2               0.09                1.3               0.00                                                                                       Sterol metabolism
13                                           Mm.10211                                 ectonucleoside triphosphate diphosphohydrolase 5, transcript variant 1 (Entpd5)           5.4       0.020        -0.70         0.03           -2.3               0.00               -1.6               0.00                                                                Purine metabolism; pyrimidine metabolism
14                                            Mm.9075                                                                         epoxide hydrolase 1, microsomal (Ephx1)           3.3       0.000         1.50         0.02           -1.8               0.00               -0.3               0.14                                                                                   Xenobiotic metabolism
15                                          Mm.252391                                                           glycerol-3-phosphate dehydrogenase 1 (soluble) (Gpd1)           3.1       0.020        -0.10         0.24            1.4               0.02                1.2               0.08                                                                                 Carbohydrate metabolism
16                                          Mm.283573                                                                                   Glutathione reductase 1 (Gsr)           3.2       0.000         0.20         0.42            1.2               0.02               -1.1               0.00                                                                                  Glutathione metabolism
17                                          Mm.197422                                                                 Glutathione S-transferase, alpha 1 (Ya) (Gsta1)          23.4       0.000        -0.20         0.33           -3.6               0.00               -0.3               0.14                                                           Glutathione metabolism; xenobiotic metabolism
18                                          Mm.422778                                                                Glutathione S-transferase, alpha 2 (Yc2) (Gsta2)           2.9       0.001         0.45         0.55           -2.3               0.06                1.2               0.00                                                           Glutathione metabolism; xenobiotic metabolism
19                                            Mm.2662                                                                      Glutathione S-transferase, alpha 4 (Gsta4)           8.6       0.000         0.60         0.51           -1.5               0.00                1.8               0.05                                                           Glutathione metabolism; xenobiotic metabolism
20                                           Mm.37199                                                                         Glutathione S-transferase, mu 1 (Gstm1)           3.2       0.010         1.40         0.00            0.0               0.20                1.5               0.10                                                           Glutathione metabolism; xenobiotic metabolism
21                                           Mm.37199                                                                         Glutathione S-transferase, mu 2 (Gstm2)           4.8       0.010        -0.60         0.03           -1.2               0.00               -1.8               0.00                                                           Glutathione metabolism; xenobiotic metabolism
22                                           Mm.37199                                                                         Glutathione S-transferase, mu 3 (Gstm3)          12.0       0.010         0.40         0.54            0.0               0.16                1.2               0.21                                                           Glutathione metabolism; xenobiotic metabolism
23                                            Mm.5731                                                                      Glutathione S-transferase, theta 3 (Gstt3)           5.1       0.040        -1.80         0.07           -2.4               0.15                1.3               0.01                                                                                  Glutathione metabolism
24                                          Mm.276389                                                                            heme oxygenase (decycling) 1 (Hmox1)          17.3       0.000         1.60         0.08            2.4               0.00                2.2               0.02                                             Porphyrin and chlorophyll metabolism; xenobiotic metabolism
25                                          Mm.299381                                                       hypoxanthine guanine phosphoribosyl transferase 1 (Hprt1)           2.8       0.000         0.60         0.54            1.3               0.00                1.1               0.12                                                                                       Purine metabolism
26                                          Mm.218286                                                                  microsomal glutathione S-transferase 3 (Mgst3)           5.8       0.000        -0.50         0.05           -2.7               0.00                1.1               0.04                                                           Glutathione metabolism; xenobiotic metabolism
27                                          Mm.344831                                                                                UDP-glucose dehydrogenase (Ugdh)           6.4       0.002         0.50         0.56           -0.1               0.16               -1.2               0.00                                              Nucleotide sugar metabolism; starch and sucrose metabolism
28                                          Mm.312095                                                 UDP glucuronosyltransferase 2 family, polypeptide B35 (Ugt2b35)           5.0       0.010         0.60         0.61           -2.4               0.00               -1.4               0.00                                                                                        Sugar metabolism
29                                                NaN                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
30  Intracellular communication/signal transduction b                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
31                                           Mm.18628                                                                                             CD36 antigen (Cd36)           5.6       0.000        -2.60         0.00           -3.2               0.00               -3.8               0.00                                                 Adipocytokine signaling pathway; PPAR signaling pathway
32                                            Mm.6529                                                                      Dystrophia myotonica-protein kinase (Dmpk)           5.0       0.000         1.00         0.97            1.3               0.06                1.5               0.00             Protein amino acid phosphorylation; regulation of small GTPase mediated signal transduction
33                                           Mm.12967                                                  inhibitor of kappaB kinase gamma, transcript variant 2 (Ikbkg)           5.1       0.020         1.20         0.01           -1.6               0.00               -1.1               0.00                                                                 Activation of NF-kappaB-inducing kinase
34                                          Mm.294007                          PREDICTED: proprotein convertase subtilisin/kexin type 6, transcript variant 4 (Pcsk6)           3.7       0.000         0.90         0.94           -0.7               0.03                1.8               0.04  Determination of left/right symmetry; transmembrane receptor protein tyrosine kinase signaling pathway
35                                          Mm.308180                                               protein tyrosine phosphatase-like A domain containing 1 (Ptplad1)           3.0       0.000         0.70         0.64            1.6               0.09                0.3               0.41                         I-kappaB kinase/NF-kappaB cascade; JNK cascade; Rho protein signal transduction
36                                                NaN                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
37            Cell cycle/Growth and differentiation b                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
38                                           Mm.20801                                                      HIV-1 tat interactive protein 2, homolog (human) (Htatip2)           4.2       0.010        -0.10         0.22           -0.7               0.03                0.4               0.40                                          Regulation of angiogenesis and apoptosis; cell differentiation
39                                           Mm.43831                                                                   lectin, galactose binding, soluble 1 (Lgals1)           6.0       0.010        -1.40         0.03           -1.1               0.00               -1.5               0.00                                                                 Myoblast differentiation; sugar binding
40                                           Mm.62876                                                                                         ZW10 interactor (Zwint)           3.0       0.010        -0.50         0.04           -1.2               0.00                0.3               0.43                                                                               cell cycle; cell division
41                                          Mm.290692                                                                                             transketolase (Tkt)           2.6       0.000        -0.50         0.03            0.5               0.40               -1.2               0.00                                                                 Metal ion binding; regulation of growth
42                                                NaN                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
43       Cellular transport and transport mechanism b                                                                                                             NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                                                     NaN
44                                          Mm.103777                                                             Rhesus blood group-associated B glycoprotein (Rhbg)           4.8       0.020         0.10         0.24           -0.8               0.03               -1.1               0.00                                                                           Ammonium transporter activity
45                                          Mm.222536            solute carrier family 25 (mitochondrial carrier, peroxisomal membrane protein), member 17 (Slc25a17)           2.4       0.000        -0.90         0.02           -1.9               0.00               -5.8               0.00                                                           mitochondrial transport; transporter activity
46                                          Mm.281800  Solute carrier family 35 (UDP-glucuronic acid/UDP-N-acetylgalactosamine dual transporter), member D1 (Slc35d1)           2.8       0.000         0.60         0.53            0.5               0.37               -1.2               0.00                                                                            Nucleotide-sugar transporter
47                                          Mm.218875                                                  target of myb1-like 2 (chicken), transcript variant 1 (Tom1l2)           2.1       0.000        -2.10         0.06            5.4               0.00                2.5               0.01                                       Golgi vesicle-mediated transport; intracellular protein transport

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Transcripts in reduced levels within liver of knockout mice relative to wild type mice a
  footer_text: a Genes depleted ≥ 2.0 fold in ΔTrsp mice as compared to Trsp mice with a P-value ≤ 0.05 were assessed and shown in the table. The corresponding transcript levels were also analyzed in A34, G37L and G37H replacement mice relative to Trsp mice. Gene Unigene Accession Number, gene description, fold change with P value, and gene function(s) are shown. Four control and four experimental animals were used for comparing ΔTrsp, A34 and G37L with Trsp, while three control and three experimental animals were used for comparing G37H with Trsp. b Genes are grouped into classes according to function.
    unique: PMC2423936/PMC2423936.xml::T4-0

                                     \n                                                                                                                              ΔTrsp vs Trsp A34 vs Trsp G37L vs Trsp G37H vs Trsp \n             Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0                                                           Unnamed: 10_level_0
                                              UniGene                                                                                                    Description         Folds     P value        Folds      P value          Folds            P value              Folds            P value                                                        Function/Gene Ontology
0        Cellular transport and transport mechanism b                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
1                                           Mm.381860                                                              coatomer protein complex, subunit gamma 2 (Copg2)          -2.3        0.00         -0.8         0.05           -2.5               0.00               -1.7               0.00                                                             Protein transport
2                                           Mm.261168                                           Potassium inwardly-rectifying channel, subfamily J, member 9 (Kcnj9)          -2.3        0.00         -0.5         0.08            1.1               0.01               -1.7               0.00                             Ion transport; voltage-gated ion channel activity
3                                           Mm.283370                                                                                      Neurocalcin delta (Ncald)          -2.3        0.00         -1.5         0.00            1.5               0.00                1.2               0.00                                                    Vesicle-mediated transport
4                                           Mm.296837                                                                                         sideroflexin 2 (Sfxn2)          -3.8        0.01          0.1         0.49           -1.4               0.05                0.0               0.43                                                                 Ion transport
5                                           Mm.250738                      solute carrier family 13 (sodium-dependent dicarboxylate transporter), member 3 (Slc13a3)          -2.4        0.00         -0.8         0.04           -1.2               0.00                1.0               0.00               Dicarboxylic acid transport; ion transport; symporter activity;
6                                           Mm.255586                                          solute carrier organic anion transporter family, member 1a4 (Slco1a4)          -2.5        0.00          1.0         0.98           -0.3               0.20               -1.2               0.00                             Ion transport; organic anion transporter activity
7                                                 NaN                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
8   Intracellular communication/Signal transduction b                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
9                                           Mm.376094                                                                                   Anti-Mullerian hormone (Amh)          -2.3        0.00         -0.0         0.41           -0.1               0.24               -1.0               0.32                              Transforming growth factor beta receptor binding
10                                          Mm.271854                                                      Low density lipoprotein receptor-related protein 1 (Lrp1)          -2.3        0.00         -0.1         0.23            0.0               0.18               -1.3               0.00                         Negative regulation of Wnt receptor signaling pathway
11                                            Mm.6595                                                      mitogen activated protein kinase kinase kinase 5 (Map3k5)          -2.3        0.00         -0.2         0.35            1.2               0.00                0.1               0.43                                                   Activation of MAPK activity
12                                            Mm.3810                               phosphatidylinositol 3-kinase, C2 domain containing, alpha polypeptide (Pik3c2a)          -2.2        0.00          0.4         0.58           -0.7               0.23                1.6               0.00                                               Intracellular signaling cascade
13                                                NaN                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
14                                       Metabolism b                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
15                                           Mm.46269                                                                                               insulin I (Ins1)          -2.3        0.00          1.7         0.02           -1.1               0.00                2.1               0.01                                                       Carbohydrate metabolism
16                                           Mm.34459                                                                                          junctophilin 2 (Jph2)          -2.7        0.00          0.3         0.34           -1.8               0.00               -1.2               0.00                                                       Carbohydrate metabolism
17                                           Mm.19669                                                 6-phosphofructo-2-kinase/fructose-2,6-biphosphatase 3 (Pfkfb3)          -2.3        0.05         -2.3         0.19            0.7               0.60                2.1               0.01                                               Fructose and mannose metabolism
18                                            Mm.9277                      phospholipase A2, group VII (platelet-activating factor acetylhydrolase, plasma) (Pla2g7)          -2.8        0.00          2.2         0.14            0.7               0.60                1.1               0.03                                                              Lipid catabolism
19                                                NaN                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
20                 Cellular structural organization b                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
21                                           Mm.49994                                                                            hook homolog 1 (Drosophila) (Hook1)          -3.1        0.00          0.4         0.59            0.0               0.19               -1.1               0.00               Cytoskeleton organization and biogenesis; spermatid development
22                                          Mm.129840                                       phosphodiesterase 4D interacting protein transcript variant 1 (Pde4dip),          -2.4        0.00          0.5         0.56           -1.2               0.00                1.0               0.21                               Association with spindle pole body microtubules
23                                            Mm.9684                                                                   vasodilator-stimulated phosphoprotein (Vasp)          -2.0        0.00          1.2         0.01           -1.2               0.00               -1.1               0.00                                Actin cytoskeleton organization and biogenesis
24                                                NaN                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
25                        Transcription/Translation b                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
26                                          Mm.174044                                               RIKEN cDNA 2700050L05 gene, transcript variant 2 (2700050L05Rik)          -2.0        0.00         -1.2         0.00           -1.4               0.00               -1.8               0.00                                                      Transcription regulation
27                                            Mm.2645                                                    eukaryotic translation elongation factor 1 alpha 2 (Eef1a2)          -2.4        0.00         -2.4         0.02           -1.8               0.00                1.3               0.03                                Protein biosynthesis; translational elongation
28                                          Mm.303355                                                                      One cut domain, family member 1 (Onecut1)          -4.0        0.04         -1.8         0.09           -2.1               0.00               -2.5               0.00                                                   Regulation of transcription
29                                            Mm.7916                                      Paf1, RNA polymerase II associated factor, homolog (S. cerevisiae) (Paf1)          -2.7        0.00          0.7         0.77           -0.9               0.16                0.0               0.31                                                   Regulation of transcription
30                                          Mm.244820                                                                                 TATA box binding protein (Tbp)          -2.6        0.00          0.4         0.45            1.2               0.00               -1.4               0.00                                                   Regulation of transcription
31                                                NaN                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
32                  Miscellaneous (Mixed functions) b                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
33                                           Mm.28796                                                                    RIKEN cDNA 5730446C15 gene, (5730446C15Rik)          -2.1        0.00          0.7         0.74           -0.5               0.24                1.7               0.00                                                            Peptidase activity
34                                           Mm.71924                                                                             ankyrin repeat domain 38 (Ankrd38)          -2.3        0.00         -0.7         0.01           -1.3               0.00               -1.1               0.00                                                   Protein-protein interaction
35                                          Mm.119936                                                                                               attractin (Atrn)          -2.0        0.00          2.2         0.01           -1.1               0.00               -1.7               0.00                         Inflammatory response; protein binding; sugar binding
36                                          Mm.212861                                                                                              cullin 4A (Cul4a)          -2.2        0.00          1.7         0.62           -1.4               0.00               -1.1               0.00  Cell cycle; induction of apoptosis by intracellular signals; ubiquitin cycle
37                                          Mm.171323                                                   nuclear receptor coactivator 6 interacting protein (Ncoa6ip)          -2.4        0.00         -0.8         0.03           -0.4               0.17               -0.6               0.14     S-adenosylmethionine-dependentmethyltransferase activity; protein binding
38                                          Mm.261818                                                                               Ring finger protein 167 (Rnf167)          -2.8        0.00          1.2         0.91           -1.5               0.00               -1.5               0.00                        Metal ion binding; protein binding; peptidase activity
39                                          Mm.284592                                                                      SUMO/sentrin specific peptidase 3 (Senp3)          -2.2        0.00          0.2         0.35           -0.6               0.04                0.3               0.43  Peptidase activity; protein metabolism; ubiquitin-specific protease activity
40                                                NaN                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
41                                          Unknown b                                                                                                            NaN           NaN         NaN          NaN          NaN            NaN                NaN                NaN                NaN                                                                           NaN
42                                          Mm.416885                                                                                     RIKEN cDNA 2010109N18 gene          -2.9        0.00          0.3         0.36            3.5               0.27               -1.4               0.00                                                                       Unknown
43                                          Mm.138091                                    PREDICTED: RIKEN cDNA 3110001I20 gene, transcript variant 1 (3110001I20Rik)          -2.3        0.00         -0.9         0.05           -1.7               0.10               -0.9               0.13                                                                       Unknown
44                                          Mm.395958                                                                                     RIKEN cDNA 9130221J18 gene          -4.9        0.00         -0.3         0.14            0.3               0.52                1.4               0.01                                                                       Unknown
45                                          Mm.395042                                                                                     RIKEN cDNA 9430078K24 gene          -2.1        0.00         -0.3         0.13           -1.2               0.00                1.8               0.00                                                                       Unknown
46                                          Mm.425114  PREDICTED: similar to gonadotropin inducible ovarian transcription factor 1, transcript variant 3 (LOC664985)          -2.9        0.00          0.2         0.35            0.1               0.24               -1.2               0.00                                                                       Unknown
47                                          Mm.219946                                                                       SET and MYND domain containing 5 (Smyd5)          -2.7        0.00          0.0         0.21           -1.1               0.00               -2.0               0.00                                                                       Unknown

PMC0024XXXXX/PMC2424084.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Characteristics of the Study Sample: Community-dwelling Framingham Heart Study Original Cohort
  footer_text: * Cardiovascular disease= coronary heart disease, stroke, transient ischemic attack, congestive heart failure, or intermittent claudication. Hypertension= blood pressure ≥ 140/90 or on antihypertensive medication treatment. Diabetes=causal blood glucose of 200 mg/dl or greater or treatment with oral hypoglycemic agent or insulin. Depressive symptoms assessed at examinations 22 and 25 with the Center for Epidemiologic Studies Depression Scale (CES-D). A score of 16 or greater defined the presence of depressive symptoms. Medical conditions included any of the following five conditions: diabetes, cardiovascular disease, cancer, chronic obstructive pulmonary disease, and hip fracture. NA= not available as data not collected. Rx=medication treatment
    unique: PMC2424084/PMC2424084.xml::T1-0

              CharacteristicMean or percent Exam15(1977-79)N=177 WomenExam20(1988-90)N=159 Exam25(1997-99)N=174 Exam15(1977-79)N=103 MenExam20(1988-90)N=98 Exam25(1997-99)N=119
         \n                \n                 Unnamed: 1_level_1        Unnamed: 2_level_1   Unnamed: 3_level_1   Unnamed: 4_level_1     Unnamed: 5_level_1   Unnamed: 6_level_1
                        Mean age, years82.2                 82.2                      81.9     \n                               81.6                   82.1                 82.3
0               Chronic medical conditions*                  NaN                       NaN                  NaN                  NaN                    NaN                  NaN
1                           Hypertension, %                 76.1                      81.1                 83.3                 56.4                   85.7                 76.5
2                 Hypertension treatment, %                 47.9                      63.5                 60.3                 33.0                   61.2                 55.9
3     Total cholesterol ≥ 240 mg/dL or Rx,%                 38.3                      24.5                 32.8                 12.9                   11.7                 22.9
4                               Diabetes, %                  9.8                       8.2                  5.7                  7.4                   13.3                 10.1
5               Obesity (BMI ≥ 30 kg/m2), %                 12.4                      15.5                 20.7                  2.2                   12.4                 15.3
6                 Cardiovascular disease, %                 37.9                      28.3                 29.3                 41.7                   44.9                 55.5
7                                 Cancer, %                 11.3                      14.5                 19.0                 15.5                   16.3                 24.4
8   Chronic obstructive pulmonarydisease, %                  9.9                       9.6                  5.7                 18.5                   12.5                 10.3
9                           Hip fracture, %                  5.1                       8.8                  6.9                  1.9                    1.0                  1.7
10                   Depressive symptoms, %                  NaN                      16.7                 10.4                  NaN                    6.1                  7.0
11        At least one medical condition, %                 52.7                      52.2                 51.1                 63.0                   58.7                 75.2
12                         Health behaviors                  NaN                       NaN                  NaN                  NaN                    NaN                  NaN
13              Current cigarette smoker, %                  4.9                       5.7                  4.0                 15.3                    4.1                  5.1
14       Alcohol intake, number drinks/week                  1.9                       3.6                  2.5                  6.1                    6.4                  5.4
15                Socio-demographic factors                  NaN                       NaN                  NaN                  NaN                    NaN                  NaN
16               Marital Status, Married, %                 17.8                      19.0                 30.2                 73.4                   80.9                 73.7
17                               Widowed, %                 69.9                      63.3                 59.3                 22.3                   14.9                 21.2
18                                Single, %                 10.4                      12.0                  8.7                  2.1                    2.1                  3.4
19                              Divorced, %                  1.9                       5.7                  1.8                  2.2                    2.1                  1.7
20     Education, high school or greater, %                 53.2                      58.3                 78.5                 46.5                   54.3                 76.3
21         Living situation, lives alone, %                  NaN                      72.2                 46.2                  NaN                   17.3                 19.3
22        Work status, currently working, %                  2.3                       6.3                  6.3                 12.6                   14.3                 16.0
23   Subjective health, good or excellent,%                 66.9                      80.5                 79.2                 80.0                   76.5                 84.0

  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Self-reported Prevalence of Functional Limitation or Physical Disability: Framingham Heart Study Original Cohort, Mean Age 82 years
  footer_text: Nagi physical performance scale limitation= some difficulty, a lot of difficulty, unable to do, do not do on physician order Rosow-Breslau functional health scale disability= unable to do. Modified Katz ADL scale disability=human assistance needed, minimally dependent; dependent † At exam 25 this question was asked as part of the modified Katz ADL Scale ‡ At Exams 20 and 25 the question was changed to transferring (getting in and out of a chair) and walking on a level surface about 50 yards
    unique: PMC2424084/PMC2424084.xml::T2-0

                              Scale and Scale Items* \n                     WOMEN \n                                  MEN \n
                                           (percent)      Exam15N=177 Exam20N=159      Exam25N=174 Exam15N=103 Exam20N=98    Exam25N=119
0                    Nagi Physical Performance Scale              NaN         NaN              NaN         NaN        NaN            NaN
1                   Pulling or pushing large objects             40.6        31.6             18.3        14.7       11.2            6.7
2            Either stooping, crouching, or kneeling             48.3        47.8             18.5        23.5       18.4           17.6
3     Reaching or extending arms above shoulderlevel              9.7        14.6              7.5         5.9        8.2            4.2
4     Reaching or extending arms below shoulderlevel              4.5         3.8              1.1         1.0        2.0            0.8
5      Writing, handling, or fingering small objects             17.5        11.9              5.7        15.5       11.2           10.1
6   Standing in place for long periods say 15minutes             39.0        29.7             15.9        22.3       16.3           12.2
7                Sitting for long periods say 1 hour              9.7         5.0              4.0         9.9        6.1            0.8
8              Rosow-Breslau Functional Health Scale              NaN         NaN              NaN         NaN        NaN            NaN
9                        Heavy work around the house             65.5        39.0             30.5        35.9       31.6           19.3
10         Walks up and down stairs to second floor†             26.0         7.5              6.9         6.8        2.0            0.0
11                                Walk one half mile             39.5        25.2             16.7        16.5       11.2           14.3
12    Modified Katz Activities of Daily Living Scale              NaN         NaN              NaN         NaN        NaN            NaN
13                         Bathing/personal grooming             15.3         2.5              2.9         4.9        2.0            0.0
14                                          Dressing              1.7         1.9              3.4         2.9        3.1            0.8
15                                            Eating              0.0         0.0              1.1         0.0        2.0            0.8
16                    Getting from a bed to a chair‡              0.0         1.3              2.9         1.0        3.1            0.0
17                        Walking across small room‡              4.5         1.3              0.6         0.0        1.0            0.8
18                                               NaN              NaN         NaN              NaN         NaN        NaN            NaN
19               Any special equipment or device use              7.9        13.2             28.2         3.9        4.1           17.6

  ----------------------------------------
  id: T3
  label_text: TABLE 3
  caption_text: Sex-specific Trends in Self-reported Functional Limitations and Physical Disability Adjusted for Age
  footer_text:
    unique: PMC2424084/PMC2424084.xml::T3-0

                                        \n               Community-dwelling Framingham Heart Study Original Cohort, Mean Age 82 years Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0
                      \n                \n                                                                         Unnamed: 1_level_1 Unnamed: 2_level_1 Unnamed: 3_level_1 Unnamed: 4_level_1 Unnamed: 5_level_1 Unnamed: 6_level_1 Unnamed: 7_level_1 Unnamed: 8_level_1
                                 Physical Function Scale                                                             \n                            Women   \n                 \n                 \n                              Men     \n             Unnamed: 8_level_2
                  Mean or percent95% confidence interval                                                                 Exam 15N=177        Exam20N=159        Exam25N=174            p-value       Exam 15N=103         Exam20N=98        Exam25N=119            p-value
0                      Functional limitation, Nagi Scale                                                                          NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
1                        Number of items with limitation                                                                         1.67               1.45               0.70               <0.0               0.93               0.73               0.53               0.03
2                                                    NaN                                                                   1.46, 1.88           1.231.67           0.480.91                 01           0.711.14           0.510.96           0.320.73                NaN
3                            Any difficulty on the scale                                                                         74.6               60.5               37.9               <0.0               54.2               37.8               27.8             <0.001
4                                                    NaN                                                                   66.7, 81.1           51.568.8           29.946.5                 01           43.165.0           27.649.2           19.637.9                NaN
5   Physical disability, Rosow-Breslau & Katz ADL Scales                                                                          NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
6                        Number of items with impairment                                                                         1.52               0.81               0.64             <0.001               0.71               0.55               0.35               0.02
7                                                    NaN                                                                   1.34, 1.70           0.621.00           0.460.82                NaN           0.520.90           0.360.75           0.170.52                NaN
8                           Any difficulty on the scales                                                                          NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
9                                                    NaN                                                                         74.5               48.5               34.6             <0.001               42.3               33.3               22.8              0.009
10                                                   NaN                                                                   66.7, 80.9           39.857.2           27.043.0                NaN           31.953.3           23.744.4           15.432.3                NaN
11                             Summary, All three scales                                                                          NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
12                    Number of items with limitation or                                                                         3.19               2.26               1.34             <0.001               1.64               1.29               0.87              0.009
13                                            impairment                                                                   2.86, 3.52           1.912.61           1.001.67                NaN           1.282.00           0.921.66           0.541.20                NaN
14                                                   NaN                                                                          NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
15                          Any difficulty on the scales                                                                         88.1               69.6               49.1             <0.001               63.9               48.8               36.4             <0.001
16                                                   NaN                                                                   81.9, 92.4           60.877.0           40.457.9                NaN           52.973.5           37.759.8           27.146.9                NaN

  ----------------------------------------
  id: T4
  label_text: Appendix 1
  caption_text: Study Sample: Framingham Original Cohort, Aged 79 to 88, Attending Index Examinations 15, 20, and 25
  footer_text: † Examinations off-site in participants’ homes or nursing homes were not available at examination 15. ‡ The Framingham Disability Study collected physical function data at examination 15.(19;43)
    unique: PMC2424084/PMC2424084.xml::T4-0

                                                         \n               Exam 151977–1979N Exam 201988–1990N Exam 251997–1999N
0   Eligible: Age 79 to 88 years at the Index Exam Based on Date of Birth              1435              1727              1969
1                                                                     NaN               NaN               NaN               NaN
2                                               Death Prior to Index Exam               855              1076              1170
3                                                                     NaN               NaN               NaN               NaN
4                                                     Alive at Index Exam               580               651               799
5                                                                     NaN               NaN               NaN               NaN
6                          Exclusions, N (percent of living participants)               NaN               NaN               NaN
7                                    Alive, did not attend the index exam        156 (26.9)        269 (41.3)        243 (30.4)
8                                                     Alive with dementia           5 (0.9)          10 (1.5)           6 (0.8)
9      Alive, examination took place outside the Framingham Study clinic†               NaN          58 (8.9)        122 (15.3)
10                    (nursing home, personal residence, or unknown site)               NaN           57(8.8)        135 (16.9)
11       Alive, missing data (≥1 item on the 3 physical function scales)‡               NaN               NaN               NaN
12                                                                    NaN        139 (24.0)               NaN               NaN
13                                                                    NaN               NaN               NaN               NaN
14                       Final Sample, N (percent of living participants)         280(48.3)         257(39.5)         293(36.7)

PMC0024XXXXX/PMC2424085.xml
  ----------------------------------------
  id: T1
  label_text: TABLE 1
  caption_text: Characteristics of Participants, by Age Group: Health and Retirement Study, 1998
  footer_text: Note. ADL = activities of daily living. IADL = instrumental activities of daily living. ADL include bathing, dressing, eating, transferring, and toileting. IADL include shopping, preparing meals, using the telephone, managing medications, and managing finances.
    unique: PMC2424085/PMC2424085.xml::T1-0

                    \n               Age 50–59 Years (n = 5382), %      Age 60–69 Years (n = 6591), % Age 70–79 Years (n = 4903), % Age 80–89 Years (n = 2219), % Age 80–89 Years (n = 335), % All Participants (n = 19 430), % Unnamed: 7_level_0
                    \n                            \n               \n                \n                          Unnamed: 3_level_1            Unnamed: 4_level_1           Unnamed: 5_level_1               Unnamed: 6_level_1 Unnamed: 7_level_1
0                          Mortality                             5                               11.0                          24.0                          47.0                         76.0                             18.0                NaN
1                                Men                            42                               46.0                          45.0                          38.0                         30.0                             44.0                NaN
2                 Chronic conditions                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
3                       Hypertension                            38                               48.0                          53.0                          55.0                         53.0                             47.0                NaN
4                  Diabetes mellitus                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
5                                NaN                          None                               89.0                          85.0                          83.0                         85.0                             90.0               86.0
6                                NaN         Oral medications only                                7.0                          10.0                          11.0                         10.0                              8.0               10.0
7                                NaN                       Insulin                                3.0                           3.0                           4.0                          3.0                              2.0                3.0
8                                NaN                Kidney disease                                2.0                           2.0                           2.0                          2.0                              1.0                2.0
9                      Heart disease                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
10                               NaN                          None                               87.0                          81.0                          75.0                         69.0                             68.0               79.0
11                               NaN                        Angina                               10.0                          16.0                          19.0                         22.0                             20.0               16.0
12                               NaN         Heart attack past 2 y                                1.0                           2.0                           3.0                          4.0                              3.0                2.0
13                               NaN                 Heart failure                                1.0                           2.0                           4.0                          5.0                              9.0                3.0
14                            Cancer                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
15                               NaN                          None                               94.0                          90.0                          85.0                         82.0                             86.0               89.0
16                               NaN                     Localized                                6.0                          10.0                          14.0                         17.0                             13.0               11.0
17                               NaN                        Spread                                0.4                           0.4                           0.8                          0.8                              0.6                1.0
18                      Lung disease                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
19                               NaN                          None                               94.0                          90.0                          89.0                         88.0                             94.0               91.0
20                               NaN                No medications                                4.0                           5.0                           5.0                          5.0                              3.0                5.0
21                               NaN                   Medications                                2.0                           4.0                           4.0                          4.0                              3.0                3.0
22                               NaN                        Oxygen                                0.4                           1.0                           2.0                          2.0                              0.6                1.0
23                            Stroke                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
24                               NaN                          None                               97.0                          95.0                          91.0                         87.0                             84.0               93.0
25                               NaN           No current deficits                                1.0                           3.0                           5.0                          7.0                              6.0                3.0
26                               NaN              Current deficits                                2.0                           3.0                           5.0                          6.0                              9.0                3.0
27            Any chronic conditions                            70                               83.0                          88.0                          92.0                         90.0                             82.0                NaN
28            Functional limitations                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
29                         Toileting                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
30                               NaN                 No difficulty                               97.0                          96.0                          94.0                         89.0                             81.0               95.0
31                               NaN                    Difficulty                                3.0                           3.0                           5.0                          7.0                             10.0                4.0
32                               NaN                     Dependent                                0.6                           0.8                           2.0                          4.0                              8.0                1.0
33                            Eating                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
34                               NaN                 No difficulty                               98.0                          98.0                          97.0                         92.0                             88.0               97.0
35                               NaN                    Difficulty                                0.8                           1.0                           1.0                          3.0                              6.0                1.0
36                               NaN                     Dependent                                0.7                           1.0                           2.0                          5.0                              6.0                2.0
37                           Bathing                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
38                               NaN                 No difficulty                               97.0                          95.0                          92.0                         82.0                             68.0               93.0
39                               NaN                    Difficulty                                2.0                           3.0                           4.0                          7.0                              6.0                3.0
40                               NaN                     Dependent                                1.0                           2.0                           4.0                         11.0                             26.0                4.0
41               Using the telephone                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
42                               NaN                 No difficulty                               98.0                          97.0                          94.0                         87.0                             78.0               95.0
43                               NaN                    Difficulty                                2.0                           2.0                           4.0                          9.0                             14.0                4.0
44                               NaN                     Dependent                                0.1                           0.5                           1.0                          3.0                              9.0                1.0
45                 Managing finances                           NaN                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
46                               NaN                 No difficulty                               97.0                          97.0                          94.0                         85.0                             72.0               95.0
47                               NaN                    Difficulty                                2.0                           2.0                           4.0                          8.0                             17.0                4.0
48                               NaN                     Dependent                                0.4                           0.8                           2.0                          7.0                             11.0                2.0
49  Any difficulty in an ADL or IADL                            15                               19.0                          26.0                          46.0                         68.0                             21.0                NaN
50                               NaN                       Walking                                NaN                           NaN                           NaN                          NaN                              NaN                NaN
51                               NaN            Able to jog 1 mile                               24.0                          15.0                           8.0                          3.0                              1.0               14.0
52                               NaN   Able to walk several blocks                               57.0                          61.0                          60.0                         45.0                             30.0               57.0
53                               NaN          Able to walk 1 block                               11.0                          14.0                          17.0                         24.0                             21.0               15.0
54                               NaN    Difficulty walking 1 block                                7.0                           9.0                          13.0                         21.0                             29.0               11.0
55                               NaN            Can't walk 1 block                                0.8                           2.0                           2.0                          7.0                             19.0                2.0

  ----------------------------------------
  id: T2
  label_text: TABLE 2
  caption_text: Harrell's C Statistic of Cox Mortality Models Including Different Risk Factors by Age Groups: Health and Retirement Study, 1998
  footer_text: a Permutation test of whether slope of regression between age group and C statistic = 0.
    unique: PMC2424085/PMC2424085.xml::T2-0

                             Models   Age 50–59 Years   Age 60–69 Years   Age 70–79 Years   Age 80–89 Years   Age 90–99 Years Test for Trenda
0          A: Base (age and gender)  0.62 (0.59–0.65)  0.60 (0.58–0.62)  0.61 (0.59–0.62)  0.60 (0.58–0.62)  0.58 (0.54–0.62)         P = .05
1  B: Base + functional limitations  0.73 (0.71–0.76)  0.72 (0.70–0.73)  0.70 (0.69–0.72)  0.67 (0.66–0.69)  0.67 (0.63–0.70)        P = .017
2      C: Base + chronic conditions  0.78 (0.75–0.81)  0.72 (0.70–0.74)  0.70 (0.68–0.71)  0.65 (0.63–0.67)  0.61 (0.58–0.65)        P = .016
3   D: Base + conditions + function  0.79 (0.77–0.82)  0.75 (0.73–0.77)  0.73 (0.72–0.74)  0.69 (0.68–0.71)  0.69 (0.66–0.72)        P = .017
4  P value for model B/C comparison              .001               .48               .36              .006              .004             NaN

PMC0024XXXXX/PMC2424090.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Characteristics of those who died compared to those who did not die during follow-up.
  footer_text: a CES-D = Center for Epidemiologic Studies Depression Scale – Short Form
    unique: PMC2424090/PMC2424090.xml::T1-0

        Average Characteristics Dead (N = 1168) Alive (N = 2986)
0        Mean age in years (SD)     80.2 (7.34)      76.0 (5.45)
1                       Sex (%)             NaN              NaN
2                        Female            26.3             73.7
3                          Male            31.0             69.0
4                      Race (%)             NaN              NaN
5                         Black            26.6             73.4
6                         White            30.5             69.5
7                  Lifetime SES     −0.04 (.76)       0.09 (.76)
8        Mean score CES-Da (SD)      2.31(2.34)      1.58 (2.02)
9   Mean no. medical conditions     1.22 (1.04)      0.99 (0.93)
10     Perceived discrimination     1.13 (1.72)      0.99 (1.58)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Relative risk of mortality associated with perceived discrimination
  footer_text: Hazard ratios and 95% confidence interval; Hazard ratios are estimated from separate models adjusted for age, sex, race, race*age, and lifetime SES.
    unique: PMC2424090/PMC2424090.xml::T2-0

                               Variable        Full Cohort (N = 4101) Unnamed: 2_level_0
                     Unnamed: 0_level_1                       Model 1            Model 2
0  Discrimination score (range = 0 − 9)             1.05 (1.01, 1.09)  1.12 (1.04, 1.20)
1                Discrimination × Black                           NaN  0.92 (0.85, 0.99)
2                                   NaN  Race-Matched Cohort (N=3070)                NaN
3                                   NaN                       Model 1            Model 2
4         Discrimination (range = 0 −9)             1.07 (1.03, 1.12)  1.11 (1.03, 1.20)
5                Discrimination × Black                           NaN  0.95 (0.87, 1.04)

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Relative risk of mortality associated with unfair treatment and personal rejection
  footer_text: Hazard ratios and 95% confidence interval; Hazard ratios are estimated from separate models adjusted for age, sex, race, race*age, and lifetime SES.
    unique: PMC2424090/PMC2424090.xml::T3-0

                               Variable                Unfair Treatment              Personal Rejection Unnamed: 3_level_0 Unnamed: 4_level_0
                     Unnamed: 0_level_1          Full Cohort (N = 4098)          Full Cohort (N = 4099) Unnamed: 3_level_1 Unnamed: 4_level_1
                     Unnamed: 0_level_2                         Model 1                         Model 2            Model 1            Model 2
0  Discrimination score (range = 0 − 4)               1.05 (0.99, 1.11)               1.12 (1.00, 1.24)  1.12 (1.05, 1.20)  1.29 (1.12, 1.48)
1                Discrimination × Black                             NaN               0.92 (0.81, 1.04)                NaN  0.84 (0.72, 0.99)
2                                   NaN  Race-Matched Cohort (N = 3069)  Race-Matched Cohort (N = 3068)                NaN                NaN
3                                   NaN                         Model 1                         Model 2            Model 1            Model 2
4  Discrimination score (range = 0 − 5)               1.09 (1.02, 1.16)               1.14 (1.02, 1.28)  1.16 (1.07, 1.25)  1.22 (1.04, 1.43)
5                Discrimination × Black                             NaN               0.94 (0.82, 1.07)                NaN  0.93 (0.78, 1.12)

PMC0024XXXXX/PMC2430055.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Peripheral blood cell counts in 10-month post-transplant animals
  footer_text: Data shown are mean (±SD) values from three to five mice per genotype * p<0.05, ** p<0.005 when compared to wild type VEX
    unique: PMC2430055/PMC2430055.xml::T1-0

  \n                    RBC (M/ul)  Hematocrit (%)      WBC (K/ul)  Plt (K/ul)
0    Wild type VEX    9.03 (±0.48)   43.68 (±2.87)   17.72 (±5.99)  638 (±257)
1     Wild type RE    7.26 (±2.21)   40.80 (±5.55)   12.13 (±5.75)  353 (±132)
2        p15KO VEX    9.31 (±0.54)   43.96 (±2.52)   11.79 (±3.34)  805 (±126)
3         p15KO RE  6.90 (±0.94)**  36.79 (±3.68)*  7.64 (±2.24)**  789 (±176)
4        p16KO VEX    9.22 (±0.48)   45.13 (±1.01)   13.20 (±4.85)  602 (±151)
5         p16KO RE   7.09 (±1.04)*  41.45 (±10.73)   7.76 (±3.05)*  480 (±212)

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Differential counts of sorted VEX (+) myeloid cells from 10-month post-transplant animals
  footer_text: Data shown are percentages of >250 cells counted per sample. Blast/Pro: myeloblast and promyelocytes; Myelo: myelocytes; Band: band-form granulocytes; Eos: eosinophils; Mono: monocytes
    unique: PMC2430055/PMC2430055.xml::T2-0

       Unnamed: 0  Blast/Pro (%)  Myelo(%)  Band(%)  Eos (%)  Mono (%)
0   Wild type VEX            8.9      15.0     73.7      0.4       2.0
1             NaN           10.7      12.0     75.7      0.8       0.8
2    Wild type RE           31.5      11.7     51.7      2.3       2.7
3             NaN           35.4      13.0     46.3      0.4       4.9
4             NaN           35.0      15.4     46.2      1.1       1.3
5       p15KO VEX           33.8      12.1     47.0      1.0       6.1
6             NaN           27.5      35.8     30.0      2.5       4.2
7             NaN           36.0      24.2     39.3      0.0       0.6
8        p15KO RE           14.6      24.5     58.8      0.3       1.9
9             NaN           25.4      35.7     36.4      0.4       2.1
10            NaN           32.2      12.4     47.2      1.9       6.2
11      p16KO VEX           15.0      25.0     57.0      2.3       1.0
12            NaN           13.4       9.1     67.2      9.1       1.2
13            NaN           18.4      10.4     62.0      4.4       4.8
14       p16KO RE           56.8      15.7     15.3      4.7       7.6
15            NaN           45.7      23.3     25.7      2.7       2.7
16            NaN           38.1      24.6     34.7      2.1       0.5

PMC0024XXXXX/PMC2430763.xml

PMC0024XXXXX/PMC2435206.xml

PMC0024XXXXX/PMC2435220.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Counts of edge classification results
  footer_text:
    unique: PMC2435220/PMC2435220.xml::T1-0

  Unnamed: 0_level_0 b-Statistic Polygon Womble Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0
  Unnamed: 0_level_1           a              b                  c                  d                  a                  b                  c                  d
0              Model          36              0                  0                117                 36                  0                  0                117
1         Simulation          21             15                  4                113                 12                 24                  0                117

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Accuracy and error statistics for boundary classification using the little b and polygon wombling approaches
  footer_text:
    unique: PMC2435220/PMC2435220.xml::T2-0

  Unnamed: 0_level_0 b-Statistic Polygon Womble Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0
  Unnamed: 0_level_1 Specificity         Type I            Type II              Power        Specificity             Type I            Type II              Power
0              Model       1.000          0.000              0.000              1.000              1.000              0.000                0.0                1.0
1         Simulation       0.583          0.417              0.034              0.966              0.333              0.667                0.0                1.0

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Counts from classification table for Big B, Ladder and Local Moran methods
  footer_text:
    unique: PMC2435220/PMC2435220.xml::T3-0

  Unnamed: 0_level_0 Big B Ladder Local Moran Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0 Unnamed: 10_level_0 Unnamed: 11_level_0 Unnamed: 12_level_0
  Unnamed: 0_level_1     a      b           c                  d                  a                  b                  c                  d                  a                   b                   c                   d
0              Model     5      5           6                 70                 10                  0                  0                 76                  2                   8                   7                  69
1         Simulation     4      6           5                 71                 10                  0                  4                 72                  4                   6                   6                  70

  ----------------------------------------
  id: T4
  label_text: Table 4
  caption_text: Specificity, Type I and Type II error, and sensitivity of the Big B, Ladder and Local Moran methods
  footer_text:
    unique: PMC2435220/PMC2435220.xml::T4-0

  Unnamed: 0_level_0       Big B Ladder Local Moran Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0 Unnamed: 10_level_0 Unnamed: 11_level_0 Unnamed: 12_level_0
  Unnamed: 0_level_1 Specificity Type I     Type II              Power        Specificity             Type I            Type II              Power        Specificity              Type I             Type II               Power
0              Model         0.5    0.5       0.079              0.921                1.0                0.0              0.000              1.000                0.2                 0.8               0.092               0.908
1         Simulation         0.4    0.6       0.066              0.934                1.0                0.0              0.053              0.947                0.4                 0.6               0.079               0.921

PMC0024XXXXX/PMC2435384.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Average ± SD values (%) of degree of substitution (DS) and purity of the MPS-peptide-dextran conjugates (n = 3).
  footer_text:
    unique: PMC2435384/PMC2435384.xml::T1-0

        Conjugate     DS (%)  Purity (%)
0      MPS-mG-Dex  9.4 ± 0.2          91
1     MPS-mGG-Dex  7.0 ± 0.2          91
2    MPS-mGGG-Dex  9.5 ± 0.9          95
3   MPS-mGGGG-Dex  7.4 ± 0.1          90
4  MPS-mGGGGG-Dex  6.9 ± 0.1          93

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Inter-run accuracy (%Error) and precision (%CV) of the reversed-phase assay (n =5)
  footer_text:
    unique: PMC2435384/PMC2435384.xml::T2-0

          Analyte  Added Conc. (μg/mL)  Calculated Conc. (μg/mL) % Error  % CV
0              MP                  0.5                      0.50     0.5   6.3
1             MPS                  0.5                      0.49    −2.9   3.1
2       MPS-mG-OH                  0.5                      0.53     6.9   5.5
3      MPS-mGG-OH                  0.5                      0.48    −3.6   3.5
4     MPS-mGGG-OH                  0.5                      0.48    −4.7   8.7
5    MPS-mGGGG-OH                  0.5                      0.44   −12.8  12.0
6   MPS-mGGGGG-OH                  0.5                      0.43   −13.2   9.8
7              MP                  5.0                      5.06     1.1   1.2
8             MPS                  5.0                      4.82    −3.6   2.4
9       MPS-mG-OH                  5.0                      4.79    −4.2   1.6
10     MPS-mGG-OH                  5.0                      4.81    −3.8   1.0
11    MPS-mGGG-OH                  5.0                      4.82    −3.6   2.2
12   MPS-mGGGG-OH                  5.0                      4.82    −3.6   0.7
13  MPS-mGGGGG-OH                  5.0                      4.87    −2.6   1.3
14             MP                100.0                    108.00     7.6   1.6
15            MPS                100.0                    107.00     7.2   1.7
16      MPS-mG-OH                100.0                    108.00     7.7   3.2
17     MPS-mGG-OH                100.0                    104.00     3.9   3.1
18    MPS-mGGG-OH                100.0                    103.00     3.2   3.2
19   MPS-mGGGG-OH                100.0                    102.00     2.0   2.8
20  MPS-mGGGGG-OH                100.0                    101.00     0.6   3.5

  ----------------------------------------
  id: T3
  label_text: Table 3
  caption_text: Mean ± SD values of degradation half lives (h) of DMP conjugates in pH 7.4 buffer and rat blood (n = 3).
  footer_text: a–j Means with similar letters are significantly different each other: ANOVA with post-hoc Scheffe test..
    unique: PMC2435384/PMC2435384.xml::T3-0

  \n                             pH 7.4              Blood
0       MPS-mG-Dex  10.7 ± 0.1a,b,c,d,e  24.5 ± 3.0e,g,h,i
1      MPS-mGG-Dex         5.67 ± 0.03a       8.36 ± 0.45g
2     MPS-mGGG-Dex       5.87 ± 0.03b,f   9.80 ± 0.25f,h,j
3    MPS-mGGGG-Dex         4.69 ± 0.03c       6.89 ± 0.25i
4   MPS-mGGGGG-Dex         4.27 ± 0.02d     4.67 ± 0.21g,j

PMC0024XXXXX/PMC2435391.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Human IBD patient description
  footer_text: NOTE. CD; Crohn’s disease, UC; ulcerative colitis, Sm Intest; small intestine.
    unique: PMC2435391/PMC2435391.xml::T1-0

    Patient #     Sex  Age Diagnosis     Tissue  Patient #.1   Sex.1  Age.1 Diagnosis.1   Tissue.1
0           1    Male   78    Normal      Colon           25    Male     29          CD      Ileum
1           2    Male   47    Normal      Colon           26    Male     42          CD  Sm Intest
2           3  Female   31    Normal      Colon           27  Female     39          CD      Ileum
3           4    Male   54    Normal      Colon           28    Male     54          UC      Colon
4           5    Male   37    Normal      Ileum           29    Male     59          UC      Colon
5           6  Female   61    Normal      Ileum           30    Male     72          UC      Colon
6           7    Male   56        CD      Colon           31    Male     41          UC      Colon
7           8    Male   33        CD      Colon           32  Female     54          UC     Rectum
8           9  Female   46        CD      Colon           33  Female     72          UC      Colon
9          10  Female   51        CD      Colon           34  Female     36          UC      Colon
10         11  Female   31        CD      Ileum           35    Male     56          UC      Colon
11         12    Male   37        CD      Ileum           36    Male     31          UC     Rectum
12         13    Male   48        CD      Ileum           37    Male     23          UC      Colon
13         14  Female   65        CD      Ileum           38    Male     42          UC      Colon
14         15  Female   26        CD      Ileum           39    Male     42          UC      Colon
15         16    Male   33        CD      Cecum           40    Male     68          UC     Rectum
16         17  Female   45        CD  Sm Intest           41    Male     45          UC     Rectum
17         18    Male   64        CD      Ileum           42  Female     60          UC      Colon
18         19  Female   31        CD      Ileum           43    Male     33          UC      Colon
19         20    Male   35        CD      Colon           44  Female     27          UC      Colon
20         21    Male   20        CD      Ileum           45    Male     57          UC     Rectum
21         22    Male   41        CD      Colon           46  Female     35          UC      Colon
22         23  Female   21        CD      Colon           47  Female     30          UC      Colon
23         24    Male   41        CD      Colon           48  Female     26          UC      Colon

  ----------------------------------------
  id: T2
  label_text: Table 2
  caption_text: Gene expression analysis in the colon of Hnf4αF/F and Hnf4αΔIEpC mice
  footer_text: NOTE. Quantitative real-time PCR of colon mRNA from 2-month-old mice (n=6). All the values are means ± SD. Significant difference compared to Hnf4αF/F mice: * , p< 0.05 ** , p< 0.01 *** , p< 0.001.
    unique: PMC2435391/PMC2435391.xml::T2-0

      Gene \n                Hnf4α\n                F/F\n               \n                Hnf4α\n                ΔIEpC\n
0    HNF4α                                                  1.00 ± 0.16                                                 0.01 ± 0.00***
1     Muc1                                                  1.00 ± 0.34                                                 7.54 ± 1.42***
2     Muc2                                                  1.00 ± 0.49                                                    0.88 ± 0.41
3     Muc3                                                  1.00 ± 0.38                                                 0.07 ± 0.05***
4     Muc4                                                  1.00 ± 0.34                                                   1.64 ± 0.47*
5   Muc5AC                                                  1.00 ± 0.39                                                   1.74 ± 0.46*
6    Muc5B                                                  1.00 ± 0.35                                                   1.77 ± 0.51*
7     Muc6                                                  1.00 ± 0.36                                                   1.54 ± 0.39*
8     Aqp1                                                  1.00 ± 0.43                                                  0.32 ± 0.10**
9     Aqp4                                                  1.00 ± 0.33                                                   1.50 ± 0.39*
10    Aqp8                                                  1.00 ± 0.21                                                 0.15 ± 0.03***
11   Mep1α                                                  1.00 ± 0.30                                                 0.12 ± 0.05***
12   Mep1β                                                  1.00 ± 0.32                                                 0.10 ± 0.04***

PMC0024XXXXX/PMC2435511.xml

PMC0024XXXXX/PMC2440269.xml
  ----------------------------------------
  id: T1
  label_text: Table 1
  caption_text: Percent of Potentially Eligible Subjects Rejected by Reason for Exclusion
  footer_text:
    unique: PMC2440269/PMC2440269.xml::T1-0

                                          0               1          2
0                        Modifiable Reasons             NaN        NaN
1                           Lack of Consent           21.4%        NaN
2                 Patient/Surrogate Refusal           10.9%        NaN
3                   Surrogate Non-available            7.0%        NaN
4                         Enrollment Window             NaN        NaN
5                                  Original  Post -Revision  6.6%/2.3%
6   Delayed Notification of Study Personnel            4.4%        NaN
7                                MD Refusal            2.7%        NaN
8                               Other Study            2.3%        NaN
9                    Non-Modifiable Reasons             NaN        NaN
10                             CMO/Moribund           11.8%        NaN
11                          Chronic illness            7.8%        NaN
12                                      CKD            7.6%        NaN
13                                  Obesity            5.9%        NaN

In [192]:
table.remove(table.find('thead'))

In [193]:
table_html = (ET.tostring(table).decode('utf-8'))

In [194]:
HTML(table_html)

In [197]:
pd.read_html(table_html)[0]

                 0       1       2       3     4
0        Raw rates  0.6984  0.6413  0.7467   NaN
1  Empirical Bayes  0.2584  0.2252  0.2916   NaN
2  Poisson kriging  0.2345  0.1961  0.2740  92.0
3  E-type estimate  0.2348  0.1967  0.2750  92.0

In [180]:
df = table_df[0].copy()
df

         \n               Working side\n Balancing side\n Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0
         \n                          Max              Min              Shear              Direc                Max                Min              Shear              Direc
0         Premaxilla (PM)            NaN              NaN                NaN                NaN                NaN                NaN                NaN                NaN
1                    Sham    30.3 ± 30.6     −45.1 ± 52.9        75.4 ± 81.8         27.4 ± 6.4        27.3 ± 20.7       −37.9 ± 40.5        63.5 ± 60.5         29.1 ± 7.2
2               Reduction    28.7 ± 20.0     −34.6 ± 42.1        62.4 ± 58.9    151.8 ± 35.0***        19.9 ± 15.3       −26.3 ± 28.3        46.2 ± 42.9    159.2 ± 40.6***
3   Mandible-Incisor (MI)            NaN              NaN                NaN                NaN                NaN                NaN                NaN                NaN
4                    Sham    68.3 ± 45.2     −37.4 ± 34.2       105.7 ± 71.5        79.2 ± 34.1        64.9 ± 45.5       −31.5 ± 25.5        96.5 ± 67.0        87.9 ± 41.7
5               Reduction    46.9 ± 53.7     −30.0 ± 18.4        76.9 ± 64.2     126.7 ± 35.3**       29.0 ± 23.6*       −17.3 ± 5.4*      46.4 ± 22.5**      119.1 ± 32.5*
6     Mandible-Molar (MM)            NaN              NaN                NaN                NaN                NaN                NaN                NaN                NaN
7                    Sham    80.0 ± 57.8     −40.5 ± 32.1       120.5 ± 67.6        50.1 ± 28.2        58.9 ± 30.3       −44.3 ± 24.2       103.2 ± 50.2        54.3 ± 23.8
8               Reduction    69.6 ± 56.6     −41.0 ± 40.3       110.6 ± 89.3        69.3 ± 24.7        48.4 ± 45.5       −36.7 ± 45.7        85.2 ± 84.6        63.1 ± 29.6
9                     NaN            NaN              NaN                NaN                NaN                NaN                NaN                NaN                NaN
10            ANOVA/Tukey            NaN              NaN                NaN                NaN                NaN                NaN                NaN                NaN
11                   Sham       MM > PM#              NaN           MM > PM#          MI > PM##           MM > PM#                NaN                NaN          MI > PM##
12              Reduction            NaN              NaN                NaN          PM > MM##           MM > PM#                NaN                NaN           PM > MI#
13                    NaN            NaN              NaN                NaN           MI > MM#                NaN                NaN                NaN          PM > MM##

In [168]:
table_df[0].dtypes

\n                  \n                  object
Working side\n      Max                 object
Balancing side\n    Min                 object
Unnamed: 3_level_0  Shear               object
Unnamed: 4_level_0  Direc               object
Unnamed: 5_level_0  Max                 object
Unnamed: 6_level_0  Min                 object
Unnamed: 7_level_0  Shear               object
Unnamed: 8_level_0  Direc               object
dtype: object

In [140]:
c = next(table_wrap.getiterator())

In [110]:
tables = table_wrap.findall('table')

In [112]:
table = tables[0]

In [113]:
table.attrib

{'frame': 'void', 'rules': 'none'}

In [114]:
table.getchildren()

In [95]:
caption = table_wrap.find('caption')

print()

Mean (SD) Neuropsychological Test Performance for the Three Age Groups in Experiment 1

In [82]:
table_wrap.attrib

{'id': 'T1', 'position': 'float'}

In [8]:
tree = ET.parse(MANUSCRIPT_DATA_DIR.joinpath('PMC0021XXXXX/PMC2136438.xml'))

In [9]:
root = tree.getroot()

```xml
<table-wrap id="T1" position="float">
<label>Table 1</label>
<caption>
  <p>Mean (SD) Neuropsychological Test Performance for the Three Age Groups in Experiment 1</p>
</caption>
<table frame="void" rules="none">
  <thead>
    <tr>
      <th align="left" valign="middle" rowspan="1" colspan="1"/>
      <th align="center" valign="middle" rowspan="1" colspan="1">Young Adults</th>
      <th align="center" valign="middle" rowspan="1" colspan="1">Older-Young Adults</th>
      <th align="right" valign="middle" rowspan="1" colspan="1">Older Adults</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="left" valign="middle" rowspan="1" colspan="1">Test (Maximum Score)</td>
      <td align="center" valign="middle" rowspan="1" colspan="1"/>
      <td align="center" valign="middle" rowspan="1" colspan="1"/>
      <td align="right" valign="middle" rowspan="1" colspan="1"/>
    </tr>
    <tr>
    ...
    </tr>
  </tbody>
</table>
<table-wrap-foot>
  <p><italic>Note</italic>. CVLT = California Verbal Learning Test</p>
  <fn id="TFN1">
    <label>*</label>
    <p id="P61">= significant group differences</p>
  </fn>
  <fn id="TFN2">
    <label>†</label>
    <p id="P62">= significant group differences</p>
  </fn>
</table-wrap-foot>
</table-wrap>
```

In [73]:
table_wraps = tree.findall('.//table-wrap')

In [75]:
table_wrap = table_wraps[0]
table_wrap.findall('table')

In [76]:
table_wrap.attrib

{'id': 'T1', 'position': 'float'}

In [77]:
table_wrap.text

'\n        '

In [79]:
table_wrap.find('caption')

In [71]:
tree.findall('*/*/*/table')

[<Element 'table' at 0x7f16c64a7c78>,
 <Element 'table' at 0x7f16c5942d68>,
 <Element 'table' at 0x7f16c592f868>,
 <Element 'table' at 0x7f16c591e0e8>,
 <Element 'table' at 0x7f16c591ee58>,
 <Element 'table' at 0x7f16c6c57188>,
 <Element 'table' at 0x7f16c6c5adb8>,
 <Element 'table' at 0x7f16c6c48d18>,
 <Element 'table' at 0x7f16c6c4cd18>]

In [40]:
a, b = get_tables(root)

In [41]:
a

[<Element 'table-wrap' at 0x7f16c6c2d0e8>,
 <Element 'table-wrap' at 0x7f16c6c2dc78>,
 <Element 'table-wrap' at 0x7f16c6c34868>,
 <Element 'table-wrap' at 0x7f16c6c3b818>,
 <Element 'table-wrap' at 0x7f16c6c42778>,
 <Element 'table-wrap' at 0x7f16c6bcf4a8>,
 <Element 'table-wrap' at 0x7f16c6bde1d8>]

In [42]:
b

[<Element 'table' at 0x7f16c6c2d228>,
 <Element 'table' at 0x7f16c6c2ddb8>,
 <Element 'table' at 0x7f16c6c349a8>,
 <Element 'table' at 0x7f16c6c3b958>,
 <Element 'table' at 0x7f16c6c428b8>,
 <Element 'table' at 0x7f16c6bcf5e8>,
 <Element 'table' at 0x7f16c6bde318>]

In [36]:
for child in root:
    print(child)
    print(child.findall('*/table-wrap'))

<Element 'front' at 0x7f16bff4e8b8>
[]
<Element 'body' at 0x7f16bff5b368>
[]
<Element 'back' at 0x7f16c6c23f48>
[<Element 'table-wrap' at 0x7f16c6c2d0e8>, <Element 'table-wrap' at 0x7f16c6c2dc78>, <Element 'table-wrap' at 0x7f16c6c34868>, <Element 'table-wrap' at 0x7f16c6c3b818>, <Element 'table-wrap' at 0x7f16c6c42778>, <Element 'table-wrap' at 0x7f16c6bcf4a8>, <Element 'table-wrap' at 0x7f16c6bde1d8>]

In [11]:
child.findall

In [27]:
table.tostring()

AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'tostring'

In [12]:
tables = child.findall('**/table')

In [13]:
table = tables[0]

In [23]:
table.makeelement(0)

TypeError: makeelement expected 2 arguments, got 1

In [32]:
df = pd.read_html(ET.tostring(table))

In [34]:
df[0]

         Predictor  Average  Minimum  Maximum  % best prediction
0        Raw rates   0.6984   0.6413   0.7467                NaN
1  Empirical Bayes   0.2584   0.2252   0.2916                NaN
2  Poisson kriging   0.2345   0.1961   0.2740               92.0
3  E-type estimate   0.2348   0.1967   0.2750               92.0